### ISSUE TITLE
ITMS-90809: Deprecated API Usage New apps that use UIWebView are no longer accepted

### ISSUE THREAD

**Issue by Danishbegmirza** [inspireui/support#3926] opened 2020-06-26 14:03 UTC
IOS Build is rejected mutiple times and got this email : New apps that use UIWebView are no longer accepted
Instead, use WKWebView for improved security and reliability
I am using latest version of webview still problem exists
![Screenshot_2020-06-26 Message “Fwd App Store Connect Your app Edee Supermarket (Apple ID 1517412731 Version 1 0 0 Build 1) ](https://user-images.githubusercontent.com/45626491/85865516-a44a1880-b7e3-11ea-9232-d6f4b948b409.png)

[common.zip](https://github.com/inspireui/support/files/4837350/common.zip)

**Comment by ameenbadri7** [comment] 2020-06-26 15:53
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

our team will look for you issue as soon as possible.

Thank you for your time!

**Comment by minhcasi** [comment] 2020-06-28 03:19
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-06-28 03:19 UTC
Labels: needs-more-info
