### ISSUE TITLE
Back Android is deprecated and has been removed from this package use BankHandler instead

### ISSUE THREAD

**Issue by khaja25** [inspireui/support#1441] opened 2019-11-22 14:17 UTC
![Backandroid](https://user-images.githubusercontent.com/58036762/69433072-e8ae9b00-0d60-11ea-98c7-b89cc48cce15.jpeg)

**Comment by minhcasi** [comment] 2019-11-23 09:25
Hi, thank you for reaching. Could you help to share the purchased screenshot from http://codecayon.net/downloads ? Just want to verify your proof of purchase, sorry for any inconvenience - thank you!

**Comment by minhcasi** [comment] 2019-11-23 09:27
Duplicate of #1437

**Closed by minhcasi** 2019-11-23 09:27 UTC

**Comment by khaja25** [comment] 2019-11-25 05:58
Hey there this is my purchased screenshot from http://codecayon.net/downloads ,i want the solution for above mentioned issue of Back Android is deprecated and has been removed from this package use BankHandler instead...
![download](https://user-images.githubusercontent.com/58036762/69516090-a494e380-0f76-11ea-887a-4ca91de415cd.jpeg)
