### ISSUE TITLE
How i can skip categories?

### ISSUE THREAD

**Issue by lpzczar** [inspireui/support#3932] opened 2020-06-26 17:45 UTC
Hello, I hope you are well, today I would like to request help from the support for the following reason

**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I need to skip some categories in my fluxnews app
+ Product & version: Fluxnews 1.4.1
+ Flutter (or React Native) version: Flutter v1.17.2
+ Testing Device/Simulator: iOS & Android
+ Screenshot issues (drag the file to attach here): 
![CatErr](https://user-images.githubusercontent.com/19940455/85883308-64187500-b7a6-11ea-97c8-b64f21ed8a7a.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment] 2020-06-27 05:41
@lpzczar - it is possible to add condiction to skip on this file
<img width="951" alt="Screen Shot 2020-06-27 at 12 40 31" src="https://user-images.githubusercontent.com/1459805/85915624-64cb0d00-b873-11ea-857a-ea5f7a9a7866.png">


Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-06-28 03:20
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-06-28 03:20 UTC
Labels: needs-more-info
