### ISSUE TITLE
I encountered an error while building my app for release on the play store.

### ISSUE THREAD

**Issue by Justnopeople** [inspireui/support#4727] opened 2020-08-25 07:02 UTC
Detail Issues: 
![image](https://user-images.githubusercontent.com/49190031/91142278-af81cd80-e6da-11ea-855a-39e10225f928.png)
This is an image when I'm building my application and an error occurs. Can you help me to fix this issue?

**Comment by minhcasi** [comment] 2020-08-25 07:47
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-08-26 03:29
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-08-26 03:29 UTC
Labels: needs-more-info
