### ISSUE TITLE
Posts not submit and payment method Mstore pro

### ISSUE THREAD

**Issue by Osamasomy** [inspireui/support#3985] opened 2020-06-30 09:54 UTC
**sorry you are not allowed to create posts as this user**

Im register as vendor and try to submit post but each time I face this error.

My 2nd issue is that Im trying to integrate stripe payment gateway but stripe image is not displaying and and when I check out It will redirect me to 404 page.

Help me.

**Comment by minhcasi** [comment] 2020-06-30 10:21
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-07-02 03:30
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-02 03:30 UTC
Labels: needs-more-info
