### ISSUE TITLE
Opencart problems

### ISSUE THREAD

**Issue by uzumnetkurumsal** [inspireui/support#2863] opened 2020-04-24 00:07 UTC
Connecting to openCart.
Hi dear, These are the issues which is really causing troubles for me:

Prices differ between site and app
Discount price is not shown
Cart error when reopen the application
Filter by price range not working
New addresses are added to the website with every order.

**Comment by minhcasi** [comment] 2020-04-24 02:48
@uzumnetkurumsal - could you mind you share the screenshot of these issues so that we could reproduce with your config file? Thank you for your time

**Comment by harry503** [comment] 2020-04-24 12:55
@minhcasi it's the same as i reported. and my ticket has been closed. but when will it be released?

**Comment by minhcasi** [comment] 2020-04-26 10:44
@harry503 - we will release the latest 1.7.0 on Monday, the new 1.6.7 is also available on Gitlab - thank you!

**Comment by harry503** [comment] 2020-04-26 11:09
@minhcasi Thank you. this is exciting! Please make sure that it's well tested especially for us in Opencart. I'll wait for version 1.7

Ask your team to come up with test scripts for each platform. I can see that the app is amazing, but it's just lack of a lot of testing.

The apple sign in as reported in another ticket was also not working for the 2nd login and forward, since it does not give email anymore. I hope this is also fixed in 1.7.

**Comment by uzumnetkurumsal** [comment] 2020-04-27 09:26
> @harry503 - we will release the latest 1.7.0 on Monday, the new 1.6.7 is also available on Gitlab - thank you!

How can I update the github. Do you have a document about it

**Comment by minhcasi** [comment] 2020-04-28 02:48
@uzumnetkurumsal - pls help to download the latest 1.7.0 - we have note the detail on https://medium.com/@inspireui/announcing-fluxstore-1-7-x-9a636c5468e8

@harry503  - thank you for your suggestion, we will add more UnitTest into the services file for each platform

**Closed** 2020-04-29 06:13 UTC
Labels: FluxStore, opencart-issues
