### ISSUE TITLE
[mstore-expo] - Search page keeps moving up and down after hitting enter

### ISSUE THREAD

**Issue by khiemhuynh95** [inspireui/support#1097] opened 2019-09-22 01:16 UTC
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
Hi, trong search page, khi mình search 1 keyword, hit done trên bàn phím 1 lần thì nó hiển thị ra nhưng nó nhảy lên xuống liên tục. Phải hit enter lần nữa mới đứng yên lại
2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by minhcasi** [comment] 2019-09-22 04:05
Duplicate of #1098

**Closed by minhcasi** 2019-09-22 04:05 UTC
Labels: question ❓
