### ISSUE TITLE
[Fluxstore Pro Woocommerce] SMS Login not working 

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#3264] opened 2020-05-18 11:47 UTC
Step 1 (require): detail issues and screenshots
Getting error on SMS and Gmail login. Attached screen shot.
![Screenshot_20200518-164646](https://user-images.githubusercontent.com/6376301/82209782-7a235200-992b-11ea-8027-55ddc9ed63e2.jpg)
![Screenshot_20200518-172341](https://user-images.githubusercontent.com/6376301/82210416-ac817f00-992c-11ea-8678-069e7a2c3ebd.jpg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment] 2020-05-19 03:33
Duplicate of #3151

Please move to the same conversation on 3151, this is a new issue from Google library

**Closed by minhcasi** 2020-05-19 03:33 UTC
