### ISSUE TITLE
[FluxStore] -  Razorpay app crash

### ISSUE THREAD

**Issue by UTimung** [inspireui/support#2306] opened 2020-03-07 11:31 UTC
In debug apk, Razorpay payment works perfectly

But in release apk, when choose Razorpay as payment method, the app crash

**Comment by minhcasi** [comment] 2020-03-08 03:36
@UTimung - could you zip the current source and send us for investigating - support@inspireui.com - thank you!

**Comment by minhcasi** [comment] 2020-03-08 03:52
Duplicate of #2303

**Closed by minhcasi** 2020-03-08 03:52 UTC
Labels: FluxStore, question ❓

**Comment by UTimung** [comment] 2020-03-08 06:35
> @UTimung - could you zip the current source and send us for investigating - [support@inspireui.com](mailto:support@inspireui.com) - thank you!

i sent you an email with current source code
 please check
