### ISSUE TITLE
Paypal payment gateway error

### ISSUE THREAD

**Issue by fasttend** [inspireui/support#3868] opened 2020-06-23 12:53 UTC
Error showing Currency not supported.

![paypal error](https://user-images.githubusercontent.com/63434487/85405792-892a9f00-b57e-11ea-862e-a4ea38cb9a47.jpeg)

**Comment by ameenbadri7** [comment] 2020-06-23 20:01
if you haven verifies your self please do this : 

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

if you have been verified before we will investigate about this problem.

**Comment by fasttend** [comment] 2020-06-24 07:35
Already submitted my response in google forms. Please check and do the needful.

**Comment by minhcasi** [comment] 2020-06-25 00:45
@ameenbadri7 - pls help with investigating - sharing private common config via email

**Comment by ameenbadri7** [comment] 2020-06-25 02:40
@fasttend could you please resend your   common config via the private http://verify.inspireui.com/
You send us the  fluxstore default common and config files.

**Comment by fasttend** [comment] 2020-06-25 18:04
Please check now

‪On Thu, Jun 25, 2020 at 8:10 AM ‫amin badri أمين بدري‬‎ <
notifications@github.com> wrote:‬

**Comment by ameenbadri7** [comment] 2020-06-28 20:24
if you have fluxstore you are not using the latest version 
I see your config files and you are still using the old once.

please we have to take a lot of updates you should update to the latest using these guides 

https://github.com/inspireui/support/wiki/Guide-to-using-git-to-work-repo-Fluxstore-pro
https://www.youtube.com/watch?v=SWLHKx-xzn0

and let us know if you still have this problem?

**Comment by ameenbadri7** [comment] 2020-06-30 15:40
I'm sorry to close this ticket as there is no response or active conversation, 
please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed** 2020-06-30 15:41 UTC
Labels: FluxStore
