### ISSUE TITLE
Application can't run on Android or ios imulator

### ISSUE THREAD

**Issue by ozihno** [inspireui/support#3179] opened 2020-05-13 15:51 UTC
Compiler message: when running application both on Android or Ios

Compiler message:
../../../../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.7.2/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name 'animation'.
        animation: animation,
        ^^^^^^^^^
../../../../../../../development/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Compiler message:
../../../../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.7.2/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name 'animation'.
        animation: animation,
        ^^^^^^^^^
../../../../../../../development/flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script '/Users/inside/development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/inside/development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 58s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by minhcasi** [comment] 2020-05-14 03:29
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-05-15 02:21
I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!

**Comment by ozihno** [comment] 2020-05-18 15:01
@minhcasi I've long sent you my verification. I can send you the email copy.

**Comment by minhcasi** [comment] 2020-05-19 13:04
@ozihno - sorry for missing your comment, this issue is caused by the latest Flutter version - please try to update the latest Fluxstore & Flutter version
```
flutter channel stable
flutter upgrade --force
```
or use this guide https://medium.com/@inspireui/announcing-fluxstore-1-7-x-9a636c5468e8

**Closed** 2020-05-21 04:36 UTC
Labels: FluxStore, common-installing ⁉️
