### ISSUE TITLE
How to build ios version app

### ISSUE THREAD

**Issue by investisocial** [inspireui/support#3787] opened 2020-06-18 11:25 UTC
Hi,
I've completed the android building but I don't understand how can I release ios version.
Have I to do always from the android studio program?
I'm trying to open the project on a MacBook but it doesn't work.
Can you help me, please?
I cannot find an ios building guide on inspireui docs.
Thank you.
Regards
Carlo

![envato_panel](https://user-images.githubusercontent.com/57216890/85014740-22187f00-b167-11ea-95a5-5cc1ee4e3c4e.jpg)

Thank you so much for your time 😊

**Comment by minhcasi** [comment] 2020-06-18 13:12
Could i know what is the detail issue when you run with ios? Please check the release guide on this link https://docs.inspireui.com/fluxstore/delivery/

**Comment by minhcasi** [comment] 2020-06-19 12:15
Duplicate of #3803

**Closed by minhcasi** 2020-06-19 12:15 UTC
Labels: FluxstoreMV
