### ISSUE TITLE
[ Mstore ] - Facebook login not working in TestFlight but working fine in expo 

### ISSUE THREAD

**Issue by santhoniral** [inspireui/support#689] opened 2019-06-10 11:33 UTC
Envato Username : Manovee

Issue : Facebook login not working in Test Flight but working fine in expo 

please resolve this issue...its very urgent for me

thanks

**Comment by minhcasi** [comment] 2019-06-11 01:52
can you share the screenshot issue, it could be some missing from your FB app setting, thanks

**Comment by minhcasi** [comment] 2019-06-11 01:52
Duplicate of #690

**Closed by minhcasi** 2019-06-11 01:52 UTC
Labels: question ❓
