### ISSUE TITLE
Loggin and catogories

### ISSUE THREAD

**Issue by Kindakart** [inspireui/support#4803] opened 2020-08-30 11:15 UTC
1. i did set up everything, and the app was working fine but now the app is not fetching catogories although, the set up is fine
2. l added firebase set up like google services, sha-1 fingerprint and so on but the app is not responding well, please see screenshot below. 

Here is the my common file to check what is the issue:
https://drive.google.com/drive/folders/1Rqa54UVyvw3dWfw3et4SAoBEMcndZOFD?usp=sharing

https://drive.google.com/drive/folders/1Rqa54UVyvw3dWfw3et4SAoBEMcndZOFD?usp=sharing

**Comment by minhcasi** [comment] 2020-08-30 12:43
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-09-01 02:13
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-09-01 02:13 UTC
Labels: needs-more-info
