### ISSUE TITLE
homepage not changing from demos

### ISSUE THREAD

**Issue by nomicool** [inspireui/support#4032] opened 2020-07-03 04:38 UTC
i have Fluxstore Multi Vendor - Flutter E-commerce Full App.
i have Copied and replaced the content of config_theme11.json to lib/config/config_en.json but the homepage is not getting changed I have tried all no one is working. then I tried many ready-made config files but the homepage is still the same

**Comment by minhcasi** [comment] 2020-07-03 04:48
Duplicate of #3979

**Comment by nomicool** [comment] 2020-07-03 11:56
hey its not the duplicate for 3979 its the issue with new other flutter multi vendor app issue kindly brief me on this

**Comment by minhcasi** [comment] 2020-07-04 02:51
Oh sorry for closing as i though you have purchased one product. 

We will checking the issue on this theme and let you know. Please note that it could be customize from the Fluxbuilder theme as well - thank you!

**Comment by nomicool** [comment] 2020-07-04 08:50
Hey i have used vs code as per guide I simply copy json 11 content to json en but no change in homepage happened

**Comment by nomicool** [comment] 2020-07-04 11:07
with fluxbuilder i faces rest API not connected face consumer secret invalid even tried many new keys and vs code, content copy is not working please help

**Comment by minhcasi** [comment] 2020-07-05 11:11
would you mind to share the latest config.dart and json files here so that we could help with checking  - you could also share private to support@inspireui.com - thank you!

**Comment by nomicool** [comment] 2020-07-05 11:39
here are the files kindly respond to
[files.zip](https://github.com/inspireui/support/files/4874839/files.zip)

 me today for this

**Comment by minhcasi** [comment] 2020-07-06 03:52
@vumanhsn97 - pls help to investigate this feature

**Comment by nomicool** [comment] 2020-07-06 04:11
How can I help you please help a quick client is forcing me

**Comment by vumanhsn97** [comment] 2020-07-06 07:16
@nomicool 
Set isCaching: false in lib/common/config/general.dart
run cmd:
flutter clean
flutter run

**Closed** 2020-07-10 01:59 UTC
Labels: FluxstoreMV
