### ISSUE TITLE
[Mstore] - Billing address not visible perfectly....alignment error

### ISSUE THREAD

**Issue by santhoniral** [inspireui/support#710] opened 2019-06-18 05:02 UTC
My Purchase code : 889b39fb-3631-4513-8368-612d8edc6432

Billing address not visible perfectly....alignment error

![59325466-ce2bbc80-8d00-11e9-9637-cbac4ec3d0db](https://user-images.githubusercontent.com/32481586/59654509-11c86f80-91b4-11e9-8f1d-f7f60eb4a64c.png)
[WhatsApp.zip](https://github.com/inspireui/support/files/3299836/WhatsApp.zip)

**Comment by minhcasi** [comment] 2019-06-18 15:26
Duplicate of #690

**Closed by minhcasi** 2019-06-18 15:26 UTC
Labels: question ❓
