### ISSUE TITLE
Works fine on FluxBuilder but not on iOS Simulator or TestFlight

### ISSUE THREAD

**Issue by lucianacouto** [inspireui/support#3927] opened 2020-06-26 14:06 UTC
This is the configuration we are using for the flutter project and for the FluxBuilder. It works fine when we load into the iOS app to preview (FluxBuilder Pro), but when I load from the flutter project using the iOS simulator and a TestFlight app, the products won’t load.

We are using:
fluxstore-shopify 1.7.5
Xcode 11.5
Flutter version:
Flutter 1.17.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1ad9baa8b9 (9 days ago) • 2020-06-17 14:41:16 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

This is on Fluxbuilder:
<img width="1277" alt="Screen Shot 2020-06-26 at 10 00 20 AM" src="https://user-images.githubusercontent.com/67471269/85865442-e51a4100-b793-11ea-958e-7ac363e75801.png">

This is on TestFlight:
![IMG_3664](https://user-images.githubusercontent.com/67471269/85865797-738ec280-b794-11ea-9de9-03fc3a37210b.PNG)

<img width="682" alt="Screen Shot 2020-06-26 at 10 03 23 AM" src="https://user-images.githubusercontent.com/67471269/85865745-5528c700-b794-11ea-90b5-10c2a0da9b77.png">

Thanks for your help,
Luciana

**Comment by ameenbadri7** [comment] 2020-06-26 15:48
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by luyx2412** [comment] 2020-07-02 14:31
Closed, because no longer response. Feel free to create new issue.

Thanks

**Comment by lucianacouto** [comment] 2020-07-02 20:24
I don't get it! I filled out the form right after you asked me to.

**Comment by luyx2412** [comment] 2020-07-05 04:24
Hi @lucianacouto Can you share me your source code via inspireui.team@gmail.com Let me investigate and reply you soon.

Thanks

**Comment by lucianacouto** [comment] 2020-07-06 23:16
Hi @luyx2412 ,

I invited you to access the repository. The branch that contains the changes to my store is in `development`. Let me know if you were able to access it.

Thanks

**Comment by michaelbrinkworth** [comment] 2020-07-07 21:48
i face the same problem!

**Comment by lucianacouto** [comment] 2020-07-08 12:03
Hey @luyx2412, noticed that you didn't access the code I shared. Did you have any issue with that?

**Comment by luyx2412** [comment] 2020-07-08 14:42
Hi @lucianacouto I just invited you again, because i need clean the users. Sorry about it.

Hi @michaelbrinkworth Can you submit your issue ticket, i will help you.

Thanks

**Comment by lucianacouto** [comment] 2020-07-09 01:38
Hi @luyx2412 , It's loading the products, but it still has some bugs.
- It's not loading the next page for a product list properly (it repeats the first page, and above the current list)
- Staggered layout doesn't work.

**Comment by luyx2412** [comment] 2020-07-09 15:51
Hi @lucianacouto can you share me your screenshot about the issue? Let me investigate about it.

Thanks

**Comment by lucianacouto** [comment] 2020-07-10 00:58
it stays on "Loading" foerever.

![Screen Shot 2020-07-09 at 8 57 06 PM](https://user-images.githubusercontent.com/67471269/87104757-df5a3c00-c226-11ea-8e4f-3ce7fb2a0f4c.png)

**Comment by lucianacouto** [comment] 2020-07-10 01:20
the `staggered` is ignored:
![Screen Shot 2020-07-09 at 9 16 57 PM](https://user-images.githubusercontent.com/67471269/87105745-cd2dcd00-c229-11ea-935c-65da75d41b4d.png)

I changed some texts
```
"HorizonLayout": [
    {
      "layout": "logo",
      "showMenu": false,
      "image": "assets/images/logo.png",
      "showLogo": true,
      "showSearch": true
    },
    {
      "layout": "bannerImage",
      "isSlider": true,
      "autoPlay": true,
      "design": "default",
      "items": [
        {
          "image": "replaced",
          "padding": 0.0,
          "category": "blah"
        },
        {
          "image": "replaced",
          "padding": 0.0,
          "category": "blah"
        }
      ],
      "radius": 0.0
    },
    {
      "name": "On Sale Now",
      "layout": "staggered",
      "category": "blah",
      "isSnapping": false
    }
  ],
```

**Comment by luyx2412** [comment] 2020-07-16 15:28
Hi @lucianacouto Can you send me your latest source code via inspireui.team@gmail.com? I will investigate and reply you soon. 

Thanks

**Comment by minhcasi** [comment] 2020-07-20 10:46
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-20 10:46 UTC
Labels: Fluxshopify
