### ISSUE TITLE
Animated Splashscreen Issue

### ISSUE THREAD

**Issue by ajeets1978** [inspireui/support#1270] opened 2019-10-22 11:29 UTC
Changed the Splashcreen.flr but still I am seein the fluxstore screen only.

**Comment by minhcasi** [comment] 2019-10-22 11:52
Duplicate of #1271

Kindly notes:
- Create one ticket for your all issue with detail screenshot
- Share your config file (common/config.json and config.js) so we can reproduce issues.
- Also, make sure to check the document first - https://docs.inspireui.com/fluxstore

**Closed by minhcasi** 2019-10-22 11:52 UTC
Labels: question ❓
