### ISSUE TITLE
Hide header and footer for website in webview payment

### ISSUE THREAD

**Issue by AhmedMaherPro** [inspireui/support#4563] opened 2020-08-11 11:47 UTC
how i can remove header and footer from webview payment 
![removeit](https://user-images.githubusercontent.com/25661721/89893812-580f3800-dbd9-11ea-9ef2-a1c64940be6e.PNG)

**Comment by ameenbadri7** [comment] 2020-08-11 18:48
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by AhmedMaherPro** [comment] 2020-08-11 18:53
i already fill it before

**Comment by AhmedMaherPro** [comment] 2020-08-11 19:06
i filled it agian please check

**Comment by minhcasi** [comment] 2020-08-12 02:23
You could customize this file - https://tppr.me/xXFVZ - as the payment screen is loaded your whole webview payment site.

for example
```
var myJsCode = ```
   let linkElement = document.createElement('link');
   linkElement.setAttribute('rel', 'stylesheet');
   linkElement.setAttribute('type', 'text/css');
   linkElement.setAttribute('href', 'data:text/css;charset=UTF-8,' + encodeURIComponent('[url to css file]'));
```;

flutterWebviewPlugin.evalJavascript(myJsCode)
```

To load from the local asset folder, you can first read the file into a string and inject it in a similar way.

**Comment by AhmedMaherPro** [comment] 2020-08-12 06:42
can you please guide me where i can put this codes and i want to remove this two classes in webview payment
(.site-footer) - (.site-header)
i need more explain please
thank you

**Comment by AhmedMaherPro** [comment] 2020-08-12 09:31
i did it thank you , but there is a problem The price on the app is different from the website , why ?

**Comment by minhcasi** [comment] 2020-08-12 14:05
pls share the screenshot pricing issue

**Comment by AhmedMaherPro** [comment] 2020-08-12 18:16
please see the difference

**Comment by AhmedMaherPro** [comment] 2020-08-13 10:17
can you please tell me what is the problem ??

**Comment by minhcasi** [comment] 2020-08-15 03:57
@AhmedMaherPro - could you help to double-check if you have updated the setting the Exchange Rating to form the currency setting - https://tppr.me/ZYGIw

**Comment by AhmedMaherPro** [comment] 2020-08-15 06:11
i have only one currency and i don't use wpml

**Comment by minhcasi** [comment] 2020-08-16 02:11
@AhmedMaherPro - if it is possible please share your website admin login and also include your config & common folder from the folder project to our email inspireui.team@gmail.com - we will help to investigate this root cause, it could be the data config issue - thanks

**Comment by AhmedMaherPro** [comment] 2020-08-16 06:17
it's show price without taxes , how i can show price with tax in app ?

**Comment by minhcasi** [comment] 2020-08-17 01:46
@AhmedMaherPro - you could try to customize the Product Model to apply new Tax

The current Fluxstore app only support to display Tax from the other, display on product view is not available

**Comment by AhmedMaherPro** [comment] 2020-08-18 06:12
can you please response on mail

**Comment by minhcasi** [comment] 2020-08-18 07:06
Hi, could i know your email pls?

As the feature request is not supported by Fluxstore so that i'm losing the ticket, please let us know if you have other question. Thank you!

**Closed by minhcasi** 2020-08-18 07:06 UTC
Labels: FluxStore, webview-payment

**Comment by AhmedMaherPro** [comment] 2020-08-18 07:22
my mail :
ahmedmaher.programmer@gmail.com
i want to add some features , sol please response on me

**Comment by krdvijay** [comment] 2020-08-24 01:56
@AhmedMaherPro: Thanks a lot bro, it helped me achieve the expected results, appreciate your support.

**Comment by Alnaggar94** [comment] 2020-08-24 02:02
> please download file from this link
> https://www.mediafire.com/download/7461l9g711d34ah
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/7f8807270be2c6c01bc2e17336be5ec3999fb87d/68747470733a2f2f7374617469632e6d65646961666972652e636f6d2f696d616765732f66696c65747970652f646f776e6c6f61642f64656661756c742e6a7067">MediaFire**[payment_webview](http://www.mediafire.com/file/7461l9g711d34ah/payment_webview.dart/file)**MediaFire is a simple to use free service that lets you put all your photos, documents, music, and video in a single place so you can access them anywhere and share them everywhere.

@AhmedMaherPro - Thank you so much for sharing the file, I really appreciate that.

@minhcasi - I suggest you add it to the documentation because most of the users are using webview payment, it really make a difference when hiding the header and footer also some other stuff make it feel like native payment.

**Comment by AhmedMaherPro** [comment] 2020-08-24 06:25
> @AhmedMaherPro: Thanks a lot bro, it helped me achieve the expected results, appreciate your support.

you are welcome

**Comment by AhmedMaherPro** [comment] 2020-08-24 06:25
you are welcome

**Comment by amin5400** [comment] 2020-08-28 20:31
> you are welcome

ahmed can me talk to you ?

**Comment by AhmedMaherPro** [comment] 2020-08-28 20:53
yes , sure

**Comment by amin5400** [comment] 2020-08-28 22:20
@ami4ever
telegram

**Comment by AhmedMaherPro** [comment] 2020-08-28 22:58
send me your whatsapp
