### ISSUE TITLE
[fluxstore eccommerce  package name already in google] - 

### ISSUE THREAD

**Issue by khaledsalama32** [inspireui/support#2351] opened 2020-03-14 12:16 UTC
1. My issue:
please help me :
You need to use a different package name because "com.inspireui.fluxstore" already exists in Google Play.   

note :  i rename package name in my app 
![2020-03-14 (13)](https://user-images.githubusercontent.com/61389531/76681685-a73f4580-6606-11ea-9d3c-ad4162c488b1.png)
![3333](https://user-images.githubusercontent.com/61389531/76682245-685fbe80-660b-11ea-8172-2af527638155.png)

2. Screenshots issues (required):
![2020-03-14 (12)](https://user-images.githubusercontent.com/61389531/76681663-7101c600-6606-11ea-93f2-6702e8e8644d.png)

3. Proof of my purchased (required):
9e83ec40-8414-4b23-960d-0b69d207dd89
3. Config files (required)

**Comment by khaledsalama32** [comment] 2020-03-14 12:37
@minhcasi

**Comment by khaledsalama32** [comment] 2020-03-14 17:31
@minhcasi  Please do not answer me
can you help me

**Comment by themeix** [comment] 2020-03-14 20:52
Replace **com.inspireui.fluxstore** that to your own package name.
src\main\AndroidManifest.xml

**Comment by minhcasi** [comment] 2020-03-15 02:41
@khaledsalama32 - pls try this guide - https://docs.inspireui.com/fluxstore/customization/#1-app-nameicon-bundle-id - thanks

**Comment by khaledsalama32** [comment] 2020-03-15 14:09
after run my app   this is show me 



FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> No matching client found for package name 'com.facekuwait.teknetstore'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13m 32s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by khaledsalama32** [comment] 2020-03-16 05:40
@minhcasi  no answer sir ?

**Comment by minhcasi** [comment] 2020-03-19 08:11
Duplicate of #2357

**Closed by minhcasi** 2020-03-19 08:11 UTC
Labels: FluxStore, question ❓
