### ISSUE TITLE
My WordPress site store data not showing in android app but rather shows on ios and fluxbuilder. Using fluxstore 1.7.5. Thanks

### ISSUE THREAD

**Issue by Kenpo84** [inspireui/support#4325] opened 2020-07-23 03:00 UTC

**Comment by Kenpo84** [comment] 2020-07-23 03:02
Do I send my purchase code here?

**Comment by Kenpo84** [comment] 2020-07-23 03:06
![Screenshot_20200723-030358](https://user-images.githubusercontent.com/63457846/88248604-4c42ec80-cc91-11ea-9065-91d079afd008.jpg)

**Comment by ameenbadri7** [comment] 2020-07-24 00:11
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.
We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 
Thank you for your time!

**Comment by ameenbadri7** [comment] 2020-07-24 23:53
I'm sorry to close this ticket as there is no response or active conversation. 

Please help to create a new one and link to this ticket if the problem is not solved. 

- Thank you for your time!

**Closed by ameenbadri7** 2020-07-24 23:53 UTC
Labels: needs-more-info
