### ISSUE TITLE
[mstore-expo] - TYPE ERROR: Undefined is not an object...

### ISSUE THREAD

**Issue by khiemhuynh95** [inspireui/support#1096] opened 2019-09-22 01:12 UTC
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue
Hi, mình gặp lỗi này trên ipad air 2. Trên samsung tablet và iphone thì ko sao. Link hình: 
2. Screenshots
https://ibb.co/pd8YbFg

**Comment by minhcasi** [comment] 2019-09-22 04:05
Duplicate of #1098

**Closed by minhcasi** 2019-09-22 04:05 UTC
Labels: question ❓

**Comment by khiemhuynh95** [comment] 2019-09-22 05:08
Update: This error now happens on any devices
