### ISSUE TITLE
Installation error for mac

### ISSUE THREAD

**Issue by macahamed** [inspireui/support#3143] opened 2020-05-11 07:48 UTC

**Comment by minhcasi** [comment] 2020-05-11 09:15
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by macahamed** [comment] 2020-05-11 09:19
Hi install issue finished no problem, new doubt is how to complete flutter doctor installation, 2 thinngs not showing in your video, how to make tick, i send the screenshot also

![Screen Shot 2020-05-11 at 1 16 07 PM](https://user-images.githubusercontent.com/62641104/81545238-a4a06880-9389-11ea-9e79-61f47ce3340d.png)

**Comment by macahamed** [comment] 2020-05-11 10:27
no device available? this only issue, how to solve this issue in flutter doctor

**Comment by minhcasi** [comment] 2020-05-12 02:52
could you try to run this script to install cocopod first

```
sudo gem install cocoapods
```

**Comment by minhcasi** [comment] 2020-05-13 03:22
@macahamed - let us know if you have any update on this ticket :)

**Comment by macahamed** [comment] 2020-05-13 09:20
installation finished, after how to run your code, send me that video please, if you provide video for complete app easy for everyone? installation video very good

**Comment by macahamed** [comment] 2020-05-13 09:21
so please guide how to run your code? asap

**Comment by minhcasi** [comment] 2020-05-14 04:05
We have a lot of video on youtube - pls check this link https://www.youtube.com/watch?v=ReAUZDIgh2I

also subscribe to https://www.youtube.com/inspireui

**Comment by macahamed** [comment] 2020-05-14 10:57
ok i got video am doing like that, then
Why very slow while running app? everything very slow any solution

**Comment by macahamed** [comment] 2020-05-14 11:53
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running pod install...                                             61.3s
Running Xcode build...
Xcode build failed due to concurrent builds, will retry in 2 seconds.
Xcode build done.                                           923.1s
Could not find the built application bundle at build/ios/iphonesimulator/Runner.app.
Error launching application on iPhone 11 Pro Max.
![Screen Shot 2020-05-14 at 3 51 58 PM](https://user-images.githubusercontent.com/62641104/81931372-0a475b80-95fb-11ea-9878-dbb9888d3c64.png)

**Comment by minhcasi** [comment] 2020-05-15 02:53
@macahamed - you could zip the source and send us for investigating the issue - pls share via http://wetransfer.com/ to private email support@inspireui.com

**Comment by macahamed** [comment] 2020-05-16 06:22
You only give that file, i download from codecanyon from your recent update, i think the problem is run  in ios , means i run open Runner.xcodeproj or Runner.xcworkspace? open .Runner.xc is not correct? from xcode this app is runnimg open another simulator!

**Comment by macahamed** [comment] 2020-05-17 06:09
Till now you cannot solve my issue, and no reply also, please give any solution please reply!

**Comment by macahamed** [comment] 2020-05-17 06:21
how to create splash screen flr file? i change icon and logo, splash screen not changed!

**Comment by macahamed** [comment] 2020-05-17 09:03
I have already wordpress website, then api key for code and upload plugin thats only enough!

**Comment by macahamed** [comment] 2020-05-18 07:49
I have 3 issue,
1.My app is not running in ios, ios is very important please solve asap
2. i cannot change splash screen and for android icon is not good i send screesnshot
3. how to change home page

**Comment by macahamed** [comment] 2020-05-19 07:11
you send code in mail, ican use that code?

**Comment by minhcasi** [comment] 2020-05-19 12:52
Thank you, we got it

**Comment by minhcasi** [comment] 2020-05-19 12:54
@vumanhsn97 - pls help with checking - thank you!

**Comment by vumanhsn97** [comment] 2020-05-20 04:03
@macahamed 
Are you sure this code correctly? It's working in both android and ios. All data get from mstore.io and name app is different. https://tppr.me/Rp9gs

**Comment by macahamed** [comment] 2020-05-20 07:45
![Screen Shot 2020-05-20 at 11 39 21 AM](https://user-images.githubusercontent.com/62641104/82419365-58db7680-9a8f-11ea-9aa6-8b3941df2ced.png)
Check and update ? not proper response?

**Comment by vumanhsn97** [comment] 2020-05-20 08:26
@macahamed Checked! Everything working well in my devices. I research this error in the internet. Try this solution: open Runner.xcworkspace in ios folder by Xcode. Replace your app name to Runner. https://tppr.me/oYNYV follow this issue: https://stackoverflow.com/questions/57980900/flutter-could-not-find-the-built-application-bundle-at-build-ios-iphonesimulato. If it not working, you can sent your id and password teamview to vumanhsn97@gmail.com

**Comment by macahamed** [comment] 2020-05-20 10:40
ok thanks, i cannot change theme i follow your docs but not changing anything, i copy config theme 1 code paste to config en json, one more i try with config.json also no changes, pls guide me

**Comment by vumanhsn97** [comment] 2020-05-20 10:44
@macahamed 
Try with fluxbuilder. Download at: https://github.com/inspireui/fluxbuilder/releases

**Comment by macahamed** [comment] 2020-05-20 12:19
fluxbuilder is very good, my purchase is not working pls give suggestion, or am gng to buy again?

**Comment by vumanhsn97** [comment] 2020-05-21 03:57
@macahamed  Can you show more information about error in your purchase code?

**Comment by macahamed** [comment] 2020-05-21 07:45
am not purchase fluxbuilder pro, am purchase only fluxstore woocommerce, this purchase code will be working for fluxbuilder pro!!!!

**Comment by vumanhsn97** [comment] 2020-05-21 07:55
Fluxbuilder use purchase code in evanto. When you buy a product as fluxstore, you just enter this code into fluxbuilder in publish site to generate config json file

**Comment by macahamed** [comment] 2020-05-21 08:23
sorry am not understand, i can use this fluxstore purchase code or not?

**Comment by vumanhsn97** [comment] 2020-05-21 08:36
You can use this fluxstore purchase code. Try it!!!

**Comment by macahamed** [comment] 2020-05-21 09:59
yeah its working, after that where i paste that code

**Comment by macahamed** [comment] 2020-05-23 12:24
hi, how to run this in my iphone, pls tell how to get apk i want to share this app for demo?

**Comment by vumanhsn97** [comment] 2020-05-25 02:09
- To run in your iphone. Follow this document: https://docs.inspireui.com/fluxstore/delivery/
- To build apk release. Follow this document: https://docs.inspireui.com/fluxstore/delivery-android/

**Comment by minhcasi** [comment] 2020-05-28 03:00
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-05-28 03:00 UTC
Labels: FluxStore, common-installing ⁉️

**Comment by macahamed** [comment] 2020-05-28 07:22
![Screen Shot 2020-05-28 at 11 20 20 AM](https://user-images.githubusercontent.com/62641104/83111342-7cc53a80-a0d5-11ea-8fe9-73dbe1222fa6.png)

**Comment by macahamed** [comment] 2020-05-28 07:25
yes now am active, am doing to do get apk for demo and i want to change contact details can you please help?

**Comment by macahamed** [comment] 2020-05-28 07:26
you don't have any video for getting apk file?
