### ISSUE TITLE
flutter_svg 0.18.0 erros and not pod ınstall 

### ISSUE THREAD

**Issue by metinemredonmez** [inspireui/support#4869] opened 2020-09-04 07:12 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue
- [ ] second issue
- [ ] third issue

+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment] 2020-09-04 07:42
Duplicate of #4870 - pls help to comments your all issues into one ticket

**Closed by minhcasi** 2020-09-04 07:42 UTC
