### ISSUE TITLE
No title text 

### ISSUE THREAD

**Issue by hakihosting** [inspireui/support#309] opened 2019-02-16 18:20 UTC
**Required Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the bug**

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting
The title of text not showing 
![image](https://user-images.githubusercontent.com/47614045/52903588-e5a9db80-321f-11e9-8230-1bfd92b63f98.png)

**Comment by minhcasi** [comment] 2019-02-18 01:23
Duplicate of #301

**Closed by minhcasi** 2019-02-18 01:23 UTC
