### ISSUE TITLE
No route was found matching the url and request method

### ISSUE THREAD

**Issue by nishantbhandari** [inspireui/support#4764] opened 2020-08-27 09:48 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
I am trying to integrate facebook login on the fluxstore pro, I have done everything as per the steps provided in
https://medium.com/@inspireui/setup-facebook-login-for-flutter-apps-4e7bd031479d
But I am getting the following error when I click on the facebook login button 
"No route was found matching the url and request method"
+ Product & version:
+ Flutter (or React Native) version:  Flutter 1.20.2 
+ Testing Device/Simulator:  Device & Simulator
+ Screenshot issues (drag the file to attach here):  
![IMG_0782](https://user-images.githubusercontent.com/4096035/91425284-931b9780-e878-11ea-9c15-9567b57c8dd0.jpg)

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment] 2020-08-28 04:35
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-08-29 06:00
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-08-29 06:00 UTC
Labels: needs-more-info
