### ISSUE TITLE
Gmail Signup , SMS , Payments & Taxation , Product Thumbnail Issue

### ISSUE THREAD

**Issue by mailfordipak** [inspireui/support#4068] opened 2020-07-05 10:26 UTC
1) sign up issue on gmail / sms 
---------------------------------------
Gmail and sms not working for signup i have configured google json configuration file and Firebase. as it was mentioned in your documentation.

2) payment done but order not placed 
amount deducted from cards cart 
---------------------------------------
While placing order from razorpay payment gateway amount was deducted but order was not placed on store nor any confirmation given , screen return to previous payment page with showing some error on at "index:additional_data". also bank payment not working.

for Testing account : - shionaapp@gmail.com
Pwd :- admin@123

3) total calculation issue / GST Issue
---------------------------------------
Cart total amounts not calculated with proper GST tax amount and payment gateway fees on the cart payments.
Eg : 1000 Base Product Price and Customer Opted Online Payment GST 5% + Payment Gateway Fees 2 % Will Be Charges On Final Cart.

If You Have Configuration Instructions for Magento 2 Installation Regarding Taxation We can Arrange to Install.

  
4) product thumbnail issue on product page
--------------------------------------
product main thumbnail image low resolution 

5) push notification
--------------------------------------
new products notifications not shown to all registered users of the app , while new products added to store by admin.

i had followed all the documentations configuration that you have mentioned in your documentation , i am attaching whole configured application source code over the mail.

Above all points 1 to 4 we have attached snapshots of the issues on application , Please Get It Done as soon as possible .

I have validated my license in your google support ticket , kindly check.
I have also dropped an email with whole configured source of the app Please check with gmail.

Thanks & Regards

![issue 1](https://user-images.githubusercontent.com/67859061/86530616-c6285700-bed7-11ea-97ac-a8412b280ab5.jpeg)
![issue 2 extended](https://user-images.githubusercontent.com/67859061/86530620-c9234780-bed7-11ea-99cf-9172ee2453a7.jpeg)
![issue 2](https://user-images.githubusercontent.com/67859061/86530621-caed0b00-bed7-11ea-9af8-35fa48d3a24b.jpeg)
![issue 4](https://user-images.githubusercontent.com/67859061/86530622-cc1e3800-bed7-11ea-80e9-7d0f7da7bb74.jpeg)

**Comment by ameenbadri7** [comment] 2020-07-05 17:33
@mailfordipak 
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-07-06 11:26
@mailfordipak - the config is share to your email ;)

**Comment by ameenbadri7** [comment] 2020-07-08 04:32
I'm sorry to close this ticket as there is no response or active conversation, 
please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Comment by minhcasi** [comment] 2020-07-08 07:39
@ameenbadri7 - pls help to investigate this issue

**Comment by mailfordipak** [comment] 2020-07-09 07:37
Hello, Sir I have had Discussion on the support mail , with all source code and details , if needed to resubmit please provide your mail id so i can arrange to forward the source code again , please arrange to fix the code issues on a priority because mobile app is given to hundreds of users for real time testing and having much issues on business front.

Regards

**Comment by minhcasi** [comment] 2020-07-09 10:19
Hi @mailfordipak, we have investigated the source and found out some heavy customization source - https://tppr.me/Ixd8i - Checking and fixing the issues will take us a lot of time and not include from our support scope - https://inspireui.com/support-policies/

Please try your best to custom the project.

**Comment by mailfordipak** [comment] 2020-07-09 11:43
> 
> 
> Hi @mailfordipak, we have investigated the source and found out some heavy customization source - https://tppr.me/Ixd8i - Checking and fixing the issues will take us a lot of time and not include from our support scope - https://inspireui.com/support-policies/
> 
> Please try your best to custom the project.
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/5897675be6c6d482f8f4026236cc8fc870f1a487/68747470733a2f2f747070722e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f66373639643732656466663666646437353333346130636632316461626534312e6a7067"><img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public - Sourcetree_2020-07-09 15-04-33](https://tppr.me/Ixd8i)**
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/976a4293be95e930377b7da44ce9072e74dc2a8b/68747470733a2f2f696e737069726575692e636f6d2f77702d636f6e74656e742f7468656d65732f626f6f2f66617669636f6e2e69636f"><img alt="" height="14" src="https://camo.githubusercontent.com/aa02ab50e73c96a1d2d47b04d9ce85a0bde895c9/68747470733a2f2f696e737069726575692e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031382f30312f63726f707065642d69636f6e2d6661766f726974652d313932783139322e706e67"> InspireUI**[Support Policies » InspireUI](https://inspireui.com/support-policies/)**This Support Policies apply to all products from InspireUI Ltd and takes effect as of July 1, 2020

Sir Vary First Issue is with Taxation Where Tax and Attributes have no things connected , Taxation only concerns to Order API in Your Mobile App structure where thats not working , Product Thumbnails , again Media storage or Processing dosent seems to have any concerns with back end product attributes nor we have anything attached to media images in terms of attributes...Gmail is separate entity which works with mobile app...where we did nothing again. How come this complete issue is out of your support criteria sir ?

anyways , Please do Proceed for Order Amount Refund , will look for " Better Working Options Without Arguments or Baseless Reasons ".

Kudos to Your Brilliant Technical Team Again ,

**Comment by mailfordipak** [comment] 2020-07-09 12:04
Sir Vary First Issue is with Taxation Where Tax and Attributes have no things connected , Taxation only concerns to Order API in Your Mobile App structure where thats not working , Product Thumbnails , again Media storage or Processing dosent seems to have any concerns with back end product attributes nor we have anything attached to media images in terms of attributes...Gmail is separate entity which works with mobile app...where we did nothing again. How come this complete issue is out of your support criteria sir ?
Whout Basic configuration or customization the app is not useful for us, so please do one thing resolve all my issues on your source and provide me gitlab access. I'll merge it myself. to see if that works else fix the thing and get me proper working code this is vary much frustrating to wait for an answer or things to get done for no good .

**Comment by mailfordipak** [comment] 2020-07-09 12:04
> 
> 
> Hi @mailfordipak, we have investigated the source and found out some heavy customization source - https://tppr.me/Ixd8i - Checking and fixing the issues will take us a lot of time and not include from our support scope - https://inspireui.com/support-policies/
> 
> Please try your best to custom the project.
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/5897675be6c6d482f8f4026236cc8fc870f1a487/68747470733a2f2f747070722e73332e616d617a6f6e6177732e636f6d2f75706c6f6164732f66373639643732656466663666646437353333346130636632316461626534312e6a7067"><img alt="" height="14" src="/favicon-32x32.png"> tppr.me**[Public - Sourcetree_2020-07-09 15-04-33](https://tppr.me/Ixd8i)**
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/976a4293be95e930377b7da44ce9072e74dc2a8b/68747470733a2f2f696e737069726575692e636f6d2f77702d636f6e74656e742f7468656d65732f626f6f2f66617669636f6e2e69636f"><img alt="" height="14" src="https://camo.githubusercontent.com/aa02ab50e73c96a1d2d47b04d9ce85a0bde895c9/68747470733a2f2f696e737069726575692e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031382f30312f63726f707065642d69636f6e2d6661766f726974652d313932783139322e706e67"> InspireUI**[Support Policies » InspireUI](https://inspireui.com/support-policies/)**This Support Policies apply to all products from InspireUI Ltd and takes effect as of July 1, 2020

 Sir Vary First Issue is with Taxation Where Tax and Attributes have no things connected , Taxation only concerns to Order API in Your Mobile App structure where thats not working , Product Thumbnails , again Media storage or Processing dosent seems to have any concerns with back end product attributes nor we have anything attached to media images in terms of attributes...Gmail is separate entity which works with mobile app...where we did nothing again. How come this complete issue is out of your support criteria sir ?
Whout Basic configuration or customization the app is not useful for us, so please do one thing resolve all my issues on your source and provide me gitlab access. I'll merge it myself. to see if that works else fix the thing and get me proper working code this is vary much frustrating to wait for an answer or things to get done for no good .

**Comment by mailfordipak** [comment] 2020-07-09 12:06
@minhcasi Seems Your Technical Developement Team is Not Intrested to Solve the Customer Issues , Kindly Suggest a Better Option further.

**Comment by mailfordipak** [comment] 2020-07-09 12:43
![Screenshot_20200709-181005](https://user-images.githubusercontent.com/67859061/87041240-934fcd00-c20f-11ea-92cc-cce7c1dc2d59.jpg)
@minhcasi @ameenbadri7 @luyx2412 @trunghieuvn 
This New thing We Saw Today In Your Code , Once the End User Removes Product from Mobile app still that charges the shipping to newly added product from previous order...check in snapshot where it meant to show shipping charges 500/- thats showing 1500/- for 1 product in cart in total.
flat shipping per product is 500/-
Please Explain.

Regards

**Comment by minhcasi** [comment] 2020-07-10 02:58
@mailfordipak - sorry it is a limitation from the Fluxstore app, as we could only deliver the available same as our demo app and ads. You could use the app to add more customize features to meet your requirements.

The Taxation is also not supported by the WooCommerce API so that it is a complex feature that we could not fix from the app. If you are not satisfied with the app feature, it is possible to process the refund. 

We sincerely apologize for the delay and thank you for your patience.

**Closed** 2020-07-13 12:35 UTC
Labels: FluxStore
