### ISSUE TITLE
Mstore Plugin API WordPress Issue "The purchase code is incorrect."

### ISSUE THREAD

**Issue by swapnildesai5** [inspireui/support#4209] opened 2020-07-15 09:55 UTC
When i try to put purchase code in the Mstore Api Plugin error pops up as "The purchase code is incorrect." with an error showing "string(94) "{"error":"Please fill the Email and App Name, also update to the latest Fluxbuilder release!"}""

I want app to be enabled on one domain only which is https://vistamall.co.tz/ as and according to your guidelines

Thank You

**Comment by ameenbadri7** [comment] 2020-07-15 17:25
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 
Thank you for your time!

**Comment by minhcasi** [comment] 2020-07-16 01:48
@swapnildesai5 - pls update the latest mstore-api plugin from this link https://wordpress.org/plugins/mstore-api/ - thank you!

**Comment by minhcasi** [comment] 2020-07-17 04:26
Duplicate of #4226

**Closed by minhcasi** 2020-07-17 04:26 UTC
Labels: FluxstoreMV
