### ISSUE TITLE
fluxstore woocommerce app issue images and categories part is not seen in app which is design by using fluxbuilder

### ISSUE THREAD

**Issue by alokmalewar** [inspireui/support#4586] opened 2020-08-13 12:09 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue
- [ ] second issue
- [ ] third issue

+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment] 2020-08-13 23:55
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by alokmalewar** [comment] 2020-08-14 06:26
Sir,
In the mail you are saying not to share the purchase code or screenshot
public here as another user will use it for activation and in the drive it
is asking for proof of purchased licensed pdf file. what to do now.

‪On Fri, Aug 14, 2020 at 5:25 AM ‫amin badri أمين بدري‬‎ <
notifications@github.com> wrote:‬

**Comment by minhcasi** [comment] 2020-08-15 03:30
@alokmalewar - pls help to submit private via this from - http://verify.inspireui.com - you need only submit one time for the first ticket - thank you!

**Comment by minhcasi** [comment] 2020-08-16 02:01
Hi @alokmalewar - I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-08-16 02:01 UTC
Labels: needs-more-info
