### ISSUE TITLE
Login & Signup Not Working

### ISSUE THREAD

**Issue by hackzie** [inspireui/support#3242] opened 2020-05-17 14:11 UTC
I have followed all the steps correctly but the login/signup section in the app is not working. Please suggest me some solution.

**Comment by trunghieuvn** [comment] 2020-05-17 15:50
![](https://camo.githubusercontent.com/8f47913622e766b5ce1b1b708b84d26e79e8b8cb/68747470733a2f2f70617065722d6174746163686d656e74732e64726f70626f782e636f6d2f735f374639353545393338374233334239383330333638413134353733413033303041383842383032443337343733413646393846413938423344464144334343445f313538383734353334363534335f696d6167652e706e67)

Please change bundle id (package name) and get SHA1 key add to console firebase  
https://github.com/inspireui/support/wiki/Setup-login-with-Google

**Comment by minhcasi** [comment] 2020-05-18 04:06
Duplicate of #3151

@hackzie - pls move the conversation to same ticket

**Closed by minhcasi** 2020-05-18 04:06 UTC
