### ISSUE TITLE
Error fatal activating MstoreAPI

### ISSUE THREAD

**Issue by inspireuis** [inspireui/support#3161] opened 2020-05-12 08:12 UTC
Good Day InspireUi,

Step 1 (require): detail issues and screenshots

im getting the next error when im trying to activate the mstoreAPI Plugin,

Fatal error: Cannot declare class MstoreCheckOut, because the name is already in use in /home/jobyas82/public_html/wp-content/plugins/mstore-api/mstore-api.php on line 24

![image](https://user-images.githubusercontent.com/65219388/81658013-01d60180-93fe-11ea-9e3b-a7d60a394d11.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment] 2020-05-12 10:53
@inspireuis - on the Fluxstore Listing - you only need to install the Listapp Manager Plugin (mstore-api is not required for this product) - thank you!

**Comment by minhcasi** [comment] 2020-05-13 01:55
Duplicate of #3170

**Closed by minhcasi** 2020-05-13 01:55 UTC
Labels: FluxstoreMV
