### ISSUE TITLE
product quantity to My Wishlist page

### ISSUE THREAD

**Issue by niranjan62** [inspireui/support#4506] opened 2020-08-07 08:09 UTC
1. How to add product quantity to My Wishlist page?

![Wishlist---add-count](https://user-images.githubusercontent.com/69341826/89623749-13a83300-d88d-11ea-9f17-19561ccc0a78.png)

2. App Footer Checkout icon showing quantity of the total products. can you change that function to show products count (Don't use quantity field)?

**Comment by ameenbadri7** [comment] 2020-08-08 01:16
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

and please try to merge your open tickets on one ticket next time .. 
Thank you for your time!

**Comment by minhcasi** [comment] 2020-08-09 02:59
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-08-09 02:59 UTC
Labels: needs-more-info
