### ISSUE TITLE
pod install faild

### ISSUE THREAD

**Issue by rasel6999** [inspireui/support#4069] opened 2020-07-05 15:36 UTC
**  Product =  Fluxstore Pro - Flutter 
**  version =  1.7.5 
** Testing Device/Simulator = problem while building app

I can't install the pod file.  I already attach screenshot app command.

error::===

[!] Error installing FBAudienceNetwork
[!] /usr/bin/curl -f -L -o /var/folders/13/0hdhg6mx3w35k1893tjgb2mr0000gn/T/d20200705-1271-xeiny3/file.zip https://developers.facebook.com/resources/FBAudienceNetwork-5.8.0.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
Warning: Transient problem: HTTP error Will retry in 1 seconds. 2 retries 
Warning: left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
Warning: Transient problem: HTTP error Will retry in 2 seconds. 1 retries 
Warning: left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 500 

[!] Automatically assigning platform `iOS` with version `10.3` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] Automatically assigning platform `iOS` with version `10.3` on target `OneSignalNotificationServiceExtension` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

<img width="1440" alt="Screen Shot 2020-07-05 at 7 27 11 PM" src="https://user-images.githubusercontent.com/17203863/86536076-d6e7c580-bef5-11ea-8b81-2b98323212d2.png">
_**

**Comment by ameenbadri7** [comment] 2020-07-05 17:33
@rasel6999 
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by ameenbadri7** [comment] 2020-07-05 17:38
@rasel6999 
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by rasel6999** [comment] 2020-07-05 19:43
Hello bro. I already submit my form. Ease chake. Username rasel6999

**Comment by rasel6999** [comment] 2020-07-05 19:45
![Screenshot_20200705-234447_Gmail](https://user-images.githubusercontent.com/17203863/86540929-969a3e80-bf19-11ea-9baf-6412d35fea54.jpg)

**Comment by minhcasi** [comment] 2020-07-06 02:20
@rasel6999 - there is some pod install issue could be caused by the network - pls help try clean up the cache on flutter - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

Could you also send us the result from `flutter doctor` ?

Thank you!

**Closed** 2020-07-08 02:55 UTC
Labels: FluxStore, ios-build-fail

**Comment by rasel6999** [comment] 2020-07-09 05:25
Hi bro, is possible tp set Custom group name in  horizonLayout category??  I wanna put custom name in. Json file    
![Screenshot_20200709-092049](https://user-images.githubusercontent.com/17203863/87000374-fae12a80-c1c5-11ea-8c24-34b7c7bed8b2.jpg)
