### ISSUE TITLE
FluxStore Pro 1.6.1 (Magento 2) Custom options not showing

### ISSUE THREAD

**Issue by Abhiv66** [inspireui/support#1646] opened 2019-12-19 19:44 UTC
1. My issue:
Not getting custom_options in app of any product  due to which i can't select options in product.
and also not got solved previous issue of payment which is urgent too urgent

2. Screenshots issues:
![Screenshot_2019-12-20-01-12-08-568_com inspireui fluxstore](https://user-images.githubusercontent.com/58973413/71204315-dd01b600-22c5-11ea-9a18-2845c858b57c.jpg)

3. Proof of my purchased:
Already given in the #1630 

4. Config files (optional)
Send to email

**Comment by minhcasi** [comment] 2019-12-20 00:37
Duplicate of #1630

**Closed by minhcasi** 2019-12-20 00:37 UTC
Labels: question ❓
