### ISSUE TITLE
Fluxstore Multi Vendor Version: 1.7.5 Cant show Vendor on this app

### ISSUE THREAD

**Issue by attare026** [inspireui/support#3735] opened 2020-06-14 18:00 UTC
+ I will use a dokan plugin but I can't show Store on the category page!  I can't find dokan rest API and I cant show my products on the setting page! please help!
+ Multi Vendor Version: 1.7.5
+ 1
+ Note 7 Pro Android 10
+ 
![IMG_20200614_235503](https://user-images.githubusercontent.com/34741721/84600455-1d1fab00-ae9b-11ea-9566-0a1a48968e38.jpg)
![IMG_20200614_235635](https://user-images.githubusercontent.com/34741721/84600456-201a9b80-ae9b-11ea-8570-fe437c58f2da.jpg)

![image](https://user-images.githubusercontent.com/34741721/84600416-dfbb1d80-ae9a-11ea-8eec-2e80f08e13d8.png)
![image](https://user-images.githubusercontent.com/34741721/84600429-fd888280-ae9a-11ea-85f8-054dbf4dd8ff.png)

**Comment by minhcasi** [comment] 2020-06-15 04:05
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by attare026** [comment] 2020-06-15 04:25
I am already submitted my license pdf on your Google form please check!

**Comment by attare026** [comment] 2020-06-15 05:24
please check it!

**Comment by attare026** [comment] 2020-06-15 11:24
Waiting for your response! 😣

**Comment by minhcasi** [comment] 2020-06-15 11:54
@attare026  - we got your verify - could i know which the plugin Dokan you are using? the Rest API will come with the Dokan plugin after installing ?

**Comment by attare026** [comment] 2020-06-15 12:37
> @attare026 - we got your verify - could I know which the plugin Dokan you are using? the Rest API will come with the Dokan plugin after installing?

i will use ![image](https://user-images.githubusercontent.com/34741721/84657971-f31bc680-af36-11ea-92b3-ecd90b4f7899.png) 
can you themviwer I will show you!

**Comment by attare026** [comment] 2020-06-15 12:51
why can't give the proper video for the setup!

**Comment by attare026** [comment] 2020-06-15 16:15
> @attare026 - we got your verify - could i know which the plugin Dokan you are using? the Rest API will come with the Dokan plugin after installing ?

Waiting for your response! 😣

**Comment by attare026** [comment] 2020-06-16 09:14
hello anyone can replay?

**Comment by minhcasi** [comment] 2020-06-16 10:39
@attare026 

We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.
We sincerely apologize for the delay and hope you’re staying safe.

@kvt0012 - pls help with investigating

**Comment by attare026** [comment] 2020-06-16 12:12
Please Fixed my Issue! I bought your product with high hopes! But I can't do any vendor on my store section when I use wcfm product not showing!

**Comment by attare026** [comment] 2020-06-16 12:12
> @attare026
> 
> We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.
> We sincerely apologize for the delay and hope you’re staying safe.
> 
> @kvt0012 - pls help with investigating

Please Fixed my Issue! I bought your product with high hopes! But I can't do any vendor on my store section when I use wcfm product not showing!

**Comment by attare026** [comment] 2020-06-17 21:05
If your team can't support please directly say i can't help you!

**Comment by minhcasi** [comment] 2020-06-18 04:14
@attare026 - sorry for the late response - I've updated the ticket as a high priority.

@philipvu30 - pls help with investigating

**Comment by attare026** [comment] 2020-06-18 06:18
Thanks! if I use WCFM plugin in the category no product show!
After I face this issue I will go to the dokan plugin but here are some other error face in-store section no store found I will create too many vendors but not found any store!

**Comment by philipvu30** [comment] 2020-06-18 06:40
Hi,

Do you have access to our GitLab Repository? If you do, please pull the latest source code on it.
It seems fine to me on the latest version pre-1.7.6. Otherwise,  I'll send you the lib folder via email.

Thank you.

**Comment by attare026** [comment] 2020-06-18 06:47
> Hi,
> 
> Do you have access to our GitLab Repository? If you do, please pull the latest source code on it.
> It seems fine to me on the latest version pre-1.7.6. Otherwise, I'll send you the lib folder via email.
> Also, please install/update MStore API to the latest version.
> 
> Thank you.

okay I will check

**Comment by attare026** [comment] 2020-06-18 06:50
can you tell me which plugin here work perfectly?

**Comment by philipvu30** [comment] 2020-06-18 06:58
Hi,

Currently, our Dokan demo website/app uses these plugins:
- MStore API
- Dokan
- Dokan Pro
- Better REST API Featured Images
- Regenerate Thumbnails
- Default WooCommerce

**Comment by attare026** [comment] 2020-06-18 07:35
![image](https://user-images.githubusercontent.com/34741721/84991538-753f0180-b168-11ea-8cb5-61c1c7fb3c5a.png)
i will upload here config.json?
its work?

**Comment by philipvu30** [comment] 2020-06-18 07:42
Hi,

If you decide to use this feature, your app won't be able to use Multi-Languages in the app.

**Comment by attare026** [comment] 2020-06-18 07:48
I don't need Multi-Languages how can I enable it?

> Hi,
> 
> If you decide to use this feature, your app won't be able to use Multi-Languages in the app.

**Comment by attare026** [comment] 2020-06-18 07:59
![product upload problem](https://user-images.githubusercontent.com/34741721/84993639-60b03880-b16b-11ea-9f7d-c3ac4b48fa0b.gif)
When I Create a new product chose my product picture is not an open gallery. its open camera when I click the picture and conformed it app was restart! 
how can I fixed it!

**Comment by philipvu30** [comment] 2020-06-18 08:04
Hi,

1. In lib/common/config/general.dart, find **const kAppConfig = 'lib/config/config_en.json';** and change it to your config.json url like this: your-website-url/wp-content/uploads/2000/01/config.json
2. In lib/vendor/products/widgets/select_image.dart, find this function _getImageFromGallery and change this term from ImageSource.camera -> ImageSource.gallery.

**Comment by attare026** [comment] 2020-06-18 08:55
![image](https://user-images.githubusercontent.com/34741721/85000021-ac66e000-b173-11ea-8913-1dbdcbe37717.png)

**Comment by philipvu30** [comment] 2020-06-18 09:20
Hi,

Could you give a more detailed explanation of this error instead of posting only an error picture? 
How did you get it? Was this your first attempt to upload the product or second/third attempt? 

My apologies for the troublesome but we really do not have enough time to reproduce your issue.
Thank you.

**Comment by attare026** [comment] 2020-06-18 09:42
When I press post product then show like this error
![product upload problem](https://user-images.githubusercontent.com/34741721/85005217-4b8ed600-b17a-11ea-9865-e1efe8cfd758.gif)

**Comment by philipvu30** [comment] 2020-06-18 10:25
Hi,

Please remove the extra slash at the end of your URL in config.dart file and try again.

Thanks.

**Comment by attare026** [comment] 2020-06-18 10:49
> Hi,
> 
> Please remove the extra slash at the end of your URL in config.dart file and try again.
> 
> Thanks.
Same Problem I delete to build folder and again full app build 
but the same issue 
![product upload problem](https://user-images.githubusercontent.com/34741721/85011597-8fd2a400-b183-11ea-8ca8-0b30cfdec03e.gif)

**Comment by philipvu30** [comment] 2020-06-18 10:59
Hi,

Please send a support account of your website to my email: toan@inspireui.com.
I'll help you check the issue tmr.

**Comment by attare026** [comment] 2020-06-18 13:14
> Hi,
> 
> Please send a support account of your website to my email: [toan@inspireui.com](mailto:toan@inspireui.com).
> I'll help you check the issue tmr.

Check your i will give you assess of my website

**Comment by rabahaldoori** [comment] 2020-06-19 10:10
@attare026 i had same problem 

replace this "products" file will work with you 

lib/vendor/products

[products.zip](https://github.com/inspireui/support/files/4803899/products.zip)

**Comment by attare026** [comment] 2020-06-19 12:55
when I complete ordering its redirect on the website checkout

**Comment by attare026** [comment] 2020-06-19 12:57
when you add a product to cart and continue to checkout instead of submitting the Order redirect us in checkout page as webview

**Comment by attare026** [comment] 2020-06-20 10:23
> @attare026 i had same problem
> 
> replace this "products" file will work with you
> 
> lib/vendor/products
> 
> [products.zip](https://github.com/inspireui/support/files/4803899/products.zip)

After replace i was face same error

**Comment by attare026** [comment] 2020-06-20 16:22
![product upload problem](https://user-images.githubusercontent.com/34741721/85206484-4aa9a000-b344-11ea-8145-429d4daa3f3e.gif)
if I upload whit image show like this error when I remove it product it's uploaded

**Comment by attare026** [comment] 2020-06-21 06:58
Hello!!!!

**Comment by attare026** [comment] 2020-06-21 10:52
Now parches 10 days above but still i have got no solution

**Comment by philipvu30** [comment] 2020-06-22 03:03
Hi

Sorry for the delayed response but we do not work at the weekends. I was trying to access your website last Friday without success and already sent you the issue via email. 
It seems your website is back. I'm working on your issue right now.

Thank you for your patience.

**Comment by philipvu30** [comment] 2020-06-22 03:43
Hi,

```
Warning: array_key_exists() expects parameter 2 to be array, null given in /home4/oneshknj/public_html/wp-includes/rest-api/class-wp-rest-request.php on line 412

Warning: array_key_exists() expects parameter 2 to be array, null given in /home4/oneshknj/public_html/wp-includes/rest-api/class-wp-rest-request.php on line 412

Warning: Cannot modify header information - headers already sent by (output started at /home4/oneshknj/public_html/wp-includes/rest-api/class-wp-rest-request.php:412) in /home4/oneshknj/public_html/wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php on line 192

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 36636672 bytes) in /home4/oneshknj/public_html/wp-includes/deprecated.php on line 3193
```

Please fix the Fatal error on your server by setting memory_limit to exceed 36636672 bytes. You can refer to this [solution](https://haydenjames.io/understanding-php-memory_limit/).

Thank you.

**Comment by attare026** [comment] 2020-06-22 05:55
Where you find this error?

**Comment by attare026** [comment] 2020-06-22 06:01
I will update my PHP version Please check now

**Comment by attare026** [comment] 2020-06-22 06:20
> Hi,
> 
> ```
> Warning: array_key_exists() expects parameter 2 to be array, null given in /home4/oneshknj/public_html/wp-includes/rest-api/class-wp-rest-request.php on line 412
> 
> Warning: array_key_exists() expects parameter 2 to be array, null given in /home4/oneshknj/public_html/wp-includes/rest-api/class-wp-rest-request.php on line 412
> 
> Warning: Cannot modify header information - headers already sent by (output started at /home4/oneshknj/public_html/wp-includes/rest-api/class-wp-rest-request.php:412) in /home4/oneshknj/public_html/wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php on line 192
> 
> Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 36636672 bytes) in /home4/oneshknj/public_html/wp-includes/deprecated.php on line 3193
> ```
> 
> Please fix the Fatal error on your server by setting memory_limit to exceed 36636672 bytes. You can refer to this [solution](https://haydenjames.io/understanding-php-memory_limit/).
> 
> Thank you.

I will update it please check it now

**Comment by philipvu30** [comment] 2020-06-22 07:48
Hi,

Please turn off debug mode on your website and it should be good to upload the product.
Also in lib/vendor/products/widgets/select_image.dart, please add these attributes to reduce the size of the uploaded images.
Thank you.

- Turn off warning errors in apache server or disable the debug mode in wp-config.php
![image](https://user-images.githubusercontent.com/54442328/85261991-4b068000-b497-11ea-978a-de6e39d6acf5.png)

- Reduce image size.
![image](https://user-images.githubusercontent.com/54442328/85262045-62456d80-b497-11ea-89bc-e65c64455df1.png)

**Comment by attare026** [comment] 2020-06-22 16:08
> Hi,
> 
> Please turn off debug mode on your website and it should be good to upload the product.
> Also in lib/vendor/products/widgets/select_image.dart, please add these attributes to reduce the size of the uploaded images.
> Thank you.
> 
> * Turn off warning errors in apache server or disable the debug mode in wp-config.php
>   ![image](https://user-images.githubusercontent.com/54442328/85261991-4b068000-b497-11ea-978a-de6e39d6acf5.png)
> * Reduce image size.
>   ![image](https://user-images.githubusercontent.com/54442328/85262045-62456d80-b497-11ea-89bc-e65c64455df1.png)

debug mode is not issued now!
![image](https://user-images.githubusercontent.com/34741721/85309338-47451e80-b4d4-11ea-987a-8fed55217eb8.png)
I will try more 10 times but still face this issue! can tell me on your side its work or not??

**Comment by philipvu30** [comment] 2020-06-23 02:44
No. It's not working on your website.

As you can see, below the warning errors are the result that helps to upload the product. But it cannot get it because of the warnings.
You can refer to this [answer](https://stackoverflow.com/questions/46775591/how-to-disable-error-message-in-rest-api-output) to hide those errors.

Thank you.

**Comment by attare026** [comment] 2020-06-23 06:02
> No. It's not working on your website.
> 
> As you can see, below the warning errors are the result that helps to upload the product. But it cannot get it because of the warnings.
> You can refer to this [answer](https://stackoverflow.com/questions/46775591/how-to-disable-error-message-in-rest-api-output) to hide those errors.
> 
> Thank you.

![image](https://user-images.githubusercontent.com/34741721/85366325-eefc3400-b548-11ea-9dfb-4ce7b653f37b.png)
I can't find any error 
![image](https://user-images.githubusercontent.com/34741721/85366371-0cc99900-b549-11ea-8abc-f8bfc67dbb60.png)
please fix my issue!
if you need any access I will give you please fix my issue!

**Comment by philipvu30** [comment] 2020-06-23 06:44
Hi,

Add this line **@ini_set('display_errors', 1);** under the WP_DEBUG. Then I'll help you check the issue again.

Thank you.

**Comment by attare026** [comment] 2020-06-23 07:05
> @ini_set('display_errors', 1);

done

**Comment by attare026** [comment] 2020-06-23 09:52
I will check on localhost same problem

**Comment by philipvu30** [comment] 2020-06-23 10:44
Hi,

It was my mistake. Please change this @ini_set('display_errors', 1);  from 1 to 0.
If it still cannot solve your issue, please follow these [solution 1](https://serverfault.com/questions/509559/change-php-error-reporting-to-hide-warnings-for-specific-site-only-debianubunt) and [solution 2](https://serverfault.com/questions/263167/disabling-php-deprecation-warnings-and-notices)

Thank you.

**Comment by attare026** [comment] 2020-06-23 15:08
please check your email I will give you access my website file manager

**Comment by attare026** [comment] 2020-06-25 07:48
Have you any solution?

**Comment by philipvu30** [comment] 2020-06-25 08:27
Hi,

Would you mind testing it again?

Thank you.

**Comment by attare026** [comment] 2020-06-26 06:12
> Hi,
> 
> Would you mind testing it again?
> 
> Thank you.

Yeah!

**Comment by philipvu30** [comment] 2020-06-26 06:26
Did it work?

**Comment by attare026** [comment] 2020-06-26 08:12
> Did it work?
I will fix it but the product is not published show on draft!

**Comment by philipvu30** [comment] 2020-06-26 08:19
Hi,

It's supposed to be like that for admin to approve the product. If you don't want this behavior, please add this line of code to this file lib/models/product/product_model.dart
![image](https://user-images.githubusercontent.com/54442328/85836137-5e2f8d80-b7c0-11ea-948a-ba8d73d9fbf5.png)

**Comment by attare026** [comment] 2020-06-26 11:11
![image](https://user-images.githubusercontent.com/34741721/85851170-0731b480-b7d0-11ea-9cf2-608034a6806e.png)
I do not want this icon here how can remove it?

**Comment by philipvu30** [comment] 2020-06-26 11:13
There is a variable called kDefaultDrawer in lib/common/config/general.dart. Set it there.

**Comment by attare026** [comment] 2020-06-26 11:44
> ![image](https://user-images.githubusercontent.com/34741721/85851170-0731b480-b7d0-11ea-9cf2-608034a6806e.png)
> I do not want this icon here how can remove it?

Here no icon change operation bro!

**Comment by philipvu30** [comment] 2020-06-29 03:04
Hi,

In lib/screens/settings/settings.dart, remove these lines
![image](https://user-images.githubusercontent.com/54442328/85968684-ee9fe500-b9ef-11ea-9bb5-e1a27eeeb12c.png)

**Comment by philipvu30** [comment] 2020-07-01 04:17
Closed as no response in 2 days. 

If you are happy with our services/support, would you mind rating us on your [download page](https://codecanyon.net/downloads)?
We truly appreciate your help.

**Closed by philipvu30** 2020-07-01 04:17 UTC
Labels: FluxstoreMV, priority !!!

**Comment by attare026** [comment] 2020-07-18 16:33
https://streamable.com/p3ovwl
I want to like that on my app when past this code on my app show only 10 products!
How to show here all products! Like your demo!
