### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by MaNoOoz** [inspireui/support#4413] opened 2020-07-29 19:10 UTC
**Build failed awesome_card stuff** 

`Target debug_android_application failed: FileSystemException: Cannot copy file to 'H:\WORK\FreeLance\codecanyon-G146ryl1-fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework\FluxStore-pro-1.7.6\source\build\app\intermediates\flutter\debug\flutter_assets\packages/awesome_card/images/card_provider/american_express.png', path = 'H:\FlutterSDK\.pub-cache\hosted\pub.dartlang.org\awesome_card-1.1.0\images\card_provider\american_express.png' (OS Error: The system cannot find the path specified.
, errno = 3)
build failed.`

**Comment by ameenbadri7** [comment] 2020-07-30 00:28
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.
We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by minhcasi** [comment] 2020-07-30 07:55
Duplicate of #4417

**Closed by minhcasi** 2020-07-30 07:55 UTC
Labels: needs-more-info
