### ISSUE TITLE
Categories is synced but products from woocommerce are not showing in app

### ISSUE THREAD

**Issue by AbimaelASilva** [inspireui/support#3916] opened 2020-06-26 02:18 UTC
Categories is synced but products from woocommerce are not showing in app.

My problem is the same as other colleagues are facing.

The products we register with woocommerce does not appear in the app

**Comment by minhcasi** [comment] 2020-06-26 02:31
Duplicate of #3915

**Closed by minhcasi** 2020-06-26 02:31 UTC
