### ISSUE TITLE
When the product has more than one model and when choosing any model this error message appears

### ISSUE THREAD

**Issue by hssinaman** [inspireui/support#3660] opened 2020-06-09 21:16 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 

When the product has more than one model and when choosing any model this error message appears

+ Fluxstore Version: 1.7.4

![1](https://user-images.githubusercontent.com/61097607/84200227-4d7fd780-aa9e-11ea-82fc-ea6dc37db69e.jpeg)
![2](https://user-images.githubusercontent.com/61097607/84200241-51135e80-aa9e-11ea-930c-13887db4202c.jpeg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by hssinaman** [comment] 2020-06-09 21:21
Hi can you help please ?

**Comment by minhcasi** [comment] 2020-06-10 02:51
@hssinaman - this issue is already fixed on the latest one, please merge the fixing from gitlab - thank you!

**Comment by minhcasi** [comment] 2020-06-12 05:38
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-06-12 05:38 UTC
Labels: FluxStore
