### ISSUE TITLE
At shipping getting Exception: No route was found matching the URL and request method fluxstore version 1.7.7

### ISSUE THREAD

**Issue by BasitAmin** [inspireui/support#5044] opened 2020-09-23 01:49 UTC
No route was found matching the URL and request method flux store version 1.7.7
![image](https://user-images.githubusercontent.com/35036635/93955294-d9292580-fd68-11ea-82f0-6ba840145f96.png)

**Comment by minhcasi** [comment] 2020-09-23 03:45
Duplicate of #5006

**Closed by minhcasi** 2020-09-23 03:45 UTC
