### ISSUE TITLE
"Sorry you cannot list resources" and the bottom would disappear

### ISSUE THREAD

**Issue by victor0618** [inspireui/support#4138] opened 2020-07-09 09:02 UTC
+ Detail Issues: I want to point MStore Pro app to WordPress instance. After I changed to the website URL and the wooCommerce API consumeKey, it shows "Sorry you cannot list resources" and the bottom would disappear after clicked  
+ Product & version: Mstore Pro 4.0
+ Flutter (or React Native) version: React Native
+ Testing Device/Simulator: Genymotion
+ Screenshot issues (drag the file to attach here): 
https://imgur.com/01T0BNu
https://imgur.com/N1azxMB
https://imgur.com/5VtQQbE
https://imgur.com/oefboL6
https://imgur.com/V3J376D

**Comment by ameenbadri7** [comment] 2020-07-10 00:35
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-07-10 01:58
it's verified 

@victor0618 - could you help to check the Rest API setting from this link - https://docs.inspireui.com/mstore/wordpress-setting/#wordpress-plugins-install - thank you!

**Comment by minhcasi** [comment] 2020-07-13 13:08
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-13 13:08 UTC
Labels: MStorePro
