### ISSUE TITLE
[FluxStore Listing] Wishlist view detail issue

### ISSUE THREAD

**Issue by gokhand** [inspireui/support#2935] opened 2020-04-29 15:05 UTC
Hi,

In FluxStore Listing , when you add an item to your wishlist, wishlist section shows your list but when you tried to click "View Details" button in the wishlist section it will give an error, you can see from you "Runner" app.

The getter 'prices' was called on null.
Receiver: null
Tried calling: prices

The relevant error-causing widget was
    Consumer2<AppModel, UserModel> 
package:fstore/…/themes/simpleType.dart:177
When the exception was thrown, this was the stack
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
#1      _SimpleLayoutState.getListingContent 
package:fstore/…/themes/simpleType.dart:128
#2      _SimpleLayoutState.build.getThemeContent 
package:fstore/…/themes/simpleType.dart:172
#3      _SimpleLayoutState.build.<anonymous closure> 
package:fstore/…/themes/simpleType.dart:230
#4      Consumer2.buildWithChild 
package:provider/src/consumer.dart:198
...

**Comment by philipvu30** [comment] 2020-04-30 06:48
Hi,

This issue will be fixed in the next update. 
May I ask what theme are you using? Because there are some issues with Listeo Theme so we will delay the next release date. If you are using MyListing/ListingPro, I can send you the hot fix via email.

Thanks

**Comment by gokhand** [comment] 2020-04-30 11:09
We are using Listeo as you (your app page) suggested for the app. And for this Listeo theme even I selected Featured, it is not showing at the top of the category. Do you have any idea about that as well?

So for Listeo, what should we do, we need to wait that Listeo fix it on their side, have you contacted with them, because you are partners as far as I know.

I have another issue with Facebook and Apple sign in returns, do I need to open another ticket for that?

Thanks

**Comment by philipvu30** [comment] 2020-04-30 11:35
Hi,

Please keep all your issues in one place. Also we will update the Flux Listing in a few days.

I am so sorry for this inconvenience. And thank you for using our product.

**Comment by gokhand** [comment] 2020-04-30 14:32
OK , let me share Facebook Login after login success return to app:

It is stuck in a rotating circle and in the background throwing this error:
![image](https://user-images.githubusercontent.com/3597701/80722858-c3843c80-8af7-11ea-8597-4fbf2d2c04d3.png)

The details are:
I/FirebaseAuth(23836): [FirebaseAuth:] Preparing to create service connection to gms implementation
D/FirebaseAuth(23836): Notifying id token listeners about user ( XXXXXXXXXX (I hide token) ).
D/FirebaseAuth(23836): Notifying auth state listeners about user ( XXXXXXXXXX (I hide token) ).
E/flutter (23836): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.
E/flutter (23836): At this point the state of the widget's element tree is no longer stable.
E/flutter (23836): To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
E/flutter (23836): #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> package:flutter/…/widgets/framework.dart:3508
E/flutter (23836): #1      Element._debugCheckStateIsActiveForAncestorLookup package:flutter/…/widgets/framework.dart:3522
E/flutter (23836): #2      Element.findAncestorStateOfType package:flutter/…/widgets/framework.dart:3641E/flutter (23836): #3      Navigator.of package:flutter/…/widgets/navigator.dart:1492
E/flutter (23836): #4      _LoginPageState._welcomeMessage.<anonymous closure> package:fstore/screens/login.dart:84
E/flutter (23836): #5      new Future.delayed.<anonymous closure>  (dart:async/future.dart:316:39)
E/flutter (23836): #6      _rootRun  (dart:async/zone.dart:1122:38)
E/flutter (23836): #7      _CustomZone.run  (dart:async/zone.dart:1023:19)
E/flutter (23836): #8      _CustomZone.runGuarded  (dart:async/zone.dart:925:7)
E/flutter (23836): #9      _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:965:23)
E/flutter (23836): #10     _rootRun  (dart:async/zone.dart:1126:13)
E/flutter (23836): #11     _CustomZone.run  (dart:async/zone.dart:1023:19)
E/flutter (23836): #12     _CustomZone.bindCallback.<anonymous closure>  (dart:async/zone.dart:949:23)
E/flutter (23836): #13     Timer._createTimer.<anonymous closure>  (dart:async-patch/timer_patch.dart:23:15)
E/flutter (23836): #14     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:384:19)
E/flutter (23836): #15     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:418:5)
E/flutter (23836): #16     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:174:12)

I will share apple signin issue as well.

Thanks

**Comment by philipvu30** [comment] 2020-05-04 08:09
Hi,

All the login issues have been fixed. A new version will be uploaded to our Git Lab repository this weekend. If you don't want to wait, leave your email here and I'll send you an unofficial update.

Thank you for using our product.

**Comment by philipvu30** [comment] 2020-05-04 09:50
Hi,

Would you mind sending me your config.dart and config.json to this email: toan@inspireui.com? I need to test if the app is compatible with your site. The files you submitted were not enough.

Thanks

**Comment by gokhand** [comment] 2020-05-04 18:46
Hi, thanks for giving a feedback about the status.

I will send you via email the information.

Thanks

**Comment by gokhand** [comment] 2020-05-13 13:12
In the new version I saw that Review section is disabled for to put new reviews for logged in customers. Even you are logged in the reviews not shiowing up. When I compared that with the previous version, this section is disabled, what was the purpose of that and do you have plans to enable make review from the app. There is no point a review section without ability to share review within the app.

Thanks

**Comment by gokhand** [comment] 2020-05-13 21:28
I foxed some of the issues above, now Android is working fine but I have trouble with the IOS, even I tried pod install, pod update, flutter clean, flutter upgrade  etc different combinations I don't remember how many.

I stuck in it is giving the hundreds of errors (showed just first 200) error related with arm64 and armv7. I am pasting the beginning of the errors below. I tried to reason on the Internet but I couldn't find proper information, if you have some information please let me know how to fix it.

Undefined symbols for architecture arm64:
  "std::__1::to_string(unsigned int)", referenced from:
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > firebase::firestore::nanopb::internal::ToString<unsigned int>(unsigned int const&) in FirebaseFirestore(wrappers.nanopb.o)
  "std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(double)", referenced from:
      firebase::firestore::nanopb::internal::ToString(double) in FirebaseFirestore(pretty_printing.o)
  "std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(float)", referenced from:
      firebase::firestore::nanopb::internal::ToString(float) in FirebaseFirestore(pretty_printing.o)
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long, std::__1::allocator<char> const&)", referenced from:
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::substr(unsigned long, unsigned long) const in FirebaseFirestore(path.o)
  "_pb_decode", referenced from:
      firebase::firestore::remote::ByteBufferReader::Read(pb_field_s const*, void*) in FirebaseFirestore(grpc_nanopb.o)
      firebase::firestore::nanopb::StringReader::Read(pb_field_s const*, void*) in FirebaseFirestore(reader.o)
  "grpc::Status::OK", referenced from:
      grpc::SerializationTraits<grpc::ByteBuffer, void>::Deserialize(grpc::ByteBuffer*, grpc::ByteBuffer*) in FirebaseFirestore(grpc_connection.o)
  "grpc_impl::SslCredentials(grpc_impl::SslCredentialsOptions const&)", referenced from:
      grpc::SslCredentials(grpc_impl::SslCredentialsOptions const&) in FirebaseFirestore(grpc_connection.o)
  "grpc_impl::InsecureChannelCredentials()", referenced from:
      grpc::InsecureChannelCredentials() in FirebaseFirestore(grpc_connection.o)
  "grpc_impl::CreateCustomChannelImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<grpc_impl::ChannelCredentials> const&, grpc_impl::ChannelArguments const&)", referenced from:
      grpc::CreateCustomChannel(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<grpc_impl::ChannelCredentials> const&, grpc_impl::ChannelArguments const&) in FirebaseFirestore(grpc_connection.o)
  "grpc_impl::ChannelArguments::ChannelArguments()", referenced from:
      firebase::firestore::remote::GrpcConnection::CreateChannel() const in FirebaseFirestore(grpc_connection.o)
  "grpc_impl::ChannelArguments::SetInt(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int)", referenced from:
      firebase::firestore::remote::GrpcConnection::CreateChannel() const in FirebaseFirestore(grpc_connection.o)
  "grpc_impl::ChannelArguments::~ChannelArguments()", referenced from:
      firebase::firestore::remote::GrpcConnection::CreateChannel() const in FirebaseFirestore(grpc_connection.o)
  "grpc_impl::ClientContext::ClientContext()", referenced from:
      absl::lts_2020_02_25::memory_internal::MakeUniqueResult<grpc_impl::ClientContext>::scalar absl::lts_2020_02_25::make_unique<grpc_impl::ClientContext>() in FirebaseFirestore(grpc_connection.o)
  "std::__1::chrono::system_clock::now()", referenced from:
      std::__1::cv_status std::__1::condition_variable::wait_for<long long, std::__1::ratio<1l, 1000000000l> >(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&) in FirebaseFirestore(grpc_completion.o)

**Comment by philipvu30** [comment] 2020-05-14 07:54
Hi,

Our demo app is experiencing this issue also. Currently finding a solution.

**Comment by philipvu30** [comment] 2020-05-14 08:49
> In the new version I saw that Review section is disabled for to put new reviews for logged in customers. Even you are logged in the reviews not shiowing up. When I compared that with the previous version, this section is disabled, what was the purpose of that and do you have plans to enable make review from the app. There is no point a review section without ability to share review within the app.
> 
> Thanks

Currently, it has some issues so we have to disable it temporarily. You can uncomment them if they are working for you.

**Comment by gokhand** [comment] 2020-05-14 12:15
> > In the new version I saw that Review section is disabled for to put new reviews for logged in customers. Even you are logged in the reviews not shiowing up. When I compared that with the previous version, this section is disabled, what was the purpose of that and do you have plans to enable make review from the app. There is no point a review section without ability to share review within the app.
> > Thanks
> 
> Currently, it has some issues so we have to disable it temporarily. You can uncomment them if they are working for you.

Unfortunately even we enabled that section when you submit content and select stars are not working.

I am waiting your solution about the  arm64 and armv7 issue on IOS.

Thanks

**Comment by philipvu30** [comment] 2020-05-15 02:25
Hi,

Would you mind sharing your "flutter doctor -v" log and your Mac specs?
Thank you.

**Comment by gokhand** [comment] 2020-05-15 02:39
Hi, Here is the information:

flutter doctor -v
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.14.6 18G103, locale en-GB)
    • Flutter version 1.17.1 at /Applications/flutter
    • Framework revision f7a6a7906b (2 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/xxx/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

• No issues found!

iMac - 32 GB 3200 MHz DDR4

I haven't faced these errors before, I have another Flutter project that published on IOS already, not a similar project but it can give you an idea. And the previous 1.4.0 one I managed to run on IOS and it worked well. This time, not a chance. I am curious about the Flutter packages and the new Flutter version, but I am not sure.

Thanks

**Comment by philipvu30** [comment] 2020-05-15 09:59
Hi,

After I run flutter upgrade and the app went just fine. 

You can try to replace this pubspec.yaml and see if it works.

[pubspec.yaml.zip](https://github.com/inspireui/support/files/4633660/pubspec.yaml.zip)

Remember to run flutter packages get

**Comment by gokhand** [comment] 2020-05-15 10:12
In pubspec.yaml just difference is
- family: Feather
      fonts:
        - asset: assets/fonts/Feather.ttf

So it didn't so much difference. I have already done before flutter upgrade, I did again in anycase no new upgrades available. Still the same issue.

**Comment by philipvu30** [comment] 2020-05-15 10:14
Here is my flutter doctor -v. Do you have any idea?

flutter doctor -v
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.17.1 at /Users/toan/developer/flutter
    • Framework revision f7a6a7906b (2 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/toan/Library/Android/sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[!] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 2DF5234D-5049-48B1-81E8-92B9338BA62E • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

**Comment by gokhand** [comment] 2020-05-15 10:39
I really don't have any idea. Searched internet but nothing properly solved the issue.

In the meantime, on Android tests, the notifications show in notification list as null:
![image](https://user-images.githubusercontent.com/3597701/82041604-56001080-96a0-11ea-97a4-9cd15a02601d.png)

When you clicked the notification it shows this error:
![image](https://user-images.githubusercontent.com/3597701/82041652-6ca66780-96a0-11ea-829d-1e61ccaad877.png)

When I investigated it seems in the json "notification" is empty, "data" seems ok. So, in notification the code was expecting body and title but it is empty.

And as a result the final data is:
{body: null, title: null, seen: true, date: 2020-05-15 09:11:21.877397}

Can you please also have a look at this?

**Comment by gokhand** [comment] 2020-05-15 10:40
The full explanation of the Error when you clicked the null notification message:

A non-null String must be provided to a Text widget.
'package:flutter/src/widgets/text.dart':
Failed assertion: line 298 pos 10: 'data != null'

**Comment by philipvu30** [comment] 2020-05-15 11:00
Hi

In lib/screens/notification.dart, please add 

> ?? ''

![image](https://user-images.githubusercontent.com/54442328/82043395-b6f60b80-96d5-11ea-8d42-f95bf4728f15.png)

to these lines 232 and 238. You did not insert the title when sending the notification, did you?

**Comment by gokhand** [comment] 2020-05-15 11:14
When I added ?? now the ugly message disappeared, but the real problem is even I sent title and body (I sent for that example) it will come notification JSON is empty.

In this article there were similar discussions without proper solution there was a hack but not the proper way, you have to add the extra parameters for body and title, they should have arrived in notification anyway:

https://github.com/FirebaseExtended/flutterfire/issues/2012

**Comment by gokhand** [comment] 2020-05-15 12:58
I have found an issue:
` FStoreNotification.fromJsonFirebase(Map<String, dynamic> json) {
    try {
      print(json);
      var notification = json['data'] ?? json['notification'];
      **body = json['notification']['body'];
      title = json['notification']['title'];**
      seen = false;
      date = (new DateTime.now()).toString();
      print(date);
    } catch (e) {
      print(e.toString());
    }
  }`

I have modified the bold section, in this way Firebase message if the app is open and front of the user it is putting notification with body and title and it will be seen on message section properly:

`{notification: {title: New Test, body: New Test body}, data: {click_action: FLUTTER_NOTIFICATION_CLICK}}`

But, If it is not actively open then the notification null and cannot collect the data:

`{notification: {}, data: {collapse_key: com.xxxx.xxxx, google.original_priority: high, google.sent_time: 1589546871427, google.delivered_priority: high, google.ttl: xxxxx, click_action: FLUTTER_NOTIFICATION_CLICK}}`

===
In the meantime do you have any solution for IOS compile issue that I am facing?

Thanks

**Comment by gokhand** [comment] 2020-05-17 14:09
I finally managed to run on iOS, I didn't make any difference but try some of the steps and it worked.

I managed the notifications sending title, body in payload (data). And modified to handle in the notification.

Now I am handling notifications on android well.

But on iOS onresume, onlaunch etc never fired. I searched on the Internet there are some issues, but maybe you know if they are working?

On the other hand, still experiencing the issue on apple sign in. I saw there is a database connection for firebase. And there is no documentation that we had to create a firebase database. Even we have created we are experiencing after apple sign in returned Exception without any explanation. After the first apple sign-in attempt when you tried to do again, it is given another exception (most probably it is trying to check a database record that couldn't be created). Do you have any suggestions to fix this?

Thanks

**Comment by philipvu30** [comment] 2020-05-18 02:58
Hi @gokhand 

My apologies for the delayed response. As I have checked our documentation, I noticed that we haven't had a document for apple sign in yet. 
We'll post it later. Thanks for pointing it out. 

Back to your issue, if possible, please send your whole project after run flutter clean to our support email: support@inspireui.com or my email: toan@inspireui.com. I'll help you check the issue. Thanks

**Comment by gokhand** [comment] 2020-05-18 09:57
I have sent the email.

Thanks

**Comment by gokhand** [comment] 2020-05-18 12:34
I would like to report another issue related with login.

If you try to signup regular method (without using FB, google, Apple), it is giving an error of registration. Also you cannot use regular login as well.

The reason seems behind it the list "ListApp Mobile Manager" plugin cannot manage flutter_user controller. 

In the documentation it says:
You can check this config correctly via the link/api/get_nonce/?controller=mstore_user&method=register example: http://demo.mstore.io/api/get_nonce/?controller=mstore_user&method=register

But in the Flutter code itself is trying to use http://demo.mstore.io/api/get_nonce/?controller=flutter_user&method=register which is returning error.

I manually changed the flutter_user controller name in the Flutter code to "mstore_user" it managed to create a user. But after that again the login still not working, so it is also trying to user flutter_user controller from the api.

I don't want to create more modifications, I think better to update "ListApp Mobile Manager" to manage the flutter_user properly.

Please let me know your advice.
Thanks

**Comment by philipvu30** [comment] 2020-05-20 07:38
Hi,

What is your current version of the plugin ListApp Mobile Manager?

**Comment by gokhand** [comment] 2020-05-20 08:50
Latest one 1.6.3
Have you had a chance also look at the source files that I sent you?

Thanks

**Comment by philipvu30** [comment] 2020-05-21 06:46
Hi,

Sorry for the delayed response. 

Please replace this file in your project. It's in lib/services/woo_commerce.dart
[woo_commerce.dart](https://github.com/inspireui/support/files/4660423/woo_commerce.dart.zip). I believe this will fix the login issue :)

**Comment by gokhand** [comment] 2020-05-21 09:44
Hi,

This fixed manual register-login issue. Thanks

The other issues are still pending that I sent you over the email toan@inspireui.com. let me list them here as well.

- Apple signin has issues, Apple sign in triggered after you accept the app giving an error in return
- IOS Notifications hasn't fired onresume, onlaunch any trigger activity. On Android it works fine.
- SMS login crashes on apple, working on android. But also has some trouble even you goat the sms code , after that you enter the sms code in the app, it is returning indefinitely nothing happens.
- Last issue at the moment is that the "Home" link in the tabbar. If you are in the Settings when you use left tabbar to return home, the bottom icon selected as home but the page stays in settings screen. All other pages has similar issues just for Home button on the left tabbar.

Thanks

**Comment by philipvu30** [comment] 2020-05-22 09:28
Hi,

I sent a fixed solution via your email. Please check

Here is a brief explanation of your issues:
1. I have checked the Apple Sign in with the lib folder I sent you. It's fine for me. If the error still persists with the new lib, please record a video or images according to the issue.
2. For the IOS notification, you have to test it on a real device because the IOS simulator does not fully support Notification.
3. SMS is working fine with the lib folder I sent you. I believe a phone number cannot receive 2 verified codes in a short time. It's fine when using test numbers though. So my suggestion is when your app is in development, please add a test number to your phone authentication firebase like the example below. Remember to use a fictional number using 555 as Google recommended.
![image](https://user-images.githubusercontent.com/54442328/82653056-d5658500-9c48-11ea-9351-f43682d5c1f1.png)
4. I removed the color of the tab bar icon. It's still looking good without the color though.

**Comment by gokhand** [comment] 2020-05-22 16:57
Hi,

The lib folder that you sent me an exact copy of what I sent you.
Did you change anything or the wrong folder that you sent to me?

Thanks

**Comment by philipvu30** [comment] 2020-05-24 04:23
Hi,

The lib folder I sent you in the previous email, it worked for another user. I don't know why it is not working for you.
I sent you 3 files. Try with the pubspec and lib folder first, if it has errors with the font, please replace the asset folder. Thank you

**Comment by minhcasi** [comment] 2020-05-26 02:36
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-05-26 02:36 UTC
Labels: FluxListing
