### ISSUE TITLE
[Fluxstore] - Failed register or login with email 1.6.7

### ISSUE THREAD

**Issue by Senior-Gamal** [inspireui/support#1448] opened 2019-11-24 11:01 UTC
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------
My issue

1 - I cannot log into the account and show this message ( warning : exception: the username or password is incorrect )  But the account works normally on the site
2 - And when you sign up ( exception : you must include 'username' .var in your request )

My screenshot of the purchase product or my comment:
https://user-images.githubusercontent.com/27568540/66625373-4e512880-ebf4-11e9-9b30-c4a19f7d028d.jpeg

**Comment by minhcasi** [comment] 2019-11-25 02:35
@Senior-Gamal - could you help to attache the config file here so that we could help for checking

Please try to create 1 ticket for your all issues that help us support you better - thanks

**Comment by minhcasi** [comment] 2019-11-25 02:36
Duplicate of #1444

**Closed by minhcasi** 2019-11-25 02:36 UTC
Labels: Fluxstore-MV, question ❓
