### ISSUE TITLE
woocommerce_rest_cannot_view

### ISSUE THREAD

**Issue by Nick-tech-2691** [inspireui/support#4867] opened 2020-09-04 04:24 UTC
![post](https://user-images.githubusercontent.com/52854535/92199104-d5a22d00-ee93-11ea-847d-b2eb3ecc8866.png)
this problem is coming with all the projects which are using woocommerce plugin, all of them were working fine but suddenly since this Monday, I'm stuck with this problem. 
I've used insomnia also but the same thing is coming up.

**WordPress 5.4.2
WooCommerce plugin 4.4.1
Rest API v3**

**Comment by minhcasi** [comment] 2020-09-04 06:54
Duplicate of #4854

**Comment by minhcasi** [comment] 2020-09-04 06:54
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

**Closed by minhcasi** 2020-09-04 06:54 UTC

**Comment by SWengineer-A** [comment] 2020-09-20 23:57
Hello, @minhcasi 
I have the same issue for some days. 
Can you help me to fix them, please?
