### ISSUE TITLE
(Magento 2.3; FluxStore Pro) Search Not Working

### ISSUE THREAD

**Issue by saudadev** [inspireui/support#3370] opened 2020-05-23 05:17 UTC
Step 1 (require): detail issues and screenshots

ISSUE 1: I am trying to search the keyword “rice” in Search Tab.

The Product is a Configurable Product and the Configured Products are Marked not to be displayed Individually.

Backend of Magento Product

![Search-Magento-BackEnd](https://user-images.githubusercontent.com/63896811/82722260-a3086600-9ce2-11ea-922b-f205244018e5.png)

As you can see, these products are marked not to be searched Individually.

IN APP : As you can see, it display all the products and Displays the Primary Configurable Product Value to ZERO.

![Seacrh-App-Showing-4-Products](https://user-images.githubusercontent.com/63896811/82722264-ab60a100-9ce2-11ea-8242-9554a1625603.png)

ISSUE 2: If you Scroll Down it keep on adding 4 more Same Products and wont Stop adding as you scroll down.

![Seacrh-App-Showing-8-Products](https://user-images.githubusercontent.com/63896811/82722268-b5829f80-9ce2-11ea-92bc-97c925d10b01.png)

WORKING MAGENTO FRONT-END

![Search-Magento-frontend](https://user-images.githubusercontent.com/63896811/82722272-bd424400-9ce2-11ea-8c1a-4e3c5bf0b7da.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

**Going to Add, please don’t put the label “NEED MORE INFO”**

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by saudadev** [comment] 2020-05-23 05:18
**Added Private Files.**

**Comment by minhcasi** [comment] 2020-05-23 07:20
Duplicate of #3369 - pls move to the one ticket support

**Closed by minhcasi** 2020-05-23 07:20 UTC
