### ISSUE TITLE
I can't run the app

### ISSUE THREAD

**Issue by michmj** [inspireui/support#3647] opened 2020-06-08 22:39 UTC
I have the following problem when I try to run the app
Launching lib\main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...

Compiler message:
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/provider-4.1.0/lib/src/inherited_provider.dart:136:4: Error: Operator declarations must be preceded by the keyword 'operator'.
Try adding the keyword 'operator'.
  }+
   ^
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/provider-4.1.0/lib/src/inherited_provider.dart:136:4: Error: A method declaration needs an explicit list of parameters.
Try adding a parameter list to the method declaration.
  }+
   ^
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/provider-4.1.0/lib/src/inherited_provider.dart:137:1: Error: Expected '{' before this.
}
^
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/provider-4.1.0/lib/src/inherited_provider.dart:136:4: Error: Operator '+' should have exactly one parameter.
  }+
   ^
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

Compiler message:
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/provider-4.1.0/lib/src/inherited_provider.dart:136:4: Error: Operator declarations must be preceded by the keyword 'operator'.
Try adding the keyword 'operator'.
  }+
   ^
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/provider-4.1.0/lib/src/inherited_provider.dart:136:4: Error: A method declaration needs an explicit list of parameters.
Try adding a parameter list to the method declaration.
  }+
   ^
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/provider-4.1.0/lib/src/inherited_provider.dart:137:1: Error: Expected '{' before this.
}
^
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/provider-4.1.0/lib/src/inherited_provider.dart:136:4: Error: Operator '+' should have exactly one parameter.
  }+
   ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\Michael\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\Michael\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 49s
Exception: Gradle task assembleDebug failed with exit code 1

proof I bought is here
![image](https://user-images.githubusercontent.com/66580145/84087078-f949fa00-a9ae-11ea-8c8d-10dcb5e9f40f.png)

**Comment by michmj** [comment] 2020-06-08 22:41
I don't understand how to solve it. help me I bought it one week ago but doesn't work

**Comment by minhcasi** [comment] 2020-06-09 00:50
Duplicate of #3638

**Closed by minhcasi** 2020-06-09 00:50 UTC
