### ISSUE TITLE
Upgrade shopify flutter app from gitlab source

### ISSUE THREAD

**Issue by medsaadit** [inspireui/support#4104] opened 2020-07-07 20:14 UTC
Hi,
I cloned the new code but I couldn't upgrade the old one or open the new one directly.
Is there something I am missing? If there is any upgrade Readme, it would be great. I was able to import and run the old code but the new code returns the following :

`fluxstore-shopify-master$ bash tools/build-appbundle.sh [!] Your app is using an unsupported Gradle project. To fix this problem, create a new project by running flutter create -t app and then move the dart code, assets and pubspec.yaml to the new project.`

**Comment by minhcasi** [comment] 2020-07-08 01:48
Duplicate of #4033

**Closed by minhcasi** 2020-07-08 01:48 UTC
