### ISSUE TITLE
How to integrate cardstream payment gateway into fuxstore in magento2

### ISSUE THREAD

**Issue by subhquad** [inspireui/support#3643] opened 2020-06-08 10:52 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: how to integrate cardstream payment gateway.(https://cardstream.com)
+ Product & version: Fluxstore Pro 1.7.5
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: iPhone 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment] 2020-06-09 01:43
@subhquad - it seems the cardstream does not have the library for Flutter framework from the mobile side - https://github.com/cardstream - could you try to contact them to check the solution to integrate with the flutter app?

**Comment by minhcasi** [comment] 2020-06-09 01:44
Duplicate of #3573

**Closed by minhcasi** 2020-06-09 01:43 UTC

**Comment by subhquad** [comment] 2020-06-09 09:17
Its not a duplicate . Why its closed.

**Comment by subhquad** [comment] 2020-06-09 09:24
can we implement as web view if flutter library is not available . so what's the solution if flutter library for cardstream is not available

**Comment by minhcasi** [comment] 2020-06-09 11:15
Yes, please try to enable `EnableOnePageCheckout` or `NativeOnePageCheckout`

Also help us to move your all conversation to the same of your own ticket  #3573 - thanks for your time
