### ISSUE TITLE
discount does not work for multiple purchases fluxstore pro

### ISSUE THREAD

**Issue by roseyazilim** [inspireui/support#4124] opened 2020-07-08 15:49 UTC
**verifications have been sent to the forum!**

### problem 1

I can not register in the application gives an error.

### problem 2

There are discounts on the purchase of 100 and more for some products on the site. Mobile App No

### problem 3

When I change the order status on the site, the application does not change in the order history section

Can you please support urgently?

**Comment by ameenbadri7** [comment] 2020-07-08 20:01
hello @roseyazilim Wellcome Back.
please share screen shots for those issues so we can help you fast. 
thank you

**Comment by roseyazilim** [comment] 2020-07-08 20:36
**Problem 1** = https://prnt.sc/tebuue

**Problem 2** = https://prnt.sc/tebvy5 (This product needs to be 50 dollars for over 100 purchases, but it doesn't work in practice.)

**Problem 3** = https://prnt.sc/tebu8r

**Comment by sketchuprzr** [comment] 2020-07-10 00:50
[TR]
Merhaba @roseyazilim ;
Problem 1 Çözümü =
Gördüğüm kadarıyla api sisteminin üye veritabanına erişimi yok.
Bu yüzden wordpress sisteminde ; " ayarlar/Json Api " bölümünde Mstore user seçeneğini aktif etmelisin.

![image](https://user-images.githubusercontent.com/60021696/87104271-1862d280-c260-11ea-87e5-9c373950cb7b.png)

--------------------------------------

Problem 2 =
Attığın resim bu sorunu anlamak için yetersiz. Kullandığın sistemin wordpress olup olmadığı belli değil. Bu indirim bölümü woocommerce'nin standart arayüzü değil. Bu bir eklenti olabilir. Eğer bu bir eklentiyse, unutma ki uygulama sadece woocommerce uyumu sağlıyor. Ek eklenti ayarlarının uygulamada çalışmayacağını bilmen gerekiyor.

--------------------------------------

Problem 3 Çözümü =
Eğer sipariş durumunu, ödeme ekranından sonra "işleniyor" olarak düzeltmek istiyorsan aşağıda bulunan config ayarını "true" olarak düzenlemelisin.
 ("UpdateOrderStatus": true) olmalı.

![image](https://user-images.githubusercontent.com/60021696/87104162-b73aff00-c25f-11ea-8756-b21e358b8e64.png)

==========================================

[EN]
Hello @roseyazilim;
Problem 1 Solution =
As far as I can see, api system does not have access to member database.
So in the wordpress system; In the "settings / Json Api" section, you have to activate the Mstore user option.

![image](https://user-images.githubusercontent.com/60021696/87104271-1862d280-c260-11ea-87e5-9c373950cb7b.png)

--------------------------------------

Problem 2 =
The picture you took is insufficient to understand this problem. It is not clear whether the system you are using is wordpress. This discount section is not the standard interface of woocommerce. This can be a plugin. If this is a plugin, remember that the app only provides woocommerce compatibility. You need to know that additional plugin settings will not work in the application.

--------------------------------------

Problem 3 Solution =
If you want to fix the order status as "processing" after the payment screen, you should set the config setting below to "true".
 ("UpdateOrderStatus": true).

![image](https://user-images.githubusercontent.com/60021696/87104162-b73aff00-c25f-11ea-8756-b21e358b8e64.png)

**Comment by ameenbadri7** [comment] 2020-07-10 02:03
@sketchuprzr  thank you for answering his questions you giving us a great help by sharing your knowledge to our repo inside github.com

I have seen you're [tickets with us]( https://github.com/inspireui/support/issues?q=author%3Asketchuprzr) i guess you have the biggest tickets request in our repo 🥇 .

so thank you for that and I hope  that other new developer can go to our tutorial in our [decumentions ](https://docs.inspireui.com/fluxstore)site so they can learn more about customazing the fluxstore as they want.

please let us know if @sketchuprzr answers helped you so we can close this ticket. thank you

**Comment by roseyazilim** [comment] 2020-07-10 05:48
[TR]
Merhaba; Yanıtınız için Teşekkürler,
sistemim opencart o yüzden 1. problemi uygulayamıyorum.
Opencart kendi sisteminde indirim yapabilme özelliği var 3.0.3 opencart 100 adet üzerinde indirim yapıyor.
Teşekkürler.

**Comment by ameenbadri7** [comment] 2020-07-11 04:58
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by ameenbadri7** 2020-07-11 04:58 UTC
Labels: FluxStore

**Comment by roseyazilim** [comment] 2020-07-11 08:24
Hello! 
my system is opencart so i can't apply problem 1.
3.0.3 opencart makes over 100 discounts.
Thank you.

**Comment by roseyazilim** [comment] 2020-07-13 05:55
hello ?
