### ISSUE TITLE
category images not pulling from magento2

### ISSUE THREAD

**Issue by subhquad** [inspireui/support#3548] opened 2020-06-02 12:22 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues:  click on category tab and the category images are loaded.
+ Product & version: Fluxstore Pro 1.7.3
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: iPhone 
+ Screenshot issues (drag the file to attach here): 

<img width="343" alt="Screenshot 2020-06-02 at 13 18 38" src="https://user-images.githubusercontent.com/10830054/83519292-a1edea80-a4d3-11ea-87c7-06dc6871e154.png">

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
80f2ca3f-3e8f-43cd-97ba-9dd311d5fb75 

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment] 2020-06-04 02:05
@subhquad - could you help to update to latest Fluxstore `1.7.4` or new `1.7.5` on Gitlab to fix this issue - thank you!

**Comment by minhcasi** [comment] 2020-06-04 02:06
Duplicate of #3573

**Closed by minhcasi** 2020-06-04 02:06 UTC
Labels: FluxStore, magento-issues
