### ISSUE TITLE
regualr price and sales price not correct into search 

### ISSUE THREAD

**Issue by abdullahamer11** [inspireui/support#4840] opened 2020-09-02 11:14 UTC
Hello,

are facing issue on prices on multivendor app. we set regualr price and sales price for the product but into the search showing the regulare price not sale price and this is wrong
please check the screebshots:
https://prnt.sc/u9nu1s 
https://prnt.sc/u9nun2

**Comment by minhcasi** [comment] 2020-09-03 02:12
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-09-04 03:05
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-09-04 03:05 UTC
Labels: needs-more-info

**Comment by abdullahamer11** [comment] 2020-09-07 12:25
Hello,

i verify the ticket, but nobody answer me
