### ISSUE TITLE
Flux Store Pro - Push Notification

### ISSUE THREAD

**Issue by audiojaminc** [inspireui/support#1088] opened 2019-09-20 10:04 UTC
Your instructions in the documentation is incomplete and missing information. How do we enable Push Notification? Your documentation gives the code but it does not explain where the put the code, what file to put the code etc. 

So long just to get one app to work and still we can't launch our app. Very poorly designed app and documentation. Incomplete app. How are you allowed to sell this via CodeCanyon? Should I report?

**Comment by audiojaminc** [comment] 2019-09-20 10:06
Your instruction says **"Check out the example directory for a sample app using Firebase Cloud Messaging**." but there is no such thing.

**Comment by audiojaminc** [comment] 2019-09-20 14:33
Your instructions / documentations says:
Dart/Flutter Integration
From your Dart code, you need to import the plugin and instantiate it:
import 'package:firebase_messaging/firebase_messaging.dart';
final FirebaseMessaging _firebaseMessaging = FirebaseMessaging();

**What Dart code? What file does this go to? Your instructions are incomplete.** 

It also says:
Next, you should probably request permissions for receiving Push Notifications. For this, call _firebaseMessaging.requestNotificationPermissions(). This will bring up a permissions dialog for the user to confirm on iOS. It's a no-op on Android. Last, but not least, register onMessage, onResume, and onLaunch callbacks via _firebaseMessaging.configure() to listen for incoming messages (see table below for more information).

**How? How do we enter this code? Where is it suppose to go? This is bad support and instructions to edit your own product.**

**_Please explain how or update documentation ASAP. Thank you._**

**Comment by minhcasi** [comment] 2019-09-22 03:46
Duplicate of #1081

**Closed** 2019-09-24 09:46 UTC
Labels: enhancement ⚡️, question ❓
