### ISSUE TITLE
Listing app booking time confusing now

### ISSUE THREAD

**Issue by jinaldo** [inspireui/support#4421] opened 2020-07-30 11:49 UTC
I use the latest version of the app and have bought Listeo theme, have created users and added listings, with time slots for testing, I have synced it with the app, however when I make booking, the app doesn't check and use available time slots when I book, the app books any random time at all and the theme accepts it, how can I fix it?
*** I had also tested your sample flux listing Android and iOS apps from play store and app store. But in those apps I could book any time. For example, I could book any service 10/7/2020, but today is 31/7/2020. how can I book on the past days?
Please let me know the resolution.
***  I have checked this issue. It was same my issue. https://github.com/inspireui/support/issues/3628
But the answer was not clear.

**Comment by ameenbadri7** [comment] 2020-07-30 17:37
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by jinaldo** [comment] 2020-07-31 13:56
@minhcasi  Hi, thanks for your reply. I have just submitted the form with purchase pdf. When can I receive your reply?Because I'm in urgent need of your help.

**Comment by minhcasi** [comment] 2020-08-01 04:31
@jinaldo - we will check the issue and will get back on Monday - thank you!

We sincerely apologize for the delay and hope you’re staying safe.

**Comment by philipvu30** [comment] 2020-08-03 04:48
Hi,

May I ask what version of FluxListing you are using?

**Comment by jinaldo** [comment] 2020-08-03 08:05
Hi, I'm using the lastest one. How can I check the version?

**Comment by jinaldo** [comment] 2020-08-03 10:34
@philipvu30 Hello, mate. Please let me solve the issue. I'm waiting for your reply.

**Comment by philipvu30** [comment] 2020-08-04 07:03
Hi,

I am investigating the issue and will get back to you asap when it's solved.

Thank you for your patience.

**Comment by jinaldo** [comment] 2020-08-04 08:05
Thanks.

**Comment by jinaldo** [comment] 2020-08-05 00:53
Hello, @philipvu30. How is it going?  
One question, Does the above booking time issue happen on every fluxlisting app generally?  or else especially on my fluxlisting app?
And when can I get the solution for it?
Because I'm under heavy pressure from my client.

**Comment by jinaldo** [comment] 2020-08-05 08:10
???

**Comment by philipvu30** [comment] 2020-08-05 10:40
Hi,

There are some features we did not cover when developing this app. 
> Does the above booking time issue happen on every fluxlisting app generally?

Yes, it does. This issue is caused by the ListApp Mobile Manager plugin.
May I ask do you use the Availability Calendar feature also or only the Slots feature?

**Comment by jinaldo** [comment] 2020-08-05 10:44
Hi, I use the Availability Calendar feature and also the Slots feature.
I see web application is working properly. But only on mobile side the problems are happening.
So what's the resolution for the issues now? What's the best way to avoid these issues? any idea?

**Comment by philipvu30** [comment] 2020-08-05 15:10
Hi,

I tested the Availability Calendar and it seems working with those that are selected(the red ones) but not for the Slots feature.
Also, our app is nothing related to Listeo theme's Company. We just develop this app base on Listeo theme so it might not include all the features of Listeo theme.

We'll try to implement as many features as possible in the future. For now, my apologies for any inconvenience we may have caused and we'll fix the slot feature asap.

**Comment by jinaldo** [comment] 2020-08-07 08:43
Hi, @philipvu30 
I'm on the home page of Fluxlisting app.
But the counts of products of category are wrong.
Please check this.
The Gastronomia has 3 products. 
![Screen Shot 2020-08-07 at 11 36 28 AM](https://user-images.githubusercontent.com/45912411/89627074-fc744000-d8a2-11ea-87fd-f993aa77a168.png)
But it shows 1 products on the top horizontal scrollview (category) of the home screen.
![Screen Shot 2020-08-07 at 11 35 52 AM](https://user-images.githubusercontent.com/45912411/89627180-20378600-d8a3-11ea-87df-bd2075ff0b61.png)
Please let me know the solution.

**Comment by philipvu30** [comment] 2020-08-07 10:24
Hi,

Please check if they are the same category id.

**Comment by jinaldo** [comment] 2020-08-07 11:27
Hi, yes, they are the same. On the top scroll view, when I tap the 'Gastronomia', it also shows the same 3 products.
![Screen Shot 2020-08-07 at 2 25 17 PM](https://user-images.githubusercontent.com/45912411/89641351-284ef000-d8ba-11ea-9173-4c06fac36b74.png)
Any idea?

**Comment by jinaldo** [comment] 2020-08-07 13:29
Hello, @philipvu30.  Please check it and let me know before the weekend.

**Comment by philipvu30** [comment] 2020-08-07 15:50
Hi,

It's fine to me. It seems you have modified the app, maybe you missed something in this file lib/widgets/home/category/category_image_items.dart

![image](https://user-images.githubusercontent.com/54442328/89663736-33c50a00-d900-11ea-8837-43034f5c5bca.png)

**Comment by jinaldo** [comment] 2020-08-07 15:53
Hi, yes, but I changed color, not other things.
Can you send me the 'category_image_items.dart' file now?

**Comment by philipvu30** [comment] 2020-08-08 04:30
Sure,

Here you go.

[category_image_items.zip](https://github.com/inspireui/support/files/5044633/category_image_items.zip)

**Comment by jinaldo** [comment] 2020-08-08 11:13
Hello, @philipvu30. I've checked the dart file with mine.  But I see there aren't any difference between the 2 files.
Now I have debugged the 'services/listing.dart'.
By the way the function 'getCategories' returns count=1 about the 'gastronomia'. But it has really 3 products as you can see on the above image. It's really strange. Please check this image and let me know your thoughts.

![Screen Shot 2020-08-08 at 2 08 15 PM](https://user-images.githubusercontent.com/45912411/89708617-59462800-d981-11ea-98bf-ab863a5f1934.png)

**Comment by philipvu30** [comment] 2020-08-08 12:41
Hi,

Please remove the `&_embed` in that function. Thanks

**Comment by jinaldo** [comment] 2020-08-08 12:46
Hi, @philipvu30. It's working like charm. Thanks.

**Comment by jinaldo** [comment] 2020-08-10 04:04
How are you, @philipvu30?
I've faced a new problem.
In the detail view, the app doesn't show the rating correctly.
The product 'MAM1' has one review with 5 ratings. But it doesn't show the rating in a detail view.
Please check the following images.

![Screen Shot 2020-08-10 at 6 45 09 AM](https://user-images.githubusercontent.com/45912411/89750574-4b092080-dad5-11ea-9ca1-79bee37255b7.png)
![Screen Shot 2020-08-10 at 6 44 07 AM](https://user-images.githubusercontent.com/45912411/89750582-4f353e00-dad5-11ea-87d0-4a552b236813.png)

I debugged the review.fromMyListing  in lib/services/review.dart.
I found the wrong part.
Please check the following image and let me know your thoughts.

![Screen Shot 2020-08-10 at 7 00 38 AM](https://user-images.githubusercontent.com/45912411/89751165-a20ff500-dad7-11ea-9467-c7f33b97639e.png)

**Comment by jinaldo** [comment] 2020-08-10 14:21
Hello, @philipvu30.

**Comment by jinaldo** [comment] 2020-08-11 08:13
Hi

**Comment by jinaldo** [comment] 2020-08-12 14:48
???

**Comment by minhcasi** [comment] 2020-08-14 03:59
@jinaldo - sorry for the late response on this ticket - there is missing rating data mapping on latest Listeo as they have changed the format data - I'm working with the Listeo data to integrate with their demo and keep upgrade the Fluxstore Listing on next release `1.4.3` - thank you so much for your patience

**Comment by jinaldo** [comment] 2020-08-14 04:14
Hi, @minhcasi. Can you let me know when the v 1.4.3 will be available?

**Comment by minhcasi** [comment] 2020-08-16 03:51
The latest version is ready for download, please give a try and let us know your checking. 

You could use this method to merge with your previous code via Gitlab - https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6

**Closed** 2020-08-17 01:39 UTC
Labels: FluxListing
