### ISSUE TITLE
error on app starting and image not show properly 

### ISSUE THREAD

**Issue by ritutechno** [inspireui/support#3716] opened 2020-06-13 08:59 UTC
hello sir, 

when i open my app in mobile. then every time app will start from 1st. means app start from onboarding screen, show as in pic 
![WhatsApp Image 2020-06-13 at 2 19 50 PM (2)](https://user-images.githubusercontent.com/43493593/84564757-d5f1c700-ad81-11ea-86bf-9eda2dc7acfc.jpeg)
![WhatsApp Image 2020-06-13 at 2 19 50 PM (1)](https://user-images.githubusercontent.com/43493593/84564758-d8542100-ad81-11ea-8d01-49951d3df950.jpeg)

so please fix it. 

and 2nd problem is that image are not show properly in app home screen as well as category screen as show in fig 
![WhatsApp Image 2020-06-13 at 2 17 04 PM](https://user-images.githubusercontent.com/43493593/84564784-20734380-ad82-11ea-87d2-4cf9cdc2c8fe.jpeg)
![WhatsApp Image 2020-06-13 at 2 19 50 PM](https://user-images.githubusercontent.com/43493593/84564786-223d0700-ad82-11ea-8142-3b05b86b0768.jpeg)
![WhatsApp Image 2020-06-13 at 2 17 04 PM (2)](https://user-images.githubusercontent.com/43493593/84564787-236e3400-ad82-11ea-9dca-4e2e3a73bd73.jpeg)

so please fix both error 

![Screenshot_5](https://user-images.githubusercontent.com/43493593/84564819-4862a700-ad82-11ea-99f2-8685fa68cd56.png)

thanks.

**Comment by minhcasi** [comment] 2020-06-15 02:57
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

---

it seems you are using the old version of Fluxstore, please update the latest `1.7.5` - thanks

**Comment by ritutechno** [comment] 2020-06-15 11:03
Link not open

Thanks & Regrades-

Ritu Techno
Mob.- 946263501, 9982264200
E-mail- info@ritutechno.com
web- www.ritutechno.com

**Comment by minhcasi** [comment] 2020-06-16 03:26
@ritutechno - pls try this link https://docs.google.com/forms/d/e/1FAIpQLScWOjkAJIWJ9rgb9alopfOqLsJrGKbFM5cCYj1JBfLKLsBblQ/viewform - thank you!

**Comment by ritutechno** [comment] 2020-06-16 07:26
done form from my side. 

i get an another issue razorpay not work in app while work in website. i use live key same both. 
in last when i click on pay button then i got 404 error. so please fix it.

**Comment by minhcasi** [comment] 2020-06-16 11:19
@ritutechno - thank you for the quick response - could I know if you have activated the `mstore-api` plugin from the admin site? Please help to share the screenshot issue so that i could forward to the team for checking.

**Comment by ritutechno** [comment] 2020-06-16 13:41
Yes, i active mstore-api plugin
![Screenshot_2020-06-16-18-03-54-59](https://user-images.githubusercontent.com/43493593/84782066-380e2e80-b005-11ea-93dd-3d8ab31265f9.jpg)

**Comment by minhcasi** [comment] 2020-06-17 03:14
@minhtruong315 - pls help to check the mstore-api plugin payment issue - thank you!

**Comment by minhtruong315** [comment] 2020-06-17 08:44
@ritutechno pls upload your source code to github then invite me: minhtruong315@gmail.com
I will help u check and fix issues.
Thanks

**Comment by ritutechno** [comment] 2020-06-17 17:03
How i upload source code

Thanks & Regrades-

Ritu Techno
Mob.- 946263501, 9982264200
E-mail- info@ritutechno.com
web- www.ritutechno.com

**Comment by minhtruong315** [comment] 2020-06-18 02:01
@ritutechno you can upload the source code to github, gitlab, bitbucket or any git repo then invite me.

**Comment by minhcasi** [comment] 2020-06-20 04:17
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-06-20 04:17 UTC
Labels: FluxStore, Mstore-API
