### ISSUE TITLE
Mstore extension not working in Magento 2

### ISSUE THREAD

**Issue by Gagan557** [inspireui/support#4890] opened 2020-09-05 09:32 UTC
I added Mstore extension in Magento2.3.5-p2 . But not options available for  verify Mstore extension .Please share documentation for configuration in Mstore  extension  magento2.3.5
If possible share screenshot how to configure Mstore extension in magento 2,
I check Documentation link : https://magento.mstore.io but link not working.

**Comment by minhcasi** [comment] 2020-09-06 02:42
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-09-07 01:25
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-09-07 01:25 UTC
Labels: needs-more-info
