### ISSUE TITLE
Mstore-Pro Cannot login 

### ISSUE THREAD

**Issue by priyanka284** [inspireui/support#1427] opened 2019-11-20 06:45 UTC
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: 

a: Cannot Login with the WP user.
Sign up is working fine (after updating WPUserAPI.js from [#1406](https://github.com/inspireui/support/issues/1406) ) but when I try to login It will just show the spinner and nothing else happens.

b.Cannot login with the SMS 
When clicked on login with SMS, the app either gives a black screen or freezes. And I have to exit the simulator.

2. Screenshots issues: Not Applicable

3. Proof of my purchased: 

I can email you the purchase key if needed( Kindly provide the email id)

![Screenshot 2019-11-20 at 11 57 58 AM](https://user-images.githubusercontent.com/44432949/69214607-6457ee80-0b8d-11ea-8b49-706a1e7239fe.png)
 AM.png…]

3. Config files (optional)

**Comment by minhcasi** [comment] 2019-11-20 11:35
@priyanka284 - the SMS feature is stoped support from Facebook Account Kit - we will replace it on next version - thanks

**Comment by minhcasi** [comment] 2019-11-20 11:36
Duplicate of #1049

**Closed by minhcasi** 2019-11-20 11:36 UTC
Labels: MStorePro, question ❓

**Comment by priyanka284** [comment] 2019-11-20 12:30
@minhcasi Thanks for the quick response. 

Kindly guide me with the login/signup for the Wordpress user. I cannot log in and so cannot proceed with the checkout. The screen just shows the spinner and nothing happens.
