### ISSUE TITLE
[ListApp] Configuration issue of mylisting theme

### ISSUE THREAD

**Issue by Pavithran10** [inspireui/support#374] opened 2019-03-07 06:49 UTC
**Required Info (please complete the following information):**
 Product:[ListApp]
Version:1.6.1
Theme: MyListing

**Describe the bug**
hi, we reset the overall application now we created a new site in that configuration issue is there. In that listapp theme home screen, map and category list item are not configure. we changed all the content in the mylisting with our new site. then also it's not fetching content in mylisting theme.

Can you please configure our site creditional to fix our wordpress admin site. thanks

**Screenshots**
[err video.zip](https://github.com/inspireui/support/files/2940025/err.video.zip)

**Comment by minhcasi** [comment] 2019-03-07 08:23
Duplicate of #353
Duplicate of #341

1. please raise your one ticket for the issues, instead of 3 ticket with the same problem - thanks
2. Please take the screenshot from the download page (https://codecanyon.net/downloads) to prove that you are our customer 

Thanks

**Comment by Pavithran10** [comment] 2019-03-07 08:45
hi, sorry for that creating more issues. we are your customer only. why i'm creating more issue means issue reason is same but problem is different and then we posted any issue it will take more time for reply and then we going to solve it's takes more time. thanks.
![codecanyon](https://user-images.githubusercontent.com/46148046/53943635-8256ef00-40e3-11e9-9876-3e6ce4203a3a.PNG)

**Comment by Pavithran10** [comment] 2019-03-08 04:14
hi, we reset the overall application now we created a new site in that configuration issue is there. In that listapp theme home screen, map and category list item are not configure. we changed all the content in the mylisting with our new site. then also it's not fetching content in mylisting theme.

Can you please configure our site creditional to fix our wordpress admin site. thanks

**Comment by Pavithran10** [comment] 2019-03-11 05:02
hi, you are not responding our comment. we have posted our issue three days back but no one should reply for our issue. can you send any reply for our issue.

**Comment by thangvo9x** [comment] 2019-03-11 06:32
Before i told your url is not working. https://housora.com/wp-json/wp/v2/job_listing

**Comment by Pavithran10** [comment] 2019-03-11 07:00
yes, I know that but we reset all our old content in the wordpress admin site enter project is deleted. So, that we create new site for the project now the admin and site is enterly new. If you want to check I will send our the admin site creditional to you private. Thanks

**Comment by thangvo9x** [comment] 2019-03-12 02:23
Hi. The URL - https://housora.com/wp-json/wp/v2/job_listing it worked. Please update more listings for a demo.
Thanks

<blockquote></blockquote>

**Comment by Pavithran10** [comment] 2019-03-12 04:28
ok, what is mean by **update more listing** and then we also configure our new site with the guidence of listapp documentation and also it application is not complete. We tried to configure all the method but still listing app doesn't works properly. so, can you please fix our site creditional once. thanks

**Comment by thangvo9x** [comment] 2019-03-13 02:38
My mean, you should add more listings for the demo then the app will get data from your server.

**Comment by Pavithran10** [comment] 2019-03-13 04:50
ok, I will update and then how to solve this problem feature images are not appearing in the home page, in map location are not fetching and in catagories list content is not avaiable. thanks
[vid.zip](https://github.com/inspireui/support/files/2959813/vid.zip)

**Comment by thangvo9x** [comment] 2019-03-15 07:29
Kindly send AppConfig.json such as your info admin website, i'll config help you again.

**Comment by Pavithran10** [comment] 2019-03-15 11:16
hi, I've attached below appconfig.json file and then I've attached our admin site creditional to your mail private. so please check and config. thanks
[main.zip](https://github.com/inspireui/support/files/2970738/main.zip)

**Comment by Pavithran10** [comment] 2019-03-18 05:09
hi, It working good now thanks for config it. then home screen is totally different all old themes are changed. we can able changed old one also.

**Comment by thangvo9x** [comment] 2019-03-18 06:41
You can remove it Config/index.js with Header.enable -> false

**Closed** 2019-03-18 06:56 UTC
