### ISSUE TITLE
[Fluxstore Listing] - Error, when trying to connect to myListing

### ISSUE THREAD

**Issue by Bingo2000** [inspireui/support#1967] opened 2020-01-30 12:59 UTC
Try to connect to my website with:
json APi is accessible an d shows results in Firefox

`const serverConfig = {
  "type": "mylisting",
  "url": "https://vanagogo.de",
  "blog": "https://vanagogo.de",
  "consumerKey": "ck_0e7d6d841d5d0c952e92d827abb529674f25f8f5",
  "consumerSecret": "cs_7811cbea91c2ff24999627fc1d61a1371d6a918f",
  "forgetPassword":
      "http://mylisting.inspireui.com/wp-login.php?action=lostpassword"
};`

Get error:

![no_connection](https://user-images.githubusercontent.com/13098762/73451787-b4f77f00-4368-11ea-8fd0-e943647d181a.jpg)
![BingoEnvato](https://user-images.githubusercontent.com/13098762/73451798-b9bc3300-4368-11ea-9340-f87965d8a225.jpg)

**Comment by inspireui-support** [comment] 2020-01-31 02:25
@Bingo2000 - pls try to change the line 20 from the screenshot 

```
String categoryPath = 'job_listing_category'
```

This category issue is caused by the latest mylisting template, we have fixed it on the latest code, it will be released on the next couple of day - thank you!

**Comment by Bingo2000** [comment] 2020-01-31 07:51
No Solution:
Please see screenshot:

![error](https://user-images.githubusercontent.com/13098762/73521671-e4f55f80-4406-11ea-8404-4a93eba76412.jpg)

**Comment by inspireui-support** [comment] 2020-02-03 02:11
@Bingo2000 - could you try to update the latest 1.6.3 to fix the issues

**Closed** 2020-02-03 02:11 UTC
Labels: Fluxstore-Listing, question ❓

**Comment by Bingo2000** [comment] 2020-02-03 08:12
Want to change default language. 
You wrote:

> InspireUI Team <notifications@github.com>
> 03:11 (vor 5 Stunden)
> 
> please update the DefaultLanguage from common/config.dart - thank

But in config.dart is no such String.
