### ISSUE TITLE
order customer 

### ISSUE THREAD

**Issue by samz29** [inspireui/support#3359] opened 2020-05-22 12:43 UTC
consumer orders occur three times an order on apps what the problem is yes, whereas consumers only order once

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple s
![photo_2020-05-22 19 41 40](https://user-images.githubusercontent.com/60650955/82668754-5bdb9000-9c64-11ea-8bd0-7d4aec9de2f9.jpeg)
![photo_2020-05-22 19 41 54](https://user-images.githubusercontent.com/60650955/82668760-5ed68080-9c64-11ea-8abe-c46f340b8121.jpeg)
![photo_2020-05-22 19 41 50](https://user-images.githubusercontent.com/60650955/82668764-5f6f1700-9c64-11ea-9844-067c5fa7d7dc.jpeg)

tep by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment] 2020-05-23 02:59
@samz29 

Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by samz29** [comment] 2020-05-23 15:41
in my apps, fluxstore when consumers order on apps, when selecting the method of paying on the spot. order on the system accepts three orders at once, in the admin woocommerce. that is the wrong step.

**Comment by minhcasi** [comment] 2020-05-24 07:36
I'm sorry to close this ticket as it could not be verified, please create the new one when you got enough purchased info - thank you!

**Comment by minhcasi** [comment] 2020-05-24 07:37
@philipvu30  help to investigate this issue

**Comment by minhcasi** [comment] 2020-05-25 07:42
@samz29 - we could not reproduce this issue on our side - this could cause by the multi-tap when process the Payment button, could you try to confirm if it is happening on this test case?

**Comment by samz29** [comment] 2020-05-25 15:21
can you try my apps.in google playhttps://play.google.com/store/apps/details?id=store.medansembako.app

**Comment by minhcasi** [comment] 2020-05-26 02:48
@samz29 - could i confirm which Fluxstore version you have used for this app release?

**Comment by samz29** [comment] 2020-05-26 05:39
i use 1.70 fluxstore

**Comment by minhcasi** [comment] 2020-05-27 02:34
@samz29 - pls try to use the latest `1.7.4` to fix this issue - we remember to fix it - thank you!

**Comment by samz29** [comment] 2020-05-27 02:37
ok  
thanks

**Closed** 2020-05-28 02:21 UTC
Labels: FluxStore, common-integration
