### ISSUE TITLE
Rate My App not Working in Fluxstore for WooCommerce 1.7.7

### ISSUE THREAD

**Issue by zahmed84** [inspireui/support#5028] opened 2020-09-17 10:09 UTC
Rate the App on Settings Page not working:

When we click on Rate the App, it shows nothing. In fact  the problem seems in your code because i also tested fluxstore main source code in Android Studio and the same issue is detected in your main app. Please review it and let me know how to resolve this issue.

![RatemyApp in Fluxstore](https://user-images.githubusercontent.com/58950301/93456621-5f6fe280-f8f7-11ea-8093-fd2eae9c19e9.jpeg)

**Comment by minhcasi** [comment] 2020-09-17 12:45
Duplicate of #5006 - pls help to raise new comments to our new ticket support https://support.inspireui.com - thank you!

**Closed by minhcasi** 2020-09-17 12:45 UTC
