### ISSUE TITLE
FluxStore Woo - Taxes are not showing up in Payment Screen

### ISSUE THREAD

**Issue by anmolmajhail** [inspireui/support#4665] opened 2020-08-19 11:20 UTC
Taxes are not being fetched from the website.

Website Checkout with Taxes:
![image](https://user-images.githubusercontent.com/41463085/90628508-5da0f980-e23b-11ea-887a-b6102d1d6eef.png)

App Payment Screen without Taxes:
![Screenshot_1597835745](https://user-images.githubusercontent.com/41463085/90628606-87f2b700-e23b-11ea-97f4-17ccfdd7122a.png)

So, it can be seen total varies from the website as taxes are not being added in-app. Is there a way to fetch taxes & add in the total app side?

**Comment by minhcasi** [comment] 2020-08-19 13:20
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by anmolmajhail** [comment] 2020-08-19 14:18
Thank you for replying - I have filled the required info.

**Comment by anmolmajhail** [comment] 2020-08-19 18:24
> Thank you for the feedback.
> Please help us to submit this form and fill all required info to continue with the support - [http://verify.inspireui.com (please](http://verify.inspireui.com%C2%A0(please) don't share the purchase code or screenshot public here as another user will use it for activation)
> 
> We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

Any Update Please?

**Comment by minhcasi** [comment] 2020-08-20 03:59
we got your verify info and send to the team for investigating - thank you!

**Comment by minhcasi** [comment] 2020-08-21 05:17
@minhtruong315 - please help to investigate to see if we could display the Tax from the confirm Payment screen

**Comment by Alnaggar94** [comment] 2020-08-24 02:14
@minhcasi - any updates it? It's an urgent issue please help solving it. It show the TAX in the order history screen fine, but during checkout the TAX doesn't show.??

**Comment by minhcasi** [comment] 2020-08-24 04:30
Yes, so far - it is only shown from the order history as checking the Tax could only handle after creating new woocommerce Order. 

My team is working hard to investigate this issue, our solution has synced the Cart from mobile app to the website and refactor the API to support for this feature - it is a very complex update from the background process - we will update when it is ready for testing

Thank you for your time!

**Comment by Alnaggar94** [comment] 2020-08-24 12:17
@minhcasi - Thank you so much for your time, it's the best app in the market and you guys really deserve all the best ❤️. I think you should handle this issue as an urgent priority because it's a main feature, some of my customers are thinking we are overcharged theme because they see different price during checkout. It hurts the business so bad.

**Comment by anmolmajhail** [comment] 2020-08-24 13:05
Yes, It is an urgent issue to resolve. we are not able to go live because of this.

**Comment by minhtruong315** [comment] 2020-08-25 00:10
@anmolmajhail Fluxstore doesn't support Tax now. you can use EnableOnePageCheckout: true in common/config/payments.dart to support Tax when checkout by webview now.
We will investigate and implement that function later.
Thanks for your report

**Comment by minhtruong315** [comment] 2020-08-31 03:53
Hi @anmolmajhail I implemented Tax in our source code. we will release this function on next release. But I can apply it to your source code now so that you can use it.
Please send me full your source code via email: minhtruong315@gmail.com
and send admin account to login your website as well
Thanks

**Comment by Alnaggar94** [comment] 2020-09-01 04:29
@minhtruong315 - I need the TAX implementation too, Can I send you my source code? Or could you just post the solution here?

**Comment by anmolmajhail** [comment] 2020-09-01 10:12
> Hi @anmolmajhail I implemented Tax in our source code. we will release this function on next release. But I can apply it to your source code now so that you can use it.
> Please send me full your source code via email: [minhtruong315@gmail.com](mailto:minhtruong315@gmail.com)
> and send admin account to login your website as well
> Thanks

Thank You. I have sent an Email to minhtruong315@gmail.com

**Comment by anmolmajhail** [comment] 2020-09-01 10:14
Another Issue is there - The payment method is not according to the shipping method.

We have two Shipping methods & each has separate payment methods. On Website Checkout it is working as expected, however, in-app it only picks one payment method for both shipping methods. 

Please check also.

**Comment by anmolmajhail** [comment] 2020-09-01 10:24
> Another Issue is there - The payment method is not according to the shipping method.
> 
> We have two Shipping methods & each has separate payment methods. On Website Checkout it is working as expected, however, in-app it only picks one payment method for both shipping methods.
> 
> Please check also.

I just send an email related to this to - truong@inspireui.com - please check.

**Comment by anmolmajhail** [comment] 2020-09-01 10:34
> > Hi @anmolmajhail I implemented Tax in our source code. we will release this function on next release. But I can apply it to your source code now so that you can use it.
> > Please send me full your source code via email: [minhtruong315@gmail.com](mailto:minhtruong315@gmail.com)
> > and send admin account to login your website as well
> > Thanks
> 
> Thank You. I have sent an Email to [minhtruong315@gmail.com](mailto:minhtruong315@gmail.com)

Email failed to deliver to this Gmail so sent it to -  truong@inspireui.com  @minhtruong315

**Comment by minhtruong315** [comment] 2020-09-03 00:46
@anmolmajhail I checked your source code. it's using old version. I only can update Tax function in the latest version 1.7.7. Please download the latest package in codecayon and your source code to github, then invite me: minhtruong315@gmail.com

**Comment by Alnaggar94** [comment] 2020-09-03 01:39
@minhtruong315 - I need the TAX implementation too, I have sent you my source code to your email "minhtruong315@gmail.com"

**Comment by minhtruong315** [comment] 2020-09-04 02:14
> @minhtruong315 - I need the TAX implementation too, I have sent you my source code to your email "[minhtruong315@gmail.com](mailto:minhtruong315@gmail.com)"

please wait to update the next version 1.7.8

**Comment by minhtruong315** [comment] 2020-09-04 02:14
@anmolmajhail how?

**Comment by minhcasi** [comment] 2020-09-07 02:39
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-09-07 02:39 UTC
Labels: 1.7.8, FluxStore, tax-payment
