### ISSUE TITLE
cestore can,t install at windows 

### ISSUE THREAD

**Issue by almalizy** [inspireui/support#553] opened 2019-05-02 09:05 UTC
i need to install it at windows
but i tried alot and get this error

PS C:\CeStore-1.3.0\Source\web> npm run app:install

> cezerin@0.33.0 app:install C:\CeStore-1.3.0\Source\web
> ./scripts/install.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cezerin@0.33.0 app:install: `./scripts/install.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cezerin@0.33.0 app:install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by minhtruong315** [comment] 2019-05-02 09:14
Hi @almalizy 
Open the project in cmd. Then run these commands
- npm install
- npm run build
- npm start

**Comment by almalizy** [comment] 2019-05-03 12:29
thanks a lot it works now

but i had some bugs

while trying to add pictures at dashboard/products then  it never shown
and instead of that the old pictures duplicated 

also if i delete the old pictures at products then it returned again if i add new pictures

**Comment by minhcasi** [comment] 2019-05-07 10:56
Duplicate of #559

**Closed by minhcasi** 2019-05-07 10:56 UTC
