### ISSUE TITLE
FluxStore Woocommerce Bugs 

### ISSUE THREAD

**Issue by FaizalAndro** [inspireui/support#4005] opened 2020-07-01 11:45 UTC
Recently, puchased Fluxstore Woocommerce, Facing Two issues one is Product doesn't fetch and another is I didn't get any config.json file in common/config folder. 

Please connect with me and fix it

**Comment by ameenbadri7** [comment] 2020-07-01 12:05
hello @FaizalAndro thank you for purchasing the fluxstore product.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

you have submitted for the fluxstore listing product before please do it again for the fluxstore pro.

and for the now you can check the fluxstore [documentation](https://docs.inspireui.com/fluxstore/)
Thank you for your time!

**Comment by minhcasi** [comment] 2020-07-03 04:49
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-03 04:49 UTC
Labels: needs-more-info

**Comment by FaizalAndro** [comment] 2020-07-10 05:58
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
1. Native Forgot Screen just show blank
![Capture](https://user-images.githubusercontent.com/37078576/87120592-6bf41100-c29e-11ea-9438-2928953076c9.PNG)
![WhatsApp Image 2020-07-10 at 11 14 45 AM](https://user-images.githubusercontent.com/37078576/87120653-9776fb80-c29e-11ea-8f23-79f15543bae7.jpeg)

2. How to add specific product i Banner click through fluxbuilder
![issue 3](https://user-images.githubusercontent.com/37078576/87120689-afe71600-c29e-11ea-83ae-8a2bfe24a337.PNG)

3. How to change privacy and policy terms
![WhatsApp Image 2020-07-10 at 11 14 45 AM (1)](https://user-images.githubusercontent.com/37078576/87120723-c55c4000-c29e-11ea-955e-65951dcf9827.jpeg)

4. In categories sub categories, it only display 20 products, it is a serious issue please tell why it happened if you want source code or website login msz me privately at faizalkhan8130@gmail.com

5. After dark theme text color problem
![WhatsApp Image 2020-07-10 at 11 14 45 AM (2)](https://user-images.githubusercontent.com/37078576/87120849-153b0700-c29f-11ea-9592-4ec93a7d3ff0.jpeg)

6. App seems like slow when I run in my device. It doesn't give a feel like native app.
+ Product & version: 1.7.5
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: Both
+ Screenshot issues (drag the file to attach here): Attached accordingly




**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

Done



**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊
