### ISSUE TITLE
Error in Running on Android Studio

### ISSUE THREAD

**Issue by EISAGHANI** [inspireui/support#4361] opened 2020-07-25 11:33 UTC
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null build failed.

FAILURE: Build failed with an exception.

Where: Script ‘C:\Flutter\flutter\packages\flutter_tools\gradle\flutter.gradle’ line: 882
What went wrong: Execution failed for task ’:app:compileFlutterBuildDebug’. > Process ‘command ‘C:\Flutter\flutter\bin\flutter.bat’’ finished with non-zero exit value 1
Try: Run with—stacktrace option to get the stack trace. Run with—info or—debug option to get more log output. Run with—scan to get full insights.
Get more help at https://help.gradle.org
BUILD FAILED in 6m 55s Exception: Gradle task assembleDebug failed with exit code 1

Please solve my problem

**Comment by ameenbadri7** [comment] 2020-07-25 14:36
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by minhcasi** [comment] 2020-07-27 01:45
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-27 01:45 UTC
Labels: needs-more-info
