### ISSUE TITLE
Fluxlisting Dark Mode & Search issues

### ISSUE THREAD

**Issue by ChrisActeir** [inspireui/support#4726] opened 2020-08-25 03:36 UTC
First issue: 

How do you add location search like Yelp & Trip Advisor

Second issue:

Dark Mode for listing layout "listingHalfSizeImageType" is not showing white font in Title, Price, Locations...

![Screen Shot 2020-08-24 at 8 34 50 PM](https://user-images.githubusercontent.com/62954946/91119908-456d1800-e649-11ea-847e-4a8c54da11d5.png)

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-08-24 at 20 31 17](https://user-images.githubusercontent.com/62954946/91119925-4ef68000-e649-11ea-9935-dbc2d3b856ec.png)

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-08-24 at 20 35 20](https://user-images.githubusercontent.com/62954946/91119940-574ebb00-e649-11ea-9f2a-af97c022009a.png)

**Comment by minhcasi** [comment] 2020-08-25 07:46
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-08-26 03:28
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-08-26 03:28 UTC
Labels: needs-more-info
