### ISSUE TITLE
No ads appear inside the application

### ISSUE THREAD

**Issue by emadpost2016** [inspireui/support#4280] opened 2020-07-20 14:30 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

![image](https://user-images.githubusercontent.com/58606378/87948724-5accb080-caa5-11ea-952a-d3a99dd2a9db.png)

After adding to my ad ads from adomb, no ads appear
1.7.4
1.17.3
samsung A30

**Comment by ameenbadri7** [comment] 2020-07-20 17:27
hello @emadpost2016 
please double check this [guide ](https://docs.inspireui.com/fluxstore/Admod-FacebookAd/).
it's working we check it.
Thank you

**Comment by emadpost2016** [comment] 2020-07-20 19:54
"type": kAdType.googleReward,

if i change to this it work admob


‫في الاثنين، 20 يوليو 2020 في 7:27 م تمت كتابة ما يلي بواسطة amin badri
أمين بدري <‪notifications@github.com‬‏>:‬

**Comment by ameenbadri7** [comment] 2020-07-21 00:25
Glad that this works. 
If your problem solved please help us by closing this ticket. 

Thank you.

**Comment by ameenbadri7** [comment] 2020-07-21 22:45
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved 
- Thank you for your time!

**Closed by ameenbadri7** 2020-07-21 22:45 UTC
Labels: FluxstoreMV
