### ISSUE TITLE
Getting only one store from dokan multivendor in my app

### ISSUE THREAD

**Issue by MH-sabu** [inspireui/support#5036] opened 2020-09-21 04:42 UTC
We have moved to a new ticket support system, please post your new ticket on this link http://support.inspireui.com/
![InkedWhatsApp Image 2020-09-20 at 10 39 12 PM_LI](https://user-images.githubusercontent.com/14260461/93733225-65670b80-fbf6-11ea-9293-31c628108da0.jpg)

when using demo cosumerkey and secretkey of mstore api, I am getting all store created in dokan plugin i in my app but when using cosumerkey and secretkey of my store modestgirls.shop I am getting only one store in featured and no store when clicking on store in category
![WhatsApp Image 2020-09-17 at 11 54 43 PM](https://user-images.githubusercontent.com/14260461/93733355-e32b1700-fbf6-11ea-9734-2057ffb9a2b8.jpeg)

can you please tell me why this is happening . what are the possibility. I am trying to start a startup. Thank you

**Comment by minhcasi** [comment] 2020-09-22 02:12
Duplicate of #5006

**Closed by minhcasi** 2020-09-22 02:12 UTC

**Comment by MH-sabu** [comment] 2020-09-23 05:14
> 
> 
> Duplicate of #5006

 how can i get support form http://support.inspireui.com/? i can not register @minhcasi .
