### ISSUE TITLE
[Beonews pro] - Help with installing Beonews

### ISSUE THREAD

**Issue by dermayank** [inspireui/support#1515] opened 2019-12-04 04:56 UTC
I am trying to install beonews on Linux system and I'm facing lots of errors:

1) Even after installing all the plugins in the wordpress site, the cebuilder still says "The rest api is not working correctly!"

![Screenshot from 2019-12-04 10-49-05](https://user-images.githubusercontent.com/24271097/70114815-bddb1580-1683-11ea-9787-7d5a3d976901.png)

2) Can't install Homebrew, Yarn, Expo directly from the Cebuilder.
![Screenshot from 2019-12-04 10-49-10](https://user-images.githubusercontent.com/24271097/70114833-db0fe400-1683-11ea-9aaa-9358d2b11cd0.png)

![Screenshot from 2019-12-04 10-30-36](https://user-images.githubusercontent.com/24271097/70114062-207ee200-1681-11ea-84a9-f4c576ff183e.png)

**Comment by minhcasi** [comment] 2019-12-07 08:17
Duplicate of #1547

We have updated the solution on 1547 - please help to check

**Closed by minhcasi** 2019-12-07 08:17 UTC
Labels: beonews, cebuilder
