### ISSUE TITLE
[Fluxstore 1.5.7] - how to setup payment method MERCADOPAGO and error shipping method MERCADOENVIOS

### ISSUE THREAD

**Issue by EmilianH** [inspireui/support#1330] opened 2019-11-04 15:22 UTC
I have woocommerce correctly set up with the MERCADOPAGO payment method, this also includes the MERCADOENVIOS shipping method, I don't know how to configure this payment method, and the shipping method gives me an error tooin flutter, i put the id correctly.

![shipping-error01](https://user-images.githubusercontent.com/57189819/68132478-8995fd00-fefd-11e9-8078-eeaff6af6e6f.jpg)
[55640809-fluxstore-woocommerce-flutter-ecommerce-full-app-license (1).pdf](https://github.com/inspireui/support/files/3804645/55640809-fluxstore-woocommerce-flutter-ecommerce-full-app-license.1.pdf)
[common.zip](https://github.com/inspireui/support/files/3804653/common.zip)

**Comment by minhtruong315** [comment] 2019-11-07 02:14
@EmilianH can you send me config.dart file and admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1330

**Comment by EmilianH** [comment] 2019-11-09 19:11
Four days have passed and I don't hear from you.

Minh don't forget about me!!!

**Comment by minhcasi** [comment] 2019-11-10 01:52
@EmilianH - we still follow up your issues and keep in the update, could we able to log in as the admin to check the plugin/payment config on your site, it could be the incorrect config - pls send as private to truong@inspireui.com - thank you!

@minhtruong315 - the attache config.dart already send above, pls double check

**Comment by EmilianH** [comment] 2019-11-10 16:40
Minh! 
As I mentioned before, the configuration in woocommerce is perfect, since I can finish the purchase without problems from the web, but from the app not working.
Please I need you to tell me how to add the MERCADOPAGO payment method to fluxstore.
thanks

**Comment by minhcasi** [comment] 2019-11-13 11:56
@EmilianH - the website is not working on our side - https://tppr.me/O7qRo - could you double-check? Thank

**Comment by EmilianH** [comment] 2019-11-13 12:00
Here works perfect
![image](https://user-images.githubusercontent.com/57189819/68761887-d069ae00-05f3-11ea-889e-1990c1d5e7c5.png)

**Comment by EmilianH** [comment] 2019-11-13 12:02
Can you try with VPN or something?

**Comment by minhcasi** [comment] 2019-11-13 12:09
also, tried to check on 2 PC, still not work - could you able to enable it from the hosting config?

**Comment by EmilianH** [comment] 2019-11-13 12:23
how can i enable in the hosting config? you want the data account?

**Comment by minhcasi** [comment] 2019-11-13 12:28
Mean there is the restriction access country or firewall on your website that not allow access - try to remove the setting - thanks

**Comment by EmilianH** [comment] 2019-11-13 12:31
ok wait me please, im calling to the hosting service

**Comment by EmilianH** [comment] 2019-11-13 12:36
I already spoke with hosting service, and in 30 minutes it would be enabled, they activated Autralia, if it doesn't work I need you to pass me the public IP

**Comment by minhtruong315** [comment] 2019-11-13 13:27
@EmilianH add my skype: minhtruong315
I'll help you check via teamviewer

**Comment by EmilianH** [comment] 2019-11-13 13:50
Cool, thanks, you can now??

**Comment by EmilianH** [comment] 2019-11-13 14:25
I already wrote you on Skype, please tell me what time is good for you, I'm in Argentina

**Comment by minhtruong315** [comment] 2019-11-13 14:28
I replied on Skype

**Comment by minhcasi** [comment] 2019-11-14 02:52
Duplicate of #1324

**Closed by minhcasi** 2019-11-14 02:52 UTC
Labels: 1.5.8, FluxStore, question ❓
