### ISSUE TITLE
Help add new custom atributte / variation

### ISSUE THREAD

**Issue by daboujey** [inspireui/support#3877] opened 2020-06-23 19:42 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I need options with dropdown select with  custom atributte / variation
+ Product & version: Version: 1.7.5
+ Flutter (or React Native) version: 1.17.4
+ Testing Device/Simulator: Nexus 6 API 26
+ Screenshot issues (drag the file to attach here): 

![attributes](https://user-images.githubusercontent.com/64880213/85451389-30540a00-b570-11ea-83c3-d39e52795b6b.jpg)

const ProductVariantLayout = [
  {
    "name": "color",
    "type": "color"
  },
  {
    "name": "size",
    "type": "box"
  },
  {
    "name": "height",
    "type": "option"
  }
];

I need:
const ProductVariantLayout = [
  {
    "name": "cobertura",
    "type": "option"
  },
  {
    "name": "cobertura-extra",
    "type": "option"
  },
  {
    "name": "topping",
    "type": "option"
  }
];

I need options with dropdown select
How I do ???

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment] 2020-06-23 20:21
on your `lib\common\config\products.dart` file please do as this: 


```
const ProductVariantLayout = {
   "cobertura-extra": "option",
    "cobertura": "option",
    "topping": "option",
};

```
also THIS: 
```
onst kProductVariantLanguage = {
  "en": {
"cobertura-extra": "Cobertura Extra",
    "cobertura": "Cobertura",
    "topping": "Topping",
  },
```

and also other languages 
```
  "ar": {
"cobertura-extra": "Cobertura Extra",
    "cobertura": "Cobertura",
    "topping": "Topping",
  },
```

* The fluxstore team will update the documentation soon.

this is my full file if you want to see the new configurations. 
[products.txt](https://github.com/inspireui/support/files/4821713/products.txt)

change .txt to .dart 

please let me know if you have other problems.

**Comment by minhcasi** [comment] 2020-06-24 02:50
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by daboujey** [comment] 2020-06-24 07:20
> Thank you for the feedback.
> 
> Please help us to submit this form and fill all required info to continue with the support - [http://verify.inspireui.com/ -](http://verify.inspireui.com/%C2%A0-) please don't share the purchase code or screenshot public here as another user will use it for activation.
> 
> We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

I posted my license here because I didn't know this channel was public ...
How do I know if someone has activated my license ???

**Comment by minhcasi** [comment] 2020-06-25 00:32
@daboujey - pls submit it privately on this link http://verify.inspireui.com

**Comment by minhcasi** [comment] 2020-06-26 02:59
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-06-26 02:59 UTC
Labels: needs-more-info
