### ISSUE TITLE
Payment Gateway not supported

### ISSUE THREAD

**Issue by Carlosdmendoza** [inspireui/support#4064] opened 2020-07-05 00:26 UTC
Hi, I am working on the payment gateways for my account and on my website unfortunately PayPal or Stripe won't be an option for native payments however I use a third party plugin in order to make the payments on my site and I have a couple questions about it if you can answer them I would really appreciate it. 

Proof of purchase: https://github.com/inspireui/support/issues/3831#issue-642470049 that is another ticket I created before for another issue.

So back to my problem the type of payments I would like to support to see if it's possible is basically that on chekout tab I would like to do the following:

*Payment option 1:*  What I would like to show here as payment option is a Bank transfer option just for my users to know what is my bank account number for them to deposit on their local bank manually. And that when they press on that option and then go next for them to be taken to the thank you page and the order number is provided at them as usual on other payment methods but that the status if the order remains pending until I manually update it from my end.

*Payment option 2* On this point I would like to know if there is any way in which the users can just go ahead and type in their phone number or email on checkout page and then I would manually send them a payment link through another app I already have. The same as the previous one I would like to show them a message with more instructions after they do that on a web page that I have already created on my website.

*Payment option 3* That would basically be Cash on delivery I am using the Fluxstore for multi vendor. If that is possible that would be great! and you can provide me with a tutorial or instructions or just a code sample for any of the three of them  that would be great.

In the event that you consider that that cannot be done I would have to use the webview for payments however I am having an issue when I try to do so for some reason if I keep the payments on webview after the user selects his products and adds them to the cart and then when he is attempting to pay for them and is redirected to webview the cart on the web is showing as empty but in the app itself the cart is still showing the products he has added. So basically the cart content is not being transferred into the checkout page on the website. 

I would rather use the native payments using the method I told you about if it's possible if not can you please help me fix the second issue. I will wait for your response. I am using Fluxtore Multi Vendor 1.7.5 at the time I will wait for your response best regards.

**Comment by Carlosdmendoza** [comment] 2020-07-05 09:25
1.) I also would like to report some other small issues I have  regarding the vendors store page; for some reason vendor stores are only showing 6 products and when I scroll down and pull to "load more" it loads the same 6 products again I am unsure what is going on there.  

2.) And I know is not your duty to help with customization but how can I create a new page that opens when I press a button or something from the left menu I am tryng to add a button or something that takes my user to a tutorial page I ahve created for them. Or if yopu can give me an idea on how to create a native page I would really appreciate it  I already have  6 pages at the menu bar so I cannot add another one there Or is there any way to show a page I already have in my site? I know about webview but how can I open it from a custom link or something like that?

3.) Is there any way in which I can notify my vendorss through the app whenever they get a new order on their stores?

4.) How can I allow my vendors to gain access to the store control panel from the app I know they are able to add products but I would like them to be able to take the whole control of it as if they were on the website if possible it doesn't matter if it's on webview 

5.) When a person tries to register as a vendor using the app it does ask them for their name, last name and email but nothing more than that how can I start the registration process the same way as if they were on website from the app? Si the system asks them for the store name , store logo, store banner, etc.  I haven't been able to do so. I know it's a lot of questions so take your time I'll wait for your response 

Best regards.

**Comment by minhcasi** [comment] 2020-07-06 03:36
@Carlosdmendoza - thank you for long ticket questions, please give me some time to verify with the team and get back you shortly - thank you!

**Comment by Carlosdmendoza** [comment] 2020-07-06 04:04
Of Course I appreciate it.

**Comment by Carlosdmendoza** [comment] 2020-07-07 16:17
Hi, any updates on this?

**Comment by Carlosdmendoza** [comment] 2020-07-09 08:38
@minhcasi  Hi, I know you might be busy but I have to deploy the app as soon as possible if you can give me priority help me I would really appreciate it.

**Comment by minhcasi** [comment] 2020-07-10 03:12
@Carlosdmendoza - sorry for the delay on the reply

Payment option 1-2: this payment UI should require some customization to add more option, you could try to use the Inspector Tool - https://www.youtube.com/watch?v=yGMt3Y20Zmg 

Payment option 3: the COD will be displayed as the default on Fluxstore after you enable it from WooCommerce side.


1.) I also would like to report some other small issues I have regarding the vendors store page... -> thank you, i've reported to the team to fix it on next `1.7.6`

2.) And I know is not your duty to help with customization ... -> you could try this code https://tppr.me/ePB8A - the pageID could manage from wordpress site, the left menu code - https://tppr.me/T5Lxk

3.) Is there any way in which I can notify my vendorss ... -> we could upgrade this feature later, could be done by customizing the wordpress hook

4.) How can I allow my vendors to gain access to the store ... -> sorry i don't have the solution on this feature, it will be related to the user-section sync data if using webview.

5.) When a person tries to register as a vendor using the app... -> we will upgrade the UX when registering new Vendor, please suggest us as `request new feature` - our team will review and keep more upgrade for Vendor features.

**Comment by Carlosdmendoza** [comment] 2020-07-10 07:23
Hi, I appreciate your response and I will look into everything regarding the first two questions about the payment methods I am unsure on how to do it I am not really familiar with the flutter environment I know you might be really busy but if you could just provide me with a code sample on how to add a new payment method which is not listed I don't need much basically I just need a white blank space for them to type in something and a label for writing the payment method name and if possible an image for the payment I don't need to do any validations for that or something like that whatsoever. I would appreciate if you could help me.  

Regarding the 1.7.6 Version where could I get acces to it or do you know when would that be available?

Regarding the this:
2.) And I know is not your duty to help with customization ... -> you could try this code https://tppr.me/ePB8A - the pageID could manage from wordpress site, the left menu code - https://tppr.me/T5Lxk

It worked perfect with me so thank you!

**Comment by Carlosdmendoza** [comment] 2020-07-10 08:00
But if that would be too hard I would appreciate if you could help me fix this issue with the webview payments as you can see I am having issues with the items on the cart when I add them on the app but I get redirected to the website to make the checkout the cart is showing as if it is empty if you could help me with this I believe it would be way easier. to fix than adding a custom payment gateway.

![WhatsApp Image 2020-07-10 at 1 55 25 AM](https://user-images.githubusercontent.com/46724211/87130700-8d2e1080-c250-11ea-9d47-f1825f26364b.jpeg)
![WhatsApp Image 2020-07-10 at 1 55 25 AM (1)](https://user-images.githubusercontent.com/46724211/87130704-8e5f3d80-c250-11ea-9533-49e68aece07b.jpeg)

**Comment by minhcasi** [comment] 2020-07-11 11:59
@Carlosdmendoza - could i confirm when you process the payment it displays blank screen? What does the error mean? I could not read message language

**Comment by Carlosdmendoza** [comment] 2020-07-11 20:43
Oh I am sorry the message is saying "Your cart is empty " I am adding the products to my cart but when I am trying to use the webview to make the payment since I couldn't solve the issues with native payment for app it's showing that message of your "cart is empty" even do the products are added to the cart seems as if cart content is not being transferred to the website cart. But on my website there is no problems with that. Do you have an idea what could be the problem?

**Comment by Carlosdmendoza** [comment] 2020-07-11 20:44
So basically that app is opening the cart on my website but is showing that the cart content is empty that is basically the problem.

**Comment by minhcasi** [comment] 2020-07-14 04:33
we will investigate and keep an update, @minhtruong315 - pls help with checking

**Comment by Carlosdmendoza** [comment] 2020-07-14 09:21
Ok I"ll wait for your response its urgent fpr me to fix this

**Comment by Carlosdmendoza** [comment] 2020-07-15 18:44
Hey any updates on this? it's been more than 10 days....

**Comment by minhcasi** [comment] 2020-07-16 03:41
@Carlosdmendoza - 
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. Although checking this Integration Issue is not included from our support scope - https://inspireui.com/support-policies/, but we’re working as hard as we can to reply to your request as soon as possible.

Would you mind to check this pre-config site that fixes the payment issue - https://docs.inspireui.com/fluxstore/multi-vendor/#1-website-integration

**Comment by Carlosdmendoza** [comment] 2020-07-16 06:01
@minhcasi  I have done that all of the settings are good I have followed all of the steps already to have that done yet the same issue remains when attempting to pay using webview cart is still showing as empty.. please don't wait another 3 days to reply to this ticket. I have waited over 10 days now..

**Comment by Carlosdmendoza** [comment] 2020-07-16 07:42
I am also having this error I am unsure why would you ming giving a look at it?
![image](https://user-images.githubusercontent.com/46724211/87641443-5602a800-c705-11ea-9d96-b011c315fdf8.png)

this is a copy of my pubspec.yaml file I have no idea what the problem is 

name: emprendedorhn
description: Tu tienda en linea

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.7.5+35

environment:setup
  sdk : ">=2.1.0 <3.0.0"

dependencies:
  logs:
    git: https://github.com/pq/logs
  flutter:
    sdk: flutter
  http: 0.12.1
  html_unescape: 1.0.1+3
  provider: 4.1.2
  after_layout: 1.0.7+2
  font_awesome_flutter: 8.8.1
  vector_math: 2.0.8
  carousel_pro: 1.0.0
  flutter_widget_from_html: 0.3.3+4
  configurable_expansion_tile: 1.0.0
  timeago: 2.0.26
  share: 0.6.4+3
  validate: 1.7.0
  country_pickers: 1.3.0
  shared_preferences: 0.5.7+3
  firebase_messaging: 6.0.16
  firebase_analytics: 5.0.14
  transparent_image: 1.0.0
  pull_to_refresh: 1.5.8
  localstorage: 3.0.2+5
  notification_permissions: 0.4.4
  flare_splash_screen: 3.0.1
  rate_my_app: 0.6.1+3
  page_indicator: 0.3.0
  intro_slider: 2.3.1
  url_launcher: 5.4.10
  extended_image: 0.9.0
  firebase_core: 0.4.4 # keep these version as there is new issue
  firebase_auth: 0.15.3 # with the latest firebase https://github.com/FirebaseExtended/flutterfire/issues/2084
  flutter_webview_plugin: 0.3.11
  connectivity: 0.4.8+6
  random_string: 2.0.1
  google_maps_flutter: 0.5.28+1
  cached_network_image: 2.2.0+1
  uuid: 2.0.4
  uni_links: 0.4.0
  flutter_staggered_grid_view: 0.3.0
  auto_size_text: 2.1.0
  flutter_swiper: 1.1.6
  flutter_widgets: 0.1.12
  video_player: 0.10.11+1
  flutter_spinkit: 4.1.2+1
  percent_indicator: 2.1.3
  animated_text_kit: 2.1.0
  wave: 0.0.8
  http_auth: 0.2.9
  firebase_admob: 0.9.3+2
  facebook_audience_network: 0.6.1
  pin_code_fields: 3.0.1
  flutter_facebook_login: 3.0.0
  webview_flutter: 0.3.22+1
  rubber: 0.4.0
  flutter_localizations:
    sdk: flutter
  custom_splash: 0.0.2
  apple_sign_in: 0.1.0
  google_sign_in: 4.5.1
  google_fonts: 1.1.0
  flutter_statusbarcolor: 0.2.3
  app_settings: 4.0.0
  animated_splash: 1.0.0
  firebase_database: 3.1.6
  event_bus: 1.1.1
  cloud_firestore: 0.13.4 # firestore_ui 1.9.1 depends on cloud_firestore 0.13.4
  firestore_ui: 1.9.1
  image_picker: 0.6.7
  country_code_picker: 1.3.14
  flutter_typeahead: 1.8.1
  flash: 1.3.1
  graphql: 3.0.2
  flutter_cupertino_date_picker: 1.0.26
  location: 3.0.2
  liquid_swipe: 1.4.3
  sticky_headers: 0.1.8+1
  onesignal_flutter: 2.4.1
  zoom_widget: 0.1.3
  awesome_card: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.7.5
  pedantic: 1.8.0+1 # Analysis
  flutter_driver:
    sdk: flutter

# Run this script to generate the app icon: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - lib/config/
    - lib/common/
    - lib/config/mocks/
    - lib/config/states/
    - assets/icons/categories/
    - assets/icons/tabs/
    - assets/icons/profile/
    - assets/icons/payment/
    - assets/images/
    - assets/images/country/
    - assets/images/favicon/
    - assets/html/
    - assets/images/background/
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/MaterialIcons.ttf
    - family: Entypo
      fonts:
        - asset: assets/fonts/Entypo.ttf
    - family: FontAwesome
      fonts:
        - asset: assets/fonts/FontAwesome.ttf
    - family: MaterialCommunityIcons
      fonts:
        - asset: assets/fonts/MaterialCommunityIcons.ttf
    - family: Feather
      fonts:
        - asset: assets/fonts/Feather.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
flutter_intl:
  enabled: true

**Comment by minhcasi** [comment] 2020-07-17 09:59
@Carlosdmendoza - could i know if you are using the flutter stable channel? 

Pls check this solution if it could help to fix the cache issue on your flutter sdk - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by Carlosdmendoza** [comment] 2020-07-19 00:04
I am using a flutter stable channel version 1.17.3  you did not respond to my main query of the payments not supported via web view is there any way someone to help me through skype to have this fixed?

**Comment by minhcasi** [comment] 2020-07-19 04:11
@Carlosdmendoza - the missing params from Webview could cause by the out-date mstore-api - could you help to check if you are using the latest mstore-api version (Wordpress side) - thank you!

**Comment by Carlosdmendoza** [comment] 2020-07-19 04:16
@minhcasi  Hi, mstore-api version is at latest version there is no updates pending at the time.

**Comment by minhcasi** [comment] 2020-07-20 12:22
@Carlosdmendoza - pls send your final source and share to inspireui.team@gmail.com - we will help to debug this issue - thank you!

**Comment by Carlosdmendoza** [comment] 2020-07-20 22:44
Hi @minhcasi  I appreciate your response I just send it to the email provided; I appreciate your time into this matter please let me know if you need me to send anything else. Thank you!

**Comment by minhcasi** [comment] 2020-07-23 04:34
Could be about the SignIn state from the user iphone, you could try to check this solution:

Open up the `Setting` app in your iPhone and tap on your name at the top. Then press `Password & Security`, then Apple ID login. They listed all the apps there and you can delete the `Fluxstore app` to revoke access.

**Comment by Carlosdmendoza** [comment] 2020-07-23 05:02
Hi, did you received my e-mail? Is there something else I can send you?

**Comment by Carlosdmendoza** [comment] 2020-07-23 06:17
Was that meant for me?

**Comment by minhcasi** [comment] 2020-07-24 09:15
@Carlosdmendoza - our team report to fix the payment issues on the latest code `1.7.6` - please help to merge your project with this version and give a try with the testing, please help to update the `mstore-api` plugin as well

ref guide: https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6

**Comment by Carlosdmendoza** [comment] 2020-07-25 08:18
Hello @minhcasi  I have updated to the latest code 1.7.6 and double checked if Mstore Api plugn was updated and now this happens products are not loading properly and this happens after 10 seconds of oppening the app:

![WhatsApp Image 2020-07-25 at 2 05 24 AM](https://user-images.githubusercontent.com/46724211/88452561-09158480-ce1d-11ea-9481-01780c9ab838.jpeg) 

![WhatsApp Image 2020-07-25 at 2 05 25 AM](https://user-images.githubusercontent.com/46724211/88452565-129eec80-ce1d-11ea-8437-d4b2f56b1e8a.jpeg)

Any suggestions on what may I do?

**Comment by Carlosdmendoza** [comment] 2020-07-27 07:44
any updates on this?

**Comment by minhcasi** [comment] 2020-07-27 09:30
@Carlosdmendoza - this issue is caused the `config_en.json` had the wrong format that the app could not read, could you quick sharing the json config here - thank you!

**Comment by Carlosdmendoza** [comment] 2020-07-27 15:57
{
  "HorizonLayout":[
    {
      "showLogo":true,
      "showSearch":true,
      "image":"https://emprendedorhn.com/wp-content/uploads/2020/07/LogoMasiso-1.png",
      "layout":"logo",
      "showMenu":true
    },
    {
      "layout":"header_search",
      "text":"Buscar producto..",
      "height":77,
      "shadow":15,
      "padding":17,
      "radius":30
    },
    {
      "radius":17,
      "items":[
        {
          "url":"https://emprendedorhn.com/tiendas",
          "image":"https://emprendedorhn.com/wp-content/uploads/2020/07/2-3-1.png",
          "padding":5
        },
        {
          "padding":5,
          "url":"https://emprendedorhn.com/registro-emprendedor",
          "image":"https://emprendedorhn.com/wp-content/uploads/2020/07/1-2-1.png"
        },
        {
          "url":"https://emprendedorhn.com/mi-tienda",
          "image":"https://emprendedorhn.com/wp-content/uploads/2020/07/3-2-1.png",
          "padding":5
        }
      ],
      "autoPlay":true,
      "layout":"bannerImage",
      "design":"swiper",
      "isSlider":true
    },
    {
      "type":"image",
      "items":[
        {
          "originalColor":true,
          "colors":["#333333"],
          "showText":false,
          "image":"https://emprendedorhn.com/wp-content/uploads/2020/06/Regalos.png",
          "category":92
        },
        {
          "originalColor":true,
          "category":94,
          "colors":["#333333"],
          "showText":false,
          "image":"https://emprendedorhn.com/wp-content/uploads/2020/06/Moda.png"
        },
        {
          "showText":false,
          "category":201,
          "image":"https://emprendedorhn.com/wp-content/uploads/2020/06/Supermercado.png",
          "colors":["#333333"],
          "originalColor":true
        },
        {
          "category":91,
          "colors":["#333333"],
          "showText":false,
          "originalColor":true,
          "image":"https://emprendedorhn.com/wp-content/uploads/2020/06/hechoamano.png"
        },
        {
          "originalColor":true,
          "category":85,
          "colors":["#333333"],
          "showText":false,
          "image":"https://emprendedorhn.com/wp-content/uploads/2020/06/Arte.png"
        },
        {
          "originalColor":true,
          "showText":false,
          "colors":["#333333"],
          "image":"https://emprendedorhn.com/wp-content/uploads/2020/06/Belleza.png",
          "category":77
        },
        {
          "colors":["#333333"],
          "showText":false,
          "category":82,
          "image":"https://emprendedorhn.com/wp-content/uploads/2020/06/Tecnologia.png",
          "originalColor":true
        },
        {
          "showText":false,
          "category":196,
          "image":"https://emprendedorhn.com/wp-content/uploads/2020/06/Entrtenimiento.png",
          "originalColor":true,
          "colors":["#333333"]
        },
        {
          "category":80,
          "originalColor":true,
          "colors":["#333333"],
          "showText":false,
          "image":"https://emprendedorhn.com/wp-content/uploads/2020/06/maternidad.png"
        },
        {
          "showText":false,
          "originalColor":true,
          "colors":["#333333"],
          "category":74,
          "image":"https://emprendedorhn.com/wp-content/uploads/2020/06/Mascotas.png"
        },
        {
          "category":78,
          "image":"https://emprendedorhn.com/wp-content/uploads/2020/06/oficina.png",
          "showText":false,
          "originalColor":true,
          "colors":["#333333"]
        },
        {
          "originalColor":true,
          "showText":false,
          "colors":["#333333"],
          "category":81,
          "image":"https://emprendedorhn.com/wp-content/uploads/2020/06/hogar.png"
        }
      ],
      "radius":50,
      "line":false,
      "layout":"category",
      "wrap":false,
      "size":1.4
    },
    {
      "layout":"threeColumn",
      "isSnapping":false,
      "category":94,
      "name":"Moda"
    },
    {
      "category":92,
      "layout":"threeColumn",
      "name":"Productos personalizados",
      "isSnapping":false
    },
    {
      "category":77,
      "layout":"threeColumn",
      "name":"Salud y Belleza",
      "isSnapping":false
    },
    {
      "layout":"threeColumn",
      "name":"Opciones de regalo",
      "isSnapping":false,
      "category":354
    },
    {
      "layout":"listTile",
      "name":"Para regalar",
      "category":88
    },
    {
      "layout":"twoColumn",
      "name":"Joyeria",
      "category":98,
      "isSnapping":true
    },
    {
      "category":91,
      "layout":"threeColumn",
      "name":"Hecho a Mano",
      "isSnapping":false
    },
    {
      "category":85,
      "isSnapping":true,
      "name":"Arte y Cultura",
      "layout":"twoColumn"
    },
    {
      "layout":"threeColumn",
      "category":217,
      "name":"Maquillaje",
      "isSnapping":false
    },
    {
      "layout":"recentView",
      "isSnapping":false,
      "category":18,
      "name":"Vistos recientemente"
    },
    {
      "isSnapping":true,
      "category":201,
      "layout":"threeColumn",
      "name":"Supermercado"
    },
    {
      "name":"Carnes",
      "layout":"threeColumn",
      "isSnapping":false,
      "category":291
    },
    {
      "isSnapping":true,
      "name":"Lacteos",
      "layout":"threeColumn",
      "category":290
    },
    {
      "layout":"threeColumn",
      "isSnapping":false,
      "name":"Especias y condimentos ",
      "category":328
    },
    {
      "layout":"twoColumn",
      "name":"De la finca a tu mesa",
      "isSnapping":false,
      "category":338
    },
    {
      "name":"Tazas artesanales",
      "category":344,
      "layout":"threeColumn",
      "isSnapping":false
    },
    {
      "name":"Bioseguridad",
      "isSnapping":true,
      "layout":"twoColumn",
      "category":90
    },
    {
      "category":350,
      "name":"Vestidos",
      "layout":"twoColumn",
      "isSnapping":false
    },
    {
      "name":"Juguetes para mascotas",
      "isSnapping":false,
      "layout":"threeColumn",
      "category":352
    },
    {
      "layout":"staggered",
      "category":74,
      "isSnapping":false,
      "name":"Jardin y Mascotas"
    },
    {
      "category":353,
      "name":"Shampoo para mascotas",
      "layout":"listTile"
    }
  ],
  "Setting":{
    "MainColor":"#0288D1",
    "ProductListLayout":"list",
    "StickyHeader":true,
    "ProductDetail":"simpleType"
  },
  "TabBar":[
    {
      "layout":"home",
      "pos":100,
      "icon":"assets/icons/tabs/icon-home.png"
    },
    {
      "data":{
        "subHeader":"This is sub heading",
        "container":{
          "height":0.5,
          "header":{
            "padding":{
              "vertical":10,
              "horizontal":20
            },
            "color":"#FFFFFF",
            "text":"About US",
            "align":{
              "x":-1,
              "y":0.8
            },
            "background":"#000000"
          },
          "image":{
            "align":{
              "x":1,
              "y":1
            },
            "width":1,
            "height":0.5,
            "url":"https://images.unsplash.com/photo-1584352587534-5763683125b5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2700&q=80"}
        },
        "description":"This is description",
        "id":1
      },
      "layout":"category",
      "categoryLayout":"card",
      "pos":200,
      "icon":"grid"
    },
    {
      "pos":300,
      "layout":"cart",
      "icon":"assets/icons/tabs/icon-cart2.png"
    },
    {
      "icon":"heart",
      "layout":"wishlist",
      "pos":400
    },
    {
      "images":["briefcase",
        "chrome",
        "download",
        "compass",
        "instagram",
        "activity",
        "map",
        "package",
        "camera",
        "briefcase",
        "chrome",
        "download",
        "compass",
        "instagram",
        "activity",
        "map",
        "package",
        "camera",
        "briefcase",
        "chrome",
        "download",
        "compass",
        "instagram",
        "activity",
        "map",
        "package",
        "camera",
        "briefcase",
        "chrome",
        "download",
        "compass",
        "instagram",
        "activity",
        "map",
        "package",
        "camera",
        "briefcase",
        "chrome",
        "download",
        "compass",
        "instagram",
        "activity",
        "map",
        "package",
        "camera",
        "briefcase",
        "chrome",
        "download",
        "compass"],
      "url":"https://inspireui.com",
      "layout":"search",
      "title":"",
      "categoryLayout":"card",
      "icon":"search",
      "data":{
        "container":{
          "height":0.5,
          "image":{
            "align":{
              "y":1,
              "x":1
            },
            "width":1,
            "url":"https://images.unsplash.com/photo-1584352587534-5763683125b5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2700&q=80",
            "height":0.5
          },
          "header":{
            "text":"About US",
            "padding":{
              "horizontal":20,
              "vertical":10
            },
            "background":"#000000",
            "align":{
              "y":0.8,
              "x":-1
            },
            "color":"#FFFFFF"}
        },
        "subHeader":"This is sub heading",
        "id":1,
        "description":"This is description"
      },
      "pos":500,
      "categories":["85",
        "338",
        "305",
        "196",
        "91",
        "81",
        "74",
        "80",
        "94",
        "18",
        "88",
        "304",
        "77",
        "201",
        "82"]
    },
    {
      "pos":600,
      "data":{
        "id":1,
        "container":{
          "image":{
            "url":"https://images.unsplash.com/photo-1584352587534-5763683125b5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2700&q=80",
            "align":{
              "y":1,
              "x":1
            },
            "height":0.5,
            "width":1
          },
          "header":{
            "text":"About US",
            "background":"#000000",
            "color":"#FFFFFF",
            "align":{
              "x":-1,
              "y":0.8
            },
            "padding":{
              "vertical":10,
              "horizontal":20}
          },
          "height":0.5
        },
        "subHeader":"This is sub heading",
        "description":"This is description"
      },
      "icon":"user",
      "categoryLayout":"animation",
      "categories":["85",
        "338",
        "305",
        "196",
        "91",
        "81",
        "74",
        "80",
        "94",
        "18",
        "88",
        "304",
        "77",
        "201",
        "82"],
      "settings":["products",
        "chat",
        "wishlist",
        "notifications",
        "language",
        "darkTheme",
        "order",
        "privacy",
        "about"],
      "layout":"profile"
    }
  ],
  "Drawer":{
    "logo":"assets/images/logo.png",
    "items":[
      {
        "type":"home",
        "show":true
      },
      {
        "type":"blog",
        "show":true
      },
      {
        "type":"login",
        "show":true
      },
      {
        "type":"category",
        "show":true
      }
    ]
  },
  "Background":{
    "height":0.35,
    "type":"wave",
    "color":"#FFFFF",
    "image":"https://emprendedorhn.com/wp-content/uploads/2020/07/onlineshop.png"
  },
  "VerticalLayout":{
    "category":"95",
    "name":"Ropa y Accesorios",
    "key":"v5ffzec1uz",
    "layout":"columns"}}

**Comment by minhcasi** [comment] 2020-07-28 04:20
@Carlosdmendoza - the format is correct, we will investigate the issue and will let you know

**Comment by Carlosdmendoza** [comment] 2020-07-28 05:49
please let me know.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by minhcasi** [comment] 2020-07-29 09:49
@Carlosdmendoza - could you zip the latest common and config folder then share again to support@inspireui.com - your previous file is form old version so that we could not check - thank you for your time!

**Comment by Carlosdmendoza** [comment] 2020-07-29 17:45
I just send them right now, please let me know if you receive them.

**Comment by minhcasi** [comment] 2020-07-31 03:54
@Carlosdmendoza - could you help to check these simple step on this link https://docs.inspireui.com/fluxstore/woocommerce-setup/#1-website-integration - thank you!

**Comment by minhcasi** [comment] 2020-07-31 03:55
We got the file and will let you know after checking - thank you for your patience

**Comment by Carlosdmendoza** [comment] 2020-07-31 05:20
Alright, thank you.

**Comment by minhcasi** [comment] 2020-07-31 13:02
@Carlosdmendoza - please note that we are still checking the issue as it is quite of weird issues cause from the JSON format 😅

**Comment by Carlosdmendoza** [comment] 2020-07-31 14:58
Thanks for letting me know, yes I know it's really strangd

**Comment by Carlosdmendoza** [comment] 2020-08-03 03:36
Any updates on this?

**Comment by minhcasi** [comment] 2020-08-03 04:11
@Carlosdmendoza - we will update you on today - thanks

**Comment by vumanhsn97** [comment] 2020-08-03 06:01
@Carlosdmendoza 
Config.json in your site wrong format
Please upload new config in mstore api or set isCaching = false in lib/common/config/general.dart
https://tppr.me/kaY2V

**Comment by Carlosdmendoza** [comment] 2020-08-03 07:13
If I setup the isCaching option to false wouldn\t that slow down my app performance?

**Comment by Carlosdmendoza** [comment] 2020-08-03 07:35
I am gonna try both options which is the right config I should upload in the Mstore api in that case?

**Comment by Carlosdmendoza** [comment] 2020-08-03 23:30
@vumanhsn97  I appreciate your help your solution worked fine just as a quick not I have noted that several people were having the same issue with cart not being filled coorectly on checkout that was caused because of an incompatibility between your app and Cartflow pluginn on woocommerce that is a very common plugin for woocommerce I removed it and it worked. I appreciate your help, everything else in the app seems to be fine I am still testing.  There is only a small bug when trying to load all the store from the store list is only showing exactly 10 stores I am having about 80-90 stores in my site any suggestion to fix that?

**Comment by minhcasi** [comment] 2020-08-04 02:30
@Carlosdmendoza - thank you for quick response, we will investigate the `Cartflow plugin`

The loading missing store was fixed on the latest build, we will release it on the next version 👍

**Comment by Carlosdmendoza** [comment] 2020-08-04 18:10
That is good to know, In the meantime is there a temporary solution for that? Or where may I acquire that version? I need to deploy  the app as soon as possible.

**Comment by minhcasi** [comment] 2020-08-07 02:04
@Carlosdmendoza you could get the latest code from our GitLab repo - if you don't have an account please submit here http://gitlab.inspireui.com/

The Cartflow integrate need more time to investigate, we could not promise the delivery time for this feature yet - thank you :)

**Comment by Carlosdmendoza** [comment] 2020-08-07 03:28
Great I will take a look into that and will keep you posted about it, is there any particular folder I should look in order to update the problem with the stores not showing, or  I have to update the whole project to fix that part?

**Comment by minhcasi** [comment] 2020-08-08 02:03
@Carlosdmendoza - pls help to check this guide https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6

**Comment by Carlosdmendoza** [comment] 2020-08-08 02:29
Already thank you I will do so and let you know how it goes, I appreciate your time and patience on this.

**Comment by minhcasi** [comment] 2020-08-10 04:58
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-08-10 04:58 UTC
Labels: FluxstoreMV, Mstore-API
