### ISSUE TITLE
fluxstore targeted api 

### ISSUE THREAD

**Issue by nomicool** [inspireui/support#4612] opened 2020-08-15 16:40 UTC
Playstore is not accepting app error is targetted API is 28 must have 29.
"Your app currently targets API level 28 and must target at least API level 29 to ensure it is built on the latest APIs optimized for security and performance. Change your app's target API level to at least 29. Learn More"

**Comment by minhcasi** [comment] 2020-08-16 01:40
Duplicate of #4601

**Closed by minhcasi** 2020-08-16 01:40 UTC
