### ISSUE TITLE
Error after Mstore API update

### ISSUE THREAD

**Issue by hkhealthliving** [inspireui/support#4776] opened 2020-08-28 08:23 UTC
Hi, we recently update the Wordpress system to 5.5 and Mstore API plugin to 2.9.4. Then error occurs, we cannot login in the mstore app, and found an error at Json API session of Wordpress setting, saying "cannot find controller class 'json_api_mstore_user_controller". We had been using the old version of Mstore API and Mstore.io for framework customization and use CE Builder, which is not compatible with the new version. Therefore, can I have the installation pack for 1.4.0 or the controller file directly? We urgently need it to solve our error. Thanks so much!
![未命名](https://user-images.githubusercontent.com/70368549/91538602-a4cd6f80-e94a-11ea-8de2-98b36419e27e.png)

**Comment by minhcasi** [comment] 2020-08-28 12:37
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-08-29 06:03
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Comment by minhcasi** [comment] 2020-08-31 06:36
@minhtruong315 - pls suggest on this issue

**Comment by hkhealthliving** [comment] 2020-09-01 01:39
Thanks! Or can you provide me with the controller file?

**Comment by minhtruong315** [comment] 2020-09-01 02:53
Hi @hkhealthliving Can u send me full your source code via email: minhtruong315@gmail.com
and admin account to login your website as well
Thanks.

**Comment by hkhealthliving** [comment] 2020-09-01 05:01
Hi,

Addressing ticket #4776 (https://github.com/inspireui/support/issues/4776 ),
I now provide you with our staging site login and pw. You can go in and
investigate.

https://staging-wwwhkhlcomhk.kinsta.cloud/wp-admin
username: hkhealthliving
pw: Health^^Health

Attached please find the error messages found in mobile login interface and
json API session in WP setting.

Thanks!

Best Regards,
Kit So

minhtruong315 <notifications@github.com> 於 2020年9月1日 週二 上午10:53寫道：

**Comment by minhtruong315** [comment] 2020-09-03 03:07
@hkhealthliving how?

**Comment by hkhealthliving** [comment] 2020-09-03 03:31
> @hkhealthliving how?

I have sent an email to minhtruong315@gmail.com on 1/9. Can you receive it?

**Comment by minhtruong315** [comment] 2020-09-03 03:35
Can u resend? I dont see it. Thanks

**Comment by minhtruong315** [comment] 2020-09-03 06:01
@hkhealthliving can u give me the link?

**Comment by hkhealthliving** [comment] 2020-09-03 08:08
I sent you through this email address: minhtruong315@gmail.com 
What link do you need?

**Comment by minhtruong315** [comment] 2020-09-03 10:43
<img width="1201" alt="Screen Shot 2020-09-03 at 5 43 01 PM" src="https://user-images.githubusercontent.com/10402500/92105363-efe4f800-ee0c-11ea-9c79-b2a0061c168b.png">
@hkhealthliving this email?

**Comment by minhtruong315** [comment] 2020-09-04 02:10
@hkhealthliving how?

**Comment by hkhealthliving** [comment] 2020-09-04 03:21
![image](https://user-images.githubusercontent.com/70368549/92195923-a5ad5680-eea0-11ea-9fad-bf939e0d614b.png)
This one, is it treated as spam?

**Comment by hkhealthliving** [comment] 2020-09-04 03:23
@minhtruong315 Sent again just now.
Maybe you can send me a greeting to hkhealthliving@gmail.com if you still cannot receive

**Comment by minhtruong315** [comment] 2020-09-08 08:54
Hi @hkhealthliving I fixed on your website. 
<img width="1434" alt="Screen Shot 2020-09-08 at 3 53 37 PM" src="https://user-images.githubusercontent.com/10402500/92455133-82a9dc00-f1eb-11ea-8021-e8c33897b379.png">

**Closed by minhtruong315** 2020-09-08 08:54 UTC
Labels: MStorePro, Mstore-API

**Comment by HasanHuse** [comment] 2020-09-09 15:25
I am having the same issue, can you explain how you solve this?
