### ISSUE TITLE
Products not showing

### ISSUE THREAD

**Issue by AmaouiON** [inspireui/support#4397] opened 2020-07-28 11:09 UTC
Hi,

I'm facing some problems showing products in different places:

1- on the home screen I'm not always seeing the "recent products" and never seeing the categories products
![image](https://user-images.githubusercontent.com/7475137/88657996-acd78c80-d0ca-11ea-96ed-b2f5edddd4e1.png)

2- Sometimes, when I click on a category it says there is no product on it
3- on the product page, I cant see the related product section 
![image](https://user-images.githubusercontent.com/7475137/88658256-0c359c80-d0cb-11ea-820a-668294340948.png)

Also, if I don't have variants for the product I'm seeing "Title" "Default Title"
![image](https://user-images.githubusercontent.com/7475137/88658321-25d6e400-d0cb-11ea-8c0b-19bc6feb681c.png)

Can you help me fix that ASAP?

**Comment by ameenbadri7** [comment] 2020-07-28 12:41
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by AmaouiON** [comment] 2020-07-28 14:30
I've Filled the form with all the required information

**Comment by minhcasi** [comment] 2020-07-29 02:30
@AmaouiON - the recent view is used to track the view history from other product, example once you navigate to see any product, it will be added to the recent view - let us know if it working fine

**Comment by AmaouiON** [comment] 2020-07-29 15:05
It works at the beginning, but sometimes it's not working. you have just answered a part from my Question 1-

What about the others?

**Comment by luyx2412** [comment] 2020-07-31 09:59
Hi @AmaouiON I just invited you to the fluxshopify latest version repo. Please check email and merge with your code.

Thanks

**Comment by minhcasi** [comment] 2020-08-02 03:26
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-08-02 03:26 UTC
Labels: Fluxshopify
