### ISSUE TITLE
Facing issue when running the project

### ISSUE THREAD

**Issue by iamkunalpitale** [inspireui/support#4416] opened 2020-07-30 06:34 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: e: C:\Users\HP\StudioProjects\fluxstore_woocommerce\android\app\src\main\kotlin\com\inspireui\fluxstore\MainActivity.kt: (11, 48): Type mismatch: inferred type is MainActivity but FlutterEngine was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 36s
Exception: Gradle task assembleDebug failed with exit code 1

+ Product & version: Fluxstore WooCommerce - Flutter E-commerce Full App
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: Nexus 6 API 27
+ Screenshot issues (drag the file to attach here): 
![image](https://user-images.githubusercontent.com/26413565/88888809-9feaa280-d25c-11ea-8693-eb1d146b53ab.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment] 2020-07-30 07:57
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-07-31 02:30
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-31 02:30 UTC
Labels: needs-more-info
