### ISSUE TITLE
[MMV] - Product image and price is not inserted

### ISSUE THREAD

**Issue by santihabib** [inspireui/support#1076] opened 2019-09-17 20:22 UTC
Hello! I have several problems, but I start with the most serious ones. When I upload a product from the app, only the title and content are uploaded. But the price and the main image is not inserted.
The image is uploaded to the server, but it is not placed as a featured image.
In addition to all this, I cannot upload reviews or see existing ones.
I add purchase screenshot and config.

[AppConfig.txt](https://github.com/inspireui/support/files/3623273/AppConfig.txt)

![compra](https://user-images.githubusercontent.com/55243343/65076487-7770f700-d96f-11e9-8cd3-ab36f8b04aba.png)

**Comment by santihabib** [comment] 2019-09-19 13:42
hi! will someone answer? I need help! They can't take so long!

**Comment by minhcasi** [comment] 2019-09-20 01:07
@thangvo9x  - any update ?

**Comment by santihabib** [comment] 2019-09-20 01:14
I do not understand.  It's not working for me and I need help.

**Comment by thangvo9x** [comment] 2019-09-20 01:58
Could you share your admin dashboard for checking? Thanks

**Comment by santihabib** [comment] 2019-09-20 09:29
I sent It to you by email

**Comment by santihabib** [comment] 2019-09-20 19:57
some help?

**Comment by minhcasi** [comment] 2019-09-23 02:15
@santihabib - we have just found out the problem caused by subfolder domain /web (that cause the wrong API request), could you try to map the website to subdomain? 

Example: http://web.bazarios.com

**Comment by santihabib** [comment] 2019-09-26 12:48
please help me!!

**Comment by minhcasi** [comment] 2019-09-26 12:55
Sorry for late response, I will have a check again and let you know on tomorrow - thank  you!

**Comment by santihabib** [comment] 2019-09-26 13:01
ok! Please!

**Comment by santihabib** [comment] 2019-09-28 23:50
any update? please help!!!

**Comment by minhcasi** [comment] 2019-09-29 01:23
@concuacon - pls update

**Comment by santihabib** [comment] 2019-09-29 21:47
@minhcasi  an @concuacon please give me priority and help me

**Comment by santihabib** [comment] 2019-10-02 00:16
Heeeeeelp!!

**Comment by concuacon** [comment] 2019-10-04 13:00
Hello @santihabib i checked this work
[AppConfig.txt](https://github.com/inspireui/support/files/3690629/AppConfig.txt)

![Simulator Screen Shot - iPhone X - 2019-10-04 at 19 56 47](https://user-images.githubusercontent.com/11958061/66209309-47508480-e6e1-11e9-8e89-a2c9ccce1f2d.png)
![Simulator Screen Shot - iPhone X - 2019-10-04 at 19 56 58](https://user-images.githubusercontent.com/11958061/66209315-49b2de80-e6e1-11e9-8720-65447bc7cc82.png)
![Simulator Screen Shot - iPhone X - 2019-10-04 at 19 57 35](https://user-images.githubusercontent.com/11958061/66209322-4d466580-e6e1-11e9-886c-49b104902111.png)

**Comment by santihabib** [comment] 2019-10-04 13:42
hi @concuacon ! 
[AppConfig.txt](https://github.com/inspireui/support/files/3690785/AppConfig.txt)

 17 days ago I answered few words and they didn't help me with my problem! change to subdomain as requested so the config also changed! I attach the current config. Also the problem is not that it does not start! The problem is that when loading a new product, it is loaded without image and without price!

**Comment by santihabib** [comment] 2019-10-06 10:21
19 Days!  What should I do to help me?

**Comment by minhcasi** [comment] 2019-10-06 10:29
@santihabib - confirm - there is an issue with the Create product that missing the Feature image, we have noted for fixing on new release - thank you!

**Comment by santihabib** [comment] 2019-10-06 11:14
And the same goes for the price!  when will they update?

**Comment by minhcasi** [comment] 2019-11-26 15:13
Duplicate of #1456

**Closed by minhcasi** 2019-11-26 15:13 UTC
Labels: MStoreMV, Upgrade, question ❓
