### ISSUE TITLE
fluxsture problems - Android Studio

### ISSUE THREAD

**Issue by roseyazilim** [inspireui/support#3747] opened 2020-06-15 10:59 UTC
![image](https://user-images.githubusercontent.com/53063121/84649924-05363e80-af10-11ea-84c1-ec7e0d9a2dfa.png)

terminal to flutter doctor : 
![image](https://user-images.githubusercontent.com/53063121/84650156-5e05d700-af10-11ea-8ff7-512409a1ae02.png)

i bought your app and it will appear as flutter apk i got this error

can you support me

**Comment by roseyazilim** [comment] 2020-06-15 11:21
![image](https://user-images.githubusercontent.com/53063121/84651966-7aefd980-af13-11ea-8287-63a0a42a76b5.png)

**Comment by minhcasi** [comment] 2020-06-16 01:33
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-06-17 01:37
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one with full information - thank you for your time!

**Comment by minhcasi** [comment] 2020-06-18 12:38
@roseyazilim - we got your verified purchase, pls help to check the solution on this link #3708

**Comment by minhcasi** [comment] 2020-06-19 04:44
let us know your checking - thanks

**Comment by minhcasi** [comment] 2020-06-19 12:13
Duplicate of #3801

**Closed by minhcasi** 2020-06-19 12:13 UTC
Labels: FluxStore
