### ISSUE TITLE
Issues as on 08-07-2020

### ISSUE THREAD

**Issue by stockracee** [inspireui/support#4121] opened 2020-07-08 14:45 UTC
Dear sir, Myself is sahni & I am a tester. I hv found following bug in this app.Pl find attach video link as https://filebin.net/um2gdas0twimcyne

1)Tabs Bug: When we open app & clk on any category then tab screen will open where ‘See All’ tab selected as default tab & it show ‘no product’. 
2)Price Filter bug: you hv set default filter for price as 0$$500 which means when user open app then only product which hv range $0$500 will only shown which is very ordinay bcz to see full list of product, customer has to clk on filter button & set filter $1000 to see full list of items. Which destroy the principal of UX. 
3)NotShowAllProduct: I hv 500 product in my store but app show only 189item. (Even i use filter all to show items) 
4)Product Overlap: Products are overlap on other products. even cart button not seen of some product 
5)Unsymmetrical Space between items: Space between product is not equal which gives ugly look especially when u use ‘single Card view’(One coloum). these type of spacing system should only use when u hv to show portfolio images(only images), not for products. 
6)Many times Repeat Category shown 7)Performance Issue.

I am still testing & let u know more about it…

If u ask then I can give u my woo site api for yours check

**Comment by ameenbadri7** [comment] 2020-07-08 20:41
could you use our [issue opening](https://github.com/inspireui/support/issues/new/choose) template so we can know what is your fluxstore version and the flutter version and also what type of emulator you have so we can help you more.

thank you.

**Comment by stockracee** [comment] 2020-07-09 08:02
I sent details on https://github.com/inspireui/support/issues/new/choose Now pl reply for my query. 
I uses fluxstore as 1.7.5,  I use Nexus 6 Emulator & real device realme 6, Flutter 47.x.x

**Comment by ameenbadri7** [comment] 2020-07-10 01:32
on issue 1 , 3, 4, 5-
we do have more than 20 themes already you can see them in this [video ](https://www.youtube.com/watch?v=5AzAIU7Dddk  ).
you should config your config_en.json to be like your website category IDs and also edit all the necessary Lines inside common files `lib\common `
you can use our [tutorials  ](https://docs.inspireui.com/fluxstore/customization/) to know them better 

on issue 2- 
you can go to `lib\common\constants\slider.dart` and change the values of kMaxPriceFilter

try to see our [common-issues page](https://docs.inspireui.com/fluxstore/common-issues/) and [common-question](https://docs.inspireui.com/fluxstore/common-question/)


thank you sir

**Comment by ameenbadri7** [comment] 2020-07-11 05:00
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Comment by minhcasi** [comment] 2020-07-11 11:01
@ameenbadri7 please help to see a comment from @stockracee and double-check the ticket - thank you!

hi, Its very ordinary Customer care. I lodge a issue on github & tell the bugs(https://github.com/inspireui/support/issues/4121) & yours customer support team ask me for watch a video. Even I watch a videos but its does not hv any solution regard my issue. Its my 2nd time expereance. yours customer care misguide the customers & wasting their time…I humble request to use to pl pay serious attention on customers issue bcz customer invest time & effor to write long queries. deliberating the issue on customer who come to u, is not ideal for any firm . Pl take my comment in positive way. this is also inform u that I browse the other tickets where i find one same problem & in this ticket yours executive accpet the issue & even ask that issue will be resolved in next update. but my customer care executive misguide me & ask me to watch video for my issues(4Issues).

**Comment by minhcasi** [comment] 2020-07-11 11:05
@stockracee - would you mind to share more detail screenshot issues (example the item 5-6-7) to clarify the missing one from @ameenbadri7 - we have upgraded the ticket as high priority to check your issues deeper - thank you for your time 👍

**Comment by stockracee** [comment] 2020-07-11 14:59
I already send u video with explanation with text. Again I am sending u. Pl find https://filebin.net/um2gdas0twimcyne
Also i think It will be best if i send u my woo site api. so that u can check with yours own hand. pl suggest. Issue No1 & 4 are very critical. And I already explain in video. Pl pay serious attention on it.

**Comment by ameenbadri7** [comment] 2020-07-11 15:01
could you talk with me on skype sir so I can help you directly?
add me with `ameenbadri7@gmail.com`.
thank you .

**Comment by minhcasi** [comment] 2020-08-01 02:50
@stockracee - we got your feedback about the issue, please help to update the detailed status here, I have reopened the ticket for further investigating 👍 

Thank you for your patience

**Comment by stockracee** [comment] 2020-08-01 22:32
Dear sir, Myself is sahni & I am a tester. I hv found following bug in this app.Pl find attach video link as https://youtu.be/DRO1wrODoAM

1)Tabs Bug: When we open app & clk on any category then tab screen will open where ‘See All’ tab selected as default tab & it show ‘no product’.
2)Price Filter bug: you hv set default filter for price as 0$$500 which means when user open app then only product which hv range $0$500 will only shown which is very ordinay bcz to see full list of product, customer has to clk on filter button & set filter $1000 to see full list of items. Which destroy the principal of UX.
3)NotShowAllProduct: I hv 500 product in my store but app show only 189item. (Even i use filter all to show items)
4)Product Overlap: Products are overlap on other products. even cart button not seen of some product
5)Unsymmetrical Space between items: Space between product is not equal which gives ugly look especially when u use ‘single Card view’(One coloum). these type of spacing system should only use when u hv to show portfolio images(only images), not for products.
6)Many times Repeat Category shown 
7)Performance Issue.

I am still testing & let u know more about it…

If u ask then I can give u my woo site api for yours check

**Comment by minhcasi** [comment] 2020-08-02 01:48
@stockracee - yes, please share the site admin as private by sending email to support@inspireui.com - thank you so much for your time. 

I've updated the ticket as high priority so that the team could focus to check on next Monday 👍

**Comment by minhcasi** [comment] 2020-08-02 01:49
Could you public the youtube link above as it is set as private so that we could get it?. If it is possible please share some screenshot of each issue as well - thank you!

**Comment by stockracee** [comment] 2020-08-03 11:58
Pl check https://youtu.be/DRO1wrODoAM

**Comment by minhcasi** [comment] 2020-08-05 06:08
@minhtruong315 - please help to investigate this issue

**Comment by minhtruong315** [comment] 2020-08-05 15:05
Hi @stockracee Can u check your issues on version 1.7.6? if your issues are in version 1.7.6. please send me full your source code via email: minhtruong315@gmail.com
I will help check it. Ping me when you sent.
Thanks

**Comment by stockracee** [comment] 2020-08-06 22:00
Yes this issues with 1.7.5 & 1.7.6 also. Can U pl come on TeamView so that I can explain problem live, Which will save a lot of time I already pass 45Days with these Issue.

**Comment by stockracee** [comment] 2020-08-09 15:20
Can U Pl suggest

**Comment by minhtruong315** [comment] 2020-08-09 23:14
@stockracee can u send me full your source code version 1.7.6 via my email? ping me when you sent,

**Comment by stockracee** [comment] 2020-08-11 08:13
hi, Source code is about 1GB, How I can send u by email. Pl suggest.  https://ibb.co/FW7Vy1z

**Comment by minhtruong315** [comment] 2020-08-11 15:07
@stockracee pls delete build folder and ios/Pods folder  then zip source code and upload to google drive then invite me: minhtruong315@gmail.com

**Comment by minhtruong315** [comment] 2020-08-13 09:30
@stockracee ping me when you sent. thanks

**Comment by minhcasi** [comment] 2020-08-16 07:19
@stockracee - let us know if you have any update on this ticket - thank you!

**Comment by minhtruong315** [comment] 2020-08-19 02:37
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Closed by minhtruong315** 2020-08-19 02:37 UTC
Labels: FluxStore, priority !!!
