### ISSUE TITLE
i want to know .jks password and key alias password [fluxstore]

### ISSUE THREAD

**Issue by Saifahmad99** [inspireui/support#4282] opened 2020-07-20 16:30 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I want to know .jks password and key alias password and name. And where to find them
+ Product & version: Fluxstore 1.6.3
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: Android Phone
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment] 2020-07-20 17:28
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by minhcasi** [comment] 2020-07-21 02:39
@Saifahmad99 - you could create your own key https://flutter.dev/docs/deployment/android#create-a-keystore

**Comment by ameenbadri7** [comment] 2020-07-21 22:48
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved.
- Thank you for your time!

**Closed by ameenbadri7** 2020-07-21 22:48 UTC
Labels: FluxStore
