### ISSUE TITLE
ListApp & ListPro

### ISSUE THREAD

**Issue by Suhaibaj** [inspireui/support#907] opened 2019-08-10 19:48 UTC
Hi Team 

i have a qustion about ListApp and ListPro 

Is it compatible with this template?
https://themeforest.net/item/food-guide-restaurant-food-and-drinks-directory-listing-wordpress-theme/17090002
And if you link it to a site based on this template
Will certain problems appear?

thanks,

**Comment by minhcasi** [comment] 2019-08-12 01:48
Duplicate of #906

**Closed by minhcasi** 2019-08-12 01:48 UTC
Labels: question ❓
