### ISSUE TITLE
Fluxstore mv dokan apk not working

### ISSUE THREAD

**Issue by nomicool** [inspireui/support#4161] opened 2020-07-11 07:16 UTC
After having all configuration flux store mv works fine on emulator debug but releasing apk does not works shows error app not open and also I have tried flutter build apk and flutter build apk --split-per-abi
 command not apk works on physical device app crashes not an open issue.

**Comment by minhcasi** [comment] 2020-07-11 11:42
Duplicate of #4137

**Closed by minhcasi** 2020-07-11 11:42 UTC

**Comment by nomicool** [comment] 2020-07-11 12:07
its not the duplicate could you please double check its about fluxstore and other was by store react native
