### ISSUE TITLE
Fluxstore

### ISSUE THREAD

**Issue by qorane099** [inspireui/support#4835] opened 2020-09-02 09:28 UTC
Dear Team,

I have 3 issue:

1. issue of SHA-1, l followed the guide to get sha-1 but the app shows this below error:

Abdulkadirs-MBP:KindaKart abdulkadirqoranesuleiman$ keytool -list -v \
> -alias key -keystore android/app/mstore.jsk
Enter keystore password:  
keytool error: java.lang.Exception: Alias <key> does not exist
java.lang.Exception: Alias <key> does not exist
        at java.base/sun.security.tools.keytool.Main.doPrintEntry(Main.java:2034)
        at java.base/sun.security.tools.keytool.Main.doCommands(Main.java:1267)
        at java.base/sun.security.tools.keytool.Main.run(Main.java:416)
        at java.base/sun.security.tools.keytool.Main.main(Main.java:409)
Abdulkadirs-MBP:KindaKart abdulkadirqoranesuleiman$ 

please see screenshot for your reference, what am l missing?
<img width="1204" alt="Screenshot 2020-08-29 at 3 29 38 PM" src="https://user-images.githubusercontent.com/39888242/91964344-a7eea400-ed2c-11ea-968b-e7c73dce01b6.png">

2. the issue of banner, is there any way possible to use my local images instead of images from servers, if no. what is your suggested servers with a free assets eg. Unplash.

3. if l try to sign up the app as a vendor, it gives me below issue, is it due to sha-a missing or any other error.
<img width="422" alt="screen" src="https://user-images.githubusercontent.com/39888242/91964049-4c241b00-ed2c-11ea-8030-a6a4d474ca35.png">

I have these 3 issue only, everything now is good apart from these issue.

thank you for your help

**Comment by minhcasi** [comment] 2020-09-03 02:56
1. pls try to check more guide and video related to sha1 on this link - https://medium.com/@inspireui/setup-google-login-for-flutter-apps-fedc58a490b8

2. Yes, you could download the image into the asset folder and update the json to load in app local file - https://tppr.me/jTrbi - that will help to speed up your app performance

3. Please try to check the detail log from the android studio to see if that warning is come from which function?

**Comment by qorane099** [comment] 2020-09-03 07:34
Dear @minhcasi 

l try everything about SHa1 but nothing is working out.

please can l share with you the common file and add you my firebase to check where the issue is coming from.


please note that, i have only that above 3 issue, l could have released the app if l do solve these issue.

**Comment by qorane099** [comment] 2020-09-03 07:40
Although l placed the banner images in assets folder, still the app is not fetching the image.

please check the screenshot below.
<img width="1337" alt="Screenshot 2020-09-03 at 1 09 00 PM" src="https://user-images.githubusercontent.com/39888242/92085719-d7fa7d80-ede6-11ea-88e8-04a83377e97c.png">

**Comment by minhcasi** [comment] 2020-09-04 04:31
@qorane099 - try to customize this file `/lib/widgets/home/banner/banner_items.dart`

```
child: widget.config["image"].toString().contains('http')
                ? Tools.image(
                    fit: widget.boxFit ?? BoxFit.fitWidth,
                    url: widget.config["image"],
                  )
                : Image.asset(
                    widget.config['image'],
                    fit: widget.boxFit ?? BoxFit.fitWidth,
                  ),
```

<img width="1094" alt="Screen Shot 2020-09-04 at 11 30 39" src="https://user-images.githubusercontent.com/1459805/92199683-1143f380-eea2-11ea-909b-34cb4cdade0f.png">

**Comment by qorane099** [comment] 2020-09-04 20:11
You only tell me to customize. what changes do l have to make in order banner images to work??


Also, l am requesting you to look what is the issue of login, Sha-1 issue, i am writing this issues and waiting your solve more than weeks.

please let me share with you my common file and check if my files has internal issue and investigate the issue.

I beliave you can solve this issue within seconds

**Comment by minhcasi** [comment] 2020-09-05 03:42
@qorane099 - the provide solution above will fix the asset image issue

The sha1 issue could be fixed by following our guide on this blog https://medium.com/@inspireui/setup-google-login-for-flutter-apps-fedc58a490b8 - it is about your Firebase setting to config the sha1, not from the app side - thank you!

**Comment by qorane099** [comment] 2020-09-05 09:34
1. thank you, the issue of banner is now fixed, l can any images to app banners.


2. the issue of login is still exist, l followed the guide manually and videos also, but still apps throws exception.
l added sha1 and registered the app from google console, 

<img width="433" alt="yy" src="https://user-images.githubusercontent.com/39888242/92302331-0adc7700-ef89-11ea-8e89-326c563b834e.png">

**Comment by qorane099** [comment] 2020-09-05 17:53
Dear Team,

I am having this issue of login since long. please assist me and investigate the issue.😔

I have followed this guide https://medium.com/@inspireui/setup-google-login-for-flutter-apps-fedc58a490b8 but still the issue still exist.

**Comment by minhcasi** [comment] 2020-09-06 04:21
@qorane099 - try to send us your screenshot setting from google consent, Firebase SHA1 setting. Also, try to regenerate the keystore key

**Comment by qorane099** [comment] 2020-09-06 05:50
@minhcasi Below is screenshot you required!!

<img width="1440" alt="Screenshot 2020-09-06 at 11 13 42 AM" src="https://user-images.githubusercontent.com/39888242/92319121-e89f3380-f032-11ea-904a-a20a808978da.png">
<img width="1440" alt="Screenshot 2020-09-06 at 11 15 23 AM" src="https://user-images.githubusercontent.com/39888242/92319126-f0f76e80-f032-11ea-90df-ebf39601f040.png">
<img width="1440" alt="Screenshot 2020-09-06 at 11 15 59 AM" src="https://user-images.githubusercontent.com/39888242/92319127-f2289b80-f032-11ea-9549-7c0f2b31036e.png">
<img width="1437" alt="Screenshot 2020-09-06 at 11 17 39 AM" src="https://user-images.githubusercontent.com/39888242/92319128-f2c13200-f032-11ea-8bca-56fc78b6f84c.png">
<img width="1115" alt="Screenshot 2020-09-06 at 11 18 14 AM" src="https://user-images.githubusercontent.com/39888242/92319131-f3f25f00-f032-11ea-8bc0-132660e1ba8d.png">

**Comment by qorane099** [comment] 2020-09-07 06:37
Any reply here?

Please get back to me and try to help me today. l am on stuck with issue since long time

**Comment by qorane099** [comment] 2020-09-07 09:08
Please try your best to solve this problem today.

I am really losing a lot time.

9121948906

**Comment by minhcasi** [comment] 2020-09-08 10:52
@qorane099 

1. Please follow strictly the official documentation ( https://medium.com/@inspireui/setup-google-login-for-flutter-apps-fedc58a490b8)

If fail please double-check these solutions: 

1. In the beginning the main problem will face a lot of you is that you are getting the wrong SHA1 & SHA256 code!
When you use this code for example: keytool -list -v -keystore C:\Users\MG\Desktop\test.jks -alias test
it will show the current code not the code which the app build with, so I recorded a video for the full solution to fix that and the common problem will be caused by Facebook as well!
Here's the video with English subtitle: https://www.youtube.com/watch?v=spC-CJzlno4 🎥

2. The second problem, that Firebase doesn't support the old Google Play services on the phones, that means you need to update it by following these steps from your smartphone: `Settings > Apps > Apps > Google Play services > App Details` then check for updates - https://tppr.me/k9eEg
For Huawei, I solved the problem by downloading the update manually from here: https://www.apkmirror.com/apk/google-inc/google-play-services/

**Comment by qorane099** [comment] 2020-09-09 06:22
Dear @minhcasi 

I try everything possible, l did follow the guide and video doc deeply.

Google signing is not working still but facebook login is working successfully.

please investigate my issue, may l have a code with a bug.

**Comment by minhcasi** [comment] 2020-09-10 04:29
@qorane099 - pls try to regenerate the keystore to fix the issue, as you can see that error is caused by the setting from Google Sign in setting library, not from the Fluxstore app. 

You could also try the fresh example from https://pub.dev/packages/google_sign_in - thank you!

**Comment by qorane099** [comment] 2020-09-10 12:47
I have generated keystore and added firebase but still google signin is not working.

<img width="731" alt="Screenshot 2020-09-10 at 6 14 16 PM" src="https://user-images.githubusercontent.com/39888242/92730762-df46fb80-f391-11ea-87d7-6ec6fa2b4960.png">
<img width="731" alt="Screenshot 2020-09-10 at 6 14 34 PM" src="https://user-images.githubusercontent.com/39888242/92730773-e2da8280-f391-11ea-981c-2eb42d969c17.png">

**Comment by qorane099** [comment] 2020-09-10 12:51
This is small issue but l am on stuck because of this for too long. also l created too much ticket about this issue.

please why dont you assist me and check this issue through teamviewer, l believe it takes less than 2 for you to identify the issue.

**Comment by minhcasi** [comment] 2020-09-11 04:27
@qorane099 - did you release the app on Google Play store and try to set up with Release mode - sometime it will not work with debug mode

**Comment by qorane099** [comment] 2020-09-11 05:06
I didn't release to google play store, the app is on debug mode, I was
trying to test before releasing to play store and Apple Store.

In your question above, do you mean, l have to release the app on play
store wihout fixing google sign-in function.

9121948906

**Comment by qorane099** [comment] 2020-09-11 07:00
Also, google sign in is running successfully in app devices the issue is from android devices

**Comment by qorane099** [comment] 2020-09-12 11:14
Hello dears,

please can you suggest me the solution.

i need to upload app to playstore and apple store but i have one error which google signing.

1.apple signing is working fine
2.phone no. signing is working fine
3. google signing in apple device is working fine
4. facebook both android and apple are working.


the only signing method is not working is google signing in android device.

please can you check the issue.

i have try everything possible.

**Comment by minhcasi** [comment] 2020-09-13 03:08
1. try to use your key with the Fresh example from this lib - https://pub.dev/packages/google_sign_in 
https://github.com/flutter/plugins/tree/master/packages/google_sign_in/google_sign_in/example

2. Then compare with the example with your own setting, could be missing something on your config file. 

3. Create a new SHA1 key could fix the android login issue.

**Comment by qorane099** [comment] 2020-09-13 07:10
Brother the above example you sent me is so confusing, which file can l compare to my setting. if you need me to compare the whole example to my setting then i can tell you the files are different.

example: 
I have small code not more than 10 lines in main.dart file while the example you sent me has a code more than 50 lines in main.dart file.

**Comment by minhcasi** [comment] 2020-09-15 08:00
@qorane099 - it's form google 😅

Btw, you could check there config example and replace your own app ID so see if have the same issues. Please give a try to regenerate the store keys as our document guides.

**Comment by minhcasi** [comment] 2020-09-23 12:22
Please help to move the new conversation to new Ticket Support http://support.inspireui.com (you could mention on this ticket history) - thank you!

**Closed by minhcasi** 2020-09-23 12:22 UTC
Labels: FluxstoreMV, login-issue, sha-1
