### ISSUE TITLE
Error when building IOS app

### ISSUE THREAD

**Issue by maxileft** [inspireui/support#4197] opened 2020-07-14 14:36 UTC
<img width="670" alt="Screen Shot 2020-07-14 at 9 26 15 PM" src="https://user-images.githubusercontent.com/1119206/87438557-e2d03780-c619-11ea-98c1-07016c6d3a61.png">

i have downloaded Fluxstore woocommerce app and configured. 
i amtrying to build app for IOS, but getting error like in the picture, i already did the REST api configuration, and website url configuration.

**Comment by ameenbadri7** [comment] 2020-07-14 17:09
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 
Thank you for your time!

**Comment by minhcasi** [comment] 2020-07-15 03:12
@maxileft - please help to check this solution to fix the XCode build issue - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by ameenbadri7** [comment] 2020-07-17 00:40
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved. 

 - thank you for your time!

**Closed by ameenbadri7** 2020-07-17 00:40 UTC
Labels: FluxStore
