### ISSUE TITLE
ListApp 1.7.5 kept failing when building

### ISSUE THREAD

**Issue by gfunkerwin** [inspireui/support#4265] opened 2020-07-19 15:46 UTC
Hi,

I bought the ListApp code a while ago and followed all instructions, until it comes to testing and running it via Android Studio and it always failed.

This is the error log from Android Studio 3.6.2 with the latest version of Yarn and NodeJS installed using Expo

Error: Problem validating fields in app.json. See https://docs.expo.io/workflow/configuration/
 • Field: android.package - 'android.package' should be a valid Android Application ID. For example, host.exp.exponent, where exp.host is our domain and Expo is our app. The name may only contain lowercase and uppercase letters (a-z, A-Z), numbers (0-9) and underscores (_), separated by periods (.). Each component of the name should start with a lowercase letter..
Unable to resolve "react-native-screens" from "node_modules/react-navigation-tabs/lib/module/navigators/createBottomTabNavigator.js"
Failed building JavaScript bundle.

When I open app.json (I have not alter anything yet)

{
  "expo": {
    "name": "Qetemu",
    "description": "React Native app for Listing Directory, demo website: http://mylisting.inspireui.com. Download app from \nhttps://shrtm.nu/MOeZ",
    "slug": "listapp-mylisting",
    "privacy": "public",
    "sdkVersion": "36.0.0",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "1.8.1",
    "orientation": "portrait",
    "icon": "assets/icon.png",
    "splash": {
      "image": "assets/splash.png",
      "resizeMode": "cover"
    },
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.inspireui.listapplisting",
      "infoPlist": {
        "NSLocationWhenInUseUsageDescription": "Your current location will be displayed on the map and used for directions"
      },
      "loadJSInBackgroundExperimental": true,
      "buildNumber": "2"
    },
    "android": {
      "package": "com.",
      "versionCode": 8,
      "googleServicesFile": "./release/google-services.json"
    },
    "facebookAppId": "1809822172592320",
    "facebookDisplayName": "beoNews",
    "updates": {
      "checkAutomatically": "ON_LOAD",
      "fallbackToCacheTimeout": 0
    }
  }
}

Please help as I took a while to build the Website until completed before going for the app

**Comment by ameenbadri7** [comment] 2020-07-19 16:26
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by gfunkerwin** [comment] 2020-07-19 17:02
submitted, thanks

**Comment by luyx2412** [comment] 2020-07-21 05:20
Hi @gfunkerwin Can you give me the list app version? Expo or React native original.

Thanks

**Comment by minhcasi** [comment] 2020-07-23 06:59
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-23 06:59 UTC
Labels: ListingApp

**Comment by gfunkerwin** [comment] 2020-07-23 13:59
Hi luvy

> Hi @gfunkerwin Can you give me the list app version? Expo or React native original.
> 
> Thanks

The app is Expo version of ListApp, sorry for the late reply, didn't receive any notice on my email

**Comment by gfunkerwin** [comment] 2020-07-23 14:00
when I ran it through Expo, this is what I got:

"Unable to resolve "react-native-screens" from "node_modules/react-navigation-tabs/lib/module/navigators/createBottomTabNavigator.js""
