### ISSUE TITLE
[Fluxstore] - Issues With 1.5.6 

### ISSUE THREAD

**Issue by underscore15** [inspireui/support#1288] opened 2019-10-26 16:39 UTC
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. Three issues: 
1. When closing the add to cart screen app returns to splashscreen and freezes (Attaching screenshots)

![Screen Shot 2019-10-26 at 7 37 29 PM](https://user-images.githubusercontent.com/56452467/67622937-19fe7e80-f828-11e9-8891-84769ea1eac7.png)
![Screen Shot 2019-10-26 at 7 36 56 PM](https://user-images.githubusercontent.com/56452467/67622938-1e2a9c00-f828-11e9-914c-63349ade28a8.png)

2. Shipping options not showing up 

![Screen Shot 2019-10-26 at 7 36 56 PM](https://user-images.githubusercontent.com/56452467/67622949-2d114e80-f828-11e9-8b37-f65e5338ef60.png)

3. Remove requirement from ZIP Code in address. 

![Screen Shot 2019-10-26 at 7 36 38 PM](https://user-images.githubusercontent.com/56452467/67622951-339fc600-f828-11e9-9d8b-31c60d1925d0.png)

Placed a comment yesterday and have a ticket open 
Thanks

**Comment by underscore15** [comment] 2019-10-27 12:00
To summarize the issues with this build: 

1. When closing the add to cart screen app returns to splash screen and freezes (Attaching screenshots)
2. shipping options not showing up

3. Users registering are not registered as users on WP only in application.

4. How to make ZIP not required ?

**Comment by underscore15** [comment] 2019-10-28 16:39
Same issues with the new release on Codecanyon

**Comment by underscore15** [comment] 2019-10-29 06:11
Hello ? Any updates?

**Comment by underscore15** [comment] 2019-10-30 11:29
4 days no reply?

**Comment by minhtruong315** [comment] 2019-10-30 11:35
@underscore15 send me config.dart file and admin account via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1288

**Comment by minhcasi** [comment] 2019-10-30 11:36
Duplicate of #1284

Please try to create 1 ticket for your all issues that help us focus to your issues, create multi ticket that will take more time and reset the new cycle of investigating, hope you can understand - thank you!

I can see there is a support on the #1284

**Closed by minhcasi** 2019-10-30 11:36 UTC
Labels: FluxStore, question ❓
