### ISSUE TITLE
Woocommerce fluxtrore search not work

### ISSUE THREAD

**Issue by twt93** [inspireui/support#4538] opened 2020-08-09 11:18 UTC
Can you help me... my search in tabbar not working...![Screenshot_20200809-211500.jpg](https://user-images.githubusercontent.com/29052044/89733069-8a0f8580-da85-11ea-8126-62dc336ba4f1.jpg)

**Comment by ameenbadri7** [comment] 2020-08-09 17:59
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by minhcasi** [comment] 2020-08-10 04:34
Duplicate of #4485

I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one with full information - thank you for your time!

**Closed by minhcasi** 2020-08-10 04:34 UTC
Labels: needs-more-info
