### ISSUE TITLE
Fluxnews- Push notification only opens app not the actual post

### ISSUE THREAD

**Issue by imbritto** [inspireui/support#4423] opened 2020-07-30 12:40 UTC
I have tried both Onesignal and Firebase.

With the Onesignal WordPress plugin it opens the app only, not the actual post. Also When the notification is clicked user is asked to choose which app should the notification use to open. If I choose the app instead of the browser then only opens the app and for any other deep link in the app doesn't work. Because the deep link only works with the browser.

Also Does only one type of ads work at a time? for example if i add kAdType.googleBanner in config.dart only Banner ads shows. How to set Banner and Interstitial together? 

I am sorry to say the Fluxnew is just a version of Fluxstore and there is a lot of unnecessary stuff.  Many things are broken and not working. If you only focus on Fluxstore then the customers of Fluxnews are left out. 

For a news/ blog app login feature is very unpopular but fluxnews is using it because Fluxstore has it. Think about the customers of Fluxnews please.

**Comment by ameenbadri7** [comment] 2020-07-30 17:37
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by imbritto** [comment] 2020-07-30 17:40
> Thank you for the feedback.
> 
> Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.
> 
> We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission.
> 
> Thank you for your time!
> 
> > **[Google Forms - create and analyze surveys, for free.](http://verify.inspireui.com/)**Create a new survey on your own or with others at the same time. Choose from a variety of survey types and analyze results in Google Forms. Free from Google.

Done

**Comment by minhcasi** [comment] 2020-07-31 03:15
@imbritto - thank you for your suggestion

1. Please help to refer this ticket so resolve the deep-link issue from Onesignal - #4427

2. We will update the app and remove some redundant code, as there is some other request that prefer to combine the payment into Fluxnews so that we keep the previous one.

**Comment by imbritto** [comment] 2020-07-31 19:08
Any comment on this?

Also, Does only one type of ads work at a time? for example if i add kAdType.googleBanner in config.dart only Banner ads appear. How to set Banner and Interstitial together?

**Comment by minhcasi** [comment] 2020-08-01 04:50
I think it is possible to show 2 type banner at the same time. 

example, you could customize this file and move these function out side the switch condition:

```
/// show banner
Ads.createBannerAd();
Ads.showBanner();

// show Interstitial
Ads.createInterstitialAd();
Ads.showInterstitialAd();
```

<img width="1226" alt="Screen Shot 2020-08-01 at 11 49 33" src="https://user-images.githubusercontent.com/1459805/89094340-128a8800-d3ed-11ea-8d86-aaf7fce48b67.png">

**Comment by imbritto** [comment] 2020-08-01 13:44
> ```
> /// show banner
> Ads.createBannerAd();
> Ads.showBanner();
> 
> // show Interstitial
> Ads.createInterstitialAd();
> Ads.showInterstitialAd();
> ```

Thanks. Working

**Comment by imbritto** [comment] 2020-08-01 14:46
Thanks for an awesome app. 

For now, I have published the app to the Play store but it has a few issues which need to fix. Also, how do I update the app one you update the source code? Do I have to redo everything from the start?

Here is the list of bugs I found:

1. Setting screen login issue I have reported. For now, I disabled the settings screen altogether. 
2. setting screen doesn't store any changes. For ex, if I set dark mode or turn off notification and leave the app, then when I open the app again its white again also the notification is turned on.
3. Onesignal notification opens the article but doesn't show the image also "Things you might love" section gives "Error getting data"
4. For now, the comment section is disabled but I hope there will be a way to comment on posts without login like native WordPress. I bet 99% sites using WordPress doesn't want login to make comment.  But it's not a bug, it's just a suggestion.

**Comment by minhcasi** [comment] 2020-08-02 01:56
Congratulation @imbritto - would you mind to your store URL here, we will give some good rating to your app 🎖

Please help to share the detailed screenshot for the issue so that we could have a look, it could be the user-data or missing config issues.

**Comment by minhcasi** [comment] 2020-08-04 02:39
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-08-04 02:39 UTC
Labels: FluxNews
