### ISSUE TITLE
[mstore multi vendor] - new update 

### ISSUE THREAD

**Issue by muratakgoz** [inspireui/support#2118] opened 2020-02-17 15:21 UTC
when I enter the product in the new version
1.I get the error "sorry, you are not allowed to create a post on behalf of this user."
![88c9486c-891f-4ce6-baa3-6e958f1b4243](https://user-images.githubusercontent.com/22097767/74643987-a68dcd80-5186-11ea-9b43-e2989be8ec02.jpg)
I sent my user information to luyxtran264 mail address.
2. Stores are not visible on the vendor page.
![a79af2f2-e05f-4fdd-a37b-a280b29b456a](https://user-images.githubusercontent.com/22097767/74644325-2caa1400-5187-11ea-8b73-262d2d8d2968.jpg)
3. When the store logs in, the products registered in my products are not displayed.
![2aa435dc-825d-4039-989d-c027c85c0548](https://user-images.githubusercontent.com/22097767/74644496-67ac4780-5187-11ea-82a9-6d0a524a2144.jpg)

**Comment by inspireui-support** [comment] 2020-02-18 02:37
Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by inspireui-support** [comment] 2020-02-18 02:38
Duplicate of #2109

**Closed by inspireui-support** 2020-02-18 02:38 UTC
Labels: question ❓

**Comment by muratakgoz** [comment] 2020-02-18 10:34
![Ekran Resmi 2020-02-18 13 33 35](https://user-images.githubusercontent.com/22097767/74728158-529cea80-5253-11ea-8448-df3dc5b6cc70.png)

**Comment by muratakgoz** [comment] 2020-02-18 10:37
wcfm plugin active.
