### ISSUE TITLE
Takes too long to get the response while searching a product in search

### ISSUE THREAD

**Issue by inforaamitsolutions** [inspireui/support#4790] opened 2020-08-29 14:20 UTC
my internet connection good and all the other things loads good during search the response takes too long to return ...please help me with this

**Comment by minhcasi** [comment] 2020-08-30 01:26
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-08-31 02:24
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-08-31 02:24 UTC
Labels: needs-more-info
