### ISSUE TITLE
Side menu is blank on dark theme 3.8

### ISSUE THREAD

**Issue by IvoKalu** [inspireui/support#615] opened 2019-05-21 08:38 UTC
**Required Info (please complete the following information):**
 - Product: [MStore Pro]
 - Your Purchased Code: [41384711-598d-400d-9b04-1b414a388036 ]

**Describe the bug**
When you change to dark mode the category is blank.

**Screenshots**
![Screenshot_20190517-073341_MStore Pro](https://user-images.githubusercontent.com/8544219/58080895-f3b72180-7bab-11e9-886b-8ebc90cd23d2.jpg)

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by minhcasi** [comment] 2019-05-22 02:30
Duplicate of #613

We've moved to 613 for checking on your all issues in one ticket - thanks

**Closed by minhcasi** 2019-05-22 02:30 UTC
