### ISSUE TITLE
Fluxstore Woocommerce 1.6.6b - Stock is not updated real time & How to enable product quantity in decimal

### ISSUE THREAD

**Issue by chikip** [inspireui/support#2755] opened 2020-04-17 07:04 UTC
Step 1 (require): detail issues and screenshots

1. Inventory stock management is enabled from the backend woocommerce, but the app does not update the stock

![emulator2](https://user-images.githubusercontent.com/63201901/79540082-28c24180-80a5-11ea-882d-82ba29f43796.jpg)
![emulator](https://user-images.githubusercontent.com/63201901/79540101-3081e600-80a5-11ea-90d1-e35a03fe719d.jpg)

2. A product category requires quantity in decimal form. For eg. 1.5kg or 0.5 kg.
This is enabled in the site via a plugin but does not get reflected in the app.

![quantity in decimal](https://user-images.githubusercontent.com/63201901/79540587-067cf380-80a6-11ea-8d70-1551501956d0.jpg)

![quantity in decimal app](https://user-images.githubusercontent.com/63201901/79540616-1268b580-80a6-11ea-87d2-90d786c8ea04.jpg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase.*

**Comment by chikip** [comment] 2020-04-20 02:48
Kindly check, it has been 3 days, I am awaiting your response for further development of the app....

**Comment by minhcasi** [comment] 2020-04-20 02:54
@trunghieuvn - please keep follow this issue - thanks

**Comment by trunghieuvn** [comment] 2020-04-20 07:58
> 2. A product category requires quantity in decimal form. For eg. 1.5kg or 0.5 kg.
> This is enabled in the site via a plugin but does not get reflected in the app.

Sorry, so far the app could not support for the decimal if you are using extra plugin it will not work - it's only support default WooCommerce API

**Comment by trunghieuvn** [comment] 2020-04-20 08:15
> Inventory stock management is enabled from the backend woocommerce, but the app does not update the stock

I do not quite understand what you mean. Did you mean that after the customer orders the product successfully, the amount of inventory in the product detail screen is not updated?

**Comment by chikip** [comment] 2020-04-20 11:01
> > 1. A product category requires quantity in decimal form. For eg. 1.5kg or 0.5 kg.
> >    This is enabled in the site via a plugin but does not get reflected in the app.
> 
> Sorry, so far the app could not support for the decimal if you are using extra plugin it will not work - it's only support default WooCommerce API

Is it possible in any way to implement it in the app, because without it I cannot launch the app.
Thank you

**Comment by chikip** [comment] 2020-04-20 11:03
> > Inventory stock management is enabled from the backend woocommerce, but the app does not update the stock
> 
> I do not quite understand what you mean. Did you mean that after the customer orders the product successfully, the amount of inventory in the product detail screen is not updated?

Yes, exactly, kindly check.
Thank you

**Comment by trunghieuvn** [comment] 2020-04-21 05:26
> > > Inventory stock management is enabled from the backend woocommerce, but the app does not update the stock
> > 
> > 
> > I do not quite understand what you mean. Did you mean that after the customer orders the product successfully, the amount of inventory in the product detail screen is not updated?
> 
> Yes, exactly, kindly check.
> Thank you

Hi @chikip , after doing a lot of testing I finally found the cause of the error.
You can see the clip below, the error occurs because the server could not update the data immediately when the customer ordered successfully.

In the clip, I performed the api test on your server before I placed the order. The quantity before I ordered was 5. 
After I placed the order, I refeshed the API page, strangely, the number remained unchanged. I tried refeshing the api page several times, but the results remained unchanged. 
Until I return to the product details page, this time the api will change. In some cases, even when I go back to the product details page, the number of products remains unchanged (that's the case you mentioned).

https://drive.google.com/file/d/17VF6BXZtd0kurMrQoxdkGPcMAsSqvOep/view?usp=sharing

Please check the order-related api on your server, there may be a problem there.

**Comment by chikip** [comment] 2020-04-22 05:45
> > > > Inventory stock management is enabled from the backend woocommerce, but the app does not update the stock
> > > 
> > > 
> > > I do not quite understand what you mean. Did you mean that after the customer orders the product successfully, the amount of inventory in the product detail screen is not updated?
> > 
> > 
> > Yes, exactly, kindly check.
> > Thank you
> 
> Hi @chikip , after doing a lot of testing I finally found the cause of the error.
> You can see the clip below, the error occurs because the server could not update the data immediately when the customer ordered successfully.
> 
> In the clip, I performed the api test on your server before I placed the order. The quantity before I ordered was 5.
> After I placed the order, I refeshed the API page, strangely, the number remained unchanged. I tried refeshing the api page several times, but the results remained unchanged.
> Until I return to the product details page, this time the api will change. In some cases, even when I go back to the product details page, the number of products remains unchanged (that's the case you mentioned).
> 
> https://drive.google.com/file/d/17VF6BXZtd0kurMrQoxdkGPcMAsSqvOep/view?usp=sharing
> 
> Please check the order-related api on your server, there may be a problem there.
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/c1fb840811d99a246d33c4f2f42da35aedd7b73b/68747470733a2f2f6c68362e676f6f676c6575736572636f6e74656e742e636f6d2f386a3254576b4a457a50536145497a637735317970653166797678704d38705675585155616e6b5739717a46586b577141676771786636545a334f63586c343d77313230302d683633302d70">Google Drive**[buginserver.mp4](https://drive.google.com/file/d/17VF6BXZtd0kurMrQoxdkGPcMAsSqvOep/view?usp=sharing&usp=embed_facebook)**

Ok, I'll check with my hosting server and any update regarding the decimal quantity issue...
Thank you

**Comment by trunghieuvn** [comment] 2020-04-23 10:22
Thank you. I will close this ticket. If there are any problems, please create a ticket with a new topic, we will help you solve the problem.

Thanks.

**Closed by trunghieuvn** 2020-04-23 10:22 UTC
Labels: FluxStore
