### ISSUE TITLE
FluxStore FormatException at Placemyorder in checkout screen

### ISSUE THREAD

**Issue by AmeerEbrahim** [inspireui/support#4481] opened 2020-08-05 21:46 UTC
+ Detail Issues: Having issues while checking out at payment screen
+ Product & version: Fluxstore
+ Flutter (or React Native) version: 
Flutter 1.17.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8af6b2f038 (5 weeks ago) • 2020-06-30 12:53:55 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

+ Testing Device/Simulator: Android emulator

+ Screenshot issues (drag the file to attach here): 
[
![Screenshot_1596664139](https://user-images.githubusercontent.com/38166596/89467654-ac03c200-d77e-11ea-9f6f-1b7186339055.png)
](url)

FormatException: Unexpected end of input(at character 1)
this is the error log that's showing up. I have recently enabled guest checkout and will this error be because of that ?
This error shows up when I click on "PLACE MY ORDER"

Thank you so much for your time 😊

**Comment by minhcasi** [comment] 2020-08-06 02:33
Duplicate of #4480 - pls move your all comments to 1 open ticket - thanks

**Closed by minhcasi** 2020-08-06 02:33 UTC

**Comment by AmeerEbrahim** [comment] 2020-08-06 16:47
Can you please explain how can be this a Duplicate of #4480 ? 
Both are different issues, one related to pod install in IOS simulator and other related to checkout screen format exception in Android.
Please give further clarification and consider this issue and give the necessary support.

**Comment by minhcasi** [comment] 2020-08-07 01:26
@AmeerEbrahim - pls help us to add your all comment to the same ticket support ID so that i could assign to the team checking you all issues at the same time.
