### ISSUE TITLE
After Indexing Project on Android Studio Showing Errors in Dart Analysis FluxNews

### ISSUE THREAD

**Issue by Akash305** [inspireui/support#3642] opened 2020-06-08 10:21 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: error: Target of URI doesn't exist: '../generated/l10n.dart'. (uri_does_not_exist at [fstore] ios\Flutter\App.framework\flutter_assets\lib\common\tools.dart:13)
error: Undefined name 'S'. (undefined_identifier at [fstore] ios\Flutter\App.framework\flutter_assets\lib\common\tools.dart:265)
error: Undefined name 'S'. (undefined_identifier at [fstore] ios\Flutter\App.framework\flutter_assets\lib\common\tools.dart:267)
error: Undefined name 'S'. (undefined_identifier at [fstore] ios\Flutter\App.framework\flutter_assets\lib\common\tools.dart:269)
error: Undefined name 'S'. (undefined_identifier at [fstore] ios\Flutter\App.framework\flutter_assets\lib\common\tools.dart:272)
error: Undefined name 'S'. (undefined_identifier at [fstore] ios\Flutter\App.framework\flutter_assets\lib\common\tools.dart:274)
error: Undefined name 'S'. (undefined_identifier at [fstore] ios\Flutter\App.framework\flutter_assets\lib\common\tools.dart:276)
error: Undefined name 'S'. (undefined_identifier at [fstore] ios\Flutter\App.framework\flutter_assets\lib\common\tools.dart:278)
error: Undefined name 'S'. (undefined_identifier at [fstore] ios\Flutter\App.framework\flutter_assets\lib\common\tools.dart:322)
error: Undefined name 'S'. (undefined_identifier at [fstore] ios\Flutter\App.framework\flutter_assets\lib\common\tools.dart:329)
error: Undefined name 'S'. (undefined_identifier at [fstore] ios\Flutter\App.framework\flutter_assets\lib\common\tools.dart:336)
+ Product & version: FluxNews 1.4.1
+ Flutter (or React Native) version:  Flutter
+ Testing Device/Simulator: A6000 OnePlus 6
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment] 2020-06-09 01:39
@Akash305 
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-06-10 03:11
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-06-10 03:11 UTC
Labels: needs-more-info
