### ISSUE TITLE
woocommerce rest api

### ISSUE THREAD

**Issue by Nick-tech-2691** [inspireui/support#4854] opened 2020-09-03 05:17 UTC
{
    "code": "woocommerce_rest_cannot_view",
    "message": "Sorry, you cannot list resources.",
    "data": {
        "status": 401
    }
}
My all woocommerce rest API giving me this result even all the projects were working fine but since yesterday nothing. I've checked my keys also which are 100% correct because I was getting the result but suddenly no result and getting the same error as above. any solutions or anyone else who is facing problems recently.

**Comment by Nick-tech-2691** [comment] 2020-09-03 06:57
![post](https://user-images.githubusercontent.com/52854535/92081377-9666d400-ede0-11ea-9c5d-cc61a9e3888d.png)
this is the postman screenshot

**Comment by ahmedseddiq-casheto** [comment] 2020-09-03 09:05
wt host u use

**Comment by Nick-tech-2691** [comment] 2020-09-03 09:12
crazydomain

**Comment by minhcasi** [comment] 2020-09-03 10:54
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-09-04 02:24
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-09-04 02:24 UTC
Labels: needs-more-info

**Comment by Nick-tech-2691** [comment] 2020-09-04 04:17
The problem is still here and it hasn't been resolved yet. still looking for a solution.
