### ISSUE TITLE
FLUXNEWS SPLASH SCREEN 

### ISSUE THREAD

**Issue by msesetz** [inspireui/support#4116] opened 2020-07-08 10:30 UTC
I having a problem with the splash screen, it start with blue and black (animated part) then gets to my splash screen with no animation.

"SplashScreen": {
"type": "animated",
"data": "assets/images/splashscreen.png"
},

![86702332-87031e80-c01b-11ea-9ca2-09e0a7726a2d](https://user-images.githubusercontent.com/51053867/86908294-fb72b600-c11e-11ea-909a-73817737345d.gif)
:

**Comment by ameenbadri7** [comment] 2020-07-08 13:50
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by dttrung26** [comment] 2020-07-09 02:56
Duplicate of https://github.com/inspireui/support/issues/4063

**Closed by dttrung26** 2020-07-09 02:56 UTC
Labels: needs-more-info

**Comment by msesetz** [comment] 2020-07-13 09:29
Help me to fix thise things
