### ISSUE TITLE
(Magento 2.3; FluxStore Pro) Special Price/Discount Not Displayed

### ISSUE THREAD

**Issue by saudadev** [inspireui/support#3371] opened 2020-05-23 05:33 UTC
Step 1 (require): detail issues and screenshots

ISSUE : - In APP Product Discounts are Not Shown (Magento Special Price are Not Shown)

Please find the below ScreenShot

![Discount-App-Not-Shown](https://user-images.githubusercontent.com/63896811/82722492-e82d9780-9ce4-11ea-96d8-e6228478c5c0.png)

WORKING MAGENTO FRONTEND

![Discount-Web-Working](https://user-images.githubusercontent.com/63896811/82722497-ec59b500-9ce4-11ea-8cea-b31791e94076.png)

HOW TO QUESTION (NOT AN ISSUE)

If I have an attribute as BRAND, How I can display that in the APP?

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

Please dont Mark it as Need More Info, I am adding it.

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by saudadev** [comment] 2020-05-23 05:33
Private Files Added.

**Comment by minhcasi** [comment] 2020-05-23 07:20
Duplicate of #3369 - pls move to the one ticket support

**Closed by minhcasi** 2020-05-23 07:20 UTC
