### ISSUE TITLE
How to enable multi language and let user choice wich language 

### ISSUE THREAD

**Issue by hakihosting** [inspireui/support#307] opened 2019-02-16 17:59 UTC
**Required Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the bug**

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

I have try this but not work , i have error 

  English: {
    Hello: 'Hello'
    ...
  },
  France: {
    Hello: 'Bonjour'
    ...
  }
}

**Comment by minhcasi** [comment] 2019-02-18 01:23
Duplicate of #301

**Closed by minhcasi** 2019-02-18 01:23 UTC
