### ISSUE TITLE
Coupons are not working properly 

### ISSUE THREAD

**Issue by IvoKalu** [inspireui/support#620] opened 2019-05-21 13:45 UTC
**Required Info (please complete the following information):**
 - Product: [MStore Pro]
 - Your Purchased Code: [41384711-598d-400d-9b04-1b414a388036 ]

**Describe the bug**
1.The discount only apply's as percentage even if u specify Fixed cart discount.
2.When the customer finishes the transaction it removes the discount and the full price is paid.
3.Next time the customer buys the  coupon is still shows even if you specify a 1 Usage limit per user.
Conclusion: the all coupon system needs a review because it does not work.

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by minhcasi** [comment] 2019-05-22 02:26
Duplicate of #613

Please try to create one ticket for your all issues as for better focus on your issues - thank you!

**Closed by minhcasi** 2019-05-22 02:26 UTC
