### ISSUE TITLE
[Flux-store 1.5.7] -  the side bar menu categories are repeated 

### ISSUE THREAD

**Issue by EmilianH** [inspireui/support#1384] opened 2019-11-13 16:06 UTC
---------

1. My issue
i see categories repeated like sub categories, how to fix? thanks
2. Screenshots
![catetgoriesrepited](https://user-images.githubusercontent.com/57189819/68781258-42eb8580-0616-11ea-85ac-fbd370f0a5ea.png)

3. My screenshot of the purchase product or my comment:
![compra](https://user-images.githubusercontent.com/57189819/68780994-d83a4a00-0615-11ea-9cb0-b38739c3cb5b.jpg)
3. Config files (optional)

**Comment by minhcasi** [comment] 2019-11-14 00:41
Duplicate of #1330 - try to comment on the previous ticket rather than open the new one - thanks

This issue is fixed on the latest 1.5.7, could you confirm using this version?

**Closed by minhcasi** 2019-11-14 00:41 UTC
Labels: question ❓

**Comment by EmilianH** [comment] 2019-11-14 00:55
yes im using 1.5.7 and is repeated
