### ISSUE TITLE
Build Failed on Xcode (Pods/Target Support Files)

### ISSUE THREAD

**Issue by macquack** [inspireui/support#4035] opened 2020-07-03 06:11 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
When try to build on xcode it's failed because
`
Showing Recent Issues
/Users/macquack/Desktop/FluxStore/source/ios/Flutter/Debug.xcconfig:1: could not find included file 'Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig' in search paths
` 

btw i already try 
`pos install`
and the result is
`Analyzing dependencies
[!] No podspec found for `app_settings` in `.symlinks/plugins/app_settings/ios`

[!] Automatically assigning platform `iOS` with version `10.3` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
`

nothing change still failed. I already try flutter doctor everything good
+ Product & version: Fluxstore 1.7.4
+ Flutter (or React Native) version: 1.17.5
+ Testing Device/Simulator: VMWare macOS Catalina,Xcode 11.5,iPhone8 (simulator)
+ Screenshot issues (drag the file to attach here): 
![image](https://user-images.githubusercontent.com/30103694/86437257-52971600-bd2e-11ea-957d-501e023da5e3.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
Summited 

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by macquack** [comment] 2020-07-03 06:14
I already done with you Fluxstore on Android Studio and wait for launch on Play Store. thanks for your kindness help

**Comment by minhcasi** [comment] 2020-07-03 06:25
@macquack - pls help to try some clean cache solution here - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1 - thank you!

**Comment by macquack** [comment] 2020-07-03 06:45
already try but nothing change.

**Comment by macquack** [comment] 2020-07-03 07:13
![image](https://user-images.githubusercontent.com/30103694/86442016-4ebbc180-bd37-11ea-8085-dca75dc6a08b.png)

**Comment by Shiru-kun** [comment] 2020-07-03 15:43
i had the same problem recently try run: 
pod install in 
ios folder

**Comment by macquack** [comment] 2020-07-04 08:13
so after try hard i got only this error 
![image](https://user-images.githubusercontent.com/30103694/86508260-c7d71980-be08-11ea-995e-157ffe66feae.png)

already try pod install,pod update but got this and build xcode same error
![image](https://user-images.githubusercontent.com/30103694/86508265-df160700-be08-11ea-95fe-85e715a27159.png)

**Comment by Shiru-kun** [comment] 2020-07-05 23:40
try edit your podfile  Uncomment this line 
# platform :ios, '9.0'

**Comment by Shiru-kun** [comment] 2020-07-05 23:41
delete the podfile.lock too

**Comment by minhcasi** [comment] 2020-07-06 03:23
@Shiru-kun - pls try this solution from ios folder

```
pod repo update
pod install
pod update OneSignal
```

**Comment by minhcasi** [comment] 2020-07-06 11:07
Duplicate of #4075

**Closed by minhcasi** 2020-07-06 11:07 UTC
Labels: FluxStore
