### ISSUE TITLE
flutter app crashes on iOS 12.4 iPhone6

### ISSUE THREAD

**Issue by querymaster** [inspireui/support#4200] opened 2020-07-14 16:31 UTC
I using flux store code with Magento now and I found a lot of crashes on iOS 12.4.3, iOS 12.4.4, iOS 12.4.5, iPhone6 with 1 GB or less of memory。

Need your support on it to resolve really critical.

Flutter 1.17.5 • channel stable 
Framework • revision 8af6b2f038 (2 weeks ago) • 2020-06-30 12:53:55 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.3

**Comment by ameenbadri7** [comment] 2020-07-14 16:55
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by querymaster** [comment] 2020-07-14 18:12
I have submit my submission, Please get it resolve.

[cid:image001.png@01D65A33.DC3808A0]

Regards
Abdul Samad

**Comment by minhcasi** [comment] 2020-07-15 03:02
@querymaster - pls try to use the latest release `1.7.6` to fix the performance issue - if you have the video crash issue pls share with us - thanks

**Comment by querymaster** [comment] 2020-07-15 05:18
Please find attached videos for crashing review.

I have updated version of flutter which is 1.17.5

**Comment by minhcasi** [comment] 2020-07-16 03:13
pls resend the video again, we could not see it - thank you for your time

**Comment by querymaster** [comment] 2020-07-16 06:04
Please find video with attached

**Comment by minhcasi** [comment] 2020-07-17 09:39
@querymaster - not sure if you have attache via email - pls click to this link https://github.com/inspireui/support/issues/4200 - there is no file is attached :(

**Comment by querymaster** [comment] 2020-07-17 10:19
[4.mp4.zip](https://github.com/inspireui/support/files/4937135/4.mp4.zip)

You can find attached with here

**Comment by minhcasi** [comment] 2020-07-18 05:52
@tgloc96 - please help to investigate the issue

**Comment by tgloc96** [comment] 2020-07-23 08:50
@querymaster Can you please resend me the config folder, because the folder you sent for us the file config not contain an access token key, thank you for your time.

**Comment by minhcasi** [comment] 2020-07-25 06:40
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-25 06:40 UTC
Labels: 1.7.7, FluxStore
