### ISSUE TITLE
No product or categories showing

### ISSUE THREAD

**Issue by eraldix** [inspireui/support#3655] opened 2020-06-09 14:34 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: My store is fully connected because I can see the vendors but I can't see their product. What can i do?
+ Product & version: Fluxstore Multi Vendor (latest version)
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: Both
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment] 2020-06-10 02:39
Duplicate of #3623

**Closed by minhcasi** 2020-06-10 02:39 UTC
