### ISSUE TITLE
Extracting tar content of undefined failed, the file appears to be corrupt: "EBUSY: resource busy or locked,

### ISSUE THREAD

**Issue by anandkausha** [inspireui/support#2742] opened 2020-04-16 12:44 UTC
Step 1 (require): Extracting tar content of undefined failed, the file appears to be corrupt: "EBUSY: resource busy or locked,
![555](https://user-images.githubusercontent.com/63690210/79457609-1ea13400-800e-11ea-9fc6-5e54c0e07b7b.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please submit ticket support by following above 2 require steps, we may close the ticket without providing full information.*

**Comment by minhcasi** [comment] 2020-04-17 00:56
@anandkausha - please download nodejs 10.x to fix the issue - https://nodejs.org/dist/latest-v10.x/

**Comment by minhcasi** [comment] 2020-04-19 02:18
Duplicate of #2778

**Closed by minhcasi** 2020-04-19 02:18 UTC
Labels: MStoreMV
