### ISSUE TITLE
[Fluxstore 1.5.7] - Welcome screen does not appear.

### ISSUE THREAD

**Issue by EmilianH** [inspireui/support#1386] opened 2019-11-14 01:00 UTC
---------

1. My issue
i change all the com.inpireui.fluxstore from the app, and chaged my DIR, i tried flutter clean, deleting app from emulator etc, but never appear Welcome Screen
thanks
2. Screenshots

3. My screenshot of the purchase product or my comment:
![compra](https://user-images.githubusercontent.com/57189819/68817619-ff6a3900-0660-11ea-9628-4eea3b4927dd.jpg)

3. Config files (optional)

**Comment by minhcasi** [comment] 2019-11-14 02:54
Duplicate of #1324

Could you able to note as one ticket so that the team could have better support on your issues?

**Closed by minhcasi** 2019-11-14 02:54 UTC
Labels: question ❓
