### ISSUE TITLE
Product in Stock but shows out of stock

### ISSUE THREAD

**Issue by mahajansahab** [inspireui/support#3114] opened 2020-05-09 14:44 UTC
Step 1 (require): detail issues and screenshots

Hi, I am using OpenCart with FluxStore Pro, The products are in stock but they are showing out of stock on the app

![image](https://user-images.githubusercontent.com/2174778/81476785-62641380-9231-11ea-8af2-9400b1b5bef4.png)

![image](https://user-images.githubusercontent.com/2174778/81476811-8293d280-9231-11ea-9e5f-6ed5a03e421e.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment] 2020-05-10 02:13
@mahajansahab 
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-05-10 12:05
it's verified - 
@minhtruong315 - pls help to investigate the issuer

**Comment by minhtruong315** [comment] 2020-05-11 04:33
@mahajansahab Did you set out of stock for that product on admin site? Can you take me screenshot for product setting?

**Comment by minhcasi** [comment] 2020-05-13 01:49
I'm closing this ticket as there is no response, please help to create new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed** 2020-05-13 01:48 UTC
Labels: FluxStore, opencart-issues
