### ISSUE TITLE
Category and Product sort

### ISSUE THREAD

**Issue by cenkgulgun** [inspireui/support#4293] opened 2020-07-21 13:29 UTC
Hello
I have Fluxstore Woocommerce. 
1- I want to sorting category and product same wordpress site. How can i do it?
2- I cant do pageview screen https://docs.inspireui.com/fluxstore/customization/#12-page-view-settings-screen. Always "opps, this page seems no longer exist!"
3- Checkout payment screen. I have only "pay at door". But if i choose this, backend order goes to awaiting payment. I want processing
4- How can i enter admin panel? Can i add new products or edit products on app?

**Comment by ameenbadri7** [comment] 2020-07-21 15:11
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by ameenbadri7** [comment] 2020-07-22 14:00
@cenkgulgun  
1- You can show your products inside the apps by using this tutorial :
[and then go to 'The app shows no product' ](https://docs.inspireui.com/fluxstore/common-issues/
).
2- press this link https://docs.inspireui.com/fluxstore/customization and then go to "12. Page View (Settings screen)"

3- 
- Go to a file inside lib\common\config\payments.dart 
- And then Make the payment option `false ` like this : 
```
/// Enable Payment option : 
  "EnableOnePageCheckout": false,
  "NativeOnePageCheckout": false,
```

4- add new products inside WordPress and you will see it inside the fluxstore. 

please use our documentation and videos to learn more about the Flxustore.

happy coding!

**Comment by minhcasi** [comment] 2020-07-24 13:02
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-24 13:02 UTC
Labels: FluxStore
