### ISSUE TITLE
Issue cause of gradle 6.1.1

### ISSUE THREAD

**Issue by georgesamirmansour** [inspireui/support#4083] opened 2020-07-06 12:37 UTC
Step 1 (require): describe detail issues & screenshots

Detail Issues: Problem with fluxstore
Product & version: Fluxstore Multi Vendor - Flutter E-commerce Full App
Flutter (or React Native) version:
Testing Device/Simulator: Android studio
Screenshot issues :  issue when gradle updated to 6.1.1
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.android.tools:r8:1.5.25.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/android/tools/r8/1.5.25/r8-1.5.25.pom
       - https://jcenter.bintray.com/com/android/tools/r8/1.5.25/r8-1.5.25.pom
       - http://storage.googleapis.com/r8-releases/raw/com/android/tools/r8/1.5.25/r8-1.5.25.pom
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by ameenbadri7** [comment] 2020-07-07 00:13
we are using the `Gradle-5.6.2-all.zip` as it stable, it been used by the flutter team with the latest updated big programs. please consider using it for all your flutter projects.
if you have questions about the android error or upgrading to something we are not using you can use another repo's inside Github.
thank you for your feedback.

I'm sorry to close this ticket. 
please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by ameenbadri7** 2020-07-07 00:13 UTC
Labels: FluxStore

**Comment by georgesamirmansour** [comment] 2020-07-09 12:21
actully any fluter project work with gradle version 6.1.1 , your app doesn't work with this gradle version
