### ISSUE TITLE
Error when selecting the multilanguage option

### ISSUE THREAD

**Issue by franklinbinauraldev** [inspireui/support#4590] opened 2020-08-13 18:33 UTC
I run the template with expo, and when I select a language the application breaks

![Captura de pantalla de 2020-08-13 14-27-19](https://user-images.githubusercontent.com/69120282/90173051-d4d51a00-dd71-11ea-9ca1-428d70bf4c5a.png)

**Comment by ameenbadri7** [comment] 2020-08-14 00:02
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by minhcasi** [comment] 2020-08-15 03:30
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-08-15 03:30 UTC
Labels: needs-more-info
