### ISSUE TITLE
Map not working

### ISSUE THREAD

**Issue by saurabhrinwa** [inspireui/support#3182] opened 2020-05-13 17:43 UTC
Hi 

The app crash on the listing page if the listing has the address saved. The listing without the address works well. It looks some problem with Google Maps integration.

**Comment by minhcasi** [comment] 2020-05-14 03:33
@saurabhrinwa 

Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by saurabhrinwa** [comment] 2020-05-14 20:32
Okay, I will submit in sometime after getting the project folder from my dev.

Thanks

**Comment by saurabhrinwa** [comment] 2020-05-15 15:27
@minhcasi We have submitted the details. I hope you received them. Let us know if you need more information.

**Comment by minhcasi** [comment] 2020-05-16 06:49
it's verified - thank you for your submission 

Could you help to share the screenshot issues on which the example that causes this issue? We will try to reproduce and let you know

**Comment by thisisirfan** [comment] 2020-05-17 09:20
When we visit any listing that contain location, it crashes. It doesn't show any error before crashing. It's happening because of `google map` i think. Even if you try to visit second `bottom nav tab` , it still crashes because it also have map view to show listings.
P.S All crashes happen only when we build the app via expo.
https://expo.io/@thisisirfan/foodiesalamesa

**Comment by saurabhrinwa** [comment] 2020-05-20 18:39
@luyx2412 @minhcasi any update on this, please?

**Comment by saurabhrinwa** [comment] 2020-05-26 00:09
Hi Guys, Please update on the issue 

@luyx2412 @minhcasi

**Comment by minhcasi** [comment] 2020-05-26 00:11
@saurabhrinwa 
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

We sincerely apologize for the delay and hope you’re staying safe.

**Comment by minhcasi** [comment] 2020-05-26 00:11
@luyx2412 - please help with checking

**Comment by luyx2412** [comment] 2020-05-27 17:00
Hi @saurabhrinwa Can you give me the screenshot? I just tested your config and everything worked normal.
![image](https://user-images.githubusercontent.com/8909619/83050073-312f7400-a076-11ea-8e07-c9a37c5091ec.png)

Thanks

**Comment by saurabhrinwa** [comment] 2020-05-28 14:53
The issue is on Android app only. On iOS we observed that it's working fine. Let me arrange screencast for you.

**Comment by saurabhrinwa** [comment] 2020-05-28 20:17
Here is the screencast. When you click on the listing which has the address the app crashes.

https://streamable.com/r2eqya

**Comment by luyx2412** [comment] 2020-05-30 10:42
HI @saurabhrinwa Can you send me your package.json file? I just tested on Android and everything worked normal both real device and emulator.
![image](https://user-images.githubusercontent.com/8909619/83326277-f8251880-a29c-11ea-9d84-fa319e6e302f.png)

Thanks

**Comment by saurabhrinwa** [comment] 2020-06-01 17:19
Here is the package.json file https://file.io/jSxM00JU

**Comment by luyx2412** [comment] 2020-06-03 14:45
HI @saurabhrinwa Can you share me again your config files. Your link is 404 

![](https://user-images.githubusercontent.com/8909619/83651086-4ad73b00-a5e3-11ea-9b92-2e13fe3c420f.png)

Thanks

**Comment by Stany2011** [comment] 2020-06-04 02:35
Hi, i have the same problem, in test it works perfectly.. but when deploying to device it crushes when i try to go for search or open single listing
https://we.tl/t-pK2VhHewIG
here's my entire project just without nodes modules folder

**Comment by luyx2412** [comment] 2020-06-04 14:24
Hi @Stany2011 You can try release mode or use real device to debug why's app crash.

Thanks

**Comment by Stany2011** [comment] 2020-06-04 14:44
[log.txt](https://github.com/inspireui/support/files/4730747/log.txt)

 Hi, thx for the reply @luyx2412  ..here's the log by logcat made with android device.. from when i click on a listing to when it reloads.. i restricted logs only for this app.. but however i cant understand the error.. give it a look if u can, thanks

**Comment by luyx2412** [comment] 2020-06-07 07:25
Hi @Stany2011 Please send me your project via inspireui.team@gmail.com. Let me fix the issues and resend you.

Thanks

**Comment by Stany2011** [comment] 2020-06-07 17:30
@luyx2412 this will be very aswesome.. thank u very much.. i send it to you

**Comment by luyx2412** [comment] 2020-06-14 13:18
HI @Stany2011 Please send your project with title id issues. Currently i did not see your email.

Thanks

**Comment by Stany2011** [comment] 2020-06-14 14:04
hi, i have sent it right now

________________________________
Da: luyx2412 <notifications@github.com>
Inviato: domenica 14 giugno 2020 15:18
A: inspireui/support <support@noreply.github.com>
Cc: Stany2011 <stany2010@hotmail.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [inspireui/support] Map not working (#3182)


HI @Stany2011<https://github.com/Stany2011> Please send your project with title id issues. Currently i did not see your email.

Thanks

**Comment by luyx2412** [comment] 2020-06-15 14:27
Hi @Stany2011 Can you upload your project again or use drive to avoid expired.
![image](https://user-images.githubusercontent.com/8909619/84669316-ec994900-af4e-11ea-8739-8b6829ec4125.png)

Thanks

**Comment by minhcasi** [comment] 2020-06-23 07:12
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-06-23 07:12 UTC
Labels: ListingApp
