### ISSUE TITLE
[Fluxstore 1.5.7] - MERCADOPAGO payment not working 

### ISSUE THREAD

**Issue by EmilianH** [inspireui/support#1353] opened 2019-11-09 23:49 UTC
---------

1. My issue
i have configured perfectly MERCADOPAGO payment method in woocommerce and works perfectly in the web, but no working in the app, after checkout blank screen.
i think that needs a token, how to integrate mercadopago?
thanks a lot
2. Screenshots
![payment-error](https://user-images.githubusercontent.com/57189819/68535833-5ef5db00-0327-11ea-9ebc-d12379036867.png)

3. My screenshot of the purchase product or my comment:
![compra](https://user-images.githubusercontent.com/57189819/68536315-8e104a80-032f-11ea-81d3-2d32d26f4cba.jpg)
[common.zip](https://github.com/inspireui/support/files/3827876/common.zip)

3. Config files (optional)

**Comment by minhcasi** [comment] 2019-11-10 01:49
Duplicate of #1330 
- pls comment on the previous issue instead of creating a new one

**Closed by minhcasi** 2019-11-10 01:49 UTC
Labels: question ❓
