### ISSUE TITLE
Very slow during the loading of products and order not showing in backoffice prestashop

### ISSUE THREAD

**Issue by emanuelecolella** [inspireui/support#4149] opened 2020-07-10 13:37 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I created an order from the app and I don't see it in the control panel. Products loading is very slow and I don't see products from all categories.
+ Product & version: Fluxstore prestashop 1.1.0
+ Flutter (or React Native) version: 1.17.5
+ Testing Device/Simulator: Note10+
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_** (done)

**Comment by ameenbadri7** [comment] 2020-07-10 14:12
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by emanuelecolella** [comment] 2020-07-10 14:25
Already send @ameenbadri7

**Comment by vumanhsn97** [comment] 2020-07-20 07:53
@emanuelecolella 
Please download lastest version and update this permission in Webservices https://tppr.me/fGCgb

**Comment by emanuelecolella** [comment] 2020-07-27 11:18
also after update, when i open the app for the first time, the loading of product in each category, required about 1 minute.

**Comment by vumanhsn97** [comment] 2020-07-30 04:19
@emanuelecolella 
Your list categories and product option value too large, so it will take more time in first loading https://tppr.me/IhmpP

**Comment by emanuelecolella** [comment] 2020-07-30 13:38
@vumanhsn97 how can i test the time of loading like as screen?

**Comment by vumanhsn97** [comment] 2020-07-31 03:34
@emanuelecolella 
You can use postman application https://www.postman.com/

**Comment by minhcasi** [comment] 2020-08-02 03:18
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-08-02 03:18 UTC
Labels: fluxstore-prestashop
