### ISSUE TITLE
 Banner image not loading loading from asset folder

### ISSUE THREAD

**Issue by subhquad** [inspireui/support#3550] opened 2020-06-02 12:46 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 1. Banner image not loading loading from asset folder.Its working fine when we are providing external image link.

+ Product & version:  Fluxstore Pro 1.7.3
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: iPhone 11
+ Screenshot issues (drag the file to attach here): 

<img width="336" alt="Screenshot 2020-06-02 at 13 46 14" src="https://user-images.githubusercontent.com/10830054/83521669-75d46880-a4d7-11ea-91f3-48a20f439681.png">

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

80f2ca3f-3e8f-43cd-97ba-9dd311d5fb75

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment] 2020-06-03 02:07
Duplicate of #3548 - please help to raise only one ticket for your all issue, also make sure to update to the latest Fluxstore version `1.7.4` - thank you!

**Closed by minhcasi** 2020-06-03 02:07 UTC
