### ISSUE TITLE
Facebook login bug for mstore wordpress expo project.

### ISSUE THREAD

**Issue by gorrc** [inspireui/support#5041] opened 2020-09-22 17:11 UTC
Here is bug with solution, can you confirm it and fix it:
Your method:    
const ask = await Facebook.logInWithReadPermissionsAsync(      Config.appFacebookId,
      {
        permissions: ["public_profile", "email"],
      }
    );
is having wrong interface for : export async function logInWithReadPermissionsAsync(options) 

Also in documentation https://docs.expo.io/versions/latest/sdk/facebook/ says first facebook login should be initialized then used.
So solution is next:
await Facebook.initializeAsync(Config.appFacebookId);
 const ask = await Facebook.logInWithReadPermissionsAsync(
      {
        permissions: ["public_profile", "email"],
      }
    );

Can you please confirm the bug and provide a fix, this should be working but I suppose there is a better solution.

**Comment by minhcasi** [comment] 2020-09-23 03:44
Duplicate of #5006

**Closed by minhcasi** 2020-09-23 03:44 UTC
