### ISSUE TITLE
fluxstore MV  shipping method not showing

### ISSUE THREAD

**Issue by yassiney120** [inspireui/support#1736] opened 2020-01-01 17:02 UTC
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
shipping method not shoping please check screenshot 
2. Screenshots issues:
https://ibb.co/g3GBYsq
3. Proof of my purchased:
https://ibb.co/wYmMMJm
3. Config files (optional)
https://drive.google.com/drive/folders/1rUJwLykjL_DSWXdyoPSQ6oo0wXTXrhAO?usp=sharing

**Comment by minhcasi** [comment] 2020-01-05 08:35
Duplicate of #1736

**Comment by minhcasi** [comment] 2020-01-06 11:27
@yassiney120 - i'm re-opened the ticket for further checking - pls help to update your rating - thanks

**Comment by minhtruong315** [comment] 2020-01-06 14:32
![Uploading WhatsApp Image 2020-01-06 at 19.45.19.jpeg…]()
supported

**Closed by minhtruong315** 2020-01-06 14:32 UTC
Labels: Fluxstore-MV

**Comment by yassiney120** [comment] 2020-01-06 16:05
thank you for your support i will update my rating

**Comment by minhcasi** [comment] 2020-01-07 02:35
@yassiney120  - pls update it ASAP - thanks

**Comment by yassiney120** [comment] 2020-01-07 05:48
Done

**Comment by yassiney120** [comment] 2020-01-07 05:49
![C58AF6BB-F1E7-4E0A-8195-B465A089FF76](https://user-images.githubusercontent.com/8164673/71871563-f6628900-3132-11ea-9647-8d340c5589c3.png)

**Comment by yassiney120** [comment] 2020-01-07 05:51
Please sir can you check my issues N 1768
