### ISSUE TITLE
FluxStore Multivendor - Home image and menu icon

### ISSUE THREAD

**Issue by juanmanuel0963** [inspireui/support#4369] opened 2020-07-26 04:12 UTC
Hi,
I bought today the multivendor flutter source code and I would like to ask something the home image
Where can I change the image?
Where can I change the menu icon?
![Capture](https://user-images.githubusercontent.com/44442325/88471233-53097380-cecc-11ea-88a6-7977579a6519.PNG)

**Comment by ameenbadri7** [comment] 2020-07-26 06:59
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by minhcasi** [comment] 2020-07-26 11:54
btw, you could check this guide https://docs.inspireui.com/fluxstore/customization/#1-how-to-customize-any-ui-from-app

**Comment by minhcasi** [comment] 2020-07-27 01:38
Please share your proof or purchase by submitting this form http://verify.inspireui.com/

**Comment by minhcasi** [comment] 2020-07-28 03:37
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-28 03:37 UTC
Labels: needs-more-info
