### ISSUE TITLE
change texts

### ISSUE THREAD

**Issue by saeidAalizade** [inspireui/support#630] opened 2019-05-23 09:20 UTC
- Product: [MStore]
 - Your Purchased Code: [153bb1ff-3f3e-41cd-a219-da061397aef5]

**Describe the issues**

how can I Changed texts?
  pending
  processing
  onHold
  completed
  cancelled
  refunded
  failed

**Screenshots**

**Comment by minhcasi** [comment] 2019-05-23 12:42
i'm not sure to understand your idea, can you explain more

Pls create just one ticket for your all issue, Duplicate of #626

**Closed by minhcasi** 2019-05-23 12:42 UTC

**Comment by saeidAalizade** [comment] 2019-05-23 15:23
Product: [MStore]
Your Purchased Code: [153bb1ff-3f3e-41cd-a219-da061397aef5]
Describe the issues

how can I Changed texts?
- pending
- processing
- onHold
- completed
- cancelled
- refunded
- failed
to status order 
I want to change in Arabic
Example : 
completed = منجز
cancelled = ألغيت
failed = فشل




Screenshots
