### ISSUE TITLE
FluxStore 1.6.0 [Magento] configurable products issue

### ISSUE THREAD

**Issue by Abhiv66** [inspireui/support#1635] opened 2019-12-18 05:27 UTC
1. My issue: Price not changing according to options i have added and cart not working according to configurable products,help me supporting please, if this issues will come how can i launch my product on time ?

2. Screenshots issues:
![screenshot](https://user-images.githubusercontent.com/58973413/71058274-40d09580-2185-11ea-86ae-d61072108057.jpg)

3. Proof of my purchased:
![img](https://user-images.githubusercontent.com/58973413/71058142-d9b2e100-2184-11ea-81b8-3caf388f25f3.png)

3. Config files (optional)
Already sent to this email truong@inspireui.com

--

**Comment by minhcasi** [comment] 2019-12-18 09:41
Duplicate of #1630

try to create one ticket for your all issue - thanks

**Closed by minhcasi** 2019-12-18 09:41 UTC
Labels: question ❓
