### ISSUE TITLE
product quantity

### ISSUE THREAD

**Issue by sidewinder82** [inspireui/support#4985] opened 2020-09-12 13:56 UTC
my app few day ago work fine but now product quantity have a bug, only 1 quantity.
![Screenshot_20200911-145319](https://user-images.githubusercontent.com/71181301/92997043-7a65df80-f510-11ea-8d27-90182bc98684.jpg)

**Comment by minhcasi** [comment] 2020-09-13 02:00
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-09-15 02:59
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-09-15 02:59 UTC
Labels: needs-more-info
