### ISSUE TITLE
[Fluxstore 1.5.7] - Login problems / bugs

### ISSUE THREAD

**Issue by EmilianH** [inspireui/support#1387] opened 2019-11-14 01:44 UTC
1. My issue

Two problems:

1) The login is permanent and does not automatically go to the main menu after creating a new account.

It only says a welcome message, but remains on the same screen. Which shouldn't work like this. When someone creates an account they would have to show the main screen after creating the account.

2) being logged in, every time I start again the app still shows the log in screen.
If the app already knows that I'm logged in, it shouldn't show me the login screen when I start the app, since I'm already logged in.

"isrequieredlogin" is true since I need it that way.
2. Screenshots
![loginbug](https://user-images.githubusercontent.com/57189819/68819515-f54b3900-0666-11ea-8025-a617d98d78f2.png)

3. My screenshot of the purchase product or my comment:
![compra](https://user-images.githubusercontent.com/57189819/68819481-e1073c00-0666-11ea-8357-daf3a1b50fe5.jpg)

3. Config files (optional)

**Comment by minhcasi** [comment] 2019-11-14 02:53
Duplicate of #1324

Could you able to note as one ticket so that the team could have better support on your issues?

**Closed by minhcasi** 2019-11-14 02:53 UTC
Labels: 1.5.8, FluxStore, question ❓

**Comment by EmilianH** [comment] 2019-11-14 02:57
This is not duplicated!!!! Its a different issue!!!
