### ISSUE TITLE
[FluxStore WooCommerce] Need Help for making some changes

### ISSUE THREAD

**Issue by amitw7786** [inspireui/support#3181] opened 2020-05-13 16:43 UTC
Hello I Have purchased FluxStore woocommerce app, I have done all the setup but I need Little help for making some changes in my app view please tell me how can I do this..
1)	I am using config_en.jeson as

 "VerticalLayout": {
   "layout": "menu",
    "name": "Shop by Categories"
  },
In this
 I want to display “Add to cart” Button on each product
![display add to cart button](https://user-images.githubusercontent.com/64218485/81840095-19c89500-9566-11ea-93eb-05a42bfdbe7e.jpg)

 and also want to hide “See All” Button

![see all](https://user-images.githubusercontent.com/64218485/81840138-2d73fb80-9566-11ea-9f77-169cc99cc893.jpg)

2)	I Want to remove Cancel Order Button
3)	I want to show Community dropdown option at order check out page, It is present on my woocommerce website, I have used “Checkout Form” Plugin for Community.
![checkout form plugin for checkout with community drop down](https://user-images.githubusercontent.com/64218485/82127009-36ff9c80-97ce-11ea-9273-b57ee1838917.jpeg)
![InkedCommunity drop down 1_LI](https://user-images.githubusercontent.com/64218485/82127017-41219b00-97ce-11ea-8fd6-0d113b6578fa.jpg)

4)	I want to remove attribute from filter and search.

5) Can we force Google MAP API to work for a single city, I dont need Google auto loaction to wok for all country or city, I just need it for a single city.

6) Which Plugin do I need to use for using "My Points" Option present in setting page, Order details.
![My Points](https://user-images.githubusercontent.com/64218485/81919797-e9303c00-95f5-11ea-9901-cffbfbfea9b7.jpeg)

Please tell me how to achieve this and also tell me where can I find all these things (file names)

**Comment by philipvu30** [comment] 2020-05-15 03:13
Hi,

1. 
- Add this line to menu_layout.dart
![image](https://user-images.githubusercontent.com/54442328/82006269-9f952f00-9691-11ea-916f-2497ebf063f9.png)

- Remove these lines in header_view.dart
![image](https://user-images.githubusercontent.com/54442328/82006418-f6026d80-9691-11ea-9622-2c2795ba9ad4.png)

2. Remove these lines in lib/widgets/frameworks/woocommerce/index.dart
![image](https://user-images.githubusercontent.com/54442328/82007495-948fce00-9694-11ea-9be6-a483adab65fd.png)


3. Sorry. We do not support external plugin uses. 

4. Remove lines from 193 to 205 in file backdrop_menu.dart
![image](https://user-images.githubusercontent.com/54442328/82006804-dae42d80-9692-11ea-8716-6f6e1d6b8276.png)

5. Investigating.

6. Refer to [this](https://docs.inspireui.com/fluxstore/customization/#9-product-advance-options)

**Comment by ameenbadri7** [comment] 2020-05-15 05:20
wow those tips are great !! why you did not mention in the document that you can customize the code that easy! 
i like it very much philipvu30. thank you.

**Comment by amitw7786** [comment] 2020-05-15 12:24
Thank you very much.. !! All queries has been solved except my checkout form plugin, which we use for combine different areas of our city , It is very important for us, can you tell me any other way to add community drop down box at Address checkout page ??

**Comment by amitw7786** [comment] 2020-05-15 12:58
Can I use Field editor id plugin instead of checkout form plugin??
It is very important for us to use that drop down box in address field

**Comment by amitw7786** [comment] 2020-05-15 13:05
Also Please tell me Can I use terra wallet plugin for wallet payment?? Or you can suggest me which wallet should I use for payment..

**Comment by amitw7786** [comment] 2020-05-16 11:05
As of Point No. 2 , We removed Cancel Order button, 
I did the same thing for Deleting Refund button but
Refund button is still there.. I deleted code below the cancel button "refund button code"

**Comment by amitw7786** [comment] 2020-05-16 11:07
And on My home page as we are using Menu Layout, this layout is not showing all products.. It is showing just 20 Products, not loading more products even there are 35 products in that category

**Comment by amitw7786** [comment] 2020-05-17 07:28
**1)**	As you suggested for removing ”Order Cancel” Button, I did same thing for “Refund” Button but it is still appearing ..
I deleted code of Cancel Order as well as code of Refund too but it is not removed, How can I remove “Refund” Button also..
![removed refund](https://user-images.githubusercontent.com/64218485/82124854-7a064380-97bf-11ea-905a-6b32e9d46e6d.png)
![Refund still there](https://user-images.githubusercontent.com/64218485/82124862-84c0d880-97bf-11ea-8756-f95e8b71188c.jpg)

**2)**	My config_en.json contains
"VerticalLayout": {
 	"layout": "menu",
"name": "Shop by Categories"
},

It is now showing Add to Cart button but It is not showing All products of selected category, It is showing only 20 products when category contains 36 products.
![shows 20 products](https://user-images.githubusercontent.com/64218485/82124885-b46fe080-97bf-11ea-83ca-378e41edef1f.jpg)

**3)**	When I use filter, and select any category then after getting into that category , category name is not changing, it is showing previous category name.
![filter](https://user-images.githubusercontent.com/64218485/82124914-fdc03000-97bf-11ea-9fea-75af1cc3dbc7.jpeg)
![category name dosent change when we use filters ](https://user-images.githubusercontent.com/64218485/82124921-07e22e80-97c0-11ea-8ea3-4f23c8840ecf.jpeg)

**4)**       At the address page, I don’t need country and State, I want to rename country as flat No and make this editable (Now country can’t be edited) and want to rename state as “Community” and add some predefined name of area groups in its drop-down instead of states.. Please tell me how can I do this..
![change country and city](https://user-images.githubusercontent.com/64218485/82127402-dde53800-97d0-11ea-9a9c-6586925cc198.jpg)


**5)**       At the checkout page, Address searching button when I try to search address by entering in text field I get the following error
"You have exceeded your daily request quota for this API, If you did not set a custom daily request quota, verify your project has an active billing account :"
Please tell me how to force this location service to work for just Bangalore (Bangalore, Karnataka, India) city only and
tell me how can I disable this Search address button also ..
![api error](https://user-images.githubusercontent.com/64218485/82127253-b477dc80-97cf-11ea-9010-d1a4d639d9b8.jpg)



**6)**	If I use “See All” button and click on it, it displays a blank category named as “See All” , How to remove this “See All” category blank page
![see all](https://user-images.githubusercontent.com/64218485/82124965-5db6d680-97c0-11ea-8d53-4c83b673fdb5.jpg)
![See All No products](https://user-images.githubusercontent.com/64218485/82124970-6dceb600-97c0-11ea-95bd-bfe44e7268dc.jpeg)

**Comment by amitw7786** [comment] 2020-05-18 06:27
Hello... Please reply its urgent..

**Comment by philipvu30** [comment] 2020-05-18 08:17
Hi,

1. You need to remove from line 277 - 300 also. You can find them here lib/screens/orders/order_detail.dart
![image](https://user-images.githubusercontent.com/54442328/82185964-3f61ef80-9914-11ea-98ec-0c636750615f.png)

2. In lib/common/constants/general.dart, set the ApiPageSize from 20 to your preferred number. The maximum is 100. But to remind you, this will cause the categories loading speed to slow down.

5. Already stated in the previous comment.

6. add/replace this in smartchat.dart. As FluxStore does not support chat integration, it will open messenger if it is available on your phone.
'app': 'https://m.me/YOURFANPAGE',
'iconData': 'YOUR ICON'

For all the remove widget/button/icon. Please use the inspector tool to locate them as we are lacking staff and time so we cannot answer all of your questions in detail. My apologies for this inconvenience.

**Comment by amitw7786** [comment] 2020-05-18 11:01
2. Thanks I set it to 60 but even if it was 20 it must load more products after reaching at bottom.. Thanks for help, I try to find some solution myself for other issues I mentioned recently ..

**Comment by philipvu30** [comment] 2020-05-19 03:01
> Thanks I set it to 60 but even if it was 20 it must load more products after reaching at bottom..

Thank you. We'll take note of this detail and implement it in the future releases.

**Comment by philipvu30** [comment] 2020-05-21 07:00
Closed as no activity. Feel free to ask us to re-open your ticket if you have any issues.
Thanks

**Comment by amitw7786** [comment] 2020-05-22 08:19
Hello I need a little help again..
**1.** I have a setting of Shipping Method on my website in wocommerce > Setting > Shipping , under which I have added 3 types of Rates applied to order value
Flat rate
Flat rate ( Order value < 400)
and 
Local pickup
![screen1](https://user-images.githubusercontent.com/64218485/82645842-28cbd900-9c31-11ea-9486-5954e00cb150.png)
![screen2](https://user-images.githubusercontent.com/64218485/82645851-2e292380-9c31-11ea-9335-7d40e3318fdc.png)

This setting work good on website it automatically pick the setting if order value is less than ( < ) 400
but it is not working in our app even it is a woocommerce default setting not a 3rd party plugin..
It is not showing Less than symbol (<) also 
![lessthansignnotcoming](https://user-images.githubusercontent.com/64218485/82645975-63ce0c80-9c31-11ea-8050-b3ba6cefee40.jpeg)

So please tell me what to do for setting it to auto select this shipping method if order value is less than 400

**2.** I want to show categories by my required category id or name as on my website, It is showing alphabetically.
![categorybyid](https://user-images.githubusercontent.com/64218485/82646184-c2938600-9c31-11ea-97d8-0636655149c3.jpeg)

**3.** When we pay by razorpay it is redirecting app to website payment page.. 
**4.** I had renamed the Country textfield as Flat No. if I add 40 as a Flat No then, when it gets redirected to website for razorpay payment then it is showing we cannot deliver to 40...
![adres1](https://user-images.githubusercontent.com/64218485/82646682-acd29080-9c32-11ea-9120-d1e5ae4210dd.jpeg)
![adres2](https://user-images.githubusercontent.com/64218485/82646847-e99e8780-9c32-11ea-822b-eee96fbe3bd4.jpeg)

**5.** Solve above problem No 4 Or Please tell me how can I add Additional Text field and DropDown box in app at shipping address section..
Its Needed Urgent !!

**Comment by amitw7786** [comment] 2020-05-22 08:23
> Closed as no activity. Feel free to ask us to re-open your ticket if you have any issues.
> Thanks

Please Reopen my ticket I have some issues....

**Comment by philipvu30** [comment] 2020-05-22 10:03
Hi,

Our apologies, currently, we don't have any solutions to all of your requested customizations. 

Since these requests are not related to bugs/errors/issues, please ask someone else who is able to help you modify the app. Thank you.

**Comment by amitw7786** [comment] 2020-05-27 15:04
Hii 
I found some bugs in this template ..
**1)** I am using woocommerce based setting for checking whether order is greater than 400 Rs or less than 400 (Order value < 400) In this setting, after placing the order and when we check Order history then we cant see it properly it is giving &lt; instead of < this symbol ...
![Screenshot_2020_0527_142407](https://user-images.githubusercontent.com/64218485/83036995-e05d5280-a058-11ea-866f-d8cc5ba2b977.jpg)
![Screenshot_2020_0527_202655](https://user-images.githubusercontent.com/64218485/83037036-ece1ab00-a058-11ea-89e9-86c5f888e555.jpg)
![error](https://user-images.githubusercontent.com/64218485/83037085-0256d500-a059-11ea-8dd0-609a38e1520e.png)
**2)** I am using 
config_en.json as
"VerticalLayout": {
"layout": "menu",
"name": "Shop by Categories"
},
When it displays menu and when there is No internet connection or slow internet connection then it is giving following error 
![WhatsApp Image 2020-05-27 at 8 13 50 PM](https://user-images.githubusercontent.com/64218485/83037445-68dbf300-a059-11ea-84c1-0398d34994cc.jpeg)

**Comment by philipvu30** [comment] 2020-05-29 03:13
Hi,

1. Please replace this file [order.dart.zip](https://github.com/inspireui/support/files/4699475/order.dart) in lib/models/order/order.dart

2. This app requires the internet to get the data though. We'll consider making it empty if it cannot connect to the internet.

**Comment by amitw7786** [comment] 2020-05-29 07:46
Hi I am getting 404 page not found message for downloading order.dart.zip

**Comment by philipvu30** [comment] 2020-05-29 07:49
Edited. Please try again. Thank you

**Comment by amitw7786** [comment] 2020-05-29 13:19
Hii thanks for the help...
Can you please tell me how can I show main page category like following any one view
![WhatsApp Image 2020-05-29 at 5 53 09 PM](https://user-images.githubusercontent.com/64218485/83263832-d5cbc600-a1dc-11ea-9fb7-afd46486fb55.jpeg)
OR
like 
below
one
![WhatsApp Image 2020-05-29 at 4 39 57 PM](https://user-images.githubusercontent.com/64218485/83263834-d7958980-a1dc-11ea-8e2b-86007d6f934d.jpeg)

 I am using below cong_en.json
{
  "HorizonLayout": [
    {
      "layout": "logo",
      "showMenu": true,
      "showSearch": true,
      "showLogo": false
    },
    {

      "layout": "bannerImage",
      "radius": 2.0,
      "padding": 0.0,
      "items": [
        {
          "category": 52,
          "image": "https://user-images.githubusercontent.com//83113936-e9483580-a0e5-11ea-96f5-f2015c0b08b2.png",
          "padding": 0.0
        }
      ]
    },

    {
      "layout": "header_text",
      "fontSize": 20.0,
      "title": "Your Daily Fresh Needs.."
    },

    {
      "layout": "bannerImage",
      "isSlider": true,
      "design": "swiper",
      "radius": 20.0,
      "items": [
        {
          "category": 45,
          "image": "https://user-images.githubusercontent.com/83120520-cbcb9980-a0ee-11ea-9a0e-6a7855d98a01.png",
          "padding": 0.0
        },
        {
          "category": 43,
          "image": "https://user-images.githubusercontent.com//81290785-4b34f280-9086-11ea-96d4-294a56c1c840.png",
          "padding": 0.0
        },
        {
          "category": 56,
          "image": "https://user-images.githubusercontent.com/-52f49700-9086-11ea-9f04-a2c4b9a212e2.png",
          "padding": 0.0
        },
        {
          "category": 389,
          "image": "https://user-images.githubusercontent.com//83118798-77271f00-a0ec-11ea-9c08-4f4680697b22.png",
          "padding": 0.0
        }
         
        
      ]
    }
  ],
  "VerticalLayout": {
    "layout": "menu",
    "name": "Shop by Categories"
  },
  "Setting": {
    "MainColor": "#47b352",
    "ProductListLayout": "list"
  },
  "TabBar": [
    {
      "layout": "home",
      "icon": "assets/icons/tabs/icon-home.png"
    },
    {
      "layout": "category",
      "categoryLayout": "column",
      "icon": "assets/icons/tabs/icon-category.png"
    },
    {
      "layout": "search",
      "icon": "assets/icons/tabs/icon-search.png"
    },
    {
      "layout": "cart",
      "icon": "assets/icons/tabs/icon-cart2.png"
    },
    {
      "layout": "profile",
      "icon": "assets/icons/tabs/icon-user.png"
    }
  ],
  "searchSuggestion": [
    "Fruit",
    "Vegetable",
    "Oil",
    "Rice"
  ],
  "OnBoarding": {
    "data": [{
      "title": "Welcome to Organics Shops",
      "image": "assets/images/fogg-delivery-1.png",
      "desc": "Organics and Natural Store is on the way to serve you. ",
      "background": "#FFF3F2"
    },
      {
        "title": "All Products are Organic here",
        "image": "assets/images/fogg-uploading-1.png",
        "desc":  "Get anything you need from Range of Multiple Organic Products",
        "background": "#F2FFFC"
      },
      {
        "title": "Let's Get Started",
        "image": "fogg-order-completed.png",
        "desc": "Waiting no more, let's see what we get!",
        "background": "#F9F2FF"
      }
    ]
  }
}

**Comment by amitw7786** [comment] 2020-06-04 12:20
Hii Its Urgent !!
There is another small bug in our template ..
I am using fluxbuiler app to create my Home page view
I have added categories on my home page, I selected Show text for showing category names with images..
![Image with name shown in preview](https://user-images.githubusercontent.com/64218485/83755544-58e09680-a68b-11ea-94e9-e6569d5f19ef.jpg)
It shows category names with images In preview but 
when I save it it shows as below
![Image without name shown in preview](https://user-images.githubusercontent.com/64218485/83755643-7e6da000-a68b-11ea-9d8c-2a2e1263790a.jpg)

Please tell me urgently how to show Category names below this Category images..
Is there any way to show category name as a static string in our json like below
{
          "category": 385,
          "image": "https://i.imgur.com/n0XX3el.jpg",
          "colors":
          [
            "#333333"
          ],
          "originalColor": true,
          "showText": true       ///// CAN I ADD CATEGORY NAME DIRECTLY HERE 
        }

**Comment by amitw7786** [comment] 2020-06-04 12:46
Also Please tell How to Increase this category card size or image size
![category card size](https://user-images.githubusercontent.com/64218485/83758296-79aaeb00-a68f-11ea-8294-1401a11145aa.jpg)

**Comment by amitw7786** [comment] 2020-06-12 18:58
Need Help urgently.. 
My application is finally on play store but i am facing new issue with signed apk from playstore.. 
When I try to login using facebook or Google then my app screen automatically becomes blak and messy and shows some error on top of screen please check the following screenshot of error
![IMG_20200613_001757](https://user-images.githubusercontent.com/64218485/84536854-4fe76900-ad0c-11ea-83a7-eea3ddaf3e34.JPG)
**Original screen is as below** 
![Screenshot_20200613_001958](https://user-images.githubusercontent.com/64218485/84537049-ab195b80-ad0c-11ea-8f29-5cd7eda88f47.JPG)

**Comment by amitw7786** [comment] 2020-06-17 11:32
@philipvu30 @ameenbadri7 
@minhcasi 
Can someone help me to set Listview layout as default layout in my product view ...??
I want to set default layout list view layout in Category >> Product
I want make this view as default view as below
![Screenshot_2020_0617_162738](https://user-images.githubusercontent.com/64218485/84892995-28055600-b0bc-11ea-89f0-6c5559c12fac.jpg)
My Current View is as below
![Screenshot_2020_0617_162708](https://user-images.githubusercontent.com/64218485/84893055-423f3400-b0bc-11ea-939f-534c431df2ba.jpg)

**Comment by amitw7786** [comment] 2020-06-30 14:25
Hii Please reopen My ticket I have some issues with our fluxstore app

**Comment by amitw7786** [comment] 2020-06-30 14:38
Why your fluxstore app is showing your notification ads inside my app when I send firebase push notifications to users...
It is very wrong thing... It should not show any of your notifications in my playstore app..
![WhatsApp Image 2020-06-29 at 12 39 55 PM](https://user-images.githubusercontent.com/64218485/86139087-f30df000-bb0c-11ea-93fa-9bf14f082b12.jpeg)
![WhatsApp Image 2020-06-29 at 12 36 42 PM](https://user-images.githubusercontent.com/64218485/86139106-f608e080-bb0c-11ea-8f73-3b57eef3e00d.jpeg)
When I send this type of notification then it is not showing inside my app notification tab... What to do..
2. Smart Chat button is not being displayed in my app when I updated my app to version 1.7.5 ,
I already have enabled this as :
const kConfigChat = {
  "EnableSmartChat": true,
};
In Smartchat.dart

**Comment by ameenbadri7** [comment] 2020-06-30 19:24
hello @amitw7786 

for issue 2-
you can add the smart chat  by enabling it from the config_xx.json file

if you want to show it inside the setting page 
you can add it like this inside ` "TabBar":`: 

```
{
      "layout": "profile",
      "label": "Settings",
      "icon": "assets/icons/tabs/icon-user.png",
      **"showChat": true**
    }
```

issue 
3-can double-checking the [firebase settings for Facebook ](https://medium.com/@inspireui/setup-facebook-login-for-flutter-apps-4e7bd031479d?source=---------8------------------)

for issue number 1- 
@philipvu30 can you help here, thank you.

let us know if you still have problems.

**Comment by philipvu30** [comment] 2020-07-01 02:41
Hi,

Did you change our google-services.json and GoogleService-Info.plist files to yours?

**Comment by amitw7786** [comment] 2020-07-01 11:03
> Hi,
> 
> Did you change our google-services.json and GoogleService-Info.plist files to yours?

Hii I have changed google-service.json but not changed GoogleService-info.plist because we dont have planing to lauch ios app for now..

**Comment by philipvu30** [comment] 2020-07-01 11:06
Hi,

In the file lib/common/config/general.dart, please leave this field empty. 
My apologies because it was our mistake that we forgot to remove it out.

![image](https://user-images.githubusercontent.com/54442328/86237221-915d8c80-bbc5-11ea-8ca9-52c540ba660a.png)

**Comment by amitw7786** [comment] 2020-07-01 11:49
Hii Thank You

**Comment by amitw7786** [comment] 2020-07-01 13:19
> hello @amitw7786
> 
> for issue 2-
> you can add the smart chat by enabling it from the config_xx.json file
> 
> if you want to show it inside the setting page
> you can add it like this inside ` "TabBar":`:
> 
> ```
> {
>       "layout": "profile",
>       "label": "Settings",
>       "icon": "assets/icons/tabs/icon-user.png",
>       **"showChat": true**
>     }
> ```
> 
> issue
> 3-can double-checking the [firebase settings for Facebook ](https://medium.com/@inspireui/setup-facebook-login-for-flutter-apps-4e7bd031479d?source=---------8------------------)
> 
> for issue number 1-
> @philipvu30 can you help here, thank you.
> 
> let us know if you still have problems.

Hi
Thanks for answer..
Will it also show messages inside my Notify Message tab under setting like below??
![WhatsApp Image 2020-06-29 at 12 39 55 PM](https://user-images.githubusercontent.com/64218485/86139087-f30df000-bb0c-11ea-93fa-9bf14f082b12.jpeg)

**Comment by amitw7786** [comment] 2020-07-01 14:11
Hello... @philipvu30 @ameenbadri7 
 It is not showing smartchat even I have added it as suggested by you like below in tabbar
TabBar :
{
      "layout": "profile",
      "label": "Settings",
      "icon": "assets/icons/tabs/icon-user.png",
      "showChat": true
    }

Below is full code of my config_en.json

`{
  "HorizonLayout":[
     {
        "layout":"logo",
        "showMenu":true,
        "showSearch":false,
        "showLogo":false
     },
     {
        "text":"",
        "height":85,
        "padding":20,
        "shadow":11,
        "radius":30,
        "layout":"header_search"
     },
     {
        "layout":"bannerImage",
        "radius":2,
        "padding":0,
        "items":[
           {
              "category":52,
              "image":"https://user-images.githubusercontent.com/64218485/83113936-e9483580-a0e5-11ea-96f5-f2015c0b08b2.png",
              "padding":0
           }
        ]
     },
     {
        "isSafeArea":true,
        "showSearch":false,
        "rotate":["Your Daily Fresh Needs . . .",
           "Your Daily Fresh Needs . . .",
           "Your Daily Fresh Needs . . ."],
        "type":"typer",
        "height":0.13,
        "padding":20,
        "fontSize":20,
        "layout":"header_text"
     },
     {
        "layout":"bannerImage",
        "isSlider":true,
        "autoPlay":true,
        "design":"swiper",
        "items":[
           {
              "category":45,
              "image":"https://user-images.githubusercontent.com/64218485/83120520-cbcb9980-a0ee-11ea-9a0e-6a7855d98a01.png",
              "padding":0
           },
           {
              "category":43,
              "image":"https://user-images.githubusercontent.com/64218485/81290785-4b34f280-9086-11ea-96d4-294a56c1c840.png",
              "padding":0
           },
           {
              "category":56,
              "image":"https://user-images.githubusercontent.com/64218485/81290807-52f49700-9086-11ea-9f04-a2c4b9a212e2.png",
              "padding":0
           },
           {
              "category":389,
              "image":"https://user-images.githubusercontent.com/64218485/83424723-6d821c00-a44a-11ea-9750-e0396d14d956.png",
              "padding":0
           }
        ],
        "radius":20.0
     },
     {
        "isSafeArea":true,
        "showSearch":false,
        "rotate":["Search By Categories. . .",
           "Search By Categories. . .",
           "Search By Categories. . ."],
        "type":"color",
        "height":0.13,
        "padding":20,
        "fontSize":20,
        "layout":"header_text"
     },
     {
        "layout":"category",
        "type":"image",
        "wrap":true,
        "size":0.9,
        "radius":0,
        "items":[
           {
              "category":45,
              "image":"https://i.imgur.com/W7SyAKL.jpg",
              "colors":["#333333"],
              "originalColor":true,
              "showText":true,
              "name":"Green Leaves & Vegetables"
           },
           {
              "category":43,
              "image":"https://i.imgur.com/3yq5SYx.jpg",
              "colors":["#333333"],
              "originalColor":true,
              "showText":true,
              "name":"Organic Fruits"
           },
           {
              "category":56,
              "image":"https://i.imgur.com/5iQSVDT.jpg",
              "colors":["#333333"],
              "originalColor":true,
              "showText":true,
              "name":"Coldpressed oil"
           },
           {
              "category":389,
              "image":"https://i.imgur.com/EBIVTWJ.jpg",
              "colors":["#333333"],
              "originalColor":true,
              "showText":true,
              "name":"Grocery"
           },
           {
              "category":383,
              "image":"https://i.imgur.com/f6XwH8d.jpg",
              "colors":["#333333"],
              "originalColor":true,
              "showText":true,
              "name":"Dairy & Snacks"
           },
           {
              "category":385,
              "image":"https://i.imgur.com/w0EJoqj.jpg",
              "colors":["#333333"],
              "originalColor":true,
              "showText":true,
              "name":"Home and Wellness"
           }
        ]
     }
  ],
  "Setting":{
     "MainColor":"#47b352",
     "ProductListLayout":"list",
     "StickyHeader":true
  },
  "TabBar":[
     {
        "layout":"home",
        "icon":"assets/icons/tabs/icon-home.png",
        "showChat": true,
        "pos":100
        
     },
     {
        "layout":"category",
        "categoryLayout":"sideMenu",
        "icon":"assets/icons/tabs/icon-category.png",
        "pos":200,
        "categories":["45",
           "43",
           "56",
           "389",
           "383",
           "385"],
        "images":["briefcase",
           "chrome",
           "download",
           "compass",
           "instagram",
           "activity"]
     },
     {
        "layout":"search",
        "icon":"assets/icons/tabs/icon-search.png",
        "pos":300
     },
     {
        "layout":"cart",
        "icon":"assets/icons/tabs/icon-cart2.png",
        "pos":400
     },
     {
        "layout":"profile",
        "icon":"assets/icons/tabs/icon-user.png",
        "pos":500
     }
  ],
  "OnBoarding": {
    "data": [
      {
        "title": "Welcome to Amruth Organics",
        "image": "assets/images/fogg-delivery-1.png",
        "desc": "Amruth Organics and Natural Store is on the way to serve you. "
      },
      {
        "title": "All Products are Organic here",
        "image": "assets/images/fogg-uploading-1.png",
        "desc":
            "Get anything you need from Range of Multiple Organic Products"
      },
      {
        "title": "Let's Get Started",
        "image": "fogg-order-completed.png",
        "desc": "Waiting no more, let's see what we get!"
      }
    ]
  }
     
  }`

**Comment by amitw7786** [comment] 2020-07-01 14:18
Please reply urgent if possible, Because I want to upload it to playstore with new update

**Comment by ameenbadri7** [comment] 2020-07-01 14:19
go to `lib\common\config\smartchat.dart`

its must be :
`
const kConfigChat = {
  "EnableSmartChat": true,
};`
and also change your numbers for SMS and whats app from the same file.

thank you

**Comment by amitw7786** [comment] 2020-07-01 14:20
hii
![Screenshot_2020_0701_192840](https://user-images.githubusercontent.com/64218485/86254886-1cde1a00-bbd4-11ea-83c3-df298da2eab7.jpg)
![Screenshot_2020_0701_193134](https://user-images.githubusercontent.com/64218485/86254893-1f407400-bbd4-11ea-83ec-ca559fcc6243.jpg)

**Comment by amitw7786** [comment] 2020-07-01 14:22
> go to `lib\common\config\smartchat.dart`
> 
> its must be :
> ` const kConfigChat = { "EnableSmartChat": true, };`
> and also change your numbers for SMS and whats app from the same file.
> 
> thank you

I have set that already
const kConfigChat = { "EnableSmartChat": true, };`
But above is the screenshot of my Old app present on playstore and another is the new one where it is not being displayed 1.7.5 version

**Comment by amitw7786** [comment] 2020-07-01 14:38
Hii
Sorry I found my mistake...
I was added that at Home instead of Setting so was not showing...
It is showing the button now..
Thanks for the Help @philipvu30 @ameenbadri7

**Comment by ameenbadri7** [comment] 2020-07-01 14:42
thank you for your feed back.
please tell us if your problem fixed so we can close this ticket issue or let us help you more.

**Comment by amitw7786** [comment] 2020-07-01 14:56
It is fixed now.. If I find any bug or error then I will tell that Thanks.

**Comment by amitw7786** [comment] 2020-07-07 18:08
Hello...
I am having some errors and bugs again with our app
1) there is an error on order history page coming on release build version present on playstore,
When my clients go on order history page then below error is appearing when they open order history..
![order history error](https://user-images.githubusercontent.com/64218485/86820286-73e96080-c0a6-11ea-9241-e49bc3eb6acf.jpeg)

2) I am using "OnpageCheckout" method, I am facing new issues with this method after updating my app to version 1.7.5
When we add 2 or more items to cart in app and go to checkout page of website then on website page it shows only one item
![having cart 2 items1](https://user-images.githubusercontent.com/64218485/86821317-e1e25780-c0a7-11ea-9d3b-1685346e7de7.jpg)
![having cart 2 items2](https://user-images.githubusercontent.com/64218485/86821356-ec045600-c0a7-11ea-976d-e72bda119a99.jpg)

Here is another example of same error with different products
![2nd having cart 2 items1](https://user-images.githubusercontent.com/64218485/86821455-0dfdd880-c0a8-11ea-9706-30fa15315286.jpg)
![2nd having cart 2 items2](https://user-images.githubusercontent.com/64218485/86821490-17874080-c0a8-11ea-8dfd-d0396ce1c5e1.jpg)

3)  Again having issue with fb login, It was working fine but after some period it is giving "invalid key has error", but I already had generated Key hashes using my keystore and followed all procedures mentioned on these both places...
https://docs.inspireui.com/fluxstore/sign-in/#3-facebook-sign-in
And
https://medium.com/@inspireui/setup-facebook-login-for-flutter-apps-4e7bd031479d
![Login with fb error](https://user-images.githubusercontent.com/64218485/86823834-f83de280-c0aa-11ea-9810-585535b251e6.jpg)

Tell me which one is complete procedure, because in video it dosent show to enable facebook login from firebase also,
and in other procedures it says to enable facebook login from firebase too.
Also tell me which " Valid OAuth Redirect URIs " should be added in this field..
we just need to add https:www.mywebsite.com/auth/facebook
or
it can be added from auto generated link from firebase when we enable facebook login

**Comment by amitw7786** [comment] 2020-07-09 14:58
Hii can you please solve issue of cart items early? Because my customers are complaining about app, they cant order their needed items as they are not appearing on checkout page of my website, before I update it to 1.7.5 it was working fine...

**Comment by philipvu30** [comment] 2020-07-10 02:24
Hi,

Can you send your latest project after running the command flutter clean to this email: toan@inspireui.com. As this bug is not happening on our current app.

Thank you.

**Comment by amitw7786** [comment] 2020-07-10 07:59
OK Thanks, I have sent you email please check....

**Comment by philipvu30** [comment] 2020-07-10 09:02
Hi,

Do you know what is this error? I chose the same products as you.

![image](https://user-images.githubusercontent.com/54442328/87137192-ba1d0a80-c2c6-11ea-811f-af98a25a8279.png)

**Comment by basithzan** [comment] 2020-07-10 09:50
Hi @amitw7786 

can you please tell me how you renamed the Country textfield as Flat No?

Thanks.

**Comment by amitw7786** [comment] 2020-07-10 10:12
Oh thanks @philipvu30 , I look for the issue of this product setting, but please also tell me what will be the problem of "Order History" with my playstore version , when customers go to that page they are getting this error
https://user-images.githubusercontent.com/64218485/86820286-73e96080-c0a6-11ea-9241-e49bc3eb6acf.jpeg

**Comment by philipvu30** [comment] 2020-07-10 10:23
Hi @amitw7786 ,

I don't encounter that issue on my side with your project. What did you click before that error?
About order item missing, may I ask what is your current version of Mstore API plugin? Because I've checked and it seems everything is fine until I click the checkout button. The order is wrongly processed on the website.
I'll forward this issue to our backend engineer and it might take a couple of days for it to be fixed.

My apologies for this inconvenience.

**Comment by amitw7786** [comment] 2020-07-10 10:59
Hi @basithzan ,
right now I am using "OnPageCheckout" instead of "NativePageCheckout" because I have many other fields to use at the checkout page so I am using them from my website checkout page..

I used "Flutter Inspector" to find the code of Country,
Run your app on connected device or emulator, then go to that page where you want to rename particular object (Label or Text field etc) ,
Then click on Flutter Inspector and click on particular object, then Android studio will automatically display that block of code from corresponding page, 
then you can find the declaration or implementation of that string by right click on particular code>> GoTo>> Declaration or usage / implementation  
You can find more help on "Inspector Tool" here
https://docs.inspireui.com/fluxstore/customization/

**Comment by amitw7786** [comment] 2020-07-10 11:20
Hello @philipvu30 ,
I am using Mstore API Version 2.6.8, Please try to solve this as soon as possible..
I check that process of error issue again and tell you what was clicked by some users before clicking on "Order History" Button.
I also faced same type of issue which was occurred when I was signed up using Facebook on my playstore release build
https://user-images.githubusercontent.com/64218485/84536854-4fe76900-ad0c-11ea-83a7-eea3ddaf3e34.JPG

**Comment by amitw7786** [comment] 2020-07-10 13:03
Hello @philipvu30, 
I spoke with my customer he told me that, they are getting this error when they login using user name and directly click on "order history"

**Comment by amitw7786** [comment] 2020-07-12 05:46
Hii @philipvu30  have you fixed issue of wrong order processing ?

**Comment by philipvu30** [comment] 2020-07-13 05:40
Hi,

Sorry for the delayed response.
1. Order item missing issue
- I have tested on our demo app and other customers' apps, but none of them have the issue as yours. In addition, if I added 3 different items to cart and proceed to checkout, the order will only display the last 2 items, it means the first one is removed from the order.
2. Order history
- I run your project and replicate your customer's steps but the error did not occur. See this [video](https://drive.google.com/file/d/1fkNf48SiaiKU8Vmf_Gf3jG1fAYhYD58i/view?usp=sharing)
3. > I also faced same type of issue which was occurred when I was signed up using Facebook on my playstore release build
- Did not happen on your project also

**Comment by amitw7786** [comment] 2020-07-13 07:45
Hi
1. So what can you suggest for the item missing issue, what I can do for it, will it be related to any plugins or updated plugins ? Because at the beginning with previous version of our app it was working fine but after updating it to 1.7.5 it is having this issue.

2. but you tested when you dont have any old orders, My customers got that error when they have their previous order in "Order History" list, So please try to place some orders then try again if possible. Because only then that issue arises .

**Comment by philipvu30** [comment] 2020-07-13 08:48
Hi,

1. Actually, just only this product has an issue. You can try to add other products, none of them are removed while doing check-out.
![image](https://user-images.githubusercontent.com/54442328/87283884-f7300980-c51f-11ea-830a-062cd5011f34.png)
2. The issue still not arises. See this [video](https://drive.google.com/file/d/1uW9kirDIRGKh24mdXZIvd-RzRYqKcH_x/view?usp=sharing)

**Comment by amitw7786** [comment] 2020-07-13 09:03
Ok @philipvu30 ,
Thanks a lot, I check for other products too, and try to re-add them on website..

**Comment by amitw7786** [comment] 2020-07-13 11:09
Hii @philipvu30 
Is there any supporting issue of our app for old handsets?
Because issue of Order History is always coming on some old handsets...
One customer is having Redmi Note 5 Pro and he is regularly facing the issue of error on "Order History"

**Comment by philipvu30** [comment] 2020-07-16 03:17
Hi,

I'm sorry I'm unable to help as I can't find any old handsets or Redmi Note 5 Pro profiles on the internet to replicate this issue.
Also FYI, the Flutter framework usually has issues with MIUI devices.

**Comment by minhcasi** [comment] 2020-07-21 03:09
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-21 03:09 UTC
Labels: FluxStore, common-integration

**Comment by amitw7786** [comment] 2020-07-28 02:17
Hii its urgent and could be small issue for you, I am not getting the solution pls help !
I am getting another issue with fluxstore 1.7.5
When I updated my app first time to 1.7.5 then a minor bug was there,
1] When app was running for first time then Intro Screen was showing, then after using our app and when I press the back button for Exit it was again showing Intro Screen
App was not being closed by pressing back button as it was being closed before. It was just happening for first time, On second time it was not showing "Intro Screen" but I recently enabled cache on my website and Set "isCaching": true in General.dart and uploaded "config_en.json" to our Api
and did flutter clean and flutter run, and when I run the app the old issue of Intro screen arised again with moderate level as it is showing Intro screen on every run of app and after using the app it is showing intro screen again when back button is pressed and not being closed by back button , we need to close the app by pressing Home button and cleaning Ram
