### ISSUE TITLE
How to configure Push Notificaiton (Android) Mstore-Expo

### ISSUE THREAD

**Issue by onlineosman** [inspireui/support#1741] opened 2020-01-02 03:32 UTC
Got Configured One Signal Correctly but where to put the ID and code in Mstore-Expo,
Searched all documents but couldn't find.?

**Comment by onlineosman** [comment] 2020-01-02 04:56
Proof of purchase 
![Purchase proof for technical support](https://user-images.githubusercontent.com/34172061/71652289-c6377680-2d3d-11ea-8483-b7dfc7507708.png)

**Comment by minhcasi** [comment] 2020-01-02 11:20
@onlineosman - the mstore-expo is not supported oneSignal, please try mstore-pro folder instead  - thank you!

**Comment by minhcasi** [comment] 2020-01-02 11:21
Duplicate of #1743

**Closed by minhcasi** 2020-01-02 11:21 UTC
Labels: MStorePro

**Comment by onlineosman** [comment] 2020-01-02 19:41
Hi,
I cannot use Mstore-Expo, tried installing from support department.  Is there any other solution for Push Notification to work with?

![Skype Suport](https://user-images.githubusercontent.com/34172061/71688437-4e0e9680-2db9-11ea-9439-0269af1641b3.png)
