### ISSUE TITLE
no login

### ISSUE THREAD

**Issue by edmi14** [inspireui/support#4129] opened 2020-07-08 20:22 UTC
when we put the user and the password and we give login it stays loading and does not leave login
![Screenshot_20200708-112741](https://user-images.githubusercontent.com/28486719/86966434-2d901200-c137-11ea-8014-efa0e2476748.png)

**Comment by ameenbadri7** [comment] 2020-07-08 20:44
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by edmi14** [comment] 2020-07-08 20:47
I already sent the information required by the website http://verify.inspireui.com/

**Comment by minhcasi** [comment] 2020-07-09 02:43
@edmi14 - thank you for a response quickly

@luyx2412 - pls help to investigate the issue

**Comment by luyx2412** [comment] 2020-07-09 15:38
Hi @edmi14 I just tested your config and everything worked normal. So can you describe specific your issue? https://drive.google.com/file/d/1WABee9d_9yTvybo3hw4UM_DTZCH--ZTl/view?usp=sharing

Thanks

**Comment by wolverineee92** [comment] 2020-07-10 09:34
> Hi @edmi14 I just tested your config and everything worked normal. So can you describe specific your issue? https://drive.google.com/file/d/1WABee9d_9yTvybo3hw4UM_DTZCH--ZTl/view?usp=sharing
> 
> Thanks
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/6fd1044924d8a6d6907e02d89f67498eaefd4c8f/68747470733a2f2f73736c2e677374617469632e636f6d2f646f63732f646f636c6973742f696d616765732f69636f6e5f31345f766964656f5f66617669636f6e2e69636f">Google Drive**[Screen Recording 2020-07-09 at 22.37.17.mov](https://drive.google.com/file/d/1WABee9d_9yTvybo3hw4UM_DTZCH--ZTl/view?usp=sharing&usp=embed_facebook)**

hello, signup working fine..problem is login function...you can try to login if working send you video

**Comment by luyx2412** [comment] 2020-07-10 13:56
Hi @wolverineee92 The video is login function. Can you send me the video issue?
![image](https://user-images.githubusercontent.com/8909619/87162144-b9e53500-c2ef-11ea-8289-278457418aaf.png)

Thanks

**Comment by minhcasi** [comment] 2020-07-13 13:09
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-13 13:09 UTC
Labels: MStorePro
