### ISSUE TITLE
Change sign in method ?? 

### ISSUE THREAD

**Issue by ahmadmadieh** [inspireui/support#3336] opened 2020-05-21 08:46 UTC
Step 1 (require): i want the login through sms to be The primary method not sign in using email and password .. how can i do that ?

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your

**Comment by minhcasi** [comment] 2020-05-21 10:54
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by ahmadmadieh** [comment] 2020-05-22 22:56
Can you help me please ...

**Comment by minhcasi** [comment] 2020-05-23 02:30
Hi @ahmadmadieh - you could try to remove the username/password and only use for SMS login, try to customize other UI from this file `user/login.dart`

<img width="1084" alt="Screen Shot 2020-05-23 at 09 29 19" src="https://user-images.githubusercontent.com/1459805/82719785-e3aeb200-9cd7-11ea-9dc5-00af38799127.png">

**Comment by minhcasi** [comment] 2020-05-25 07:46
I'm sorry to close this ticket as there is no response, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-05-25 07:46 UTC
Labels: FluxStore
