### ISSUE TITLE
[BeoNews] Many issues in 3.0 release

### ISSUE THREAD

**Issue by mustafamsy** [inspireui/support#421] opened 2019-03-22 16:03 UTC
- Product: [BeoNews]
 - Your Purchased Code: 2a6e0632-d77f-4f7a-bb66-b1d5aa869ccd

**Describe the issues**
1) The documentation is very, very old and not updated! Wrong information lead to wrong installation!! (https://beonews.inspireui.com/)
2) Lottie animation is not included in BeoNews version 3.0 why?! 
3) App crashing when navigating to video scene (see here: https://app.box.com/s/4o3wph0j86s4tlwmbhwx12f6jto7hm7v)
4) Category scene showing only titles as tab bar with no images as previous version (see here: https://app.box.com/s/uyg2c5mttd6138bf8f51drcg7210c2wk)
5) Logo overlap with menu icon (see here: https://app.box.com/s/xpc38o985mpxyzjqb0s65upip62sdka5)
6) Not able to translate text: (MORE) in the photo scene, video scene and news list
7) Photos inside webview goes beyond the edge and don't have maximum width.

**Additional context**
I really like BeoNews, but if above issues are not resolved in version 3.0 then we are not able to update the App!

**Comment by mustafamsy** [comment] 2019-03-22 16:06
`/** @format */

import Constants from './Constants'

export default {
  /**
   * The detail document from: https://beonews.inspireui.com
   * Step 1: Moved to AppConfig.json
   */

  Banner: {
    visible: true,
    sticky: true,
    tag: [19,20,21,22,25,26,54],
    categories: [1,52,53,43,44],
  },

  /**
   * Advance config
   * CategoryVideo: config the category id for video page
   *
   * */
  // Category video id from the menu
  CategoryVideo: 44,

  imageCategories: {
    news: require('@images/category/cate1.jpg'),
    photos: require('@images/category/cate2.jpg'),
    videos: require('@images/category/cate3.jpg'),
    community: require('@images/category/cate4.jpg'),
    advs: require('@images/category/cate5.jpg'),
  },

  // Custom page from left menu side
  CustomPages: {
    contact_id: 1646,
    aboutus_id: 760,
  },

  // config for Firebase, use to sync user data across device and favorite post
  Firebase: {
    apiKey: 'AIzaSyBv-7Q6cqEB1SMutYq1aI7NE***********',
    authDomain: 'alnoorclub-***********.firebaseio.com',
    databaseURL: 'https://alnoorclub-***********.firebaseio.com',
    storageBucket: 'alnoorclub-***********.appspot.com',
    messagingSenderId: '1008***********',
    readlaterTable: 'list_readlater',
  },

  // config for log in by Facebook
  Facebook: {
    showAds: false,
    adPlacementID: '',
    logInID: '330592204***********',
    sizeAds: 'standard', // standard, large
  },

  // config for log in by Google
  Google: {
    analyticId: 'UA-***********-1',
    androidClientId:
      '774021279315-***********.apps.googleusercontent.com',
    iosClientId:
      '774021279315-***********.apps.googleusercontent.com',
  },


  // The advance layout
  AdvanceLayout: [
    Constants.Layout.list,
    Constants.Layout.list,
    Constants.Layout.list,
    Constants.Layout.list,
    Constants.Layout.list,
  ],
  
  // config for log in by Admob
  AdMob: {
    visible: false,
    deviceID: 'pub-***********',
    unitID: 'ca-app-pub-***********/***********', 
    //ca-app-pub-***********/***********  iOS
    //ca-app-pub-***********/***********  Android
    unitInterstitial: 'ca-app-pub-***********/***********',
    isShowInterstital: false,
  },

  // tab animate
  tabBarAnimate: Constants.Animate.zoomIn,

  // config default for left menu
  LeftMenuStyle: Constants.LeftMenu.scale,

  notification: {
    AppId: 'bf1af05e-ca6c-4d92-b671-***********',
    NewAppId: 'bf1af05e-ca6c-4d92-b671-***********',
  },

  OneSignal: {
    appId: 'bf1af05e-ca6c-4d92-b671-***********'
  },

  // update 18 May
  // showLayoutButton: Ability to show/hide the switch layout button at homescreen
  // homeLayout: default homeLayout UI: Constants.Layout.mansory, Constants.Layout.horizontal
  // showSwitchCategory: show the switch button on categories page
  showLayoutButton: false,
  homeLayout: Constants.Layout.list,
  showSwitchCategory: false,

  EnableSanitizeHtml: true,
  RequiredLogin: false,
  showSubCategoryScreen: true,

  // update 18 Sep 
  showAppIntro: true
}`

**Comment by minhcasi** [comment] 2019-03-23 02:07
Hi, thanks for the detail reporting, could you share the appconfig.json as well - our team will have a check and update it shortly

**Comment by mustafamsy** [comment] 2019-03-23 09:31
```
{
  "URL": {
    "root": "https://*******.net"
  },
  "HorizonLayout": [
    { "tags": [61], "paging": false, "layout": 3 },
    {
          "name": "أخبار النادي",
          "categories": [1],
          "layout": 3,
          "paging": false,
          "row": 5,
        },
        {
          "name": "الأخبار الاجتماعية",
          "categories": [52],
          "layout": 5,
          "paging": false,
          "row": 5,
        },
        {
          "name": "الإعلانات",
          "categories": [53],
          "layout": 3,
          "paging": false,
          "row": 5,
        },
        {
          "name": "الصور",
          "categories": [43],
          "layout": 3,
          "paging": false,
          "row": 5,
        },
        {
          "name": "الفيديو",
          "categories": [44],
          "layout": 3,
          "paging": false,
          "row": 5,
        }
      ],
      "MainColor":"#1CB5B4"
}
```

**Comment by mustafamsy** [comment] 2019-04-28 17:27
No update?

**Comment by minhcasi** [comment] 2019-04-29 01:21
Hi sorry, for the delay - our team has fixed most of the issues and we will release new version on next couple of day 

Could you share your website URL to double check on your reporting - thanks

**Comment by mustafamsy** [comment] 2019-05-10 19:42
when are you planning the update to be released?

**Comment by minhcasi** [comment] 2019-05-18 07:17
Duplicate of #596

**Closed by minhcasi** 2019-05-18 07:17 UTC
Labels: bug 🐛, help wanted 🙏
