### ISSUE TITLE
[FluxStore 1.5.9] - Code not building - multiple Compile errors with latest flutter version . 

### ISSUE THREAD

**Issue by siyashamsudeen** [inspireui/support#1596] opened 2019-12-12 21:51 UTC
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

Im not able to build the app when i downloaded the new version 1.5.9 source code - i tried many things but no luck . 

After that i tried to run the older versions which i have been using ( 1.5.8 & 1.5.9 ) , those versions are also not building . 

i tried with different flutter versions . yet no luck

the below is the error message im getting . This error message is coming on the latest stable flutter version - Flutter 1.12.13+hotfix.5 • channel stable •

i tried all those flutter clean , fultter stable channel etc . but no luck 

Compiler message:
../../../FlutterSDKNew/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-1.1.3/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
../../../FlutterSDKNew/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
Failed to build bundle.
Error launching application on iPhone 11 Pro Max.

2. Screenshots issues:

<img width="1425" alt="Screen Shot 2019-12-13 at 1 47 39 AM" src="https://user-images.githubusercontent.com/57159602/70751754-9272bd80-1d4a-11ea-9440-124eaf3eeccf.png">

3. Proof of my purchased:

<img width="614" alt="Screen Shot 2019-12-13 at 1 50 50 AM" src="https://user-images.githubusercontent.com/57159602/70751937-03b27080-1d4b-11ea-9f5f-a32e41456309.png">

3. Config files (optional)

**Comment by minhcasi** [comment] 2019-12-13 01:01
#1595 

Noted with checking as high priority - this could related to issue on the latest Flutter 1.12

**Comment by minhtruong315** [comment] 2019-12-13 01:47
https://github.com/inspireui/support/issues/1591#issuecomment-565261329
check this solution

**Comment by siyashamsudeen** [comment] 2019-12-13 21:52
im having new error on some of the theme files . this has not been coming before , suddenly after the new update it started. 

 Exception caught by widgets library ═══════════════════════════════════════════════════
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'


<img width="257" alt="Screen Shot 2019-12-14 at 1 51 16 AM" src="https://user-images.githubusercontent.com/57159602/70834688-6754a080-1e14-11ea-9acd-ae6318f38dfe.png">


<img width="1401" alt="Screen Shot 2019-12-14 at 1 51 07 AM" src="https://user-images.githubusercontent.com/57159602/70834687-66bc0a00-1e14-11ea-90ab-b1cf1bd3f833.png">

**Comment by siyashamsudeen** [comment] 2019-12-13 22:16
Im also getting the below error during checkout when i go to the shipping step . 
<img width="265" alt="Screen Shot 2019-12-14 at 2 04 19 AM" src="https://user-images.githubusercontent.com/57159602/70835808-b3edab00-1e17-11ea-8d91-1a33fc9a657d.png">


Please help to resolve this and the above errors asap.

**Comment by myothura** [comment] 2019-12-14 04:00
@siyashamsudeen  In your woocommerce shipping method. Check  how may shipping id and Change exactly ZoneIDShipping in FluxStore-woo/1.5.9/source/lib/common/config.dart . https://tppr.me/JVUJt
If you have shipping zone is 1,2 Type 1,2 . If you have shipping zone ID 1, . You should need to type only 1. If you type extra id or wrong id this error will be occur. Please try and reply.Thanks

**Comment by siyashamsudeen** [comment] 2019-12-14 06:35
Hello Thank you for your response . but you havent replied to the issues i posted just before the shipping error . 

1.  Im having new error on some of the theme files . this has not been coming before , suddenly after the new update it started.

Exception caught by widgets library ═══════════════════════════════════════════════════
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String'

<img width="1401" alt="Screen Shot 2019-12-14 at 1 51 07 AM" src="https://user-images.githubusercontent.com/57159602/70844579-e7065d80-1e5c-11ea-855f-17b7d63a1aa4.png">
<img width="257" alt="Screen Shot 2019-12-14 at 1 51 16 AM" src="https://user-images.githubusercontent.com/57159602/70844580-e79ef400-1e5c-11ea-9535-57d4f17cab2c.png">



2. Regarding the shipping error : i have only one shipping zone 

below is the screenshot from my woocommerce and config.dart

<img width="1262" alt="Screen Shot 2019-12-14 at 10 32 37 AM" src="https://user-images.githubusercontent.com/57159602/70844608-3ba9d880-1e5d-11ea-85b8-47d5e6b39d0a.png">

<img width="475" alt="Screen Shot 2019-12-14 at 10 34 24 AM" src="https://user-images.githubusercontent.com/57159602/70844618-55e3b680-1e5d-11ea-9f3f-e866bb14919c.png">


3.  The multi language is very confusing .

i dont understand the point of Theme Config.json in arabic version because when i change or switch to arabic language it doesnt change the home screen theme automatically.

When i changed the language to Arabic, the home screen products, category name and language doesnt change . when i go to the categories tabs and explicitly select a category then yes it loads the product in translated words.

When i do a hot restart of the app , Then app loads in the arabic config.json file .

this is very confusing and i dont understand how it exactly works. i tried your documentation but there is nothing much mentioned about these.

Please help as im having a very tough time with the app. i need to finish and launch the app asap

**Comment by minhcasi** [comment] 2019-12-14 11:09
@siyashamsudeen - try to update the app to the latest version 1.6, there is some bug fix and compatible with Flutter 1.12 - Detail changelog will be updated from https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f - thank you!

**Comment by minhcasi** [comment] 2019-12-15 06:42
Duplicate of #1611

**Closed by minhcasi** 2019-12-15 06:42 UTC
Labels: FluxStore, Use-For-Docs
