### ISSUE TITLE
Errors & Api problems

### ISSUE THREAD

**Issue by domawo** [inspireui/support#4939] opened 2020-09-09 06:40 UTC
Hello, I can’t get it to work.

1st problem: (APP BUILDER)

API error, but everything is set correctly. The .htaccess file has also been adapted.
But there are always errors in the kit.

The app builder does not seem to recognize my domain during the check.  My domain has umlauts in the name.  (ü) That seems to be causing problems.

2nd problem: (IOS XCODE)

The following red error message appears in xCode. (Build failed)

Showing recent messages /Users/.......de/Downloads/FluxStore-vendor-1.7.7/source/ios/Flutter/Debug.xcconfig:2: could not find included file ‘Generated.xcconfig’ in search paths

What am I doing wrong? Regards

**Comment by minhcasi** [comment] 2020-09-09 12:50
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-09-10 02:00
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-09-10 02:00 UTC
Labels: needs-more-info
