### ISSUE TITLE
#4812

### ISSUE THREAD

**Issue by Gag1011** [inspireui/support#4872] opened 2020-09-04 07:50 UTC
**_Step 1 (require): describe detail issues & screenshots_**
Please see above closed issue number. 
This issue is not closed. Please advise on how to fix the logins?

Both google and facebook logins, as well as the email login works now but does not redirect the user to the app home screen
on successful login.
Also there is an issue with the push notifications not displaying in app.
The settings screen has had no tabs removed or edited except for one or two of the titles, which do not reflect the changes and the others still display Data Empty. 
Do you need to see any of my android folders to determine what the problem is?

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

#4812 

Thank you so much for your time 😊

**Comment by minhcasi** [comment] 2020-09-04 12:03
@Gag1011 - could you share some screenshot issues? Did you customize the app or testing on the default download package?

**Comment by Gag1011** [comment] 2020-09-04 12:30
The app has been customised and you helped us publish it to the play store a few days ago.
![After Trying Fb Login](https://user-images.githubusercontent.com/67577702/92239023-9b985180-eeba-11ea-9553-410409d59701.jpg)
![After Trying Google Login](https://user-images.githubusercontent.com/67577702/92239027-9dfaab80-eeba-11ea-8bc2-33805ae96785.jpg)
![After username login](https://user-images.githubusercontent.com/67577702/92239028-9e934200-eeba-11ea-897e-ec31861f32a7.jpg)
![Before Login](https://user-images.githubusercontent.com/67577702/92239032-9e934200-eeba-11ea-8c4b-529c099feecf.jpg)
![Logged in with google](https://user-images.githubusercontent.com/67577702/92239033-9f2bd880-eeba-11ea-8890-6b6cdd64929f.jpg)
![Trying username login](https://user-images.githubusercontent.com/67577702/92239035-9fc46f00-eeba-11ea-8e4f-949084f95230.jpg)


Please note that when there has been a successful login attempt it stays at this screen
![Hanging after successful login attempt](https://user-images.githubusercontent.com/67577702/92239151-cedae080-eeba-11ea-87d2-7db792a60b3a.jpg)

the user must navigate back from the above screen and then to the settings screen to see that they have logged in
![user must navigate to this page manually to see if they are logged in](https://user-images.githubusercontent.com/67577702/92239288-03e73300-eebb-11ea-84b9-3b8b87048100.jpg)

All of the above settings screen, screen shots show the 'Data Empty' issue.

**Comment by minhcasi** [comment] 2020-09-06 04:31
@Gag1011 - please help try your best to check the issues from the customization as it is not included from our support scope for the Regular License - https://inspireui.com/support-policies

The facebook login issue - https://tppr.me/2tzYa could be fixed by copy the hash and past to your Facebook Development Admin - pls refer to this guide https://medium.com/@inspireui/setup-facebook-login-for-flutter-apps-4e7bd031479d

**Comment by Gag1011** [comment] 2020-09-07 07:43
Minh i mean I have only customised the cosmetics. the Config-en.json file. So I am running the app without custom Developement.
Does that mean you will be able to assist?

I believe I have fixed the Fb login feature, but as stated before, it is not redirecting the customer to the home screen of the app. this is the same for Google login and normal login by email and username.

**Comment by minhcasi** [comment] 2020-09-08 11:00
@Gag1011 - actually it does not include with our support scope for the regular as well

But could you share the config file `Config-en.json`? - we will help to quickly check the root cause

**Comment by Gag1011** [comment] 2020-09-08 12:10
[config_en.zip](https://github.com/inspireui/support/files/5188158/config_en.zip)

Thank you, I hope you can assist. I have had nothing but great service and a great product from you guys.

**Comment by minhcasi** [comment] 2020-09-10 03:12
@Gag1011 - the config is config correct but we could not figure out why your setting screen showing Data empty, could i know if you have customized that screen?

**Comment by Gag1011** [comment] 2020-09-10 05:11
Hey minh

I havent edited the settings screen at all. I would like to change the
names of some of the tabs but thats all

**Comment by minhcasi** [comment] 2020-09-10 08:19
https://docs.inspireui.com/fluxstore/multi-language/#how-to-add-or-update-language - you need to update via .arb file any regenerate the language file

**Comment by minhcasi** [comment] 2020-09-11 04:20
i mean if you would like to change the Text label it requires to change via .arb file from the guide, or you could use hard code `Text('Your Label Name')`

**Comment by Gag1011** [comment] 2020-09-11 06:51
Alright I understand I think. I do have another question for you though.

 

The company is not making any money from our current business model. We want to lose the multivendor platform and turn it back into a straight up woocommerce store. Is this possible without breaking the published app?

 

If not, would it be possible to change our license to the woocommerce store app or are we going to have to pay another $79?

 

Thanks for your assistance,

Gareth Winchester

**Comment by minhcasi** [comment] 2020-09-12 09:25
Gareth - there is no problem with the License when you publish the app 👍

**Comment by Gag1011** [comment] 2020-09-12 09:43
Awesome so it won’t break the app when I remove the WCFM Plugins from the website? Just run the m-store regenerate images function and build a new app bundle?

**Comment by minhcasi** [comment] 2020-09-13 03:03
Please note that the `WCFM plugin` only compatible with the fluxstore multi-vendor to support to build marketplace. 

If you are not installed vendor plugins, try to use Fluxstore Woocommerce or Pro version

**Comment by Gag1011** [comment] 2020-09-13 06:02
I have the wcfm plugins installed. We would like to remove them and use the
normal woocommerce. So no more multi vendor.

Am I able to download the standard flux store for woocommerce?  Do I need
to buy that one too?

**Comment by minhcasi** [comment] 2020-09-15 08:03
Yes, you could use the Fluxstore Pro or WooCommerce version, as this product uses the default WooCommerce API that suitable for single Vendor/Store (the Vendor version is used API from Dokan/WCFM)

**Comment by Gag1011** [comment] 2020-09-15 08:45
Alright great thank you for clearing that up for me.

**Comment by Gag1011** [comment] 2020-09-15 13:23
So tell me, must I pay to download the woocommerce version?

**Comment by minhcasi** [comment] 2020-09-16 08:18
@Gag1011 - you could use free woocommerce plugin and follow our config to setup the pre-config website - https://docs.inspireui.com/fluxstore/woocommerce-setup/#1-website-integration

**Comment by Gag1011** [comment] 2020-09-16 08:28
I already have woocommerce installed on the corner store website. I need to
know if I must buy your $79.00 woocommerce fluxstore app template? Or can I
just swap from the wcfm fluxstore app template.

**Comment by Gag1011** [comment] 2020-09-21 10:52
Any feed back on this Minh?

**Comment by Gag1011** [comment] 2020-09-21 10:57
Can you change my licence so I can download the flux-store for woocommerce app template?

**Comment by minhcasi** [comment] 2020-09-23 12:12
Sorry we are only offering to exchange the product that purchases within 30 days - https://inspireui.com/support-policies/

Please move to our new ticket support http://support.inspireui.com/

**Closed by minhcasi** 2020-09-23 12:12 UTC
Labels: FluxstoreMV
