### ISSUE TITLE
Webview Checkout issue

### ISSUE THREAD

**Issue by jvsamoa** [inspireui/support#5027] opened 2020-09-16 20:15 UTC
Hi team, 
All the best wishes to you!

Go back, I update my checkout options to according your recommendations but my issue is persistent
This is my log:

*** My Onboarding array is empty [] on the Onboarding page, (I am using the latest version)
****My default language is ES 

I/flutter ( 5929): [2020-09-16 19:46:32.109379Z][Fluxstore][Cart] build
I/flutter ( 5929): [2020-09-16 19:46:37.102761Z][Fluxstore][wocommerce_api][16:46:37.102504] getAsync END [endPoint:coupons] url:coupons
E/flutter ( 5929): [ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter ( 5929): Receiver: null
E/flutter ( 5929): Tried calling: []("es")
E/flutter ( 5929): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter ( 5929): #1      WooCommerce.getCheckoutUrl (package:fstore/services/woo_commerce.dart:1075:41)
E/flutter ( 5929): <asynchronous suspension>
E/flutter ( 5929): #2      Services.getCheckoutUrl (package:fstore/services/index.dart:371:23)
E/flutter ( 5929): #3      WooWidget.doCheckout (package:fstore/widgets/frameworks/woocommerce/index.dart:78:37)
E/flutter ( 5929): #4      _MyCartState.doCheckout (package:fstore/screens/cart/my_cart.dart:351:29)
E/flutter ( 5929): #5      _MyCartState.onCheckout (package:fstore/screens/cart/my_cart.dart:342:7)
E/flutter ( 5929): #6      _MyCartState.build.<anonymous closure>.<anonymous closure> (package:fstore/screens/cart/my_cart.dart:255:93)
E/flutter ( 5929): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter ( 5929): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter ( 5929): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter ( 5929): #10     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter ( 5929): #11     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter ( 5929): #12     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter ( 5929): #13     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter ( 5929): #14     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter ( 5929): #15     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter ( 5929): #16     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter ( 5929): #17     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter ( 5929): #18     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter ( 5929): #19     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:220:19)
E/flutter ( 5929): #20     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
E/flutter ( 5929): #21     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:263:11)
E/flutter ( 5929): #22     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:157:7)
E/flutter ( 5929): #23     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:103:7)
E/flutter ( 5929): #24     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:87:7)
E/flutter ( 5929): #25     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter ( 5929): #26     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 5929): #27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 5929): #28     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter ( 5929): #29     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter ( 5929):

**Comment by minhcasi** [comment] 2020-09-17 01:39
Duplicate of #5006 - pls help to raise new comments to our new ticket support https://support.inspireui.com - thank you!

**Closed by minhcasi** 2020-09-17 01:39 UTC
