### ISSUE TITLE
Error in failed assertion

### ISSUE THREAD

**Issue by hackzie** [inspireui/support#3411] opened 2020-05-26 08:07 UTC
I dont know why is this error coming. I uploaded the same config in website and pased on config_en.json file of source code.

![ice_screenshot_20200526-131038](https://user-images.githubusercontent.com/35571313/82876147-f3d3c500-9f55-11ea-9ac0-d0a411cb4f92.png)

**Comment by minhcasi** [comment] 2020-05-26 08:11
Duplicate of #3410

**Closed by minhcasi** 2020-05-26 08:11 UTC
