### ISSUE TITLE
There is no woocommerce folder in lib / example

### ISSUE THREAD

**Issue by AbimaelASilva** [inspireui/support#3915] opened 2020-06-26 00:39 UTC
Good night. I was following the tutorial step by step:
https://www.youtube.com/watch?time_continue=22&v=CEyfZmzBMTw&feature=emb_logo

I got all the previous steps to set up wordpress on my website: vamosascompras.com.br.

But in the minute

16:16
For me there is no woocommerce folder in lib / example

I stopped the tutorial because I started getting this error when I used the flutter run:

lib/screens/home/onboard_screen.dart:24:34: Error: Getter not found: 'kLoginSetting'.
  final isRequiredLogin = config.kLoginSetting['IsRequiredLogin'];

**Comment by ameenbadri7** [comment] 2020-06-26 01:23
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-06-28 03:19
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-06-28 03:19 UTC
Labels: needs-more-info

**Comment by daboujey** [comment] 2020-07-09 08:22
Você é brasileiro, podemos trocar uma ideia sobre o app se quiser ... meu email jean@insaith.com.br
