### ISSUE TITLE
BITCODE BUNDLE COULD NOT BE GENERATED

### ISSUE THREAD

**Issue by miskayapp** [inspireui/support#3427] opened 2020-05-27 00:23 UTC
![Screen Shot 2020-05-24 at 10 54 32 PM](https://user-images.githubusercontent.com/64660378/82962613-991f8500-9fb8-11ea-98d4-d52cc5e5cc16.png)
[Build target webview_flutter_2020-05-27T00-54-07.txt](https://github.com/inspireui/support/files/4685695/Build.target.webview_flutter_2020-05-27T00-54-07.txt)
PLEASE HELP!!! VERY URGENT, YOUR FIX ARE NOT WORKING

**Comment by minhcasi** [comment] 2020-05-27 01:40
try to read this guide carefully pls - https://docs.inspireui.com/fluxstore/delivery/

**Comment by minhcasi** [comment] 2020-05-27 01:46
Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by miskayapp** [comment] 2020-05-27 07:41
must i add .flutter after my bundle id?

**Comment by minhcasi** [comment] 2020-05-27 07:47
No, example bundle id: com.your-company-name.your-app-name

You could try to zip the source to google drive and share to `support@inspireui.com` - we will help for quick checking

**Comment by miskayapp** [comment] 2020-05-27 16:42
i have shared them.

miskay - error  "This bundle is invalid - The Info.plist file is missing or
could not be parsed"
miskay c1 error - cant generate bitcode

please help, my client is on my neck, and i might end up refunding to them.

**Comment by miskayapp** [comment] 2020-05-27 16:43
bundle id - com.miskaybout.miskay

**Comment by minhcasi** [comment] 2020-05-28 02:42
@miskayapp - we got your files, but which project needs to be checked? Thanks

<img width="398" alt="Screen Shot 2020-05-28 at 09 41 43" src="https://user-images.githubusercontent.com/1459805/83092413-729c3f80-a0c7-11ea-9aa8-070f844acc50.png">

**Comment by miskayapp** [comment] 2020-05-28 09:43
myapp c1

error, invalid bundle id, when i try to upload to testflight

**Comment by minhcasi** [comment] 2020-05-29 03:11
we have some suggestion to fix your app issues: 

1. update bitcode to 'YES' - https://tppr.me/Ppfuo
2. try to rename from `com.miskayboutique.miskay` to `com.boutique.miskay`
3. try to update to latest `1.7.4` or `1.7.5` on gitlab
4. make sure to run `flutter release ios` before open XCode to `archive` the app

let us know your checking

**Comment by miskayapp** [comment] 2020-05-29 22:51
can you check miskayapp, its the latest version, but when i try to archive,
it says cant generate bitcode, but i have enabled bitcode.

**Comment by minhcasi** [comment] 2020-06-03 08:47
@miskayapp - could i check if you could release the app so far? Thanks

**Comment by miskayapp** [comment] 2020-06-04 06:43
albert-og:miskay Albert$ flutter release ios
Could not find a command named "release".


Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.

**Comment by minhcasi** [comment] 2020-06-04 13:00
Duplicate of #3587

**Closed by minhcasi** 2020-06-04 13:00 UTC
Labels: FluxStore, common-release
