### ISSUE TITLE
upload the config_xx.json from the common folder

### ISSUE THREAD

**Issue by hkhanal** [inspireui/support#4919] opened 2020-09-07 18:01 UTC
I could not find  config_xx.json file in any folder.  Thank you for help in advance!!

**Comment by minhcasi** [comment] 2020-09-08 08:53
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-09-09 02:16
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-09-09 02:16 UTC
Labels: needs-more-info

**Comment by hkhanal** [comment] 2020-09-12 21:26
I found it
