### ISSUE TITLE
[EvaStore] - Shipping method is missing in checkout view 

### ISSUE THREAD

**Issue by alisa140** [inspireui/support#1379] opened 2019-11-13 08:34 UTC
1. My issue: The Shipping Method in version 1.1.4 has disappeared from the checkout view. You cannot progress to payement due to an alert "Please select shipping method" 

2. Screenshots:
https://tppr.me/eQRqA
https://tppr.me/Tdq1E
3. My screenshot of the purchase product or my comment:
https://tppr.me/7dQEu

3. Config files (optional)
Not required as the issue is in the baseline.

**Comment by minhcasi** [comment] 2019-11-14 02:59
Duplicate of #1378 - pls note to this ticket

**Closed by minhcasi** 2019-11-14 02:59 UTC
Labels: EvaStore, question ❓
