### ISSUE TITLE
Fluxstore Pro - FAILURE: Build failed with an exception

### ISSUE THREAD

**Issue by jahnkit** [inspireui/support#2396] opened 2020-03-20 01:01 UTC
Hi,
When I try to launch the application with Android Studio I receive this error every time, I still followed the video.
Can you help me please thank you

Issue:
![ISSUE](https://user-images.githubusercontent.com/23610159/77128178-70768e80-6a4f-11ea-8740-56522c95484f.PNG)

Proof of my purchased:
![purchase code](https://user-images.githubusercontent.com/23610159/77128186-78363300-6a4f-11ea-9fe9-3f6980525e27.PNG)

Config files (required)
What is the configuration file?

**Comment by minhcasi** [comment] 2020-03-20 02:45
Duplicate of #2395

**Closed by minhcasi** 2020-03-20 02:45 UTC
Labels: FluxStore, question ❓
