### ISSUE TITLE
Problem in facebook login " User logged in as different Facebook user.” error

### ISSUE THREAD

**Issue by hkhanal** [inspireui/support#5035] opened 2020-09-19 17:09 UTC
I set up Facebook login as described in documentation on  Multi-vendor store App.  But got error "“User logged in as different Facebook user.” error". Any quick solution is much appreciated.

Thank you.

**Comment by minhcasi** [comment] 2020-09-20 11:20
Duplicate of #5006

**Closed by minhcasi** 2020-09-20 11:20 UTC
