### ISSUE TITLE
sorry you cannot list resources

### ISSUE THREAD

**Issue by wolverineee92** [inspireui/support#4001] opened 2020-07-01 09:21 UTC
**_Step 1 (require): describe detail issues & screenshots_**
![Screenshot at Jul 01 14-58-04](https://user-images.githubusercontent.com/67648501/86227092-32d6e500-bbaa-11ea-9eab-3afb5726be52.png)
![proof](https://user-images.githubusercontent.com/67648501/86227103-35d1d580-bbaa-11ea-9646-82855944b268.png)

mstore expo

**Comment by wolverineee92** [comment] 2020-07-01 09:21
please its urgent

**Comment by ameenbadri7** [comment] 2020-07-01 11:45
@wolverineee92

Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

if you submit the form tell us to double-check it again?

**Comment by wolverineee92** [comment] 2020-07-01 11:50
hello

**Comment by wolverineee92** [comment] 2020-07-01 11:52
I submitted the all form you want....please response quickly..very urgently needed

**Comment by wolverineee92** [comment] 2020-07-01 11:55
Mstore latest version 
react-native latest version 
issue detail - sorry you cannot list resources 
see the screenshot

**Comment by minhcasi** [comment] 2020-07-02 01:03
Duplicate of #3987

**Closed by minhcasi** 2020-07-02 01:03 UTC
