### ISSUE TITLE
[Fluxstore 1.5] - Search with Magento issues

### ISSUE THREAD

**Issue by DrChrispoper** [inspireui/support#1125] opened 2019-09-27 17:48 UTC
Flowing https://github.com/inspireui/support/issues/1123 I decided to test the search function, and have seen a few issues.
I am using Fluxstore 1.5 with Magento.

Issue 1. An exception is thrown if no results come back from the search. 
In lib/services/magento.dart
`Future<List<Product>> searchProducts({name, page}) async {`
If I do a search and no products are found, the body of the response is "" not at the least "items:{}" or something similar. Cause this line to raise an error:
`for (var item in convert.jsonDecode(response.body)["items"]) {`

This seems more like an issue on the Magento extension side not returning the correct empty list of items.

Issue 2. Searching for a product with no categories.
In lib/services/magento.dart
`Product parseProductFromJson(item) {`
If a do a search and one of the products do not have a category. An exception is raised here:
`product.categoryId = int.parse(categoryIds[0]);`

One option would be to fix it on the extension side and not return items that don't have a category.
Or add something as simple as:
```
    if (categoryIds.length > 0) {
      product.categoryId = int.parse(categoryIds[0]);
    }
```
However you best prefer to code it.

Thanks.

**Comment by minhcasi** [comment] 2019-09-28 12:20
@DrChrispoper  - thank you for the detail reporting, we will investigate and get back you soon

**Comment by minhtruong315** [comment] 2019-10-01 10:32
@DrChrispoper can you send me config.dart and config.json via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/1125

**Comment by DrChrispoper** [comment] 2019-10-01 10:40
Thanks. I've just sent it.

**Comment by minhcasi** [comment] 2019-10-01 12:59
Duplicate of #1115

**Closed by minhcasi** 2019-10-01 12:59 UTC
Labels: question ❓
