### ISSUE TITLE
Still to fix in the version of 3.8.0

### ISSUE THREAD

**Issue by hakihosting** [inspireui/support#595] opened 2019-05-17 12:01 UTC
Hello i have installed the new version but i see , these errors still bug in the version : 3.8.0

- When i insert a code promo in lower case it works ,but if i insert in Uppercase : CODE promo is invalid.

- Stock problem with variations synching

**Comment by minhcasi** [comment] 2019-05-18 07:07
Duplicate of #591

**Closed by minhcasi** 2019-05-18 07:07 UTC
