### ISSUE TITLE
Unable to Change the Bundle id, Project name

### ISSUE THREAD

**Issue by Shopyloot** [inspireui/support#3980] opened 2020-06-29 23:42 UTC
Pirchased Fluxstore Multi Vendor - Flutter E-commerce Full App and on the latest version 

when i followed the video guide at https://docs.inspireui.com/fluxstore/delivery-android/ at section 1. Update name/icon, Bundle ID. It doesn't happens as in the video for the first step when i try to rename working folder, it says no response when i use the same code in the terminal, but in the finder it gives me new folders like old file with the sub source file  and the new one with name i have created. i was struck here, what is the next step should i change the bundle id here in the old folder or in the new folder ??

**Comment by ameenbadri7** [comment] 2020-06-29 23:56
@Shopyloot
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by Shopyloot** [comment] 2020-06-30 19:24
hello can i have any update regarding this?

Step.1 : Tried to change the package name https://prnt.sc/t9crh7
Step 2: In terminal have entered the following command bash tools/change-bundleid.sh
Step 3: here is the result i got > https://prnt.sc/t9ct5n

**Comment by ameenbadri7** [comment] 2020-07-01 00:52
Did you double check our guide 
https://docs.inspireui.com/fluxstore/delivery-android/

You can do flutter clean to remove any caches douplicate and then search manually for the old name and replace it with the new name. 
Also rename the kotlin folder… 

If you still have problems you can upload your project to gitlab and let us see it and fix it for you. 
https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6?source=---------4------------------

Thank you.

**Comment by ameenbadri7** [comment] 2020-07-03 00:12
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved
 - thank you for your time!

**Closed** 2020-07-03 00:12 UTC
Labels: FluxstoreMV
