### ISSUE TITLE
Problems with payments

### ISSUE THREAD

**Issue by spconde** [inspireui/support#4422] opened 2020-07-30 12:30 UTC
Will you have any tutorial to use the payment methods installed in woocomerce?

**Comment by ameenbadri7** [comment] 2020-07-30 17:47
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by ameenbadri7** [comment] 2020-08-01 02:25
I'm sorry to close this ticket as there is no response or active conversation. 

Please help to create a new one and link to this ticket if the problem is not solved. 

- Thank you for your time!

**Closed by ameenbadri7** 2020-08-01 02:25 UTC
Labels: needs-more-info
