### ISSUE TITLE
In checkout page select address is not showing saved address magento2

### ISSUE THREAD

**Issue by subhquad** [inspireui/support#3549] opened 2020-06-02 12:42 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Go to check out and click on select address and its not showing saved addresses.
+ Product & version: Fluxstore Pro 1.7.3
+ Flutter (or React Native) version:
+ Testing Device/Simulator:  iPhone
+ Screenshot issues (drag the file to attach here): 
<img width="361" alt="Screenshot 2020-06-02 at 13 40 50" src="https://user-images.githubusercontent.com/10830054/83521207-cf886300-a4d6-11ea-88a5-412fcbe8d7d5.png">

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

80f2ca3f-3e8f-43cd-97ba-9dd311d5fb75

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment] 2020-06-03 02:07
Duplicate of #3548 - please help to raise only one ticket for your all issue, also make sure to update to the latest Fluxstore version `1.7.4` - thank you!

**Closed by minhcasi** 2020-06-03 02:07 UTC
