### ISSUE TITLE
[Fluxstore - Woo] - Update 1.6.4 All IMPORTANT ERRORS!

### ISSUE THREAD

**Issue by sketchuprzr** [inspireui/support#2227] opened 2020-02-27 07:43 UTC
**_I will report the details very soon and share them here._**

**Comment by sketchuprzr** [comment] 2020-02-27 08:21
@minhcasi 
@zahmed84
@minhtruong315
@inspireui

### Problem 1:
The category issue I mentioned earlier;
The application did not capture all of the categories on my website because the website only outputs "100" content on each page with the api. It outputs 4 pages in total.
On the other hand, you attract only 1 of these pages to the application. I wrote the solution for this before, but you did not bring it in the update. I also wanted to apply this after the update, but it didn't work.

You can check the topic here:  https://github.com/inspireui/support/issues/1907#issuecomment-578175124

### Problem 2:
You say you have solved the Stock Problem. Nothing has changed! The app still allows for more than the number of stocks. There is "24" in a product system, and I can buy "30" from this product. It shouldn't be "AND THAT IS VERY IMPORTANT, I CAN'T SELL THE STOCK THAT I DON'T HAVE"

You can check this out here: https://github.com/inspireui/support/issues/2014#issue-560045392

### Problem 3:
You say that you have made arrangements for maximum stock sales. This edit you made is very erroneous. What you do;
You want us to enter a valid value for all products. For example, I entered "100" values. And this is true for all products. This is wrong!
Online shopping stores often make campaigns, and they limit the sale of campaign products so that everyone can benefit from these campaigns. For example ;
Anyone can buy 1 piece of product A,
Anyone can buy 2 products from product B,
Anyone can take C as much as he wants.
All three can apply simultaneously.

But what you do is;
The value of "maxAllowQuantity" entered changes the list that is valid in "quantity" in the product page. But this is not a working feature, because when I click the "add to cart" button many times, "20" is added to the basket every time I click, even if I select the most "20" option in the list. As a result, "maxAllowQuantity" at the "20" limit doesn't work because I might have added thousands in the basket.

Also, all this feature is wrong because even if this works, this feature cannot be applied to all products. This value is a variable value. And I shared a post on how to pull it off the website.

In short, this feature does not work.

You can browse the topic here: https://github.com/inspireui/support/issues/2014#issue-560045392

### Problem 4:

You said that you have added a minimum order amount system for the free shipping option. This doesn't work either. You also set this value as "MinFreeShippingCost" in the application.
This is also wrong because this is a variable value. The free shipping option does not always remain the same. For example, we make this value "20" every week on "Sunday", and on the remaining days it is defined as "70". So this is about the campaigns in the world of Shopping.
This is very important because people shop for the free shipping option.
In short, this feature does not work.

You can browse the topic here: https://github.com/inspireui/support/issues/1922#issue-554829009


--------------------------------------------

### These are the problems I can report right now.
### **And these Problems "VERY IMPORTANT" problems for the shopping world!**

Except those;
I request you to make a more detailed explanation about a video or "step by step" related to the use of Multi Language.
For example, what should someone do if they want to use only one language in the application and make it a native language?

Finally;
Will you solve these problems? How long will this take if you will solve it?
I have been waiting for you for about 1 month and at the end of 1 month I could not reach any conclusions. There are users who have problems like me.

My request from you, Do not close this issue until these problems are resolved. When I look through the analysis, I see dozens of people reading the subject. Obviously there are people who have a lot of problems.

I wish conveniences.

_"suggestion: you can withdraw this update (1.6.4) because it makes no sense."_

**Comment by sketchuprzr** [comment] 2020-02-28 18:14
Nobody here?

**Comment by minhcasi** [comment] 2020-02-29 04:16
@sketchuprzr - I remember to reply on this ticket but not sure it was removed by Github. 

Our team is working hard on your all feedbacks and keep the upgrade, please bear with us with the upgrade on the next couple of days for the fixing - thank you for the detail explanation :)

**Comment by sketchuprzr** [comment] 2020-03-04 18:06
Any progress?

**Comment by sketchuprzr** [comment] 2020-03-05 13:09
I've been waiting for this problem for a very long time.
(For about 2 months)

And still unresolved.
The two most important problems are;

1) The app allows more sales than the number of stocks

2) Maximum sales quantity feature not working
(https://woocommerce.com/products/minmax-quantities/)

**Comment by minhcasi** [comment] 2020-03-06 07:37
@sketchuprzr - we are focus on these issues and will update to GitLab the latest fix to resolve these 2 issues, will confirm when it is ready - thank you!

**Comment by papaya1986** [comment] 2020-03-07 22:25
these issues too

1.coupon code not working
2.shipping also

**Comment by sketchuprzr** [comment] 2020-03-07 23:21
> these issues too
> 
> 1.coupon code not working
> 2.shipping also

coupon code is working. you just have to try it in lowercase

**Comment by sketchuprzr** [comment] 2020-03-11 07:08
### Problem 1: [Resolved]
https://github.com/inspireui/support/issues/1907#issuecomment-578175124

Reminding:
It's been 5 days. Neither incoming nor outgoing. It's been 2.5 months in total.
[ Problem 2 - 3 - 4 ] problems continue.
Also there are more problems .. I will add the report of the problem about flare animation soon.

**Comment by minhcasi** [comment] 2020-03-11 10:55
@sketchuprzr  - new release 1.6.5 will be released on this week (also include this fixed) - thanks

**Comment by philipvu30** [comment] 2020-03-12 02:24
Hi @sketchuprzr ,
Your issues have been fixed and they will be included along with the "coupon uppercase lowercase problem" in the next update. 

Thank you for taking the time to help us. We appreciate all of your suggestions and improvement on our product.

Wish you all the best. :)

**Comment by sketchuprzr** [comment] 2020-03-12 10:02
> Hi @sketchuprzr ,
> Your issues have been fixed and they will be included along with the "coupon uppercase lowercase problem" in the next update.
> 
> Thank you for taking the time to help us. We appreciate all of your suggestions and improvement on our product.
> 
> Wish you all the best. :)

Hi @philipvu30 
Where can I find the resolved version of the problems?

Thank you.

**Comment by philipvu30** [comment] 2020-03-12 10:05
Hi @sketchuprzr ,

We will update the new version in the next few days. Thank you for your patience.

**Comment by minhcasi** [comment] 2020-03-15 12:00
@sketchuprzr - please download the latest release Fluxstore 1.6.5 release 

We also note the detail changelogs from this blog -https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f 

Let us know if you have any feedback - thank you!

**Comment by sketchuprzr** [comment] 2020-03-15 12:35
Hello.

First of all, thank you very much.
Some problems have been fixed and aesthetically beautiful.
But I still have to say that some problems are not gone.

### (SOLVED)
1) First, the Stock problem has been fixed.
Now, more than the stock I have, people cannot order.

### (NOT SOLVED)
2) The "Minimum quantity" Problem still persists. Because you misunderstood the event.
Your edit becomes a valid value for all products.
But this is not the case, in some products this is active, in some products this is not active. We have managed to implement this value for you. With Api, we were able to pull the values ​​reflected in json into practice.
You would only integrate this into the application as a limitation.

![image](https://user-images.githubusercontent.com/60021696/76700689-239b5c80-66cb-11ea-978c-fdc2d9ad70e0.png)


The value you show us in the picture below has been a viable option for all products. This feature can also be, it's a good thing. But that's not what I mean.

![image](https://user-images.githubusercontent.com/60021696/76700700-3dd53a80-66cb-11ea-9c18-a637babfb882.png)

-----------------------------------

![image](https://user-images.githubusercontent.com/60021696/76700709-55acbe80-66cb-11ea-82fa-9a143ed8f573.png)

Just like the values ​​we entered in this picture. This is a feature offered by woocommerce itself.
During the campaign periods, we distribute products equally to everyone so that everyone can benefit. So this is important.

### (NOT SOLVED)
4) The minimum order amount feature for the free shipping option still doesn't work. Although I have edited the value in the config file, this does not work. All shipping options are visible.

For example, as shown in the picture, I entered a minimum amount of "75". And it didn't work.

![image](https://user-images.githubusercontent.com/60021696/76700921-6e1dd880-66cd-11ea-9e67-b6acfa5f8f3f.png)

![sjppng](https://user-images.githubusercontent.com/60021696/76700994-03b96800-66ce-11ea-9e07-2d05a99cc01e.gif)

### (NOT SOLVED)
5) the category problem continues. The application cannot load all categories and products on our website.

![kat](https://user-images.githubusercontent.com/60021696/76701180-d968aa00-66cf-11ea-8a21-02a6547dca23.gif)

I had solved the category problem with this code before. But when I use this code in 1.6.5 version, the categories do not come despite the categories.

![image](https://user-images.githubusercontent.com/60021696/76701419-061dc100-66d2-11ea-829d-be691efb8089.png)

![urn](https://user-images.githubusercontent.com/60021696/76701455-5e54c300-66d2-11ea-8479-b9ed35d5cf56.gif)

**Comment by minhcasi** [comment] 2020-03-16 03:49
@sketchuprzr - thank you for the feedbacks

regarding to the #2 issue, please check the guide from our blog - https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f the item 15.4 and change the meta_data to your own plugins - the could be caused by using difference min/max plugins so that the app could not pick the right value on your sites. On next release, we will apply this logic into the Dropdown box quantity 

We will check the Free Shipping cost issue.

**Comment by sketchuprzr** [comment] 2020-03-16 09:01
maximum, minimum is working now. Thank you very much for that. It is really beautiful.

I'm having a problem with coupons right now, I think. I will try to solve it. I will let you know if I can't solve it.

By the way, the filters (featured, on sale, date) you add in 1.6.5 version prevent all products from being listed on the screen. The (All) filter needs to be added there. And it should be (All) by default. I invalidated these filters in my own app because they don't show all of the products.

Those who wish can change their maximum and minimum status like the metadata code below.

![image](https://user-images.githubusercontent.com/60021696/76739591-79c8d800-677d-11ea-9aad-7d7663d1113a.png)

**Comment by minhcasi** [comment] 2020-03-17 02:46
@sketchuprzr - could you share the max/min plugin that you are using? I will update the document for these features - thank you!

**Comment by minhcasi** [comment] 2020-03-17 02:52
@sketchuprzr - would you mind to give us some rating/feedback to http://codecayon.net/downloads that would encourage the team to keep update more features, thank you for helping us with the great suggestion so far - very best!

**Comment by minhcasi** [comment] 2020-03-18 13:11
@sketchuprzr - pls move your new issues to #2376 - we will update the patching for 1.6.5 in this week - thank you!

**Closed by minhcasi** 2020-03-18 13:11 UTC
Labels: FluxStore, Use-For-Docs
