### ISSUE TITLE
[MStore] Dark Theme and products order issues in 3.8

### ISSUE THREAD

**Issue by naldekhel** [inspireui/support#598] opened 2019-05-18 10:49 UTC
Product: [MStore]
Your Purchased Code: e5717440-ab94-463d-88b1-54f99f460276

Hi there, 

Dark theme is not working on the new update 3.8. Also products order on categories pages and home screen is showing ( Oldest -> Newest ) not like 3.7.2 which used to show ( Newest -> Oldest ). 

Please consider fixing this issue **ASAP**

Thanks

**Comment by minhcasi** [comment] 2019-05-19 07:55
Hi, could you attach the screenshot issue - thanks

**Comment by minhcasi** [comment] 2019-05-19 07:58
Duplicate of #599

**Closed by minhcasi** 2019-05-19 07:58 UTC
