### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by dragooninasia** [inspireui/support#3807] opened 2020-06-19 15:03 UTC
**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment] 2020-06-20 03:41
Duplicate of #3783

**Closed by minhcasi** 2020-06-20 03:41 UTC
