### ISSUE TITLE
Log In Problem

### ISSUE THREAD

**Issue by maurovanschaik** [inspireui/support#4089] opened 2020-07-06 18:32 UTC
Hello!
This is a new conversation about the next ticket: https://github.com/inspireui/support/issues/3994

We have a problem with the log in in the app.

When I register as an user in the web (Listeo web), and I try to log in in the app, there appears the error “Flutter_user” (Exception: Unknown controller), like in the image.

![](https://user-images.githubusercontent.com/67668916/86195108-915a7f80-bb26-11ea-988e-daa51b9cc9e9.jpg)

We have already synchronized the app with de hosting.

We await your answer, regards!

**Comment by ameenbadri7** [comment] 2020-07-06 21:04
@maurovanschaik  you have to verify your self first please.

Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-07-07 02:22
@maurovanschaik could you know if you have activated this plugin - https://vi.wordpress.org/plugins/listapp-mobile-manager/

**Comment by minhcasi** [comment] 2020-07-09 02:29
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-09 02:29 UTC
Labels: FluxListing, common-integration

**Comment by maurovanschaik** [comment] 2020-08-08 13:59
Hi! We have another problem with some failures: 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\Usuario\Documents\FluxStore-listing 1.4.2-20200714T041041Z-001\FluxStore-listing 1.4.2\source\android\app\src\main\AndroidManifest.xml:12:5-72:19: AAPT: error: resource mipmap/launcher_icon (aka com.inspireui.fluxlisting:mipmap/launcher_icon) not found.

     C:\Users\Usuario\Documents\FluxStore-listing 1.4.2-20200714T041041Z-001\FluxStore-listing 1.4.2\source\android\app\src\main\AndroidManifest.xml:17:9-56:20: AAPT: error: resource style/LaunchTheme (aka com.inspireui.fluxlisting:style/LaunchTheme) not found.

     C:\Users\Usuario\Documents\FluxStore-listing 1.4.2-20200714T041041Z-001\FluxStore-listing 1.4.2\source\android\app\src\main\AndroidManifest.xml:57:9-59:49: AAPT: error: resource string/fb_app_id (aka com.inspireui.fluxlisting:string/fb_app_id) not found.

     C:\Users\Usuario\Documents\FluxStore-listing 1.4.2-20200714T041041Z-001\FluxStore-listing 1.4.2\source\android\app\src\main\AndroidManifest.xml:60:9-62:48: AAPT: error: resource string/app_name (aka com.inspireui.fluxlisting:string/app_name) not found.

     C:\Users\Usuario\Documents\FluxStore-listing 1.4.2-20200714T041041Z-001\FluxStore-listing 1.4.2\source\android\app\src\main\AndroidManifest.xml:63:9-65:55: AAPT: error: resource string/ak_client_token (aka com.inspireui.fluxlisting:string/ak_client_token) not found.

     C:\Users\Usuario\Documents\FluxStore-listing 1.4.2-20200714T041041Z-001\FluxStore-listing 1.4.2\source\android\app\src\main\AndroidManifest.xml:31:13-32:74: AAPT: error: resource string/api_key (aka com.inspireui.fluxlisting:string/api_key) not found.

     C:\Users\Usuario\Documents\FluxStore-listing 1.4.2-20200714T041041Z-001\FluxStore-listing 1.4.2\source\android\app\src\main\AndroidManifest.xml:69:9-71:48: AAPT: error: resource string/admob_api (aka com.inspireui.fluxlisting:string/admob_api) not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 45s

Do you have a repair service? Could you make it works? 

Best regards, Mauro
![ERROR APP](https://user-images.githubusercontent.com/67668916/89712271-365a4a80-d966-11ea-8666-f6ddb31a1367.jpg)
![ERROR APP 2](https://user-images.githubusercontent.com/67668916/89712274-3b1efe80-d966-11ea-933a-777f68b81e63.jpg)
