### ISSUE TITLE
[Fluxstore] - type 'int' is not a subtype of type 'double'

### ISSUE THREAD

**Issue by juniortimeline** [inspireui/support#2049] opened 2020-02-08 16:38 UTC
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: After I enable Caching ""isCaching": true" this red screen show with the error "type 'int' is not a subtype of type 'double'"

2. Screenshots issues: https://drive.google.com/file/d/1vahXm8DUjdYatVb_6lDYV94G_qLKBs1z/view?usp=sharing

3. Proof of my purchased: https://codecanyon.net/comments/23638774

3. Config files (optional)

**Comment by inspireui-support** [comment] 2020-02-09 02:01
Duplicate of #2001 

Please use the patching on this ticket - thank you!

**Closed by inspireui-support** 2020-02-09 02:01 UTC
Labels: question ❓
