### ISSUE TITLE
GetOwn Product Issue 

### ISSUE THREAD

**Issue by robaa1418** [inspireui/support#4809] opened 2020-08-31 02:34 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue
Can't get store product
+ Product & version: Fluxstore MV
+ Flutter (or React Native) version: 1.20.2
+ Testing Device/Simulator:  ios 
+ Screenshot issues (drag the file to attach here): 
<img width="690" alt="Screen Shot 1442-01-12 at 5 29 56 AM" src="https://user-images.githubusercontent.com/43137964/91677474-77034900-eb4b-11ea-9b70-098e22a3b79a.png">

** proof of purchasing the license

[pls down share the License key here]

**Comment by minhcasi** [comment] 2020-08-31 03:36
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by robaa1418** [comment] 2020-08-31 04:25
I submit the info in link above

**Comment by minhcasi** [comment] 2020-09-01 02:16
@tgloc96 - please help to investigate the issue

**Comment by tgloc96** [comment] 2020-09-01 02:50
Hello @robaa1418, can you record the screen when the error occurred?

**Comment by robaa1418** [comment] 2020-09-01 08:34
when I click on my product the product of store not appear

**Comment by tgloc96** [comment] 2020-09-01 11:06
@robaa1418 I checked and it working normally, can you tell me the version of the app you are using?

**Comment by tgloc96** [comment] 2020-09-03 02:27
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by tgloc96** 2020-09-03 02:27 UTC
Labels: FluxstoreMV
