### ISSUE TITLE
[mstore-pro] - Android: Category Title from ViewAll Not Translating

### ISSUE THREAD

**Issue by harry503** [inspireui/support#1181] opened 2019-10-06 01:21 UTC
1. Category Screen by clicing View All from Homepage not translating for Android
Please change {label} to {title} in src/components/AnimatedHeader/index.js line 35 which used the {label} not yet translated to {title}. This issue only affects Android only with the if condition for Android.

Purchase Code: 7c399f31-c465-4f76-ac62-7fa0f04fd615

**Comment by minhcasi** [comment] 2019-10-06 11:21
@harry503 - kindly post with the same ticket with your all issues

Duplicate of #1175

**Closed by minhcasi** 2019-10-06 11:21 UTC
Labels: question ❓

**Comment by harry503** [comment] 2019-10-06 23:37
FYI, this is not the same issue as #1175. This is the fix in the code that I did and I thought I share with you Category title not translating in Android.
