### ISSUE TITLE
[ Fluxstore MV 1.7.3 ] - OnePageCheckout (Cart is empty) on Release mode

### ISSUE THREAD

**Issue by iamar1k92** [inspireui/support#3520] opened 2020-06-01 12:17 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 

When i click on checkout using onepagecheckout, the cart is empty.

while in debug, it work fines, the website product cart is synced the app cart. 

+ Product & version: Fluxstore MV 1.7.3
+ Flutter (or React Native) version: Flutter 1.17.2 + Dart 2.8.3
+ Testing Device/Simulator: Samsung Galaxy Grand Prime
+ Screenshot issues (drag the file to attach here): 

![WhatsApp Image 2020-06-01 at 4 58 42 PM (1)](https://user-images.githubusercontent.com/58983166/83406986-40714180-a429-11ea-9fa3-1d2235c16adf.jpeg)
![WhatsApp Image 2020-06-01 at 4 58 42 PM (1)](https://user-images.githubusercontent.com/58983166/83406992-42d39b80-a429-11ea-9a0d-e317931059d1.jpeg)

**Comment by minhcasi** [comment] 2020-06-02 00:41
Duplicate of #3523 - pls move the conversation to that ticket

**Closed by minhcasi** 2020-06-02 00:41 UTC

**Comment by iamar1k92** [comment] 2020-06-02 07:45
Please this is another issue, that is different app. Please don't merge both..

**Comment by iamar1k92** [comment] 2020-06-02 10:56
Please open and solve this issue as another ticket..
both are different apps..

**Comment by iamar1k92** [comment] 2020-06-03 06:19
@minhcasi this is different issue..

**Comment by iamar1k92** [comment] 2020-06-04 14:50
???

**Comment by iamar1k92** [comment] 2020-06-09 02:28
In lib/widgets/frameworks/woocommerce/index.dart
under doCheckout method for EnableOnePageCheckout condition used following fixed my issue.

url = url.replaceAll("mstore-checkout", "mstore-checkout");
