### ISSUE TITLE
Cannot open news page after opening contact us page

### ISSUE THREAD

**Issue by tl3308** [inspireui/support#2441] opened 2020-03-25 03:11 UTC
Hi,

When I select CONTACT US on the side menu, then select NEWS, then select CONTACT US, then select NEWS again, the NEWS failed to load. When I tried to go the the NEWS page via the link at the bottom of the HOME screen, it will go to the CONTACT US page instead

![Screenshot_20200325_105749_hk com tova mstore 1](https://user-images.githubusercontent.com/696268/77497741-0748ae00-6e89-11ea-8749-02ddd40321c6.jpg)

![Screenshot_20200325_105756_hk com tova mstore 1](https://user-images.githubusercontent.com/696268/77497874-5098fd80-6e89-11ea-9089-537ba7470511.jpg)

![Screenshot_20200325_105803_hk com tova mstore 1](https://user-images.githubusercontent.com/696268/77497819-34955c00-6e89-11ea-8022-7c8777e7792c.jpg)

**Comment by minhcasi** [comment] 2020-03-25 06:43
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by minhcasi** [comment] 2020-03-25 06:44
Duplicate of #2442

**Closed by minhcasi** 2020-03-25 06:44 UTC
Labels: MStorePro
