### ISSUE TITLE
Error running pod install

### ISSUE THREAD

**Issue by metinemredonmez** [inspireui/support#4875] opened 2020-09-04 11:34 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- [ ] first issue. please ask for help I followed the instructions, but it doesn't happen why the simulator phone doesn't turn on
- [ ] second issue
- [ ] third issue

+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

<img width="1077" alt="Ekran Resmi 2020-09-04 14 32 44" src="https://user-images.githubusercontent.com/54211029/92235039-b919eb00-eebb-11ea-9012-5c26b623131a.png">

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment] 2020-09-04 12:11
Duplicate of #4870

**Closed by minhcasi** 2020-09-04 12:11 UTC
