### ISSUE TITLE
Beonews iOS build with Xcode 11 

### ISSUE THREAD

**Issue by dimmu123** [inspireui/support#4131] opened 2020-07-08 21:00 UTC
Hi! :D

Do you know if i can make iOS build using your BeoNews 3.0.2 or 3.0.3 ( not sure ) , using xCode 11?

I'm trying but i get lots of errors regarding Admob sdk and FB SDK.

If not, what version of xCode should i use for 3.0.x BeoNews?

Thanks!

**Comment by minhcasi** [comment] 2020-07-09 02:39
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-07-10 02:18
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-10 02:18 UTC
Labels: needs-more-info
