### ISSUE TITLE
[Mstore Pro] issue with android and IOS in v 3.7.2 

### ISSUE THREAD

**Issue by yosefasad** [inspireui/support#428] opened 2019-03-24 07:55 UTC
Hello 

No code modified in Mstore 3.7.2, it is the same package as downloaded from Envato.

Please check the error in the image 
https://imgur.com/a/3mxiTY6

Thanx

**Comment by minhcasi** [comment] 2019-03-24 11:11
Duplicate of #427

**Closed by minhcasi** 2019-03-24 11:11 UTC

**Comment by minhcasi** [comment] 2019-03-24 11:13
Hi, pls try to remove the android/local.properties will be fixed the issues

Or you can map this file link to your Android sdk

**Comment by yosefasad** [comment] 2019-03-24 11:32
Helo 

the issue of IOS is not solved and i have another issue in Android ....

please check the screenshot

https://imgur.com/a/98Sv0RU

**Comment by yosefasad** [comment] 2019-03-25 08:20
The issues of IOS and Android still exist in MStore  v3.7.2 

waiting for a fix 

Thanx
