### ISSUE TITLE
Error and Queries

### ISSUE THREAD

**Issue by sachinsuper** [inspireui/support#4312] opened 2020-07-22 09:05 UTC
1. While adding product into the CART, we are getting following error (SS attached)

2. When a price is updated in WP and when user tried adding product in CART, how will it behave? Will it let him complete transaction or will it show Product out of stock or remove that product from list?

3, How can I add more product quantity in CART. RIght now its only showing 10. What if quantity is more?
![WhatsApp Image 2020-07-22 at 2 32 48 PM](https://user-images.githubusercontent.com/11389704/88157585-95128b00-cc28-11ea-9196-fe9d083dca1a.jpeg)

**Comment by minhcasi** [comment] 2020-07-22 10:18
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-07-24 06:26
@sachinsuper - please help to clarify which the fluxstore version you are using as we could not reproduce the issue, please help to try with latest release `1.7.6` on gitlab - thank you!

**Comment by sachinsuper** [comment] 2020-07-24 07:18
Fluxstore version means code where do settings OR mobile app code?

**Comment by minhcasi** [comment] 2020-07-24 08:25
Fluxstore MV version - please also give a try with the latest version on Gitlab - if you have don't have an account, please submit on this link http://gitlab.inspireui.com/

**Comment by sachinsuper** [comment] 2020-07-24 10:39
Is it a open library or you will add our ID on it?

We had asked some queries. Can you please respond on it?

ALso if there is any customisation, do you do it

**Comment by minhcasi** [comment] 2020-07-24 12:59
@sachinsuper - we also release the latest release `1.7.6` to fix this issue, please give a try a let us know if it is worked fine 😊

**Comment by sachinsuper** [comment] 2020-07-25 11:28
So to download the code from GIT how do we do it? Is it open network

**Comment by minhcasi** [comment] 2020-07-27 01:51
@sachinsuper - you could submit on this link http://gitlab.inspireui.com/ - this is a useful guide to clarify how to manage the gif effective - https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6

**Comment by sachinsuper** [comment] 2020-07-27 11:17
Hi,

We have one more issue. WHen we go to checkout, we get this error attached.
Its redirecting us the website page, rather than staying on the same page.

Can you please confirm.

**Comment by minhcasi** [comment] 2020-07-28 03:59
@sachinsuper - we could not see the images, please help to attache it again - thank you!

**Comment by minhcasi** [comment] 2020-07-30 04:29
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-30 04:29 UTC
Labels: 1.7.6, FluxstoreMV
