### ISSUE TITLE
FluxStore MultiVendor - Cant set v1.1.0

### ISSUE THREAD

**Issue by daav7713** [inspireui/support#1417] opened 2019-11-18 15:01 UTC
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. I'm trying to set the project on its new version and shows me this error :+1:  Compiler message:
lib/screens/detail/index.dart:78:27: Error: Getter not found: 'halfSizeImageType'.
      case kProductLayout.halfSizeImageType:

3. 
![image](https://user-images.githubusercontent.com/15809768/69063355-fae7ac80-09e1-11ea-95d3-a957202cc2e8.png)

**Comment by minhtruong315** [comment] 2019-11-20 03:54
@daav7713 add my skype: minhtruong315. I will help you check it via teamviewer

**Comment by minhtruong315** [comment] 2019-11-26 15:05
I will close this ticker, you can't reproduce on latest version. if you have any issues, pls contact me

**Closed by minhtruong315** 2019-11-26 15:05 UTC
Labels: Fluxstore-MV, question ❓
