### ISSUE TITLE
[Mstore multi vendor] when i enable the push notification there was a error message "can't get data from server"...

### ISSUE THREAD

**Issue by ZamanGoraya** [inspireui/support#1153] opened 2019-10-02 06:46 UTC
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by minhcasi** [comment] 2019-10-02 08:33
Hi, could you share your purchased screenshot from https://codecanyon.net/downloads - thanks

**Comment by ZamanGoraya** [comment] 2019-10-03 04:28
i am an employee and my boss bought it...

**Comment by ZamanGoraya** [comment] 2019-10-03 04:29
![Mstore multi vendor](https://user-images.githubusercontent.com/52818458/66099415-41af4d80-e5c0-11e9-8cbc-5c6d2ca7f236.PNG)

**Comment by ZamanGoraya** [comment] 2019-10-03 06:44
sir @minhcasi ...!  I am waiting for your reply ...

**Comment by ZamanGoraya** [comment] 2019-10-03 07:10
![tricells chat](https://user-images.githubusercontent.com/52818458/66106215-c73df800-e5d6-11e9-825e-225f778b9c73.PNG)

**Comment by minhcasi** [comment] 2019-10-03 12:05
@ZamanGoraya - what is the pushnotification service you are using ?

**Comment by ZamanGoraya** [comment] 2019-10-03 15:32
i am using onesignal id ... with woocommerce "OneSignal Push Notifications" but when user enable the push notification then the app show the message "can't get data from server"... how can i solve this problem...?

**Comment by ZamanGoraya** [comment] 2019-10-04 11:54
?

**Comment by minhcasi** [comment] 2019-10-04 12:06
@ZamanGoraya - are you using the cli version from the download package to active the push notify, as the expo will not support, please check this guide for the detail config - https://documentation.onesignal.com/docs/react-native-sdk-setup

**Comment by ZamanGoraya** [comment] 2019-10-04 12:17
will it work for both andriod and ios...?

**Comment by ZamanGoraya** [comment] 2019-10-04 12:24
i have done this all...

**Comment by ZamanGoraya** [comment] 2019-10-04 12:24
iss it require ssl certificate...?

**Comment by ZamanGoraya** [comment] 2019-10-04 12:51
kindly do not close this ... before i get the solution... 

when i get the solution i will close it with "thank you" comment...

**Comment by ZamanGoraya** [comment] 2019-10-04 12:52
https://github.com/inspireui/support/issues/1153#issuecomment-538374979

**Comment by ZamanGoraya** [comment] 2019-10-09 11:07
Hy... i have try in react native cli also ... but it is not working for my android...

**Comment by ZamanGoraya** [comment] 2019-10-09 11:07
kindly help me to solve this problem...

**Comment by ZamanGoraya** [comment] 2019-10-09 14:06
kindly tell me how to solve this problem...?

**Comment by minhcasi** [comment] 2019-10-10 11:59
Duplicate of #1190

**Closed by minhcasi** 2019-10-10 11:59 UTC
Labels: MStoreMV, question ❓
