### ISSUE TITLE
FluxNews - Key

### ISSUE THREAD

**Issue by UlisesFleitas** [inspireui/support#4391] opened 2020-07-27 23:06 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 

**I have my own google play key, because I have a published app, and I want to update it with Flux News.
and I want to know how to proceed in this case**

**I have very problem and i can´t continue with the Login Part. Because a want use my own key.**

+ Product & version: **FluxNews 1.4.1**

+ Flutter (or React Native) version:  **FLutter**

+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**Done**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment] 2020-07-27 23:35
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by UlisesFleitas** [comment] 2020-07-28 00:36
Hello, yes, i did that at firts. Now i do again. Please help me!

**Comment by minhcasi** [comment] 2020-07-28 03:36
@UlisesFleitas - thank you for quick response, we got your file and verified 

If you already have the key, please try to change the fluxnews app with your existing bundle id - and attache the key when you build the apk, please refer to https://docs.inspireui.com/fluxnews/delivery/ 

and the detail guide: https://flutter.dev/docs/deployment/android

**Comment by UlisesFleitas** [comment] 2020-07-29 00:01
Can I generate the Sha1 and Facebook Login Hash with the example key? and use my key when I upload to Google Play

**Comment by minhcasi** [comment] 2020-07-29 07:29
@UlisesFleitas - could you help to share the video screenshot of the issue as we are not sure to understand your issue here - thank you!

**Comment by minhcasi** [comment] 2020-07-31 03:53
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-31 03:53 UTC
Labels: FluxNews, appstore-release

**Comment by UlisesFleitas** [comment] 2020-07-31 18:21
Good afternoon.

I really can't do it alone, please I need you guys to do all the work for
me ...

Right now, I need for Android.
I have an app published on Google Play, and that APP I want to update, it
already has many downloads, and I have the APP signed with my own key
I have the google json file from Firebase.
I have Admob banner and interstitial
And my wordpress is www.appsresources.com

Please tell me what you need to get started and launch the App soon.

Regards,
Ulises Fleitas

**Comment by UlisesFleitas** [comment] 2020-08-03 14:55
Hello,
I wait for your reply.
