### ISSUE TITLE
Some Issues with Fluxlisting and Listeo Config

### ISSUE THREAD

**Issue by dibbo-ru** [inspireui/support#4087] opened 2020-07-06 14:55 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Could not build the application for the simulator.
Error launching application on iPhone 11 Pro.
+ Product & version: Flux Listing app for Listeo Website,  V:1.4.2
+ Flutter (or React Native) version: Latest
+ Testing Device/Simulator: Android Studio
+ Screenshot issues (drag the file to attach here): 
I can run it on an android device but can't open on IOS

![notbuildios2](https://user-images.githubusercontent.com/19253603/86607318-edac1c00-bfca-11ea-8ad4-d0f7e6133ed1.png)
![Untitleddfdf2](https://user-images.githubusercontent.com/19253603/86607336-f270d000-bfca-11ea-97de-8df25b4c984e.png)
**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
Done

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment] 2020-07-06 21:02
@dibbo-ru 
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-07-07 02:19
@dibbo-ru could you help to try to clean up the flutter cache - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

please make sure you are using the Stable channel and could able to run the TestDrive example - https://flutter.dev/docs/get-started/test-drive?tab=vscode

**Comment by dibbo-ru** [comment] 2020-07-08 18:09
I solved this. But now I am facing problem with another few issues.
1. Can't display product's images.
2. 'Booking Now' Can't work
3. Want to hide 'Guest' option during 'Booking'

**Comment by dibbo-ru** [comment] 2020-07-09 09:06
Please give me solution

**Comment by dibbo-ru** [comment] 2020-07-09 21:02
![Uploading 333.png…](
![444](https://user-images.githubusercontent.com/19253603/87090388-b30be300-c259-11ea-8dcf-aaea56a2c7e1.png)
)
![111](https://user-images.githubusercontent.com/19253603/87090383-b0a98900-c259-11ea-8633-04b97bf11b3c.png)

**Comment by dibbo-ru** [comment] 2020-07-09 21:03
![333](https://user-images.githubusercontent.com/19253603/87090478-e189be00-c259-11ea-8bd4-562a6fa45317.png)

**Comment by dibbo-ru** [comment] 2020-07-09 21:03
![444](https://user-images.githubusercontent.com/19253603/87090509-ee0e1680-c259-11ea-994b-adfa187756c0.png)

**Comment by philipvu30** [comment] 2020-07-10 02:26
Hi,

About issues 1 and 3, please send your common folder to this email: toan@inspireui.com.
We are working on issue 2. Please be patient.

Thank you.

**Comment by dibbo-ru** [comment] 2020-07-10 06:58
I sent the common folder. Please check it out

**Comment by philipvu30** [comment] 2020-07-10 07:13
Hi,

What is the current version of Listeo Theme you are using?

**Comment by dibbo-ru** [comment] 2020-07-10 07:13
Yes, Listeo

**Comment by philipvu30** [comment] 2020-07-10 07:14
I meant the version number. Is it 1.3.1?

**Comment by dibbo-ru** [comment] 2020-07-10 07:15
Yes, Latest one

**Comment by dibbo-ru** [comment] 2020-07-11 05:22
My listeo version 1.3.3 and im using child theme which version 1.0

**Comment by dibbo-ru** [comment] 2020-07-11 18:00
Any Update?

**Comment by dibbo-ru** [comment] 2020-07-14 06:04
When will i get solutions?

**Comment by minhcasi** [comment] 2020-07-14 06:50
@dibbo-ru - there is the incompatible with the Listeo booking feature as they have changed the project booking core library - We’re working as hard as we can to get to your request as soon as possible - thank you!

**Comment by dibbo-ru** [comment] 2020-07-14 16:37
Okay Thank You

**Comment by philipvu30** [comment] 2020-07-15 10:29
Hi,

The booking feature is fixed. Please update Listing App to 1.6.5 and replace these 2 folders.
lib/screens/detail/booking -> [booking.zip](https://github.com/inspireui/support/files/4924539/booking.zip)
lib/services -> [services.zip](https://github.com/inspireui/support/files/4924540/services.zip)

Thank you.

**Comment by FaizalAndro** [comment] 2020-07-15 12:45
Hi, I didn't get any option of Fluxstore Listing in Fluxbuilder software

**Comment by FaizalAndro** [comment] 2020-07-15 13:24
BookStatus Error everywhere,

**Comment by FaizalAndro** [comment] 2020-07-15 13:33
![Capture3](https://user-images.githubusercontent.com/37078576/87551282-c42b7880-c6cd-11ea-9dcb-2c251b7e0ab5.PNG)
BookStatus Error Everywhere

**Comment by dibbo-ru** [comment] 2020-07-15 17:38
How Can i update List App Mobile Manager to 1.6.5 ?

**Comment by dibbo-ru** [comment] 2020-07-15 18:09
got it

**Comment by dibbo-ru** [comment] 2020-07-15 18:53
![zxczxc 2](https://user-images.githubusercontent.com/19253603/87584070-c1954700-c6fe-11ea-92cc-10492a936d06.png)

**Comment by philipvu30** [comment] 2020-07-16 02:17
Hi @FaizalAndro @dibbo-ru 

Sorry for my mistake. I have updated my solution. Please have a check.

Thank you.

**Comment by dibbo-ru** [comment] 2020-07-16 07:30
Now App is running but Images doesn't fetch and booking error is happening still

**Comment by FaizalAndro** [comment] 2020-07-16 09:17
@dibbo-ru Check this https://github.com/inspireui/support/issues/3891 (It will help you to fix images fetching issue)

**Comment by FaizalAndro** [comment] 2020-07-16 09:32
![Screenshot_1594891677](https://user-images.githubusercontent.com/37078576/87654933-36a36380-c775-11ea-85e1-9e9c3343bbac.png)
 I created two vendors, vendors store name visible below products but when clicking in Category section Store it shows just blank

**Comment by dibbo-ru** [comment] 2020-07-16 15:20
![new](https://user-images.githubusercontent.com/19253603/87689466-0d50fa80-c7aa-11ea-9e74-a3de3ed880a1.png)
FaizalAndro

**Comment by dibbo-ru** [comment] 2020-07-16 15:21
![new2](https://user-images.githubusercontent.com/19253603/87689708-586b0d80-c7aa-11ea-9cf2-7ba50518162f.png)

**Comment by philipvu30** [comment] 2020-07-17 07:50
Hi,

Can you give me access to your FileManager? As your endpoint does not return the gallery_images, I need to test it on your server as our demo app does not encounter this issue.
You can send it to the email: toan@inspireui.com

Thank you.

**Comment by dibbo-ru** [comment] 2020-07-17 08:59
How can i give you the file manager access?

**Comment by philipvu30** [comment] 2020-07-17 09:03
Are you using Hosting Providers or  VPS to host your website?

**Comment by dibbo-ru** [comment] 2020-07-17 15:07
Yes, on namecheap

**Comment by dibbo-ru** [comment] 2020-07-17 15:08
Do you need Namecheap access?

**Comment by dibbo-ru** [comment] 2020-07-18 18:33
I have shared the access of my hosting provider please check your email

**Comment by enriqueguardia** [comment] 2020-07-19 03:19
Can confirm the **Booking Error! Please check your detail!!** error is still present. I bought your app yesterday, and booking and reviews are not working. Everything else is stable so far.

The booking feature should sync with the booking slots on Listeo. Otherwise the booking feature serves no purpose.

Using Listeo 1.3.3, please provide a fix as soon as possible.

![1](https://user-images.githubusercontent.com/13895358/87866230-10d0b700-c94d-11ea-83d0-79120cf7788b.png)

**Comment by dibbo-ru** [comment] 2020-07-19 13:26
Did you check my file manager @philipvu30

**Comment by philipvu30** [comment] 2020-07-20 02:42
Hi @dibbo-ru  @enriqueguardia 

My apologies for the delayed response as we do not work on the weekends.
@dibbo-ru I'm checking it right now.
@enriqueguardia Please open a ticket and submit to our [Form](https://docs.google.com/forms/d/e/1FAIpQLScWOjkAJIWJ9rgb9alopfOqLsJrGKbFM5cCYj1JBfLKLsBblQ/viewform). Thank you.

**Comment by dibbo-ru** [comment] 2020-07-21 06:17
Any update? @philipvu30

**Comment by philipvu30** [comment] 2020-07-21 06:55
Hi,

I was able to access the file manager but there was no content or data inside the domain mis***i.com. Hence, I cannot investigate more on your files.
Do you know what's wrong with it?

**Comment by dibbo-ru** [comment] 2020-07-21 17:55
Did you check from cpanel? Which data do you want?

**Comment by philipvu30** [comment] 2020-07-22 03:38
Hi,

I need to directly modify our plugin ListApp Mobile Manager on your server. If possible, please show me where I can access that.

Thank you.

**Comment by dibbo-ru** [comment] 2020-07-22 07:45
Then you should have to log in to my WordPress panel. I am sending my wp-admin panel access to your mail. Please check it out.

**Comment by philipvu30** [comment] 2020-07-22 10:43
Hi,

The issue has been fixed. The reason behind this error is you changed your Website's Title so our plugin cannot detect your theme.
We'll improve this feature in the future. Now, whenever you update the plugin, please head to this file and fix this code to the image below. Please note that you have to deactivate the ListApp Mobile Manager first before modifying it.

Thank you.

![image](https://user-images.githubusercontent.com/54442328/88167205-a799be00-cc42-11ea-9507-de797173d2da.png)

**Comment by dibbo-ru** [comment] 2020-07-22 18:12
It's working now. How can I fixed booking error issue, also I want to remove 'Guest' function from booking form

**Comment by philipvu30** [comment] 2020-07-23 03:47
Hi,

- Booking issue: do the same as my previous answer

![image](https://user-images.githubusercontent.com/54442328/88250320-6d2b3200-ccd1-11ea-8739-e46ad82e5408.png)


- Removing guest: Comment lines 430-474 in the file lib/screens/detail/booking/service_booking.dart

![image](https://user-images.githubusercontent.com/54442328/88250398-b67b8180-ccd1-11ea-8b4a-95277255e061.png)

**Comment by dibbo-ru** [comment] 2020-07-24 22:20
![image](https://user-images.githubusercontent.com/19253603/88439876-34ed3600-ce2e-11ea-9062-e69f100635c9.jpeg)

**Comment by dibbo-ru** [comment] 2020-07-24 22:21
How can i remove it?

**Comment by dibbo-ru** [comment] 2020-07-24 22:22
![image](https://user-images.githubusercontent.com/19253603/88439914-4b938d00-ce2e-11ea-9dd6-79440f8c7441.jpeg)

**Comment by dibbo-ru** [comment] 2020-07-24 22:23
I want to change 'product' to 'service

**Comment by dibbo-ru** [comment] 2020-07-26 15:32
@philipvu30 can you respond to me, please?

**Comment by philipvu30** [comment] 2020-07-27 03:51
Hi,

I'm sorry for the delayed response as we don't work at the weekends.
If you are using Android Studio, please install the plugin Flutter Intl. Then in lib/l10n/intl_en.arb, find "products": "Products" and replace the term "Products" to "services".

**Comment by dibbo-ru** [comment] 2020-07-28 19:17
![UnasEDtitled 2](https://user-images.githubusercontent.com/19253603/88710959-3aea5c00-d139-11ea-9d98-2f67ccc50352.png)

**Comment by dibbo-ru** [comment] 2020-07-28 19:17
What does it mean?

**Comment by dibbo-ru** [comment] 2020-07-28 19:20
I have run this code, after that this error is happening

flutter channel beta
flutter upgrade --force

**Comment by philipvu30** [comment] 2020-07-29 03:57
Hi,

This app is developed in channel stable. Please switch to that channel and try again.
```
flutter channel stable
flutter upgrade
```

Thank you.

**Comment by dibbo-ru** [comment] 2020-07-29 06:10
Solved. Thanks @philipvu30

**Comment by dibbo-ru** [comment] 2020-07-29 06:11
I want to change this images...how can i change these?
![Simulator Screen Shot - iPhone 11 Pro - 2020-07-29 at 12 09 32](https://user-images.githubusercontent.com/19253603/88763207-90a02200-d194-11ea-88ab-cdf9cb461aaf.png)

**Comment by philipvu30** [comment] 2020-07-29 09:46
In config.dart,

![image](https://user-images.githubusercontent.com/54442328/88785107-fdc6ae00-d1ba-11ea-96df-e5cab22a5ee0.png)

**Comment by minhcasi** [comment] 2020-07-31 07:16
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-31 07:16 UTC
Labels: FluxListing, common-installing ⁉️
