### ISSUE TITLE
Unable to add https based links in config.dart

### ISSUE THREAD

**Issue by varunmannava** [inspireui/support#4010] opened 2020-07-01 17:20 UTC
Dear Team,

I would like to use https based website links in config.dart and when am using it am unable to see products category and stores and it is only visible if am using Http only and images are not showing and am receiving below error when I check in debug mode.

HandshakeException: Handshake error in client (OS Error: CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(han

**Comment by ameenbadri7** [comment] 2020-07-01 18:51
@varunmannava 
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by varunmannava** [comment] 2020-07-01 19:45
Submitted

**Comment by ameenbadri7** [comment] 2020-07-02 23:53
Are you developing on windows  or macos?  
Are you using android studio or Vscode? 
Are using the an emulator or real device? 
What is the multi vendor version you are using?  
What is flutter version are you using?  

Please help us by answering those questions.

**Comment by ameenbadri7** [comment] 2020-07-04 06:46
I'm sorry to close this ticket as there is no response or active conversation, 
please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by ameenbadri7** 2020-07-04 06:46 UTC
Labels: FluxstoreMV, common-integration
