### ISSUE TITLE
build appbundle issue

### ISSUE THREAD

**Issue by Moh-Zag** [inspireui/support#3794] opened 2020-06-18 22:33 UTC
Hello, I have an issue when I run “flutter build appbundle”  I got the following error

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\web design\mallapp\android\build.gradle' line: 37

* What went wrong:
A problem occurred evaluating root project 'android'.
> Could not find method signingConfigs() for arguments [build_cq4g0jd7lxtqhhsqmknjtq0mj$_run_closure5@3a919004] on root project 'android' of type org.gradle.api.Project.

Can you please help me resolve this issue

here is a copy of my build.gradle file

thanks

[build.gradle.txt](https://github.com/inspireui/support/files/4801510/build.gradle.txt)

**Comment by minhcasi** [comment] 2020-06-19 00:34
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by Moh-Zag** [comment] 2020-06-19 14:10
hello, 
I completed the form.

Thanks 
Best Regards

**Comment by minhcasi** [comment] 2020-06-20 04:03
@Moh-Zag  - this could be build grade config issue, we could not reproduce on our side, please try some solution on this link https://stackoverflow.com/questions/45772745/build-failed-could-not-find-method-signingconfigs

Also, help to check this detailed guide from google - https://flutter.dev/docs/deployment/android

**Comment by Moh-Zag** [comment] 2020-06-20 19:12
thanks for your help,
I recently solved this issue, but I got another error :

FAILURE: Build failed with an exception.
Running Gradle task 'bundleRelease'...

Running Gradle task 'bundleRelease'...
* Where:
Running Gradle task 'bundleRelease'...
Script 'd:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896
Running Gradle task 'bundleRelease'...

Running Gradle task 'bundleRelease'...
* What went wrong:
Running Gradle task 'bundleRelease'...
Execution failed for task ':app:compileFlutterBuildRelease'.
Running Gradle task 'bundleRelease'...
> Process 'command 'd:\flutter\bin\flutter.bat'' finished with non-zero exit value 1
Running Gradle task 'bundleRelease'...

Running Gradle task 'bundleRelease'...
* Try:
Running Gradle task 'bundleRelease'...
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get m
ore log output. Run with --scan to get full insights.
Running Gradle task 'bundleRelease'...

Running Gradle task 'bundleRelease'...
* Get more help at https://help.gradle.org
Running Gradle task 'bundleRelease'...

Running Gradle task 'bundleRelease'...
BUILD FAILED in 5m 58s
Running Gradle task 'bundleRelease'...

Running Gradle task 'bundleRelease'... Done                       362.1s (!)
Gradle task bundleRelease failed with exit code 1

Can you please tell what is wrong..
Thanks

**Comment by minhcasi** [comment] 2020-06-21 07:13
Please help to check the default download package so see if you have the same issue? 

You could also zip the project and send us for checking - support@inspireui.com - thank you!

**Comment by minhcasi** [comment] 2020-06-22 08:14
Hi @Moh-Zag , 

Please go to source/android/gradle/wrapper/ folder, open gradle-wrapper.properties file and change distributionUrl as below:
distributionUrl=https://services.gradle.org/distributions/gradle-5.6.2-all.zip

Thank you

**Comment by Moh-Zag** [comment] 2020-06-22 16:32
Hi, Thanks for your advice.

The source is working fine, and I made some customization and it works fine in debug mode.
the problem occurs  when I tried to create the appbundle, Although I did the required steps to create the keystore file and made the modifications to AndroidManifest.xml files, the problem still exist.
 I'll send you a zip of my project, Hope you will find a solution to this issue.

Thanks
Best Regards

**Comment by Moh-Zag** [comment] 2020-06-23 05:25
Hello,
I reinstalled the flutter package, and reconfigured the app with my keystore.
finally, the app works fine on the emulator. But I got the following error when I tried to create the appbundle.

Running Gradle task 'bundleRelease'...
Codepoint 58849 not found in font, aborting.

FAILURE: Build failed with an exception.

* Where:
Script 'd:\web design\apps\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'd:\web design\apps\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 37s
Running Gradle task 'bundleRelease'...
Running Gradle task 'bundleRelease'... Done                       160.4s (!)
Gradle task bundleRelease failed with exit code 1

How can I resolve this issue?

Thanks
Best Regards

**Comment by minhcasi** [comment] 2020-06-23 06:55
@Moh-Zag - please help to review these guidelines to check if you have missing change from the bundle id?
1. https://docs.inspireui.com/fluxstore/delivery-android/
2. https://flutter.dev/docs/deployment/android

**Comment by minhcasi** [comment] 2020-06-24 03:27
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-06-24 03:27 UTC
Labels: FluxStore, appstore-release

**Comment by sangeetjass** [comment] 2020-08-13 09:21
> thanks for your help,
> I recently solved this issue, but I got another error :
> 
> FAILURE: Build failed with an exception.
> Running Gradle task 'bundleRelease'...
> 
> Running Gradle task 'bundleRelease'...
> 
> * Where:
>   Running Gradle task 'bundleRelease'...
>   Script 'd:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896
>   Running Gradle task 'bundleRelease'...
> 
> Running Gradle task 'bundleRelease'...
> 
> * What went wrong:
>   Running Gradle task 'bundleRelease'...
>   Execution failed for task ':app:compileFlutterBuildRelease'.
>   Running Gradle task 'bundleRelease'...
> 
> > Process 'command 'd:\flutter\bin\flutter.bat'' finished with non-zero exit value 1
> > Running Gradle task 'bundleRelease'...
> 
> Running Gradle task 'bundleRelease'...
> 
> * Try:
>   Running Gradle task 'bundleRelease'...
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get m
>   ore log output. Run with --scan to get full insights.
>   Running Gradle task 'bundleRelease'...
> 
> Running Gradle task 'bundleRelease'...
> 
> * Get more help at https://help.gradle.org
>   Running Gradle task 'bundleRelease'...
> 
> Running Gradle task 'bundleRelease'...
> BUILD FAILED in 5m 58s
> Running Gradle task 'bundleRelease'...
> 
> Running Gradle task 'bundleRelease'... Done 362.1s (!)
> Gradle task bundleRelease failed with exit code 1
> 
> Can you please tell what is wrong..
> Thanks
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/b5cc75513aeed99e723256a9194f4645ad2a810f/68747470733a2f2f677261646c652e6f72672f696d616765732f677261646c652d343030783430302e706e67"><img alt="" height="14" src="/icon/favicon-16x16.png"> Gradle**[Gradle | Search for Help with Gradle](https://gradle.org/help/)**

How did you solve this issue, I am facing the same while building ios app
