### ISSUE TITLE
[my-product] - MissingPluginException 

### ISSUE THREAD

**Issue by MiguelHAngelH** [inspireui/support#2667] opened 2020-04-11 22:01 UTC
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

**1. My issue: MissingPluginException** 
Hello, as I have problems with some internal things that do not work.
I have followed the following tutorial that was indicated to me but it has not been solved, I have resorted to many tutorials and aids and unfortunately I am still stuck.
I would like to know if you can help me.
in channel STABLE

**2. Screenshots issues (required):**
**2.1. error REGISTER USER**
![WhatsApp Image 2020-04-11 at 17 44 47](https://user-images.githubusercontent.com/3894371/79055638-9f31f000-7c1c-11ea-8341-9a29a6c00b63.jpeg)
2.2 errro ANDROID ESTUDIO DEBUGGER 
![error 2](https://user-images.githubusercontent.com/3894371/79055719-37c87000-7c1d-11ea-91d2-d7453e118863.png)
![error 1](https://user-images.githubusercontent.com/3894371/79055720-38610680-7c1d-11ea-8cd5-a1aa83fc5596.png)
2.3 hot reload.
![error 3](https://user-images.githubusercontent.com/3894371/79056221-13bb5d80-7c22-11ea-8b45-865fc4f66d18.png)

3. Proof of my purchased (required):
The company bought
I am just a developer
![2020-04-08_1033](https://user-images.githubusercontent.com/3894371/79055608-698d0700-7c1c-11ea-976d-3e8452cf5eb1.png)

4. Config files (required)

**Comment by minhcasi** [comment] 2020-04-12 02:03
Duplicate of #2645

please move to the same ticket & root cause on this ticket

**Closed by minhcasi** 2020-04-12 02:03 UTC
Labels: Fluxstore-MV, priority !!!, question ❓
