### ISSUE TITLE
[fluxstore-eccommerc-full app] - 

### ISSUE THREAD

**Issue by khaledsalama32** [inspireui/support#2236] opened 2020-02-27 20:10 UTC
1. My issue:
I tried a lot and did not succeed
I tried linking to the app on WordPress and tried linking it to opencart and woocommerce and I never succeeded

Please help me and suggestion on what to do. I do not want to send me articles, answers and explanations. I want you to explain the reason to me and to send me the solution. Thank you.
Below is the content of the lib / common / config.dart file
I have two sites and I tried to link the application with one of them, but I did not succeed in doing so. The application appears to me, but it has nothing in it - the first site is www.axkeen.com and the second site is www.khaledalsalama.com/khaledwoo
I have made all the instructions on the application site
fluxstore and I installed all the additions and made all the instructions in the application but it did not work until now, only the application screens appear but without the contents and without sections  
--
Look at the two sites and tell me whether there is an error with them or the error from a file
lib / common / config.dart
Thank you
-----------------------------------------------------------------------------
`import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import '../common/constants.dart';

/// Server config
const serverConfig = {
"type": "opencart",
"url": "http://axkeen.com",
"blog": "http://khaledalsalama.com",
"forgetPassword":
"http://axkeen.com/index.php?route=account/forgotten"
};

2. Screenshots issues:

3. Proof of my purchased:
9e83ec40-8414-4b23-960d-0b69d207dd89
3. Config files (optional)

**Comment by minhcasi** [comment] 2020-02-28 03:10
Duplicate of #2231

**Closed by minhcasi** 2020-02-28 03:10 UTC
Labels: question ❓
