### ISSUE TITLE
I can't add product with image as a vendor I am getting format exception

### ISSUE THREAD

**Issue by eyaghi** [inspireui/support#4017] opened 2020-07-02 04:43 UTC
I am getting the below error when I try to add a product with image as a vendor.

Format Exception: Unexpected character (at character 1) </br>

**Comment by minhcasi** [comment] 2020-07-02 10:31
Also, share the detailed screenshot issues so that we could help with investigating - thank you!

**Comment by smartDeviceApps** [comment] 2020-07-05 03:15
I have issue in home page which doesn't show the products only the loader. Sometimes it works after a very long time

**Comment by smartDeviceApps** [comment] 2020-07-05 11:39
files and screenshots sent in private

**Comment by minhcasi** [comment] 2020-07-06 03:48
@smartDeviceApps - sorry could i know your email address so that we could check from the inbox

**Comment by smartDeviceApps** [comment] 2020-07-06 06:45
> @smartDeviceApps - sorry could i know your email address so that we could check from the inbox

I have sent you an email with the files of the issue and an image of the form submitted

**Comment by minhcasi** [comment] 2020-07-08 02:22
pls resend to support@inspireui.com - we could not get it, what is your email address? 

Thank you!

**Comment by smartDeviceApps** [comment] 2020-07-08 04:03
> pls resend to [support@inspireui.com](mailto:support@inspireui.com) - we could not get it, what is your email address?
> 
> Thank you!

![Simulator Screen Shot - iPhone 11 Pro - 2020-07-05 at 10 39 34](https://user-images.githubusercontent.com/67725152/86874465-14f90b00-c0e9-11ea-965a-95caa10a6705.png)


Also, more details sent to the support email from e_yaghi@hotmail.com

**Comment by minhcasi** [comment] 2020-07-15 03:58
@eyaghi - we have updated this pre-config site that set up all the require integration for the app - would you mind to reuse this setting, fore more detail please help to check this guide https://docs.inspireui.com/fluxstore/multi-vendor/#1-website-integration

**Comment by eyaghi** [comment] 2020-07-15 10:43
Hi

the issue still exists. I am receiving the text in the response when uploading the images and the exception occur when decode to json.

I have attached the response



Best Regards,

Enas



________________________________

**Comment by minhcasi** [comment] 2020-07-19 04:07
fixed on latest `1.7.6` - thank you, we will release new package in next couple of days - very best!

**Comment by minhcasi** [comment] 2020-07-20 08:00
@eyaghi - we have fixed this issue from our side, but would like to test on your side - could you share the admin login to that we could verify again on your site? Pls send privately to - inspireui.team@gmail.com

**Comment by minhcasi** [comment] 2020-07-23 04:15
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-23 04:15 UTC
Labels: 1.7.6, FluxstoreMV, config-site
