### ISSUE TITLE
when build release app its give me error

### ISSUE THREAD

**Issue by amankhan7** [inspireui/support#3468] opened 2020-05-29 15:02 UTC
E:\mstore-3.9.8\mstore-pro>cd android && .\gradlew assembleRelease

FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

E:\mstore-3.9.8\mstore-pro\android>

**Comment by minhcasi** [comment] 2020-05-30 04:13
Duplicate of #3450

**Closed by minhcasi** 2020-05-30 04:13 UTC
