### ISSUE TITLE
Flexstore Pro: bug while filter items

### ISSUE THREAD

**Issue by stockracee** [inspireui/support#3120] opened 2020-05-09 21:55 UTC
Bug:: I hv 600 prodoct(aprox) at my website, out of them 548 is under jewellery category. Now when I use filter to show only 548 product then app show only 22products, so many times i tried but result is same. Pl help also pl find bug video as 
https://filebin.net/cr8cpobcdxofxrl4/Recorder_20200509104925.mp4?t=0w5hu0xt
https://envl.app/shareddrive2000/aQPFxL!qE6JroqdgYCoNFWL

**Comment by minhcasi** [comment] 2020-05-10 02:22
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-05-10 02:23
Duplicate of #3122

**Closed by minhcasi** 2020-05-10 02:23 UTC
Labels: needs-more-info
