### ISSUE TITLE
Cant connect wooocommerce api for Fluxstore Pro

### ISSUE THREAD

**Issue by Cheewingtan** [inspireui/support#2809] opened 2020-04-20 14:19 UTC
Step 1 (require): detail issues and screenshots
I follow the guild to create woocommerce API and change the code but it doesn't working and I check https://www.wingsshops.com/wp-json/wc/v3/ it doesn't show anything ,it is my SSL block the API ? I'm using lets encrypt SSL

![Screenshot 2020-04-19 at 4 32 55 PM](https://user-images.githubusercontent.com/11556877/79762078-d73fde00-8354-11ea-90e4-243c85ecf3a3.png)
![Screenshot 2020-04-19 at 4 32 55 PM](https://user-images.githubusercontent.com/11556877/79762074-d5761a80-8354-11ea-82c4-4720a4686775.png)
![Screenshot 2020-04-16 at 1 00 28 PM](https://user-images.githubusercontent.com/11556877/79762082-d7d87480-8354-11ea-84d2-008e90fdcd65.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment] 2020-04-21 01:38
@Cheewingtan - you can try to disable the mstore-api - using your current website and try to enable the Rest API first - https://www.wingsshops.com/wp-json/

Until you could using the Rest API then start integration with the app

**Comment by minhcasi** [comment] 2020-04-21 01:39
@Cheewingtan - pls try your best with this guide - https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API

i'm closing this ticket as the root cause is from the orignial website

**Closed by minhcasi** 2020-04-21 01:39 UTC
