### ISSUE TITLE
[ListAPP] Data is not loading from my wordpress website

### ISSUE THREAD

**Issue by jabirismail** [inspireui/support#179] opened 2019-01-12 06:31 UTC
**Mandatory Info (please complete the following information):**
 - Product: [ListApp]
 - Your Purchased Code: [5ffc9558-4e19-41ac-966b-8de574ae8792]

**Describe the issues**
I have done all steps mentioned in the documentation and our wordpress listing site is working fine.
But when we open the app in Expo, no data is loading..
Listapp version 1.6.0
We are stuck on this for last couple of weeks and we tried many options, but still didnt get a solution.
I doubt the issue is with JWT authentication token.
**Screenshots**

![screenshot_20190112-113547](https://user-images.githubusercontent.com/25244597/51070122-aa851d00-1661-11e9-9e7f-4a9b9072ba53.png)

**Comment by thangvo9x** [comment] 2019-01-12 09:21
Hi. @jabirismail Can you share your Config.js file , such as ur email , plz ?

**Comment by jabirismail** [comment] 2019-01-13 05:53
I had sent a separate mail to you and minh with config file and website details from redboxslns@gmail.com

**Comment by thangvo9x** [comment] 2019-01-15 02:17
Hi. I checked your site. The problem is coming from your website .
https://yourdomain/wp-json/
can't access . 
it couldn't be displayed on your app
Thanks

**Comment by thangvo9x** [comment] 2019-01-15 06:31
Hi. The error is coming from your server. You can refer 
https://codex.wordpress.org/Nginx
Thanks

**Comment by jabirismail** [comment] 2019-01-16 14:52
Hi Thang that issue got resolved after changing the nginx.
But i have lot of other issues in the app and i sent those in the mail..
Why you are not replying even after i sent followup mails...
My queries.

1. Only one listing among 5 is showing in the app.
2. Images are not showing.
3. The design of  downloaded source code is different from the latest 1.6.0 demo.
4. Not able to select the date in the booking screen.

**Comment by maltamap** [comment] 2019-01-16 18:46
To the best of my knowledge I followed the set up instructions but the app is not populating data from the site. It is able to collect my blog post but nothing else. The listings return "undefined". The map fails to load. Please advise on how I can tackle these issues.

**Comment by maltamap** [comment] 2019-01-16 18:47
When I try to select a category in the second menu option the icon spins around endlessly.
![genymotion for personal use - google pixel 1080x1920 420dpi - 192 168 56 101_959](https://user-images.githubusercontent.com/46758875/51271336-96c21980-19c7-11e9-8e63-f97249598caa.jpg)

**Comment by jabirismail** [comment] 2019-01-17 06:17
Hi Thang,

Waiting for your reply..

**Comment by minhcasi** [comment] 2019-01-21 14:44
Hi, could you update the latest version from Listapp will be fixed your issues, try to update the plugins as the following guide - https://inspireui.github.io/listapp/docs/setup#step-3-config-the-image

You an reopen the ticket if it is not worked, thank you!

**Closed by minhcasi** 2019-01-21 14:44 UTC
Labels: help wanted
