### ISSUE TITLE
Products duplicating when searching and error showing while making order , Caching not enable after installing Mstore API for Mstore , checkout error when making order MSTORE

### ISSUE THREAD

**Issue by febinmhd** [inspireui/support#4887] opened 2020-09-05 07:35 UTC
I have activated the Mstore API plugin in Wordpress but I cannot cache and change the layout nor is it showing caching enabled . please advice

I have added 3 products in my Woocommerce a for category but hen I open it in Mstore 3 products et duplicated and it shows 6 products. please advice . also when I make the order shows the error undefined is not an object.Please advice

when I make order it shows an error undefined not an object. evaluating user.billibg.first_name. I have provided all the billing info yet this comes up.

![IMG_6351](https://user-images.githubusercontent.com/51330162/92300382-10bf6180-ef63-11ea-98e0-43a305f6181f.PNG)
![IMG_6350](https://user-images.githubusercontent.com/51330162/92300390-1c128d00-ef63-11ea-893c-f89e3ed73fdd.PNG)
<img width="854" alt="Screen Shot 2020-09-03 at 11 19 15 AM" src="https://user-images.githubusercontent.com/51330162/92300402-25035e80-ef63-11ea-82b1-2ddc81ec672c.png">
<img width="317" alt="Screen Shot 2020-09-04 at 6 35 03 PM" src="https://user-images.githubusercontent.com/51330162/92300409-2df43000-ef63-11ea-8a55-b08518280b94.png">
<img width="317" alt="Screen Shot 2020-09-04 at 7 02 23 PM" src="https://user-images.githubusercontent.com/51330162/92300414-33517a80-ef63-11ea-842f-0fface134cb5.png">

**Comment by minhcasi** [comment] 2020-09-06 02:39
Duplicate of #4878

**Closed by minhcasi** 2020-09-06 02:39 UTC

**Comment by febinmhd** [comment] 2020-09-06 04:50
> Duplicate of #4878

I was instruced to move all the issues into a single issue..
