### ISSUE TITLE
Variations quantity didn't change 

### ISSUE THREAD

**Issue by mohamedlotfyemara** [inspireui/support#4257] opened 2020-07-18 22:52 UTC
![Simulator Screen Shot - iPhone X - 2020-07-19 at 00 45 36](https://user-images.githubusercontent.com/20433462/87863301-f224ed00-c959-11ea-82e3-c5273e3765dc.png)
![Simulator Screen Shot - iPhone X - 2020-07-19 at 00 45 29](https://user-images.githubusercontent.com/20433462/87863307-023ccc80-c95a-11ea-9356-9996c46938ae.png)

when select colors stock qauntity didn’t change although stock quantity is different

**Comment by minhcasi** [comment] 2020-07-19 03:42
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission.
 Thank you for your time!

**Comment by minhcasi** [comment] 2020-07-20 03:27
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-20 03:27 UTC
Labels: needs-more-info
