### ISSUE TITLE
[fluxstore pro] - cart shows error app is open again

### ISSUE THREAD

**Issue by tjain90** [inspireui/support#2671] opened 2020-04-12 12:02 UTC
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: carts shows attached error if it is open again.

2. Screenshots issues (required):
![Screenshot_20200412-173036](https://user-images.githubusercontent.com/6376301/79068301-8b04f600-7ce3-11ea-8159-e2ca1dc344dd.jpg)

3. Proof of my purchased (required): tjain90 from themeforest

3. Config files (required)

**Comment by tjain90** [comment] 2020-04-12 12:15
I am using woocomerce as my backend.

**Comment by minhcasi** [comment] 2020-04-13 01:18
Duplicate of #2615 - pls help to check solution on this issue (there is the patching on the ticket)

**Closed by minhcasi** 2020-04-13 01:18 UTC
Labels: FluxStore, question ❓
