### ISSUE TITLE
App Stopped Working

### ISSUE THREAD

**Issue by Deeshum** [inspireui/support#3933] opened 2020-06-26 18:53 UTC
Hi Team,

My app built on Fluxstore was working fine till two days back, however overnight I am not able to see any product in the app. I have not made any changes in my woo commerce setup. I am just not able to figure out the issue
![WhatsApp Image 2020-06-27 at 00 20 57](https://user-images.githubusercontent.com/21080920/85891086-2e0ddc00-b80c-11ea-9d39-2e01eaa1c551.jpeg)

**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment] 2020-06-26 18:59
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by ameenbadri7** [comment] 2020-06-26 21:50
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-06-27 05:42
verified ✅

**Comment by ameenbadri7** [comment] 2020-06-27 16:49
please send us your project `lib\common` and also `lib\config` to our email minhcasi@gmail.com and inspireui-team@inspireui.com

thank you for your patients

**Comment by ameenbadri7** [comment] 2020-06-29 05:14
I'm sorry to close this ticket as there is no response or active conversation, 
please help to create a new one and link to this ticket if the problem is not solved -

thank you for your time!

**Closed by ameenbadri7** 2020-06-29 05:14 UTC
Labels: FluxStore
