### ISSUE TITLE
Fluxstore pro can't connect with our magento website

### ISSUE THREAD

**Issue by hssinaman** [inspireui/support#2098] opened 2020-02-15 22:58 UTC
Hi,
we have configured Fluxstore Pro for our magento store ( magento 2.3.1) and we it cant't connect with website even we follow all steps of your documentation and also the products can't be displayed  as your demo and  please check the screenshots bellow :

products  invisible -> category products not displayed  :
https://pasteboard.co/IUR8ZLp.jpg

Config :
https://pasteboard.co/IUR9tki.jpg

Same config on magento admin side :
https://pasteboard.co/IUR9MQx.jpg

Access Token :
https://pasteboard.co/IURa9Xk.jpg
https://pasteboard.co/IURakscf.jpg

https://pasteboard.co/IURaqVg.jpg

we need your urgent help please 

![1 - problem](https://user-images.githubusercontent.com/61097607/74596381-c7530780-504e-11ea-8cb5-a5365b2977cb.jpeg)
![2- config](https://user-images.githubusercontent.com/61097607/74596382-c91ccb00-504e-11ea-99e2-ade64111dc48.jpeg)
![3- the same on the admin](https://user-images.githubusercontent.com/61097607/74596383-c9b56180-504e-11ea-993a-4c55d06b0748.jpeg)
![4- access -token](https://user-images.githubusercontent.com/61097607/74596384-ca4df800-504e-11ea-9e95-91445ecf4468.jpeg)
![4- access-token_2](https://user-images.githubusercontent.com/61097607/74596385-cae68e80-504e-11ea-82af-ee373b3cbfd4.jpeg)
![5](https://user-images.githubusercontent.com/61097607/74596386-cb7f2500-504e-11ea-8065-f65e2b6dd716.jpeg)

**Comment by inspireui-support** [comment] 2020-02-16 03:32
@hssinaman - Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads  it's used to verify your proof of purchase? sorry for any inconvenience - Thank you!

**Comment by inspireui-support** [comment] 2020-02-16 03:33
Duplicate of #2099

**Closed by inspireui-support** 2020-02-16 03:33 UTC
Labels: FluxStore

**Comment by hssinaman** [comment] 2020-02-16 07:01
![Screenshot_20200216_075946_com android chrome](https://user-images.githubusercontent.com/61097607/74600466-76650280-5092-11ea-8bbf-6e29a9664564.jpg)

**Comment by hssinaman** [comment] 2020-02-16 07:15
I have shared the proof of purchase
Please help asap
It's urgent please

**Comment by hssinaman** [comment] 2020-02-16 07:23
Here is another screen of email purchase proof

**Comment by hssinaman** [comment] 2020-02-16 07:36
Please help urgent

**Comment by hssinaman** [comment] 2020-02-17 16:10
The issue isn't fixed and we still can't connect Fluxstore to our magento
website and we can't display products

your developer asked us to change enableConfigurableProduct to False and we
did but not working.

here is the source code :
https://we.tl/t-e6d1MhMBrI

let us know if you can support your product or no
its 3 days awaiting for you and without any result
