### ISSUE TITLE
You cannot list resource showed suddenly [Please help urgently]

### ISSUE THREAD

**Issue by el2adiii** [inspireui/support#4269] opened 2020-07-20 00:05 UTC
Hi, thanks for the app. I'm using "FluxStore For Woocommerce"
Everything was running smoothly, until I downloaded the latest version, I started getting 
"{"code":"woocommerce_rest_cannot_view","message":"Sorry, you cannot list resources.","data":{"status":401}}" Error
The website is https://www.elqady.co/molly
-------------
All plugins installed including JWT Authentication with its codes added to .htaccess
Please help.
Thank you

+ Product & version: Fluxstore 1.7.6
+ Flutter (or React Native) version: Flutter
+ Testing Device/Simulator: Android Studio, macOS
+ Screenshot issues (drag the file to attach here): 

![Screen Shot 2020-07-20 at 2 02 06 AM](https://user-images.githubusercontent.com/24272642/87888454-48af2b80-ca2d-11ea-95a0-30caee39107b.png)
![Screen Shot 2020-07-20 at 2 01 56 AM](https://user-images.githubusercontent.com/24272642/87888456-4baa1c00-ca2d-11ea-97ed-b8dca29b4ed0.png)
![Screen Shot 2020-07-20 at 1 53 42 AM](https://user-images.githubusercontent.com/24272642/87888235-e0137f00-ca2b-11ea-901e-91cb37957385.png)

**Comment by ameenbadri7** [comment] 2020-07-20 00:24
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by el2adiii** [comment] 2020-07-20 00:29
Hi I have already submitted the data

*Best Regards,*


[image: photograph]

Mohamed ElQadi
*The Web Guy*
Email: yourguy@elqady.co
Phone: +201003773837 <01003773837>
Schedule a Meeting <https://elqady.co/book-me>
[image: Facebook] <https://fb.com/el2adiii>  [image: LinkedIn]
<https://www.linkedin.com/in/el2adiii/>  [image: Skype]  [image: Whatsapp]
<https://api.whatsapp.com/send?phone=201003773837&text=So,%20I%20heard%20you%20are%20my%20web%20guy.>
   www.ElQady.co <http://www.elqady.co/>


‪On Mon, Jul 20, 2020 at 2:24 AM ‫amin badri أمين بدري‬‎ <
notifications@github.com> wrote:‬

**Comment by minhcasi** [comment] 2020-07-20 03:19
@el2adiii - try to use subdomain with the port `80` - it seems there is an issue with your domain access, also make sure the domain config is the same from the app config - thank you!

**Comment by el2adiii** [comment] 2020-07-20 12:00
Hi, thank you.
I've used port 80 and I get 404 as below
[image: Screen Shot 2020-07-20 at 1.59.21 PM.png]

*Best Regards,*


[image: photograph]

Mohamed ElQadi
*The Web Guy*
Email: yourguy@elqady.co
Phone: +201003773837 <01003773837>
Schedule a Meeting <https://elqady.co/book-me>
[image: Facebook] <https://fb.com/el2adiii>  [image: LinkedIn]
<https://www.linkedin.com/in/el2adiii/>  [image: Skype]  [image: Whatsapp]
<https://api.whatsapp.com/send?phone=201003773837&text=So,%20I%20heard%20you%20are%20my%20web%20guy.>
   www.ElQady.co <http://www.elqady.co/>

**Comment by el2adiii** [comment] 2020-07-21 23:22
Hi, any updates please?

**Comment by minhcasi** [comment] 2020-07-22 04:28
@el2adiii - pls try to check this solution https://github.com/woocommerce/woocommerce/issues/24338

You could test the rest api is work or not via the PostMan tool - https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API

**Comment by el2adiii** [comment] 2020-07-23 00:38
> @el2adiii - pls try to check this solution [woocommerce/woocommerce#24338](https://github.com/woocommerce/woocommerce/issues/24338)
> 
> You could test the rest api is work or not via the PostMan tool - https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API

Thank you for your reply.
I'v tried the first solution but no luck
Also, I've tried to cal the API using postman but I'm getting the same message "401 not authorized". What can be the problem?
- Double checked cs & ck keys, generated new ones, but no luck as well
- HTTPS is configured correctly
- Authorization is enabled in .htaccess

Can you help please? It's urgent :(

**Comment by el2adiii** [comment] 2020-07-23 00:40
**Postman screenshots:**

![Screen Shot 2020-07-23 at 2 35 50 AM](https://user-images.githubusercontent.com/24272642/88242547-cffada00-cc8d-11ea-9117-a8af333cb316.png)
![Screen Shot 2020-07-23 at 2 36 09 AM](https://user-images.githubusercontent.com/24272642/88242553-d25d3400-cc8d-11ea-9304-c1581f3b6c3f.png)

**Comment by minhcasi** [comment] 2020-07-24 08:15
@el2adiii - please help to check these solutions from your server-side - https://robotninja.com/blog/fix-common-woocommerce-rest-api-issues/

**Comment by minhcasi** [comment] 2020-07-27 09:13
@el2adiii - let us know you have fixed your server issue, thank you!

**Comment by el2adiii** [comment] 2020-07-27 15:02
Hi, thank you for your support so far! 
I've tried all solutions with no luck :( Below is a screenshot from my .htaccess file
![Screen Shot 2020-07-27 at 5 00 46 PM](https://user-images.githubusercontent.com/24272642/88557699-d80a9f00-d02a-11ea-9662-31c0c225e0ed.png)

I even tried to disable all plugins except Woocommerce but I get the same error

**Comment by minhcasi** [comment] 2020-07-28 03:22
@el2adiii - pls try to Issue 4 from my link about to change your server or PHP version solutions

**Comment by minhcasi** [comment] 2020-07-30 04:29
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-30 04:29 UTC
Labels: FluxStore, REST_API_401
