### ISSUE TITLE
version 1.7.6 fluxstore,  payment paypal error

### ISSUE THREAD

**Issue by angelohu** [inspireui/support#4522] opened 2020-08-08 11:46 UTC
version 1.7.6 fluxstore,  payment paypal error
![image](https://user-images.githubusercontent.com/64202693/89709135-74169d80-d97d-11ea-8918-44af7b846eff.png)

**Comment by minhcasi** [comment] 2020-08-09 01:55
@angelohu  Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by angelohu** [comment] 2020-08-11 12:36
reply my problem?

**Comment by angelohu** [comment] 2020-08-12 07:54
@minhcasi

**Comment by minhcasi** [comment] 2020-08-12 13:49
@minhtruong315 - pls help to check this issue

**Comment by minhtruong315** [comment] 2020-08-13 09:27
@angelohu can u send me full your source code via email: minhtruong315@gmail.com
ping me when you sent. I'll help you check.
Thanks

**Comment by minhcasi** [comment] 2020-08-16 07:23
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved

Also, help to update latest release `1.7.7` -  - thank you for your time!

**Closed by minhcasi** 2020-08-16 07:23 UTC
Labels: FluxStore, order-payment
