### ISSUE TITLE
[Mstore multi vendor] - How to enable chat...

### ISSUE THREAD

**Issue by ZamanGoraya** [inspireui/support#1158] opened 2019-10-03 08:06 UTC
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. how to enable chat in [Mstore multi vendor]
![Mstore multi vendor](https://user-images.githubusercontent.com/52818458/66109681-a4afdd00-e5de-11e9-8aa3-9d648ed5094c.PNG)

**Comment by minhcasi** [comment] 2019-10-03 12:04
pls check this guide - https://docs.inspireui.com/mstore-mv/firebase/

Duplicate of #1153

**Closed by minhcasi** 2019-10-03 12:04 UTC
Labels: question ❓

**Comment by ZamanGoraya** [comment] 2019-10-03 15:57
will it work for android and ios both...?

**Comment by ZamanGoraya** [comment] 2019-10-03 16:03
will it work for android and ios both...?
