### ISSUE TITLE
[FluxStore] -  Shipping class cost issue

### ISSUE THREAD

**Issue by UTimung** [inspireui/support#2221] opened 2020-02-26 18:17 UTC
You said that Shipping class cost will now support on this latest version

But just now i tested new version

And it still shows ZERO amount

![Screenshot_20200226-234506](https://user-images.githubusercontent.com/18107447/75374469-5df6b280-58f2-11ea-8e88-03b5a0fc57f5.png)

**Comment by kvt0012** [comment] 2020-02-27 04:26
It's already had but we just demo on Vietnam Religion, you can test by Vietnam religion with code is 700000. 
Thank you

**Comment by UTimung** [comment] 2020-02-27 04:32
I change the url , consumer key,  consumer secret key to my woocommerce key

And it shows ZERO Shipping charge

**Comment by kvt0012** [comment] 2020-02-27 04:32
Can you send me your config file ? 
Thank you

**Comment by kvt0012** [comment] 2020-02-27 04:34
> I change the url , consumer key, consumer secret key to my woocommerce key
> 
> And it shows ZERO Shipping charge
Oh so you should config on your woocomerce api, on shipping tab 
![image](https://user-images.githubusercontent.com/49152325/75412488-279e4f00-5955-11ea-87f4-384fbdfd73e8.png)

**Comment by UTimung** [comment] 2020-02-27 04:42
I already config shipping class cost in woocommerce

Check the image
![Screenshot_20200214-135133~2](https://user-images.githubusercontent.com/18107447/75412775-8e1d7000-5949-11ea-8a96-b2242beaddac.png)

**Comment by UTimung** [comment] 2020-02-27 04:50
my config.dart and json file
https://drive.google.com/open?id=1N1S-m_Rv80PIg4FCYb4-vg93lB8Cr-oY

**Comment by kvt0012** [comment] 2020-02-27 08:23
![image](https://user-images.githubusercontent.com/49152325/75425309-077e8800-5975-11ea-8e6d-cff8a03e14aa.png)

Dear sir, I'll test and our app is displayed all options. 
Thank you

**Comment by UTimung** [comment] 2020-02-27 08:28
Don't show someone app screenshot
In my woocommerce it dont even have local pickup, 

There is only one option 
That's Shipping charge only

Check it
![Screenshot_20200226-234506](https://user-images.githubusercontent.com/18107447/75425643-2119d280-5969-11ea-9194-387b28eb3017.png)

**Comment by kvt0012** [comment] 2020-02-27 08:38
Dear sir, 
I 'll check on your config file with your api and our api. Our api is normal. 
I think the problem is on your woocomerce api, please check it again. 
Thank you

**Comment by UTimung** [comment] 2020-02-27 08:42
What i have to do in woocommerce settings?

Should i revoke Rest api or other else?

**Comment by kvt0012** [comment] 2020-02-27 08:51
Firstly, you can create 3 of these like us. 
1. Local. On this feature, you can choose your country and your zip code first. 
2. Everywhere. The region is everywhere, it means that you don't write anything to it. 

3. Locations not covered by your other zones. 
![image](https://user-images.githubusercontent.com/49152325/75426920-27fc1180-5978-11ea-8892-79aef23e6a97.png)

I give example of Local first, everywhere is the same. 
![image](https://user-images.githubusercontent.com/49152325/75427181-9640d400-5978-11ea-81d6-c2744cdc0dba.png)
![image](https://user-images.githubusercontent.com/49152325/75427204-a22c9600-5978-11ea-9a68-98922464dc25.png)
![image](https://user-images.githubusercontent.com/49152325/75427219-ad7fc180-5978-11ea-9ef6-8eef4f247e0c.png)
![image](https://user-images.githubusercontent.com/49152325/75427239-b8d2ed00-5978-11ea-8cbc-6a255999e72a.png)

And now you can try with local first. You write your country and zipcode that you assign above here and click next to test it. 
The same as us is Vietnam, zip code is 700000
![image](https://user-images.githubusercontent.com/49152325/75427396-fe8fb580-5978-11ea-8af7-bb605f785279.png)

Thank you

**Comment by UTimung** [comment] 2020-02-27 09:02
I already setup my shipping method before
And its working fine in website

Just your app couldn't show the shipping class cost amount

This is my shipping method
All are shipping class cost method, 

No free shipping , no local pickup

![Screenshot_20200227-142707~2](https://user-images.githubusercontent.com/18107447/75428196-cd5db800-596d-11ea-884e-35c5db0b1ffb.png)

**Comment by kvt0012** [comment] 2020-02-27 09:54
Can you share me your api account ? I will check it because I can't know which inside

**Comment by UTimung** [comment] 2020-02-27 09:59
I sent admin login details, please check your email

**Comment by kvt0012** [comment] 2020-02-27 10:11
Ok, so now it works with zip code 782460
![image](https://user-images.githubusercontent.com/49152325/75434383-06088c00-5984-11ea-86b2-f4d3dd2c4da5.png)

I buy 5 products and 50$/ product * 5 = 250$ 
![image](https://user-images.githubusercontent.com/49152325/75434461-246e8780-5984-11ea-8eec-ad8767ecf803.png)

**Comment by UTimung** [comment] 2020-02-27 10:15
There's no such embellished dress products on my woocommerce

Try with my config files

**Comment by kvt0012** [comment] 2020-02-27 10:17
![image](https://user-images.githubusercontent.com/49152325/75435035-07868400-5985-11ea-9734-100e489e98c5.png)
 
Here, I check on your api.

**Comment by UTimung** [comment] 2020-02-27 10:20
How you fixed that
Did you Change anything ?

**Comment by kvt0012** [comment] 2020-02-27 10:21
> How you fixed that
> Did you Change anything ?

I just fix on your woocomerce api 
you can check again with your app

**Comment by kvt0012** [comment] 2020-02-27 10:25
You can check the newest order, nothing is hidden you, so you can make the another one order for sure

**Comment by UTimung** [comment] 2020-02-27 10:25
Yeah now ok
But can you hide the condition formula 50*[qty]
And show only the amount 50

![Screenshot_20200227-155240](https://user-images.githubusercontent.com/18107447/75435798-9392ae80-5979-11ea-85a1-c9787319a451.png)

**Comment by kvt0012** [comment] 2020-02-27 10:36
Yes, you can change this code to do this. 
![image](https://user-images.githubusercontent.com/49152325/75436708-9ac0b900-5987-11ea-8616-313dd588a85c.png)

**Comment by UTimung** [comment] 2020-02-27 10:37
What code should i add
Or i have to remove that line of code

**Comment by kvt0012** [comment] 2020-02-27 10:38
It's up to you :D 
Remove is a option 💯

**Comment by UTimung** [comment] 2020-02-27 10:40
Your app showing logo splash screen

How to make png image full splash screen

**Comment by kvt0012** [comment] 2020-02-27 10:44
You can change it on asset folder.

**Comment by kvt0012** [comment] 2020-02-27 10:49
Ah please remember to change your woocomerce api password for sure. 
Thank you

**Comment by UTimung** [comment] 2020-02-27 12:12
Helo
Shipping class cost works only on this pincode 782460

But not working on other pincode

**Comment by kvt0012** [comment] 2020-02-28 02:31
I just set up 1 situation for example, you can based on this and edit whichever you want.

**Comment by UTimung** [comment] 2020-02-28 02:45
> Yes, you can change this code to do this.
> ![image](https://user-images.githubusercontent.com/49152325/75436708-9ac0b900-5987-11ea-8616-313dd588a85c.png)

I removed this line and it shows only the shipping title
Amount not showing

**Comment by kvt0012** [comment] 2020-02-28 02:59
> > Yes, you can change this code to do this.
> > ![image](https://user-images.githubusercontent.com/49152325/75436708-9ac0b900-5987-11ea-8616-313dd588a85c.png)
> 
> I removed this line and it shows only the shipping title
> Amount not showing

Yes of course, so it's up to you.

**Comment by UTimung** [comment] 2020-02-28 03:02
But i want to show the amount,
Just want to hide the formula only *[qty]

**Comment by kvt0012** [comment] 2020-02-28 03:05
we will record your idea and discuss with our team about this feature, thank you.

**Comment by UTimung** [comment] 2020-02-28 04:50
So how many days i have to wait for that feature?

**Comment by kvt0012** [comment] 2020-02-28 08:10
we expect as soon as possible

**Comment by UTimung** [comment] 2020-02-28 08:12
Ok
In blog i use simpleType

The blog list are showing
But if i open it shows red error
![Screenshot_20200227-231216](https://user-images.githubusercontent.com/18107447/75522497-242bc600-5a30-11ea-9119-91947c679447.png)

**Comment by UTimung** [comment] 2020-02-28 08:18
config.dart

"blog":
      "https://mydomain.in", //Your website woocommerce. You can remove this line if it same url
"DetailedBlogLayout": kBlogLayout.simpleType,

**Comment by kvt0012** [comment] 2020-02-28 10:02
Because you open #2234 , so I will close this issue. 
Thank you

**Closed by kvt0012** 2020-02-28 10:02 UTC
Labels: FluxStore, question ❓
