### ISSUE TITLE
payment getway not working

### ISSUE THREAD

**Issue by mdyunus24bd** [inspireui/support#3763] opened 2020-06-16 09:48 UTC
My PayPal Express Checkout plugin payment gateway not working on your Fluxstore MV 1.7.5 version. see my website Checkout page not loading getaway page.
I see same problems on your 1.6.6b version but this time help to @philipvu30 on skype. he asks Paypal enabled to give a false and I try it this time is working fine. but now this option I give a false on your 1.7.5 version is not working. please help us...
![Annotation 2020-06-13 231104](https://user-images.githubusercontent.com/56026816/84759386-b6ec7280-afd7-11ea-88d6-648c9df2a33a.jpg)
![Annotation 2020-06-13 231152](https://user-images.githubusercontent.com/56026816/84759398-ba7ff980-afd7-11ea-98ef-410d57128726.jpg)
![Annotation 2020-06-12 112934](https://user-images.githubusercontent.com/56026816/84759420-beac1700-afd7-11ea-9332-22cd0915d4eb.jpg)

https://user-images.githubusercontent.com/56026816/77499667-2a189980-6e6c-11ea-985c-eacb506e8615.png

**Comment by minhcasi** [comment] 2020-06-17 02:00
@mdyunus24bd - pls don't share the source here

**Comment by mdyunus24bd** [comment] 2020-06-17 07:13
Thanks your suggest

**Comment by philipvu30** [comment] 2020-06-18 02:57
Hi,

Sorry for the delayed response. Since you only sent us your config.dart file, I didn't have enough information to identify your issue.
So I'll assume here is your current trouble: You want to enable the Paypal payment method but you don't know how? 
Solution -> In lib/common/config/payments.dart:
1.  Set "EnableOnePageCheckout" to false in kPaymentConfig.
2. Set  "enabled" to true in PayPalConfig to enable Paypal Payment. If you need to test the app payment, set "production" to false, otherwise, set it to true.

**Comment by mdyunus24bd** [comment] 2020-06-18 16:44
I try it 
I give an "enabled": true, see a blank page and give an "enabled": false, see my website checkout page.

"production": true, or false give no change..

 you check it


![Annotation 2020-06-18 203731](https://user-images.githubusercontent.com/56026816/85048215-10090180-b1a4-11ea-9618-95bc3cac05c5.jpg)
![Annotation 2020-06-18 204031](https://user-images.githubusercontent.com/56026816/85048224-1303f200-b1a4-11ea-9d0a-1e9d2a94a28c.jpg)
![Annotation 2020-06-18 203615](https://user-images.githubusercontent.com/56026816/85048227-139c8880-b1a4-11ea-873e-6668a38932fd.jpg)

**/// Server config demo for WooCommerce
const serverConfig = {
  "type": "dokan", // type: dokan or wcfm
  "url": "https://evaanno.com",

  /// document: https://docs.inspireui.com/fluxstore/woocommerce-setup/
  "consumerKey": "ck_313abdd7cecf705106850c37414528737b343ab6",
  "consumerSecret": "cs_dd499c7ff02fab2312547b8d7246ddeb364e68f7",

  /// Your website woocommerce. You can remove this line if it same url
  "blog": "https://evaanno.com",

  /// set blank to use as native screen
  "forgetPassword": "https://evaanno.com/my-account/lost-password"
};
**
you check it..

**Comment by philipvu30** [comment] 2020-06-19 07:24
Hi,

Please make sure you have enabled the PayPal option on your website as I don't see the Paypal method in the returned response.

![image](https://user-images.githubusercontent.com/54442328/85107681-8fe0ab80-b238-11ea-8812-f09a14109065.png)

**Comment by mdyunus24bd** [comment] 2020-06-19 08:17
I use a PayPal express checkout plugin not use Paypal...

see your 1.6.6b version apps on my google play store download and check it .
https://play.google.com/store/apps/details?id=com.evaanno.webview&hl=en 
this app I build it. it's working fine . your 1.7.5 not working...
![Annotation 2020-06-19 121229](https://user-images.githubusercontent.com/56026816/85112466-b7c71380-b226-11ea-8003-f9bada634949.jpg)

**Comment by philipvu30** [comment] 2020-06-19 08:27
Hi,

Please change "paypal" -> "ppec_paypal" in lib/common/config/payments.dart

![image](https://user-images.githubusercontent.com/54442328/85113408-6e37f200-b241-11ea-92ea-b0a89a914d71.png)

**Comment by mdyunus24bd** [comment] 2020-06-19 09:15
i try it not working . **  "enabled": true,** see this problems
![Annotation 2020-06-19 130734](https://user-images.githubusercontent.com/56026816/85116685-bdc0f280-b22e-11ea-90c1-754d5abb5a93.jpg)

  "enabled": false,
see my website checkout page

**Comment by philipvu30** [comment] 2020-06-19 09:17
Hi,

Please send you common and config folders to my email: toan@inspireui.com along with access to your website.

Thank you.

**Comment by mdyunus24bd** [comment] 2020-06-19 09:20
i send it check it full source file

**Comment by philipvu30** [comment] 2020-06-19 09:21
@mdyunus24bd 

Create a support account for your website and send it to me also.

**Comment by mdyunus24bd** [comment] 2020-06-19 09:23
whats support accounts i don't know

**Comment by philipvu30** [comment] 2020-06-19 09:25
@mdyunus24bd 

Just create an account with admin privilege access. Then send it to toan@inspireui.com. You can delete it later.

**Comment by mdyunus24bd** [comment] 2020-06-19 09:27
send it

**Comment by mdyunus24bd** [comment] 2020-06-19 09:29
this file   "isCaching":give a  false, after run .your  "isCaching give a true apps not run

**Comment by philipvu30** [comment] 2020-06-19 09:44
Hi @mdyunus24bd ,

Please send me Paypal's ClientId and Secret for both Sandbox mode and Live mode.

Thank you.

**Comment by mdyunus24bd** [comment] 2020-06-19 09:52
sandbox..
ClientId:- Ad-tawk5dZnBWSekSbMMCGfTBcbWATvX2N_yjhMA5iwed473Ta9cWdqRD10ouw0UxPIiFkGCG59X3Zyi
Secret:- EIDhm0oB0lqsyTwNgYkFuTrxKTQt4dm7_4WQGlYAz2it5Ab887LlsmE4w4T9btvmModTKD9ymn8GDMoe

Live mode..
ClientId:- AcyfhQLZx02fJBf6z-dBVXNMOvmb0yobzZD8YQdLDiObPdPj15Z9Nz1-SrFjFaRI6EqSVfDT6HjYzKlk
Secret:- EAoGMcXhvFCGtjsY5ou9r7st1ktrcYy13-dpGpE9LrcvHLbqdZXjKVFJQvKVVOdlP3HxgQcqcAHMFgYJ

**Comment by philipvu30** [comment] 2020-06-19 09:54
Got the info.

**Comment by philipvu30** [comment] 2020-06-19 10:26
Hi,

Please follow these steps in lib/common/config:
1. Replace the general.dart
2. If you are testing the app, use payment_sandbox.dart.zip (just unzip, replace, and don't change the name). If not, please use payment_live.dart.zip (just unzip, replace, and don't change the name).

**Comment by philipvu30** [comment] 2020-06-19 10:28
I sent you the files via email.

Remember to change the option for the payment on your website as well. 

If testing, select SandBox. If not, select Live

![image](https://user-images.githubusercontent.com/54442328/85123340-4bfaa000-b252-11ea-9b1a-d0aeac2317bf.png)

**Comment by mdyunus24bd** [comment] 2020-06-19 11:06
credit/debit Card payment not show apps .my website is working fine..


![Annotation 2020-06-19 150025](https://user-images.githubusercontent.com/56026816/85126238-1ea3f700-b23e-11ea-9622-bc010c5b9fe4.jpg)

![Annotation 2020-06-19 145925](https://user-images.githubusercontent.com/56026816/85126231-1c419d00-b23e-11ea-9c8a-b9cf8634f0a0.jpg)

you check it buy product apps log in id..
username- 97576151
password- Mdyunus2014@
shipping country -Oman

**Comment by philipvu30** [comment] 2020-06-19 11:09
It's the title of your Payment Method. 
I just changed the Credit/Debit card to Paypal Checkout to make it clearer for you.

**Comment by mdyunus24bd** [comment] 2020-06-19 11:14
yes i know

**Comment by mdyunus24bd** [comment] 2020-06-19 11:16
now comes a paypal log in option not comes card payment
![Annotation 2020-06-19 150025](https://user-images.githubusercontent.com/56026816/85127068-c5d55e00-b23f-11ea-9297-ec3e74abe8f0.jpg)

**Comment by philipvu30** [comment] 2020-06-22 04:32
Hi,

It shows on my device. I think the CC/Debit payment of Paypal depends on the device's location though.

**Comment by mdyunus24bd** [comment] 2020-06-22 08:49
I see same location  device on my website and old version 1.6.6b apps, show pay card payment but your 1.7.5 apps not show...
![Screenshot_20200622-124643](https://user-images.githubusercontent.com/56026816/85267591-83ea2900-b486-11ea-8351-ed8faa808fb1.png)

**Comment by philipvu30** [comment] 2020-06-22 09:56
Hi,

I cannot determine what is the problem and cannot reproduce your issue. You can try to use the OnePageCheckOut option.

Thank you.

**Comment by mdyunus24bd** [comment] 2020-06-23 07:37
Why working your 1.6.6b version, you check it any change there,your side working my side not working... please check it previous i see same problem on your 1.6.6b version after you solve it, you check skype message

**Comment by philipvu30** [comment] 2020-06-25 09:33
Closed as the error does not happen on FluxStore Demo.

**Closed by philipvu30** 2020-06-25 09:33 UTC
Labels: FluxstoreMV, order-payment
