### ISSUE TITLE
Fluxstore Pro

### ISSUE THREAD

**Issue by samik9** [inspireui/support#940] opened 2019-08-17 23:07 UTC
- [ ]When "EnableShipping": false, this happens, the  user can see shipping when click go back
 vide: https://d.pr/v/NJf8pt

---------

**Comment by minhcasi** [comment] 2019-08-19 12:00
Duplicate of #942

@samik9  - pls help to post your all issues for one ticket that help the team to focus on your issue

**Closed by minhcasi** 2019-08-19 12:00 UTC
Labels: Backlog, question ❓
