### ISSUE TITLE
error in building flutter app for woocommerce

### ISSUE THREAD

**Issue by abdulmannankhan1** [inspireui/support#4446] opened 2020-08-02 10:21 UTC
Target debug_android_application failed: FileSystemException: Cannot copy file to 'G:\CHRO.ME\WORDPRESS\flutter\fluxstore-175\codecanyon-24020929-fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework\FluxStore 1.7.5\source\build\app\intermediates\flutter\debug\flutter_assets\assets/icons/categories/ic_broom.png', path = 'G:\CHRO.ME\WORDPRESS\flutter\fluxstore-175\codecanyon-24020929-fluxstore-the-universal-woocommerce-magento-opencart-mobile-app-by-flutter-framework\FluxStore 1.7.5\source\assets\icons\categories\ic_broom.png' (OS Error: The system cannot find the path specified.
, errno = 3)
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'F:\App\flutter_windows_1.17.5-stable1\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'F:\App\flutter_windows_1.17.5-stable1\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8m 42s
The batch file cannot be found.
Exception: Gradle task assembleDebug failed with exit code 1

![1](https://user-images.githubusercontent.com/61900395/89120918-d2ec9a80-d4d7-11ea-80ee-08483aea2fe4.png)

[buildgradle.zip](https://github.com/inspireui/support/files/5011964/buildgradle.zip)

Help Me

**Comment by minhcasi** [comment] 2020-08-03 02:31
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-08-04 02:03
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-08-04 02:03 UTC
Labels: needs-more-info
