### ISSUE TITLE
Language change doesn't change categories names

### ISSUE THREAD

**Issue by Mrqozy** [inspireui/support#4277] opened 2020-07-20 12:27 UTC
Hi. 
I'm using wpml. 
I translated categories and products. 
When I change the language products changes correctly. 

But categories names and thumbnails doesn't change! 

i already submitted my verification.

**Comment by Mrqozy** [comment] 2020-07-20 13:37
please note i submitted a verification at verify.inspireui.com

**Comment by ameenbadri7** [comment] 2020-07-20 17:21
That's a question to ask the wpml plugin team not us.
but it should be inside `your_website/wp-admin/admin.php?page=wpml-wcml&tab=product_cat`
thank you.

**Comment by Mrqozy** [comment] 2020-07-20 17:45
Hi ameen.
What do you mean ask the wpml team? 
The problem is with the app I think. 

Some other guy asked this question and someone from your team fixed it for him.
If I restart the app the language changes and categories are shown correctly.

Can you take a look at my files and check it?

**Comment by ameenbadri7** [comment] 2020-07-20 17:55
Can you provide screenshots from inside the app and also screenshot from your website `WooCommerce Multilingual`
to see if you have config the wpml.

Please check our [support policies ](https://inspireui.com/support-policies).
We don't take customization requests for the regular license but you can buy the Extended License or the Support Pack and email us with your request via our email.

Thank you.

**Comment by Mrqozy** [comment] 2020-07-20 21:10
hi ameen.
thank you for your fast reply.


as you can see below categories are translated and they show on my website.
they even show in the app but i have to force stop from settings then restart the app again and categories names will be translated.


here you go.
i attached below the screenshots.

![Screenshot_1595278641](https://user-images.githubusercontent.com/40011623/87986876-655b6a00-cae6-11ea-987b-149afc322eb3.png)
![Screenshot_1595278628](https://user-images.githubusercontent.com/40011623/87986878-65f40080-cae6-11ea-9b23-54a85c6bed37.png)


![Screenshot (69)](https://user-images.githubusercontent.com/40011623/87986217-7ce62300-cae5-11ea-8faa-63cdbec11c60.jpg)
![Screenshot (68)](https://user-images.githubusercontent.com/40011623/87986219-7e175000-cae5-11ea-87d9-70b08fbf4fe4.jpg)
![Screenshot (67)](https://user-images.githubusercontent.com/40011623/87986223-7eafe680-cae5-11ea-9fd1-dbae6de9ba65.jpg)
![Screenshot_1595279340](https://user-images.githubusercontent.com/40011623/87986875-642a3d00-cae6-11ea-9ad5-a7028dd5fc79.png)

**Comment by ameenbadri7** [comment] 2020-07-20 23:40
Could you build a `release` version of your app and test you app again.  
In debug allot of things could be happening ..
Thank you for your time !

**Comment by Mrqozy** [comment] 2020-07-21 00:41
hi ameen.
i built it for release and got this release file name "app-release.apk"

it didnt work.
if i force stop my app and then restart it the categories names changes!

any idea why?

thank you so much

**Comment by minhcasi** [comment] 2020-07-21 02:30
@Mrqozy - did you try to install this plugin? https://wordpress.org/plugins/wpml-to-wp-api/

**Comment by Mrqozy** [comment] 2020-07-21 12:53
hi @minhcasi 
yes its here
see attached photos below.
i even tried to delete the wordpress site and recreate it.
i deleted my source code and downloaded new source code but still the same issue.

if i change the language then force stop the app and relaunch
 it i get correct Categories names!!
so wpml is doing its job i think.

![Screenshot (71)](https://user-images.githubusercontent.com/40011623/88057090-3c7cb880-cb6a-11ea-8a8c-3ae8054590df.png)


thank you

**Comment by Mrqozy** [comment] 2020-07-21 13:19
@minhcasi 
im getting this error when i change the language

`I/flutter (10618): #0      _ChunkedJsonParser.fail  (dart:convert-patch/convert_patch.dart:1394:5)
I/flutter (10618): #1      _ChunkedJsonParser.close  (dart:convert-patch/convert_patch.dart:512:7)
I/flutter (10618): #2      _parseJson  (dart:convert-patch/convert_patch.dart:32:10)
I/flutter (10618): #3      JsonDecoder.convert  (dart:convert/json.dart:505:36)
I/flutter (10618): #4      JsonCodec.decode  (dart:convert/json.dart:153:41)
I/flutter (10618): #5      jsonDecode  (dart:convert/json.dart:96:10)
I/flutter (10618): #6      WooCommerce.getCurrencyRate 
package:fstore/services/woo_commerce.dart:1119
I/flutter (10618): <asynchronous suspension>
I/flutter (10618): #7      Services.getCurrencyRate 
package:fstore/services/index.dart:406
I/flutter (10618): #8      AppModel.loadAppConfig 
package:fstore/models/app.dart:172
I/flutter (10618): <asynchronous suspension>
I/flutter (10618): #9      AppModel.changeLanguage 
package:fstore/models/app.dart:57
I/flutter (10618): <asynchronous suspension>
I/flutter (10618): #10     _LanguageState.build.<anonymous closure> 
package:fstore/…/settings/language.dart:61
I/flutter (10618): #11     _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:779
I/flutter (10618): #12     _InkResponseState.build.<anonymous closure> (pac`




is this the problem?

**Comment by minhcasi** [comment] 2020-07-23 04:37
@Mrqozy - this may not the root cause, pls try to move your existing app on simulator and try again. 

Then observe the detail log to see if any issue during changing the language?

**Comment by Mrqozy** [comment] 2020-07-25 02:28
@minhcasi 
hi there.
i tried it on 3 emulators and 2 real devices.
same issue.

`I/flutter ( 5488): #5      jsonDecode  (dart:convert/json.dart:96:10)
I/flutter ( 5488): #6      WooCommerce.getCurrencyRate 
package:fstore/services/woo_commerce.dart:1119
I/flutter ( 5488): <asynchronous suspension>
I/flutter ( 5488): #7      Services.getCurrencyRate 
package:fstore/services/index.dart:406
I/flutter ( 5488): #8      AppModel.loadAppConfig 
package:fstore/models/app.dart:171
I/flutter ( 5488): <asynchronous suspension>
I/flutter ( 5488): #9      AppModel.changeLanguage 
package:fstore/models/app.dart:57
I/flutter ( 5488): <asynchronous suspension>
I/flutter ( 5488): #10     _LanguageState.build.<anonymous closure> 
package:fstore/…/settings/language.dart:55
I/flutter ( 5488): #11     _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:779
I/flutter ( 5488): #12     _InkResponseState.build.<anonymous closure> (pac
I/flutter ( 5488): [2020-07-25 02:25:20.757986Z][Fluxstore][Category] getCategories
I/flutter ( 5488): [2020-07-25 02:25:20.775730Z][Fluxstore][AppState] build Theme`


this is the code i get in the log the moment i press change language

**Comment by minhcasi** [comment] 2020-07-25 06:27
@Mrqozy - we have created this pre-config site to support for the config on your site - could you help to give a try? https://docs.inspireui.com/fluxstore/multi-vendor/#1-website-integration

**Comment by Mrqozy** [comment] 2020-07-25 11:55
OK I will and I will let you know

**Comment by ameenbadri7** [comment] 2020-07-26 16:07
please let us know if you fixed this issue so we can close it.

Thank you.

**Closed** 2020-07-27 01:49 UTC
Labels: FluxStore
