### ISSUE TITLE
Remove blog 

### ISSUE THREAD

**Issue by mercadocerouno** [inspireui/support#3894] opened 2020-06-24 18:00 UTC
How can i remove the icon and the blog section 

<img width="331" alt="Screen Shot 2020-06-24 at 10 47 10 AM" src="https://user-images.githubusercontent.com/66270970/85608355-d4d65a80-b609-11ea-8eea-fb73c27564a4.png">

**Comment by ameenbadri7** [comment] 2020-06-24 19:54
inside fluxstore source folder, you will find ` lib\common\config\general.dart`

```
const kDefaultDrawer = {
  "logo": "assets/images/logo.png",
  "background": null,
  "items": [
    {"type": "home", "show": true},
    {"type": "blog", "show": true},
    {"type": "login", "show": true},
    {"type": "category", "show": true}
  ]
};
```
`blog", "show": false ` to hide the blog from the `Drawer`.

please read the documentation at [this link](https://docs.inspireui.com/fluxstore/customization/)

**Comment by mercadocerouno** [comment] 2020-06-24 20:40
Im in that part and i dont the part you mention
<img width="1435" alt="Screen Shot 2020-06-24 at 1 38 15 PM" src="https://user-images.githubusercontent.com/66270970/85625387-3c97a000-b620-11ea-9a0e-a4e03d9b0441.png">
<img width="1418" alt="Screen Shot 2020-06-24 at 1 39 21 PM" src="https://user-images.githubusercontent.com/66270970/85625403-3f929080-b620-11ea-8e97-b47ba098b80c.png">
<img width="1407" alt="Screen Shot 2020-06-24 at 1 38 55 PM" src="https://user-images.githubusercontent.com/66270970/85625405-40c3bd80-b620-11ea-9b62-f02b6516b872.png">

**Comment by ameenbadri7** [comment] 2020-06-24 22:08
you are using 1.7.3 please update to the latest 1.7.5 
we updated this option.

**Comment by minhcasi** [comment] 2020-06-25 00:01
@mercadocerouno 

Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-06-26 01:53
Duplicate of #3909

**Closed by minhcasi** 2020-06-26 01:53 UTC
Labels: needs-more-info
