### ISSUE TITLE
Cannot book this product (listapp) (my Listing) (WC Bookings)

### ISSUE THREAD

**Issue by codingastronaut** [inspireui/support#1156] opened 2019-10-02 08:04 UTC
ive tried every possible option, ive enabled booking from the code, I've enabled the rest for wc bookings API from WordPress.
the app still shows "cant Book This Product"
please what are the individual steps i need to take to enable full booking with wc vendors and listapp in my listing theme
![Screenshot from 2019-10-02 09 03 08](https://user-images.githubusercontent.com/17095995/66027773-8620e780-e4f3-11e9-97e6-b432c06190bd.jpeg)

**Comment by minhcasi** [comment] 2019-10-02 08:36
@codingastronaut - could you help to check this guide - https://docs.inspireui.com/listapp/customization/#11-how-to-enable-the-booking-feature - thank you!

**Comment by codingastronaut** [comment] 2019-10-03 02:55
thank you, but it still shows "Cannot Book this product" please tell me the step by step to enable booking on my theme and on list app (my theme is "Listable") i have both wc bookings and job manager, please tell me step by step, its very important

**Comment by codingastronaut** [comment] 2019-10-03 23:44
hello @minhcasi i havent heard back, please give me the steps after setting booking as true, it still showing "cant book this product"

**Comment by codingastronaut** [comment] 2019-10-06 04:45
hello @minhcasi please get back to me, this is not goot servoce at all, please help me solve this problem, i can give you access to my site if you want PLEASE

**Comment by codingastronaut** [comment] 2019-10-06 21:53
Hello @minhcasi @luyx2412 @vumanhsn97 could you please let me know if my question is going to be answered? and the steps to follow please

**Comment by minhcasi** [comment] 2019-10-09 12:00
@codingastronaut - sorry for some delay as we have a problem with the resource for listapp to fix the problem, we will resolve this resource issue soon - thank you for your patient

**Comment by minhcasi** [comment] 2019-10-09 12:01
Duplicate of #1156

**Closed by minhcasi** 2019-10-09 12:01 UTC
Labels: ListingApp, question ❓
