### ISSUE TITLE
error when compiling for ios impossible to execute command: flutter build ios Codepoint 58849 not found in font, aborting

### ISSUE THREAD

**Issue by victor1409** [inspireui/support#4517] opened 2020-08-08 01:06 UTC
error when compiling for ios impossible to execute command: flutter build ios Codepoint 58849 not found in font, aborting

<img width="1138" alt="Captura de Pantalla 2020-08-07 a la(s) 8 03 14 p  m" src="https://user-images.githubusercontent.com/67571967/89698910-69122d80-d8e9-11ea-89b3-5fd6043dec2a.png">

@minhcasi

**Comment by victor1409** [comment] 2020-08-08 01:11
<img width="1130" alt="Captura de Pantalla 2020-08-07 a la(s) 8 10 18 p  m" src="https://user-images.githubusercontent.com/67571967/89699044-18e79b00-d8ea-11ea-9913-6f482866b1b7.png">

**Comment by minhcasi** [comment] 2020-08-08 01:22
Duplicate of #4502 - pls help to move your all comment to this open ticket

**Closed by minhcasi** 2020-08-08 01:22 UTC

**Comment by victor1409** [comment] 2020-08-08 02:15
This case is on iOS #4502 es for Android but codepoint 58849 are in two case
