### ISSUE TITLE
VScode Flutter run error

### ISSUE THREAD

**Issue by yomight** [inspireui/support#4775] opened 2020-08-28 04:06 UTC
I get this errors below whenever I run this code ‘flutter run’ I get the below errors. I am using VScode. I am using my SAMSUNG Note 4 as emulator.

[Fatal Error] google-services-4.3.2.pom:2:1: Content is not allowed in prolog. [Fatal Error] kotlin-gradle-plugin-1.3.50.pom:2:1: Content is not allowed in prolog. [Fatal Error] gradle-3.5.0.pom:2:1: Content is not allowed in prolog.

FAILURE: Build failed with an exception.

What went wrong: A problem occurred configuring root project ‘android’. > Could not resolve all artifacts for configuration ’:classpath’. > Could not resolve com.google.gms:google-services:4.3.2. Required by: project : > Could not resolve com.google.gms:google-services:4.3.2. > Could not parse POM https://dl.google.com/dl/android/maven2/com/google/gms/google-services/4.3.2/google-services-4.3.2.pom > Content is not allowed in prolog. > Could not resolve com.android.tools.build:gradle:3.5.0. Required by: project : > Could not resolve com.android.tools.build:gradle:3.5.0. > Could not parse POM https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.5.0/gradle-3.5.0.pom > Content is not allowed in prolog. > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50. Required by: project : > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50. > Could not parse POM https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.50/kotlin-gradle-plugin-1.3.50.pom > Content is not allowed in prolog.
Try: Run with—stacktrace option to get the stack trace. Run with—info or—debug option to get more log output. Run with—scan to get full insights.
Get more help at https://help.gradle.org
BUILD FAILED in 1m 46s Running Gradle task ‘assembleDebug’... Running Gradle task ‘assembleDebug’... Done 113.1s Exception: Gradle task assembleDebug failed with exit code 1

This is—stacktrace

—stacktrace At line:1 char:3 +—stacktrace + ~ Missing expression after unary operator ’—’. At line:1 char:3 +—stacktrace + ~~~~~~ Unexpected token ‘stacktrace’ in expression or statement. + CategoryInfo : ParserError: (:) [], ParentContainsErrorRecordException + FullyQualifiedErrorId : MissingExpressionAfterOperator

**Comment by minhcasi** [comment] 2020-08-28 04:23
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-08-29 06:03
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-08-29 06:03 UTC
Labels: needs-more-info
