### ISSUE TITLE
Language Support

### ISSUE THREAD

**Issue by mpnihad** [inspireui/support#3584] opened 2020-06-04 06:58 UTC
#3582 previous ticket

currently, there are only 6 language 
needed  5 more language Philippines, Hindi, Indonesia, Malay, Thai
proof of purchase
![Screenshot (21)](https://user-images.githubusercontent.com/59775230/83724986-cd511080-a65e-11ea-8f5d-3d593cf0a2f9.png)

**Comment by philipvu30** [comment] 2020-06-04 09:47
Hi,

Would you mind translating all of the terms in lib/l10n/intl_en.arb to your preferred languages? 
After that, please send them to our email: support@inspireui.com or my email: toan@inspireui.com. We will add them in the next release.

Thanks

**Comment by minhcasi** [comment] 2020-06-04 12:54
Duplicate of #3582

**Closed by minhcasi** 2020-06-04 12:54 UTC
