### ISSUE TITLE
[ Mstore ]Address are not sync to wp site via facebook login

### ISSUE THREAD

**Issue by santhosh2210** [inspireui/support#649] opened 2019-05-28 11:16 UTC
Shipping address are storing the app....but not sync the wordpress site via facebook login.......
working fine via sign up....
See the screenshot -> http://prntscr.com/nudh2e
please find the error and reply fast

**Comment by minhcasi** [comment] 2019-05-28 12:40
kindly raise just one ticket for your issues, don't spam here - Duplicate of #642

**Closed by minhcasi** 2019-05-28 12:40 UTC
