### ISSUE TITLE
MSTORE ecommerce\shopify Warning: `flexWrap: `wrap`` is not supported

### ISSUE THREAD

**Issue by egyping** [inspireui/support#3835] opened 2020-06-21 06:54 UTC
Hello 

the collections and products si not getting synced and console give this error 

Warning: `flexWrap: `wrap`` is not supported with the `VirtualizedList` components.Consider using `numColumns` with `FlatList` instead.

and where is the installation documentation?

**Comment by ameenbadri7** [comment] 2020-06-21 12:16
if your site with `English ` language app please use this [guide ](https://docs.inspireui.com/fluxstore/multi-language/). 
if it's English only website please past your config files here maybe you have a mistake.

[use this docmantions ](https://docs.inspireui.com/fluxstore/woocommerce-setup/)

**Comment by egyping** [comment] 2020-06-21 12:46
this documentation for woocommerce my backend is shopify

**Comment by egyping** [comment] 2020-06-21 12:47
this is my laout 
`export const HorizonLayout = [
  { category: 96081313921, paging: true, layout: Constants.Layout.miniBanner },
  { name: "Plants & Floral", category: 95659917441, layout: Constants.Layout.threeColumn },
  { name: "BEDROOMS", category: 95659425921, layout: Constants.Layout.twoColumn },
  { name: "BEDROOMS", category: 95659425921, layout: Constants.Layout.twoColumnHigh },
  { name: "RUGS", category: 96081313921, layout: Constants.Layout.card },
]`

and this is my constants.js for shopify 

  Shopify: {
    url: 'athaathi.myshopify.com',
    storeFrontAPI: 'xxxxxxxxx00xxx55dxx_APIKey',
    ssl: true,
  },

**Comment by minhcasi** [comment] 2020-06-22 02:19
Duplicate of #3843 - pls help to post your all comment to one issue and provide the full info from step 2 - thank you!

**Closed by minhcasi** 2020-06-22 02:19 UTC
