### ISSUE TITLE
[Fluxstore 1.5.7] - Shipping cost calculator error

### ISSUE THREAD

**Issue by EmilianH** [inspireui/support#1352] opened 2019-11-09 22:27 UTC
---------

1. My issue
i have woocommerce correctly configured, and the shipping cost calculator from MERCADOPAGO works perfect in the web, but in the app, not recognize cost calculator
2. Screenshots
![shipping-error](https://user-images.githubusercontent.com/57189819/68535791-cc553c00-0326-11ea-9f33-8f5a42ffc3f7.jpg)

3. My screenshot of the purchase product or my comment:
![compra](https://user-images.githubusercontent.com/57189819/68535796-d2e3b380-0326-11ea-9ef2-7a8e2ec7d865.jpg)

3. Config files (optional)
[common.zip](https://github.com/inspireui/support/files/3827796/common.zip)

**Comment by minhcasi** [comment] 2019-11-10 01:48
Duplicate of #1324 
- pls comment on the previous issue instead of creating new one

**Closed by minhcasi** 2019-11-10 01:48 UTC
Labels: question ❓
