### ISSUE TITLE
[FluxStore WooCommerce] Products don't show up

### ISSUE THREAD

**Issue by menassat** [inspireui/support#4054] opened 2020-07-04 06:08 UTC
Hi, i got this issue in my app

![image](https://user-images.githubusercontent.com/59855540/86506166-30080a00-bdcd-11ea-8e9d-b3ff1821c7d1.png)

in the debug that what appear

![image](https://user-images.githubusercontent.com/59855540/86506190-7198b500-bdcd-11ea-8e3d-67ce7e3df1b1.png)

**Comment by minhcasi** [comment] 2020-07-04 11:51
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-07-05 07:21
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-05 07:21 UTC
Labels: needs-more-info
