### ISSUE TITLE
MStore Expo Login Issue

### ISSUE THREAD

**Issue by clinton-haley** [inspireui/support#4410] opened 2020-07-29 12:56 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Login to WooCommerce not working from MStore Expo.  This was tested against demo.mstore.io.  AppLoading is shown but App doesn't transition to post Login.
+ Product & version: MStore Pro (4.0.0)
+ Flutter (or React Native) version: React Native
+ Testing Device/Simulator: Android and iPhone 
+ Screenshot issues (drag the file to attach here): 

![Screenshot 2020-07-29 at 14 47 11](https://user-images.githubusercontent.com/35289712/88802089-e1227a00-d1aa-11ea-9b9f-9b0bacbc6b9e.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment] 2020-07-29 15:55
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by clinton-haley** [comment] 2020-07-29 16:06
Details were submitted via the link http://verify.inspireui.com/

Thanks

**Comment by luyx2412** [comment] 2020-07-31 09:58
Hi @clinton-haley Please fill form and upload your config files. Let me investigate about the issue.

Thanks

**Comment by clinton-haley** [comment] 2020-07-31 10:44
Hi @luyx2412, I downloaded the code direct from codecanyon.net - I have made no changes, got mstore-expo running on Expo and was not able to Login to demo.mstore.io (it works on the mstore-pro version).

Thanks

**Comment by luyx2412** [comment] 2020-08-01 07:12
Hi @clinton-haley Please provide your config file or debug with Reactotron and send me the log file. It will easier to investigate.

Thanks

**Comment by SEMION0708** [comment] 2020-08-02 09:33
Hi, I have the same problem too, I ask to solve please. The problem is that even if the password is wrong it should give an error but nothing happens, only the loading is displayed for a long period.
I used your config file and only installed EXPO environment.

**Comment by luyx2412** [comment] 2020-08-02 13:09
Hi @SEMION0708 Please replace `src/containers/Login/index.js` with this file which will fix the issue.

[Uploading index.js.zip…]()

Thanks

**Comment by clinton-haley** [comment] 2020-08-02 17:53
Hi @luyx2412 , link to file is not working.

Thanks,
Clinton

**Comment by clinton-haley** [comment] 2020-08-03 08:36
Hi @luyx2412, please advise on the fix file for this issue.  This is quite urgent.

Thanks

**Comment by clinton-haley** [comment] 2020-08-03 08:56
@SEMION0708 @luyx2412  - I managed to fix the problem

On the imports of src/containers/Login/index.js:

Replace:

**- import { has, get } from "lodash";**

With:

**- import { get, has, trim } from "lodash";**

Thanks

**Comment by luyx2412** [comment] 2020-08-03 16:06
Great!

**Closed by luyx2412** 2020-08-03 16:06 UTC
Labels: MStorePro
