### ISSUE TITLE
[Fluxstore Pro] - Product image doesn't show unless it's "JPEG" 

### ISSUE THREAD

**Issue by Alnaggar94** [inspireui/support#2184] opened 2020-02-23 02:50 UTC
1. My issue:

The problem is when I upload product image PNG or JPG it doesn't show in the product thumbnail
but when I open the product it shows. If I convert the image to JPEG it works fine.

2. Screenshots issues:

![v1](https://user-images.githubusercontent.com/49800146/75102625-c34f5880-55ff-11ea-8899-ae4f379b5381.JPG)

(Note: I used Regenerate Thumbnails with the recommended setting https://tppr.me/IbRvL)

It works fine only with JPEG, but other formats like PNG, JPG etc.. doesn't work 

3. Proof of my purchased:
https://www.dropbox.com/s/a72d73tka8rsa90/Capture.JPG?dl=0

**Comment by inspireui-support** [comment] 2020-02-23 03:47
@Alnaggar94 - I have try the image from the error log on the browser it seems not working as well - https://jomlatkom.com/wp-content/uploads/2020/02/imag e1xx1-47-Custom-medium.jpg

Could you double-check your server setting and try to run the link on a browser first ?

**Comment by Alnaggar94** [comment] 2020-02-23 04:17
@inspireui-support -I deleted the images and reupload it, see this video - https://streamable.com/6hqlb

**Comment by Alnaggar94** [comment] 2020-02-23 04:21
I even tried to Regenerate Thumbnails without luck only JPEG work others don't work. I even tried to do it in a fresh WordPress installation but also the same

**Comment by Alnaggar94** [comment] 2020-02-23 05:00
@inspireui-support - It's working now, I reinstall WordPress and it works. please close the ticket. and thank you for your time.

**Comment by inspireui-support** [comment] 2020-02-23 09:14
@Alnaggar94 - could you zip the common folder and share us for checking - thank you!

**Comment by inspireui-support** [comment] 2020-02-23 09:17
Duplicate of #2119

Please try to put you all issues to same ticket that prevents the double investigating - thank you!

**Closed by inspireui-support** 2020-02-23 09:17 UTC
Labels: FluxStore, question ❓
