### ISSUE TITLE
can not set up the app

### ISSUE THREAD

**Issue by leghost** [inspireui/support#916] opened 2019-08-14 08:30 UTC
i can't set up the app. i get error message when i run yarn install or npm . i'm using the 3.9.4 version.

![image](https://user-images.githubusercontent.com/47028114/63006116-248eb600-be7e-11e9-91c2-f670d960e2de.png)

yarn install v1.17.3
info No lockfile found.
[1/4] Resolving packages...
warning expo > fbemitter > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
warning wpapi > superagent@4.1.0: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "api-ecommerce > firebase > @firebase/database@0.3.20" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/performance@0.2.1" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/database > @firebase/database-types@0.3.11" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/functions@0.4.6" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/performance > @firebase/installations@0.1.0" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/auth > @firebase/auth-types@0.6.1" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/auth > @firebase/auth-types@0.6.1" has unmet peer dependency "@firebase/util@0.x".
warning "api-ecommerce > firebase > @firebase/performance > @firebase/installations > @firebase/installations-types@0.1.0" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/storage@0.2.15" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/messaging@0.3.19" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/functions > @firebase/messaging-types@0.2.11" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/storage > @firebase/storage-types@0.2.11" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/storage > @firebase/storage-types@0.2.11" has unmet peer dependency "@firebase/util@0.x".
warning "api-ecommerce > firebase > @firebase/firestore@1.2.2" has unmet peer dependency "@firebase/app-types@0.x".
warning "api-ecommerce > firebase > @firebase/firestore > @firebase/firestore-types@1.2.1" has unmet peer dependency "@firebase/app-types@0.x".
warning "babel-jest > babel-preset-jest > @babel/plugin-syntax-object-rest-spread@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "react-instantsearch > react-instantsearch-dom@5.7.0" has unmet peer dependency "react-dom@>= 15.3.0 < 17".
warning "react-instantsearch > react-instantsearch-core > algoliasearch-helper@2.28.0" has unmet peer dependency "algoliasearch@>= 3.1 < 4".
warning "react-native > metro-react-native-babel-transformer@0.51.0" has unmet peer dependency "@babel/core@*".
warning "react-native > @react-native-community/cli > metro-react-native-babel-transformer@0.51.1" has unmet peer dependency "@babel/core@*".
warning "react-native-clean-form > styled-components@4.3.2" has unmet peer dependency "react-dom@>= 16.3.0".
warning " > react-native-paper@2.16.0" has unmet peer dependency "react-native-vector-icons@*".
warning "react-native-paper > create-react-context@0.2.3" has unmet peer dependency "prop-types@^15.0.0".
warning " > react-native-radio-buttons@1.0.0" has unmet peer dependency "prop-types@>=15.5.0".
warning " > react-native-render-html@4.1.2" has unmet peer dependency "prop-types@>=15.5.10".
warning " > react-native-swipe-list-view@2.0.0" has unmet peer dependency "prop-types@>=15.5.0".
warning "react-navigation > react-navigation-tabs@1.1.4" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-drawer@1.2.1" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-stack@1.4.0" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning " > babel-jest@24.8.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "babel-jest > babel-preset-jest@24.6.0" has unmet peer dependency "@babel/core@^7.0.0".
warning " > reactotron-redux@3.1.1" has unmet peer dependency "reactotron-core-client@^2.5.0".
[4/4] Building fresh packages...
[1/7] ⡀ grpc
[-/7] ⡀ waiting...
[-/7] ⡀ waiting...
[-/7] ⢀ waiting...
error D:\Intermediare\Projet clients ISS\airplace\airplace mobil app\mstore-3.9.4b\mstore-expo\node_modules\@firebase\firestore\node_modules\grpc: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build --library=static_library
Arguments:
Directory: D:\Intermediare\Projet clients ISS\airplace\airplace mobil app\mstore-3.9.4b\mstore-expo\node_modules\@firebase\firestore\node_modules\grpc
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.12.0
node-pre-gyp info using node@12.7.0 | win32 | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "D:\Intermediare\Projet clients ISS\airplace\airplace mobil app\mstore-3.9.4b\mstore-expo\node_modules\@firebase\firestore\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node" (not found)
node-pre-gyp http GET https://node-precompiled-binaries.grpc.io/grpc/v1.20.0/node-v72-win32-x64-unknown.tar.gz
node-pre-gyp http 404 https://node-precompiled-binaries.grpc.io/grpc/v1.20.0/node-v72-win32-x64-unknown.tar.gz
node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.20.0/node-v72-win32-x64-unknown.tar.gz
node-pre-gyp WARN Pre-built binaries not found for grpc@1.20.0 and node@12.7.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://node-precompiled-binaries.grpc.io/grpc/v1.20.0/node-v72-win32-x64-unknown.tar.gz

D:\Intermediare\Projet clients ISS\airplace\airplace mobil app\mstore-3.9.4b\mstore-expo\node_modules\@firebase\firestore\node_modules\grpc>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.7.0 | win32 | x64
gyp info ok

D:\Intermediare\Projet clients ISS\airplace\airplace mobil app\mstore-3.9.4b\mstore-expo\node_modules\@firebase\firestore\node_modules\grpc>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --library=static_library "--module=D:\Intermediare\Projet clients ISS\airplace\airplace mobil app\mstore-3.9.4b\mstore-expo\node_modules\@firebase\firestore\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node" --module_name=grpc_node "--module_path=D:\Intermediare\Projet clients ISS\airplace\airplace mobil app\mstore-3.9.4b\mstore-expo\node_modules\@firebase\firestore\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown" --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72 )  else (node "" configure --fallback-to-build --library=static_library "--module=D:\Intermediare\Projet clients ISS\airplace\airplace mobil app\mstore-3.9.4b\mstore-expo\node_modules\@firebase\firestore\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node" --module_name=grpc_node "--module_path=D:\Intermediare\Projet clients ISS\airplace\airplace mobil app\mstore-3.9.4b\mstore-expo\node_modules\@firebase\firestore\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown" --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72 )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.7.0 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Intermediare\\Projet clients ISS\\airplace\\airplace mobil app\\mstore-3.9.4b\\mstore-expo\\node_modules\\@firebase\\firestore\\node_modules\\grpc\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Tankeu\\.node-gyp\\12.7.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Tankeu\\.node-gyp\\12.7.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Tankeu\\.node-gyp\\12.7.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\Intermediare\\Projet clients ISS\\airplace\\airplace mobil app\\mstore-3.9.4b\\mstore-expo\\node_modules\\@firebase\\firestore\\node_modules\\grpc',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\Intermediare\\Projet clients ISS\\airplace\\airplace mobil app\\mstore-3.9.4b\\mstore-expo\\node_modules\\@firebase\\firestore\\node_modules\\grpc\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
gyp info ok

D:\Intermediare\Projet clients ISS\airplace\airplace mobil app\mstore-3.9.4b\mstore-expo\node_modules\@firebase\firestore\node_modules\grpc>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --library=static_library "--module=D:\Intermediare\Projet clients ISS\airplace\airplace mobil app\mstore-3.9.4b\mstore-expo\node_modules\@firebase\firestore\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node" --module_name=grpc_node "--module_path=D:\Intermediare\Projet clients ISS\airplace\airplace mobil app\mstore-3.9.4b\mstore-expo\node_modules\@firebase\firestore\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown" --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72 )  else (node "" build --fallback-to-build --library=static_library "--module=D:\Intermediare\Projet clients ISS\airplace\airplace mobil app\mstore-3.9.4b\mstore-expo\node_modules\@firebase\firestore\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node" --module_name=grpc_node "--module_path=D:\Intermediare\Projet clients ISS\airplace\airplace mobil app\mstore-3.9.4b\mstore-expo\node_modules\@firebase\firestore\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown" --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72 )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.7.0 | win32 | x64
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [D:\Intermediare\Projet clients ISS\airplace\airplace mobil app\mstore-3.9.4b\mstore-expo\node_modules\@firebase\firestore\node_modules\grpc\build\binding.sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [D:\Intermediare\Projet clients ISS\airplace\airplace mobil app\mstore-3.9.4b\mstore-expo\node_modules\@firebase\firestore\node_modules\grpc\build\binding.sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [D:\Intermediare\Projet clients ISS\airplace\airplace mobil app\mstore-3.9.4b\mstore-expo\node_modules\@firebase\firestore\node_modules\grpc\build\binding.sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [D:\Intermediare\Projet clients ISS\airplace\airplace mobil app\mstore-3.9.4b\mstore-expo\node_modules\@firebase\firestore\node_modules\grpc\build\binding.sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [D:\Intermediare\Projet clients ISS\airplace\airplace mobil app\mstore-3.9.4b\mstore-expo\node_modules\@firebase\firestore\node_modules\grpc\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:266:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=D:\\Intermediare\\Projet clients ISS\\airplace\\airplace mobil app\\mstore-3.9.4b\\mstore-expo\\node_modules\\@firebase\\firestore\\node_modules\\grpc\\src\\node\\extension_binary\\node-v72-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=D:\\Intermediare\\Projet clients ISS\\airplace\\airplace mobil app\\mstore-3.9.4b\\mstore-expo\\node_modules\\@firebase\\firestore\\node_modules\\grpc\\src\\node\\extension_binary\\node-v72-win32-x64-unknown" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd D:\Intermediare\Projet clients ISS\airplace\airplace mobil app\mstore-3.9.4b\mstore-expo\node_modules\@firebase\firestore\node_modules\grpc
gyp ERR! node -v v12.7.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --library=static_library --module=D:\Intermediare\Projet clients ISS\airplace\airplace mobil app\mstore-3.9.4b\mstore-expo\node_modules\@firebase\firestore\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=D:\Intermediare\Projet clients ISS\airplace\airplace mobil app\mstore-3.9.4b\mstore-expo\node_modules\@firebase\firestore\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\Intermediare\Projet clients ISS\airplace\airplace mobil app\mstore-3.9.4b\mstore-expo\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Intermediare\\Projet clients ISS\\airplace\\airplace mobil app\\mstore-3.9.4b\\mstore-expo\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd D:\Intermediare\Projet clients ISS\airplace\airplace mobil app\mstore-3.9.4b\mstore-expo\node_modules\@firebase\firestore\node_modules\grpc
node-pre-gyp ERR! node -v v12.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --library=static_library --module=D:\Intermediare\Projet clients ISS\airplace\airplace mobil app\mstore-3.9.4b\mstore-expo\node_modules\@firebase\firestore\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=D:\Intermediare\Projet

**Comment by minhcasi** [comment] 2019-08-16 10:53
Hi, could you try to re-install the nodejs 10.x - https://nodejs.org - thank you!

**Comment by sackmotion** [comment] 2019-08-17 21:06
This can be closed , it's solved in #922 .

Thank you !

**Comment by minhcasi** [comment] 2019-08-18 07:23
Duplicate of #922

**Closed by minhcasi** 2019-08-18 07:23 UTC
Labels: question ❓
