### ISSUE TITLE
[MStore MV] error after bulding the app

### ISSUE THREAD

**Issue by osamasparky** [inspireui/support#545] opened 2019-04-29 10:47 UTC
MVStore
Purchase code: da4e5510-501d-456f-9d1d-fbbcdd24f102
(we may not reply if you are not our customer)

I got error on after building
the app and test it on expo
![expo](https://user-images.githubusercontent.com/36470035/56891792-5114f280-6a86-11e9-8071-5f4344d43cbf.jpeg)

also when i build the app with Cbuilder i got this error 
![image](https://user-images.githubusercontent.com/36470035/56891988-e617eb80-6a86-11e9-96ff-aac888873e97.png)

If applicable, add screenshots to help explain

**Comment by minhcasi** [comment] 2019-04-29 14:24
Hi, could we know it is the issues from the latest version of MstoreMV ?

**Comment by osamasparky** [comment] 2019-04-29 14:40
Yes I downloaded the latest version from themeforest

**Comment by osamasparky** [comment] 2019-04-30 19:09
Good day 
Any update on that

**Comment by osamasparky** [comment] 2019-05-01 18:25
Hi 
When you will answer

**Comment by minhcasi** [comment] 2019-05-03 09:52
Can you send your whole source code package to support@inspireui.com - our team will help for checking the issue - thanks

**Comment by osamasparky** [comment] 2019-05-05 12:27
1.facebook login not work after i update . and when try login the close screen is too big can't close it .
2. when chose ar not changed . and when i delete all the en . and recompile the app not working .
3- add to cart still disable even i have stock .
4-after compiled the app . work for 2 times . after that it say can't get the data from sever . ( i have internet ) .
5.Cebuilder . when you click on deliver . it go to different directory not the directory which the app files in .
i will send you the app on email .

**Comment by osamasparky** [comment] 2019-05-07 08:09
any update

**Comment by minhcasi** [comment] 2019-05-07 10:53
Hi, I have sent to our team for investigating and they will get back the result soon - thank you!

**Comment by osamasparky** [comment] 2019-05-09 17:28
Any update

**Comment by osamasparky** [comment] 2019-05-12 08:51
sir i have 13 days waiting  for now in this ticket  . what should i do .

**Comment by minhcasi** [comment] 2019-05-12 09:22
Hi, our guys have fixed the issues and they will update you on Monday, we also have new release as well - thank for your patient

**Comment by osamasparky** [comment] 2019-05-12 09:38
OK THANK YOU

**Comment by minhcasi** [comment] 2019-05-13 11:05
Hi @osamasparky - you have an email, we will send the last update from the team 3.8.0 - thanks

**Comment by osamasparky** [comment] 2019-05-13 14:39
Ok thanks a lot and i see that the support is improved. Thanks for that . 
When you think i will got that email

**Comment by minhcasi** [comment] 2019-05-14 11:22
Hi @osamasparky - pls update the latest 3.8.0 from the download page - we have just released today - also check the changelog - thank you

**Comment by osamasparky** [comment] 2019-05-14 11:31
Good day and thanks a alot . according to update . i just download the software from theme forest its V1.3.0 
also the cebuilder V 0.33.0

**Comment by osamasparky** [comment] 2019-05-14 16:32
After some search i thing the update was for mstore pro my product is  MStore Multi Vendor . Any advice

**Comment by osamasparky** [comment] 2019-05-15 08:06
@minhcasi Hello

**Comment by minhcasi** [comment] 2019-05-15 12:03
oh sorry, I though your issue from the Mstore Pro - let me check with the Mstore MV team and let you know - thank you!

**Comment by osamasparky** [comment] 2019-05-15 12:07
@minhcasi thank you for interesting on that and your replay . as you see i have 3 month now from purchasing the software and try to just build it . and this problem have 16 Days . now . it would be appreciated if you :-
1- replay fast as you can .
2- extend my support for the bast 3 month of trying . 

thank you

**Comment by thangvo9x** [comment] 2019-05-16 02:52
Hi. I am a supporter. Could you share the source to my email for checking, plz?
thang@inspireui.com
with subject 545
Thanks

**Comment by thangvo9x** [comment] 2019-05-16 04:15
1.facebook login not work after i update . and when try login the close screen is too big can't close it .
=> Refer here https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow
the error is coming from the facebook app
2. when chose ar not changed . and when i delete all the en . and recompile the app not working .
=> Brief me more detail
3- add to cart still disable even i have stock .
=> tell me your name that product
4-after compiled the app . work for 2 times . after that it say can't get the data from sever . ( i have internet ) .
=> I fixed this error and send u again when done.
5. CeBuilder error => Noted for checking. 
Thanks

**Comment by osamasparky** [comment] 2019-05-16 10:35
https://expo.io/@osamasabry/Alwecala
That is the app if you need to test it 
=> Lang problem - i have only one language Arabic and you told before to disable the En from language.js . whin i did the app not working  so i need just one Lagrange .
=> product and add to cart problem - it happens to all product not a spasific one - i can bay now but th cart icon not active it's enable just when i bay it . 
=> according to face book what i can do .
also a lot of missing things in documentation or i cannot find . how can i change the category icons in the application .

**Comment by osamasparky** [comment] 2019-05-18 00:02
Any updates

**Comment by osamasparky** [comment] 2019-05-18 21:02
That is too much waiting. Sorry if i told you that the support is improved . Nothing happened.

**Comment by minhcasi** [comment] 2019-05-20 02:21
@thangvo9x - pls provide the patching to @osamasparky email - thanks

**Comment by thangvo9x** [comment] 2019-05-20 02:35
please share AppConfig.json file with my email thang@inspireui.com. 
 @osamasparky

**Comment by osamasparky** [comment] 2019-05-21 06:31
Please the 
1-cart still disabled. On the app on all products. 
2-facebook what should i do 
3- category icons where to change  it .

**Comment by osamasparky** [comment] 2019-05-21 10:02
![expo error](https://user-images.githubusercontent.com/36470035/58087108-941b3f00-7bc8-11e9-8e40-3ffead2a0443.png)

I got this when building the app

**Comment by minhcasi** [comment] 2019-05-22 02:40
There are missing file .babelrc when you copy to the new folder

Duplicate of #osamasparky

**Closed by minhcasi** 2019-05-22 02:40 UTC
Labels: help wanted 🙏

**Comment by osamasparky** [comment] 2019-05-22 06:49
That is all the files i got from the team . And when I search i find  it there

**Comment by osamasparky** [comment] 2019-05-22 06:50
Also why you close this ticket

**Comment by osamasparky** [comment] 2019-05-22 08:33
I do install 
npm install --save-dev @babel/core @babel/cli
But the problem still there
