### ISSUE TITLE
Fluxstore Woocommerce - Unit Of Measurement  & Indian Currency ( ₹ ) Not Showing in the App

### ISSUE THREAD

**Issue by swspro** [inspireui/support#2785] opened 2020-04-19 04:53 UTC
Step 1 (require): detail issues and screenshots

Hi ,

We could successfully run the Demo App without changing the Bundle ID and APP NAME

Also we could CONNECT our Woocommerce WEBSITE at http://freshwayonline.com to the Demo APP.

But the PROBLEM which we are FACING is in the DEMO APP ie FLUXSTORE

1 ) We are not able to SEE the **UNIT OF MEASUREMENT** for any ITEM in the APP

- Refer this ITEM Link at http://freshwayonline.com/product/beans-goru-chikkudukaya/
- **Item Name :** Beans – Goru Chikkudukaya
- **Item Quantity** - 500 Gm 
- **Item Price** - ₹100

2 ) In the ATTACHMENT I am sending you SCREENSHOT of the APP where you can see **" ITEM QUANTITY "**  is never shown anywhere

- My Concern is HOW WE CAN SHOW the ITEM QUANTITY ie 500 Gm for that product in the PPRODUCT DETAIL PAGE and PRODUCT LISTING PAGE ?

3 ) INDIAN CURRENCY ( ₹ ) is NOT SHOWING in the APP even though the APP is CONNECTED to the SITE www.freshwayonline.com

Hope I am being ABLE to EXPLAIN you the ISSUE PROPERLY

All your help and quick response will be highly appreciated

Regards,
Samaresh B.

![WhatsApp Image 2020-04-19 at 10 12 13 (1)](https://user-images.githubusercontent.com/15525566/79679775-93e75180-8226-11ea-9db0-caf7166a8ad7.jpeg)
![WhatsApp Image 2020-04-19 at 10 12 13 (2)](https://user-images.githubusercontent.com/15525566/79679778-9649ab80-8226-11ea-9362-6072782b12dc.jpeg)
![WhatsApp Image 2020-04-19 at 10 12 13](https://user-images.githubusercontent.com/15525566/79679781-96e24200-8226-11ea-9c8c-327c9ef08301.jpeg)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

>> ALREADY VERIFIED , please refer to my last Issue where I had uploaded the Licence and config folder.

Thanks
Samaresh 
*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by philipvu30** [comment] 2020-04-20 10:01
Hi,

Received your config folder but that was not the one we need.

Please send your common folder to this email: toan@inspireui.com

Thanks.

**Comment by swspro** [comment] 2020-04-20 10:38
Hi Minhcasi and Philip,

Thanks for your quick response!

I will send the Common Folder to your email on to give solution for #2779  ( Bundle ID Issue )

In addition to this I would like to inform that I can build the App if I use the Bundle ID as 

com.pocketapp.freshway instead of in.pocketapp.freshway

Note : I have rename the folder from com\pocketapp\freshway\MainActivity.kt

But I need it in this way ie in\pocketapp\freshway\MainActivity.kt and this shows error

Can you please suggest whether we can or cannot use in.pocketapp.freshway as we have .in domain?

Regarding the Rupee symbol we would figure it out and is showing in our Demo App .

But wanted to now how we can display the Unit Of Measure on the App

INSPIREUI has really INSPIRED us by CREATING CLASSIC PRODUCTS and we wanted to use it 

Thank You!

**Comment by swspro** [comment] 2020-04-20 10:51
Both ANDROID FOLDER & COMMON Folder I have sent to your EMAIL at toan@inspireui.com from Email ID : samareshbisoi@gmail.com

**Comment by swspro** [comment] 2020-04-21 03:53
Ok @minhcasi #2812 issue will discuss here.

Waiting for your expert suggestions.

Sam

**Comment by swspro** [comment] 2020-04-21 08:54
**Fluxstore Woocommerce - MStore Api Plugin Asking to Verify Purchase Code** 

Hi @minhcasi 

I tried using the Envato Purchase Code which I got and it said invalid code.

Do we have any other code apart from which i had send it to you ?

Samaresh 
![MIT Plugin](https://user-images.githubusercontent.com/15525566/79845896-5d9f0300-83db-11ea-80cc-72fe4b647b76.JPG)

**Comment by philipvu30** [comment] 2020-04-21 09:28
@swspro ,

Your common folder does not come with config.dart file and config_en.json
I need those files to reproduce your issue. 
Kindly send them again. Thanks

**Comment by swspro** [comment] 2020-04-21 09:31
hi @philipvu30 

Thanks for reverting back . I am sending you right now at toan@inspireui.com

Sam

**Comment by swspro** [comment] 2020-04-21 09:34
@philipvu30 email sent

**Comment by swspro** [comment] 2020-04-21 10:38
SIGN UP ISSUE - From REGISTRATION FORM

Hi @minhcasi 

The Demo App was previously allowing us to sign up but now its show **Exception Error : You are not allowed to do that "** 

You can see the Screenshot in the Attachment 

Is there any admin setting in Wordpress we have to give permission

**WE HAVE ALREADY SET** in the Settings **ANY ONE CAN REGISTER**

Please suggest .

Sam


![Sign Up Issue](https://user-images.githubusercontent.com/15525566/79856341-dc02a180-83e9-11ea-917d-b2d769c6f25b.jpeg)

**Comment by philipvu30** [comment] 2020-04-21 11:16
Hi,

1 and 2 -> Add this
![image](https://user-images.githubusercontent.com/54442328/79859654-8f27c680-83fb-11ea-95be-b6bda13891f8.png)

3 -> You can add it as variable product.
![image](https://user-images.githubusercontent.com/54442328/79859881-e7f75f00-83fb-11ea-9d7c-c7fd3c1a619a.png)
![image](https://user-images.githubusercontent.com/54442328/79859926-00677980-83fc-11ea-97fa-5dbc41fc713b.png)

**Comment by swspro** [comment] 2020-04-21 11:19
@philipvu30 Got It . This is for Currency Setting and Unit Of Measurement..

Can you please let know what should I do on the resent issue on Sign Up Issue ?

**Comment by philipvu30** [comment] 2020-04-21 11:20
What is your current version of this plugin: Mstore API?

**Comment by swspro** [comment] 2020-04-21 11:22
My Current Version of Mstore API is Plugin is Version 2.3.2

**Comment by swspro** [comment] 2020-04-21 11:26
This Mstore Plugin is asking me for the PURCHASE CODE and when I used the purchase of the Fluxstore which I had purchased is from Envato then its showing invalid

**Comment by philipvu30** [comment] 2020-04-21 11:36
Hi,

The above issue is being investigated. I'll let you know when there is a result. Thanks

**Comment by swspro** [comment] 2020-04-21 12:35
@philipvu30 if you want I can send you the purchase code

Waiting for other solutions on  this thread.

Sam

**Comment by philipvu30** [comment] 2020-04-22 10:27
Hi,

Please update the plugin to the version 2.3.4 and enter your purchase code in the MStore API section. Then try again.

If it does not work, please download [FluxBuilder](http://fluxbuilder.com/) and use the reset function to reset your license. Thanks

**Comment by swspro** [comment] 2020-04-24 05:42
@philipvu30 I have emailed and haven't received the solutions on the BUNDLE ID where I want to use in.pocketapp.freshway which doesnt allow me to Build but when I use com.pocketapp.freshway it is beign build successfully 

Sam

**Comment by swspro** [comment] 2020-04-24 07:28
Thanks @philipvu30 for reopening.

**Comment by philipvu30** [comment] 2020-04-24 07:29
Hi,

Feel free to reopen your issue. We usually close issue after 2-3 of no response from users.
I'm sorry I did not see that issue earlier. Currently the issue is under investigation.

**Comment by philipvu30** [comment] 2020-04-24 07:32
@swspro 

Would you mind run flutter clean then send your whole project to this email: toan@inspireui.com? As we cannot modify the package on our main project. Thanks

**Comment by swspro** [comment] 2020-04-24 07:39
Sure Philip! 

Also M Store Plug-in afraid to Update on the site as the last time I updated there was registration problem

So we used the MSToRe  plugin which we got from you on the PURCHASE of Fluxstore Woocommerce app from Envato

Site is live www.freshwayonline.com website is live and people are ordering from site 

I wondering if I update the plugin and there will be registration problem.

If you want I can email you username and password and purchase code to update mstore plugin.

But please sure the visitor should be able to register after that .

Sam

**Comment by philipvu30** [comment] 2020-04-24 07:42
Hi,

That would help me a lot. But I suggest you not to update anything if the app is running fine. 
May I ask what version of MStore API are you using?

**Comment by swspro** [comment] 2020-04-24 08:46
Yes @philipvu30 the App is working fine now using the MSTORE API version Version 2.2.4

But updating it doesnt works

The website is LIVE and people are using it , so dont want to update the Plugin as well.

As of now I have two concerns

1 ) The Bundle ID issue ( in.pocketapp.freshway doesnt work .) only com.pocketapp.freshway works

2 ) How to Minimum Order Amount in the App ?

>> On the WEBSITE no one can order below Rs.100/- as we have used the Woocommerce Shipping settings to minimum Rs.100/-

>> But on the App it does works ; one can order Rs.2 item and order is placed.

Please suggest 

Regards,
Sam

**Comment by philipvu30** [comment] 2020-04-24 09:41
Hi,

1. Please send me your project to email: toan@inspireui.com so I can look into your bundle id issue.
2. Sorry, currently the app only supports min-max quantity, the min-max price has not been implemented yet.

**Comment by swspro** [comment] 2020-04-24 11:48
sure will send you by Monday. Thanks!

**Comment by swspro** [comment] 2020-04-25 09:06
Hi @philipvu30 ,

As have the files in the Office System I will email You on MONDAY.

On the Min-Max Price can I think in the checkout Page we can write if else code to restrict to the payment page

>> If Amount < 100 then block the Checkout alert " Minimum Amount Should be more than 100 

It will very much helpful if you can write that one line or two line code, and give us instruction where  and in which page to be added  . This issue will be easily resolved 

All  your ideas and suggestions will be highly appreciated.

Regards,
Sam

**Comment by swspro** [comment] 2020-04-25 11:12
@philipvu30 please refer to #2636 which @minhcasi has suggested on Setting Min and Max Amount in the App

Can you please assist me how to do it ?

Sam

**Comment by philipvu30** [comment] 2020-04-27 09:15
Hi,

It seems we misunderstand each other. The Min and Max quantity is for each product only, and the feature you said, it has not been implemented yet. I'll forward this to the technical team and it will be implemented in the future releases.

As we do not provide customization services at the moment, if you want to implement the above logic code yourself, maybe you can start at this file lib/screens/cart/my_cart.dart.

**Comment by swspro** [comment] 2020-04-28 05:59
Hi @philipvu30 thanks for that information.

Just now got an alert notification from Fluxstore Woocommerce App at ThemeForest on the New Updated version.

Is the new updated version covering the Minimum Maximum Amount settings.

Sam

I am you the whole app to your email Address on the Bundle ID issue.

**Comment by philipvu30** [comment] 2020-04-28 08:56
Hi,

Email received.
Sorry the Min Max Amount for the cart feature has not been implemented yet. You could hire a freelancer to do the customization though.

Thank you for your interest.

**Comment by philipvu30** [comment] 2020-04-29 09:01
Hi,

About the bundle ID issue: 
- You have misconfigured the bundle ID. If you are on Windows, press Ctrl + Shift + F and find all com.pocketapp.freshway and replace it with com.freshwayonline.freshway.
- The Min-Max amount for cart feature is on our plan now. I'll let you know when it is implemented.

If the above solution works, kindly close this comment. Otherwise, it will be closed after 2 days.

Thank you and have a great day.

**Comment by swspro** [comment] 2020-04-30 05:27
Hi @philipvu30 

Thanks for the update. Hope you are doing well.

Actually I had sent you the updated on where you must have found the bundle ID com.freshwayonline.freshway

My main query is why I am not able to use .in domain in the Bundle ID

If you try " in.pocketapp.freshway " this will not take even you rename the folders as com/pocketpp/freshway/MainActivity.

We want to use .in domain in the bundle ID but it shows this error which you can find in the attachment 

Sam
![1](https://user-images.githubusercontent.com/15525566/80675138-5e1d5500-8ad1-11ea-8eb0-dfd0f32e7d8c.JPG)

**Comment by philipvu30** [comment] 2020-04-30 06:41
Hi,

Please change the highlighted package name in MainActivity and folder name like this

![image](https://user-images.githubusercontent.com/54442328/80679982-2a99f500-8ae8-11ea-9f36-a5b6a496f51e.png)


Then replace all bundle ID with: in.freshwayonline.freshway

**Comment by swspro** [comment] 2020-04-30 11:32
Thanks @philipvu30 will check and update you.

**Comment by swspro** [comment] 2020-05-01 11:08
Hi @philipvu30 ,

Did the same what you suggest but its showing the same error ?

But one problem which we are facing right is the app is not receiving data from through the API

If you can browse the App no categories and products are shown.. It was working fine

In the attachment you can see the last access was 27th April ,2020 - 7:17 AM

Please have a look into it 

Also tried updating the MStore Plugin  and asked for PURCHASE CODE to Verify .

Tried to verify through the PURCHASE CODE as last time ( you can refer to this thread all issues ) and found the same INVALID code 

If you want I can give you the Login Details of the Website and the PURCHASE CODE which I had got during the PURCHASE of the PRODUCT.

All your help will be highly appreciated.

Regards,
Samaresh B.


![WhatsApp Image 2020-05-01 at 16 34 18 (1)](https://user-images.githubusercontent.com/15525566/80801359-b9cb0980-8bc9-11ea-884c-da129fea3d8d.jpeg)
![WhatsApp Image 2020-05-01 at 16 34 18 (2)](https://user-images.githubusercontent.com/15525566/80801361-bafc3680-8bc9-11ea-824a-f1b8fdaa4420.jpeg)
![WhatsApp Image 2020-05-01 at 16 34 18 (3)](https://user-images.githubusercontent.com/15525566/80801362-bb94cd00-8bc9-11ea-9c3f-6dd820c763d9.jpeg)
![WhatsApp Image 2020-05-01 at 16 34 18](https://user-images.githubusercontent.com/15525566/80801363-bc2d6380-8bc9-11ea-8b2e-4223a6003c54.jpeg)





![6](https://user-images.githubusercontent.com/15525566/80801152-2265b680-8bc9-11ea-8d23-8da40d762708.JPG)

**Comment by swspro** [comment] 2020-05-02 08:57
Hi @philipvu30 

I created a new rest api and updated in the config and it work.

Actually the issue was my friend had installed SSL Certificate on the domain recently as a result of which the domain name has become https:// , and we had previously configured and created the Rest Api key as http://

So we fixed that issue.

Now  bundle id is showing the same error when we use it as .in domain  ( Will try again in another system )

I want your help in Google Login . We have done all the setup as mentioned in the documentation and its taking to our account also.

But at the end there is a error message. I HAVE ATTACHED THE SCREENSHOT please have a look into and assist me.

Regards,
Sam

![gmail login](https://user-images.githubusercontent.com/15525566/80859724-93b47080-8c80-11ea-919b-391e625f41c5.jpeg)
![login2](https://user-images.githubusercontent.com/15525566/80859726-96af6100-8c80-11ea-89a5-3716818c2443.jpeg)

**Comment by swspro** [comment] 2020-05-02 14:42
Hi @philipvu30 

As we wanted to upload the release version app in the Google PlayStore we have decided to go with **com.pocketapp.freshway** instead of **in.pocketapp.freshway** as it is not working

Now while building the release version of the Apk we got the following error which you can find in the ATTACHMENT .

Please suggest what is  MISSING!

Your quick response will be highly appreciated.

Regards,
Sam


![release apk](https://user-images.githubusercontent.com/15525566/80867199-74cdd280-8cb0-11ea-995b-a75c86a70013.JPG)

**Comment by swspro** [comment] 2020-05-03 03:33
hi @philipvu30 I am waiting for your Expert suggestion.

**Comment by philipvu30** [comment] 2020-05-04 10:10
Hi,

Sorry for the delayed response as we just got back to work from the National holidays.

Please run flutter clean or delete the build folder then send your project to this email: toan@inspireui.com. I'll help you as soon as I receive the email (in our working time 9AM-6PM Monday-Friday GMT+7)

**Comment by swspro** [comment] 2020-05-05 08:06
Hi @philipvu30 thanks for replying back.

I really need to your help to this project a success.. Hopefully with your help I will be able to implement the complete functionalities of the product.

I am sending you the Project after sometimes.

Two Primary Issues

1 ) Social Login Error

2 ) Not able to create the release version

All your help will be highly appreciated.

Regards,
Sam

**Comment by swspro** [comment] 2020-05-05 08:15
Email Sent with **Subject Line** : **Fluxstore Woocommerce - #2785** from samareshbisoi@gmail.com

**Comment by philipvu30** [comment] 2020-05-05 10:42
Email received.

**Comment by swspro** [comment] 2020-05-05 11:19
Thanks @philipvu30 !

As per your suggestion I deleted the build Folder by running the "**Flutter Clean Command "** and it worked.

I can now build the release apk. Thanks bro!

**Comment by swspro** [comment] 2020-05-05 11:21
Help me with the social login .

**Comment by philipvu30** [comment] 2020-05-06 02:33
Hi,

Please refer to this [2895](https://github.com/inspireui/support/issues/2895#issuecomment-624402368)

**Comment by swspro** [comment] 2020-05-06 05:58
Thanks @philipvu30 will review #2895 and let you know if that worked for me.

In the attachment is my Google Login error message.

Regards,
Sam



![login2](https://user-images.githubusercontent.com/15525566/81142104-48ee6d80-8f8c-11ea-99f5-b239e2673e40.jpeg)
![gmail login](https://user-images.githubusercontent.com/15525566/81142128-57d52000-8f8c-11ea-94d9-333287028d1e.jpeg)

**Comment by philipvu30** [comment] 2020-05-06 09:52
Hi,

This error happens only when you use the account that is different from the firebase.
Please get the release SHA 1 key and add it to firebase then replace the old google-services.json in your project with the new one.

You can refer to this [one](https://stackoverflow.com/questions/51845559/generate-sha-1-for-flutter-app). It's maybe outdated but it will somehow give you an idea.

**Comment by philipvu30** [comment] 2020-05-08 03:02
Closed as no response.

**Closed by philipvu30** 2020-05-08 03:02 UTC
Labels: FluxStore
