### ISSUE TITLE
[Fluxstore Pro] - Wrong text direction the Sign-in screen (Arabic language RTL).

### ISSUE THREAD

**Issue by Alnaggar94** [inspireui/support#1488] opened 2019-11-29 11:19 UTC
1. My issue:

In the Sign-in screen (Arabic language RTL) the "Reset" text supposed to be on the opposite side. (see screenshots)

2. Screenshots issues:

https://imgur.com/xx0cN2h

3. Proof of my purchased:

https://imgur.com/a/9TsYcIf

3. Config files (optional)

Config.dart - https://filebin.net/becvkrj8hww0zj70/config.dart?t=zsbmottl

Config.json - https://filebin.net/yawilsdcvbq0cdiy/config.json?t=k20muw5l
Config_ar.json - https://filebin.net/9v2zm8kiu7b5d6bi/config_ar.json?t=k3ydcajw

**Comment by minhcasi** [comment] 2019-11-30 02:36
Duplicate of #1486

I've moved this issue to 1486 as it's duplicate, please help us to create one ticket for your all issues - thank you!

**Closed by minhcasi** 2019-11-30 02:36 UTC
Labels: question ❓
