### ISSUE TITLE
fluxnews depends on vector_math 2.0.8, flutter_test from sdk is forbidden.

### ISSUE THREAD

**Issue by Rolisys** [inspireui/support#4766] opened 2020-08-27 13:32 UTC
I just purchased the fluxnews app today and set it up in Android Studio but can't get pubs for pubspec yaml because of this error message:

event sent after app closed: {id: 0, progressId: null, message: Running "flutter pub get" in source...}
Because every version of flutter_test from sdk depends on vector_math 2.1.0-nullsafety.2 and fluxnews depends on vector_math 2.0.8, flutter_test from sdk is forbidden.
So, because fluxnews depends on flutter_test any from sdk, version solving failed.
event sent after app closed: {id: 0, progressId: null, finished: true}
pub get failed (1; So, because fluxnews depends on flutter_test any from sdk, version solving failed.)

Please help with this. 
Thanks

**Comment by minhcasi** [comment] 2020-08-28 04:05
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-08-29 06:01
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-08-29 06:01 UTC
Labels: needs-more-info
