### ISSUE TITLE
how to change the flexstore logo Loading indicator 

### ISSUE THREAD

**Issue by mmasifashraf** [inspireui/support#3279] opened 2020-05-18 23:54 UTC
How to change the default flex-store logo using from Loading indicator gif?

**Comment by minhcasi** [comment] 2020-05-19 04:29
You could update this file 

<img width="955" alt="Screen Shot 2020-05-19 at 11 28 27" src="https://user-images.githubusercontent.com/1459805/82284718-dd60c300-99c3-11ea-858e-2f49ea4b1483.png">

**Comment by minhcasi** [comment] 2020-05-20 03:53
Duplicate of #3294

**Closed by minhcasi** 2020-05-20 03:53 UTC
Labels: FluxStore, Use-For-Docs, common-questions ⁉️
