### ISSUE TITLE
Product Error

### ISSUE THREAD

**Issue by coolenginner** [inspireui/support#4813] opened 2020-08-31 11:13 UTC
Hello, I found an issue with your source code. When I read the product list using Graphiql's first time in the Category tab bar, it is working for me. 
Then I had clicked the back button and click any collection again, the product list is empty. I am sending you some screenshots. Please fix them and let me know.
Thank you. Justin. 

https://ibb.co/1XcW4h7
https://ibb.co/M20Pj4w

**Comment by minhcasi** [comment] 2020-08-31 12:46
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-09-02 06:01
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-09-02 06:01 UTC
Labels: needs-more-info
