### ISSUE TITLE
FluxNews - Flutter mobile app for Wordpress - Error

### ISSUE THREAD

**Issue by maruata** [inspireui/support#4306] opened 2020-07-22 04:46 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I am getting the following.

Compiler message:
lib/tabbar.dart:269:9: Error: The getter 'kLayoutWeb' isn't defined for the class 'MainTabsState'.
 - 'MainTabsState' is from 'package:fstore/tabbar.dart' ('lib/tabbar.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'kLayoutWeb'.
    if (kLayoutWeb) {
        ^^^^^^^^^^
lib/widgets/onesignal/onesignal.dart:9:34: Error: Getter not found: 'kOneSignalKey'.
    OneSignal.shared.init(config.kOneSignalKey['appID'], iOSSettings: {
                                 ^^^^^^^^^^^^^
lib/menu.dart:50:19: Error: The getter 'kLayoutWeb' isn't defined for the class '_MenuBarState'.
 - '_MenuBarState' is from 'package:fstore/menu.dart' ('lib/menu.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'kLayoutWeb'.
              if (kLayoutWeb) {
                  ^^^^^^^^^^
lib/menu.dart:150:65: Error: The getter 'kDefaultDrawer' isn't defined for the class '_MenuBarState'.
 - '_MenuBarState' is from 'package:fstore/menu.dart' ('lib/menu.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'kDefaultDrawer'.
        Provider.of<AppModel>(context, listen: false).drawer ?? kDefaultDrawer;
                                                                ^^^^^^^^^^^^^^

+ Product & version: 
![image](https://user-images.githubusercontent.com/57096001/88134680-e0b23e00-cc02-11ea-844a-06571597c867.png)

+ Flutter (or React Native) version: Flutter

+ Testing Device/Simulator: 

+ Screenshot issues (drag the file to attach here): 
![image](https://user-images.githubusercontent.com/57096001/88134823-430b3e80-cc03-11ea-8191-041721448e7c.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
![image](https://user-images.githubusercontent.com/57096001/88134858-5d451c80-cc03-11ea-95f7-368537a3e84f.png)

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment] 2020-07-22 06:59
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by maruata** [comment] 2020-07-22 07:09
> Thank you for the feedback.
> Please help us to submit this form and fill all required info to continue with the support - [http://verify.inspireui.com/ -](http://verify.inspireui.com/%C2%A0-) please don't share the purchase code or screenshot public here as another user will use it for activation.
> 
> We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

Submitted

**Comment by minhcasi** [comment] 2020-07-23 03:53
@maruata - this issue is cause by flutter cache, please help to try this script
```
flutter clean
flutter pub get
```

Ref: https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

Let us know your checking, thank you!

**Comment by minhcasi** [comment] 2020-07-24 08:23
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-24 08:23 UTC
Labels: FluxNews
