### ISSUE TITLE
android install issue

### ISSUE THREAD

**Issue by Candho1** [inspireui/support#3145] opened 2020-05-11 08:30 UTC
Hi now i have only this issue from your app please help me to fix . 

 <a href="https://ibb.co/b6NrR36"><img src="https://i.ibb.co/BfTgKPf/ice-screenshot-20200511-121017.png" alt="ice-screenshot-20200511-121017" border="0"></a>

 *** What went wrong:Execution failed for task** ### ':app:transformClassesAndResourcesWithR8ForRelease'.
> java.lang.IllegalArgumentException: Multiple entries with same key: Method com.google.firebase.iid.FirebaseInstanceId.zza Proto LLL com.google.android.gms.tasks.Task java.lang.String j
ava.lang.String=Encoded method Method com.google.firebase.iid.FirebaseInstanceId.zza Proto LLL com.google.android.gms.tasks.Task java.lang.String java.lang.String and Method com.google.f
irebase.iid.FirebaseInstanceId.zza Proto LLL com.google.android.gms.tasks.Task java.lang.String java.lang.String=Encoded method Method com.google.firebase.iid.FirebaseInstanceId.zza Prot
o LLL com.google.android.gms.tasks.Task java.lang.String java.lang.String

**Comment by minhcasi** [comment] 2020-05-11 09:12
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by Candho1** [comment] 2020-05-11 09:19
thanks sorry i removed now   it was accident  .

please look the screen shot now

**Comment by Candho1** [comment] 2020-05-11 10:01
Upload the Project Common Folder *
Only share the COMMON FOLDER as ZIP file from the project. These files will
help us reproduce the issue easier. Please do not share the whole source
code here. This folder will be saved privately and it will be removed after
we have solved your ticket.


Hi where can i find the    common folder    that you want  do you mean
create a zip whole source  file and than send as .  ???

**Comment by kvt0012** [comment] 2020-05-12 03:47
Which IDE do you use to build our app sir.   
And please make sure that you set up as our guide, sir.   
Thank you.

**Comment by Candho1** [comment] 2020-05-12 05:59
>cccIntelliJ IDEA 2020.1.1
Android studio 3.6

**Comment by kvt0012** [comment] 2020-05-12 07:39
https://github.com/inspireui/support/issues/3145#issuecomment-626603307   
On this comment, it means that which file do you config ? If you config any file, please send us these files and I will check what happens.   
If you don't know where to find common file, please send us your whole project, we will check it for you.,   
You can send me via my email : khiem@inspireui.com or vinhkhiemt135@gmail.com for priority. After that you comment your email you use to send to me here, I will check it for you. Thank you.

**Comment by Candho1** [comment] 2020-05-12 07:44
thanks but i sented the common folder did you got ??

**Comment by kvt0012** [comment] 2020-05-12 07:47
I will check it on our system later, thank you.

**Comment by Candho1** [comment] 2020-05-12 07:48
i all ready sended two folders with zip config and common folder >in my source\lib

**Comment by kvt0012** [comment] 2020-05-12 07:49
Which email do you use to send it to us ? It can help me find this file easier, thank you

**Comment by Candho1** [comment] 2020-05-12 07:50
khiem@inspireui.com

**Comment by Candho1** [comment] 2020-05-12 07:52
also i uploaded here
https://docs.google.com/forms/d/e/1FAIpQLScWOjkAJIWJ9rgb9alopfOqLsJrGKbFM5cCYj1JBfLKLsBblQ/viewform

**Comment by kvt0012** [comment] 2020-05-12 07:53
No, I mean that which email do you fill on this form, I will search it on our system, thank you.

**Comment by Candho1** [comment] 2020-05-12 07:55
this one candho130@gmail.com

**Comment by kvt0012** [comment] 2020-05-12 08:07
Ok thank you, I checked and please make sure that you use our newest version.

**Comment by Candho1** [comment] 2020-05-12 08:10
ok thank you which one i sure latest version

also i maked my app more than 5 day settings custom

**Comment by Candho1** [comment] 2020-05-12 08:12
can you please apply my source your latest version b/c it taked me to setup
my settings how can i apply my source your latest version without
downloading new version ..

**Comment by kvt0012** [comment] 2020-05-12 08:18
If you use the old version, please send me your whole project because on new version we config many files and it doesn't match with your version. Thank you

**Comment by Candho1** [comment] 2020-05-12 08:27
Ok i will send whole project source .

>

**Comment by kvt0012** [comment] 2020-05-12 08:38
Please update here when you send it, I will check it on our system. Thank you

**Comment by Candho1** [comment] 2020-05-12 10:41
source.zip
<https://drive.google.com/file/d/16lvgNz86gNu5b0yLi8DQExSRfRVosBGq/view?usp=drive_web>
this is whole project for soo market

**Comment by kvt0012** [comment] 2020-05-12 10:43
Dear sir, please open access because I can''t access to it, thank you.

**Comment by Candho1** [comment] 2020-05-12 11:30
ok thanks

**Comment by Candho1** [comment] 2020-05-12 11:31
https://drive.google.com/file/d/16lvgNz86gNu5b0yLi8DQExSRfRVosBGq/view?usp=sharing



you need this link roll is editor

**Comment by Candho1** [comment] 2020-05-12 11:54
did you got now access my file

**Comment by Candho1** [comment] 2020-05-12 12:35
https://drive.google.com/file/d/16lvgNz86gNu5b0yLi8DQExSRfRVosBGq/view?usp=sharing



you need this link roll is editor

please reply if you got access now .

**Comment by Candho1** [comment] 2020-05-12 22:19
khiem@inspireui.com or vinhkhiemt135@gmail.com    please check both this emails i shared the source file url .

**Comment by Candho1** [comment] 2020-05-13 05:49
> Dear sir, please open access because I can''t access to it, thank you.

How can i open the access i send the whole source file of the project .

**Comment by Candho1** [comment] 2020-05-13 09:59
still i am waiting answer

**Comment by kvt0012** [comment] 2020-05-14 07:46
What is your email, sir ? I will check it now. Thank you

**Comment by Candho1** [comment] 2020-05-14 08:10
my email is >  candho130@gmail.com


email i sent the source file is
 > vinhkhiemt135@gmail.com

**Comment by kvt0012** [comment] 2020-05-14 10:38
Please try to run   
flutter channel stable   
flutter clean   
flutter run  
Thank you

**Comment by Candho1** [comment] 2020-05-14 11:02
thanks i run all the codes you recommended  me they are working .

> bash tools/chenge-bundleid.sh
<https://www.youtube.com/redirect?redir_token=eZPaiI_rcZ29T91ICvJR-NRXsx18MTU4OTUzODE5MEAxNTg5NDUxNzkw&q=http%3A%2F%2Fchenge-bundleid.sh%2F&stzid=UgzWo251MgJfoPMUpNV4AaABAg.96TjsLTW5ww96UdPyrTTe9&event=comments>
   code not run   how can i fix?
   'bash' is not recognized as an internal or external command,
<https://www.youtube.com/redirect?redir_token=eZPaiI_rcZ29T91ICvJR-NRXsx18MTU4OTUzODE5MEAxNTg5NDUxNzkw&q=http%3A%2F%2Fchenge-bundleid.sh%2F&stzid=UgzWo251MgJfoPMUpNV4AaABAg.96TjsLTW5ww96UdPyrTTe9&event=comments>
operable program or batch file.
<https://www.youtube.com/redirect?redir_token=eZPaiI_rcZ29T91ICvJR-NRXsx18MTU4OTUzODE5MEAxNTg5NDUxNzkw&q=http%3A%2F%2Fchenge-bundleid.sh%2F&stzid=UgzWo251MgJfoPMUpNV4AaABAg.96TjsLTW5ww96UdPyrTTe9&event=comments>

**Comment by minhcasi** [comment] 2020-05-17 06:09
Duplicate of #3224

**Closed by minhcasi** 2020-05-17 06:09 UTC
Labels: FluxstoreMV
