### ISSUE TITLE
[FluxStore Pro] Some Problems

### ISSUE THREAD

**Issue by kumsalajans** [inspireui/support#3167] opened 2020-05-12 17:05 UTC
### ** 1) Go to product detail then  close product.  top icon not showing  (white color on white background)**

Same problem exists other pages 

Problem iOs, Android

![image](https://user-images.githubusercontent.com/63232893/81722233-bec17000-9489-11ea-868b-c55462e99d66.png)

### ** 2)  Using coupons, Negative amount**
![image](https://user-images.githubusercontent.com/63232893/81722613-4c04c480-948a-11ea-935a-b84d77310948.png)
![image](https://user-images.githubusercontent.com/63232893/81722630-51620f00-948a-11ea-945d-2f261e642388.png)

### **3) The amount of cargo not shown when advancing and returning in the basket is added to the first page.**

This causes problems. Cargo amount should not be included.

![image](https://user-images.githubusercontent.com/63232893/81722785-938b5080-948a-11ea-9ca8-9edc78c473ca.png)

### **4) The variant does not appear in the basket when auto-selected when the page is opened.**

reflected in the basket when the person chooses 

like 3rd product in basket page (second image)

![image](https://user-images.githubusercontent.com/63232893/81723142-16141000-948b-11ea-828f-07c280e7c148.png)

![image](https://user-images.githubusercontent.com/63232893/81723598-be29d900-948b-11ea-890f-4cc5d5c10c72.png)

**Comment by philipvu30** [comment] 2020-05-13 03:38
Hi,

Have you submitted the required information to our [form](http://private.inspireui.com)?
If you haven't, please do so. As I need your config files to reproduce your issue.

Thank you.

**Comment by EmreCaliskan1** [comment] 2020-05-13 08:59
Hi,

We have already verified ourselves. You can understand by account name. We contributed via gitlab

Please let's focus on my question.

Thank you.

**Comment by kumsalajans** [comment] 2020-05-13 09:00
Hi,

We have already verified ourselves. You can understand by account name. We contributed via gitlab

Please let's focus on my question.

Thank you.

**Comment by philipvu30** [comment] 2020-05-13 10:07
Hi,

Send your common and config folder to this email: toan@inspireui.com because I cannot find your files anywhere.

**Comment by kumsalajans** [comment] 2020-05-13 10:49
Hi,

I sent to your mail

**Comment by philipvu30** [comment] 2020-05-13 10:58
Received.

**Comment by philipvu30** [comment] 2020-05-15 05:18
Hi,

1. I don't see any problem. Would you mind sending me your asset folder?
2 3 4. Fixed

**Comment by kumsalajans** [comment] 2020-05-15 08:10
Hi,

Asset folder is original.  Is it tested on iOS ?

**Comment by philipvu30** [comment] 2020-05-15 09:02
@kumsalajans 

I need to test your "Category Icons" as I found no issue with our demo icons.
Please send your asset folder to this email: toan@inspireui.com
Thank you

**Comment by kumsalajans** [comment] 2020-05-15 09:25
Hi,

I sent to your mail

**Comment by philipvu30** [comment] 2020-05-18 05:46
Hi,

I don't see any problem. Am I reproducing your issue correctly?

[3167.zip](https://github.com/inspireui/support/files/4642234/3167.zip)

**Comment by kumsalajans** [comment] 2020-05-18 08:04
Hi, 

Go to product detail **(on home page bottom)** then close product. top icon not showing (white color on white background)**

**Comment by philipvu30** [comment] 2020-05-18 10:40
Hello,

I'm sorry but I still not manage to reproduce your issue. Everything seems fine to me. Would you mind recording your issue? Thanks.

**Comment by philipvu30** [comment] 2020-05-20 03:51
Hi,

I'll close this ticket as I haven't received any response from you. Feel free to ask us to re-open your ticket. Thanks

**Closed by philipvu30** 2020-05-20 03:51 UTC
Labels: FluxStore, order-payment, product-variant
