### ISSUE TITLE
How can I include sub-category to be visible also in my categories tab??

### ISSUE THREAD

**Issue by janpolfranco** [inspireui/support#4499] opened 2020-08-07 03:18 UTC
How can I include sub-category to be visible also in my categories tab??
I noticed that my sub categories, together with the products with the sub-categories are not visible on my category tabs in my fluxstore app.

**Comment by ameenbadri7** [comment] 2020-08-08 01:06
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Change the Categories Layout to one of those shapes: 

  card,
  sideMenu,
  column,
  subCategories,
  animation,
  grid

and put it here instead of `card` inside lib\config\config_en.json : 
` {
      "layout": "category",
      "categoryLayout": "card",
      "icon": "assets/icons/tabs/icon-category.png"
    },`

Thank you for your time!

**Comment by minhcasi** [comment] 2020-08-09 02:58
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-08-09 02:58 UTC
Labels: needs-more-info
