### ISSUE TITLE
[ Mstore ] - Image Missing from Select payment method

### ISSUE THREAD

**Issue by santhosh2210** [inspireui/support#648] opened 2019-05-28 06:26 UTC
Image missing from select payment method in my app...
i will correctly changethe config.js file and also checking the image.js....
But still image are not coming the select payment method ...
See the screenshot -> http://prntscr.com/nu8y4c

**Comment by minhcasi** [comment] 2019-05-28 12:40
kindly raise just one ticket for your issues, don't spam here - Duplicate of #642

**Closed by minhcasi** 2019-05-28 12:40 UTC
Labels: help wanted 🙏
