### ISSUE TITLE
UK Address format

### ISSUE THREAD

**Issue by niranjan62** [inspireui/support#4505] opened 2020-08-07 08:02 UTC
When selecting the United Kingdom as Shipping Address, the format should be like the below order.

      * Address line 1
      * Address line 2
      * City
      * **Post Code**

UK postcodes have Numbers and _text_. Currently postcode (Zip_code) textfield only allows numbers.
1. Please change Keypad format to add text for **Postcode field** 
2. Please change the UK Address format.

![UK-Address-format](https://user-images.githubusercontent.com/69341826/89623466-8bc22900-d88c-11ea-8ed6-3f19739286ae.png)

**Comment by ameenbadri7** [comment] 2020-08-08 01:16
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by minhcasi** [comment] 2020-08-08 01:24
Duplicate of #4505 - pls open 1 ticket for your all issue - thanks

**Closed by minhcasi** 2020-08-08 01:24 UTC
