### ISSUE TITLE
Stores are not being listed in app

### ISSUE THREAD

**Issue by keegho** [inspireui/support#5025] opened 2020-09-16 18:08 UTC
I'm an iOS native swift & flutter developer. I have same issue that stores are not being listed in the app. After some investigation and testing the end point on postman I found out that the store listing is returning an empty array. 

That is because the endpoint being printed in the debug screen is `/wp-json/wc/v2/flutter/wcfm-stores?&page=1` and `page=1` has no data. When I tried `page=0` it worked fine. So why is the app calling `page=1` as an initial call? Plus every time i use the toggle button in the nav bar to change between the categories and stores the page number is being incremented. Why?

Definitely there is something wrong here in the code. Any help how to fix that. Still couldn't find from where the `getStores()` function is being called.

_Originally posted by @keegho in https://github.com/inspireui/support/issues/4787#issuecomment-690800402_

**Comment by minhcasi** [comment] 2020-09-17 01:39
Duplicate of #5006 - pls help to raise new comments to our new ticket support https://support.inspireui.com - thank you!

**Closed by minhcasi** 2020-09-17 01:39 UTC
