### ISSUE TITLE
I'm not able to run app in even debug mode.

### ISSUE THREAD

**Issue by GNAG1993** [inspireui/support#4172] opened 2020-07-12 12:02 UTC
This is the issue-

Launching lib\main.dart on Infinix X626B in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app_settings:compileDebugAidl'.
> Failed to find Platform SDK with path: platforms;android-R

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

No changes are made in the code you guys provided. I'm trying to run the original code only.

I have submitted the proofs.

**Comment by karmelcorn** [comment] 2020-07-12 22:19
You can follow the solution in this thread. https://github.com/inspireui/support/issues/3708.

Specifically adding  the following to 

android>build.gradle helped me solve the problem. Good luck. 

`subprojects {
    project.evaluationDependsOn(':app')

    afterEvaluate {project ->
        if (project.hasProperty("android") && project.property("android").compileSdkVersion.equals("android-R")) {
            android {
                compileSdkVersion 28
            }
        }
    }

}`

**Comment by minhcasi** [comment] 2020-07-13 12:12
@GNAG1993 - pls download latest `1.7.6` to fix this issue - thank you!

**Comment by GNAG1993** [comment] 2020-07-14 04:36
@minhcasi - I'm unable to find the 1.7.6 version, its not showing up on codecanyon

**Comment by GNAG1993** [comment] 2020-07-14 04:48
@minhcasi I'm using multivendor version of Fluxstore. You guys have not updated the code of that version!!!????

**Comment by minhcasi** [comment] 2020-07-14 04:59
sorry my mistake, we will release it in 1-2 days

**Comment by GNAG1993** [comment] 2020-07-14 05:08
@minhcasi okay, thanx. Actually i'm totally newbie to development parts, so disturbing you aain and again. But we seriously need help. You guys support well really good. Keep doing the thing as same.

**Comment by minhcasi** [comment] 2020-07-15 03:53
@GNAG1993 - thank you, we will let you know when the release is updated

Please note that we may not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/ - but we are trying to best to give extra miles with the supporting.

**Comment by minhcasi** [comment] 2020-07-17 04:33
Duplicate of #4228

**Closed by minhcasi** 2020-07-17 04:33 UTC
Labels: 1.7.6, FluxstoreMV, android-R
