### ISSUE TITLE
vendor products show over and over urgent 

### ISSUE THREAD

**Issue by rabahaldoori** [inspireui/support#3626] opened 2020-06-06 18:40 UTC
vendor products show over and over this vendor has 200 products show only 10 and when load just load the 10 again    

https://www.youtube.com/watch?v=F9Op3gezUIw

thank you

**Comment by minhcasi** [comment] 2020-06-07 04:39
Duplicate of #3404 - pls move conversation to this ticket - thank you!

**Closed by minhcasi** 2020-06-07 04:39 UTC
