### ISSUE TITLE
 Fatal: failed to find callback

### ISSUE THREAD

**Issue by subhash1003** [inspireui/support#3207] opened 2020-05-15 09:40 UTC
When I am trying to integrate google and facebook login to the flutter app then after doing flutter run command it is showing the same error and the app is standstill on the splash screen.
the error is : E/FlutterFcmService(11308): Fatal: failed to find callback

**Comment by minhcasi** [comment] 2020-05-15 11:10
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-05-16 06:56
I'm sorry to close this ticket as there is no response, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-05-16 06:56 UTC
Labels: needs-more-info
