### ISSUE TITLE
Facebook login , android and ios error ? why 

### ISSUE THREAD

**Issue by metinemredonmez** [inspireui/support#5042] opened 2020-09-22 18:10 UTC
We have moved to a new ticket support system, please post your new ticket on this link http://support.inspireui.com/
below are the entries for android and ios available, and where do you think I'm making errors? 

ANDROID 
<img width="353" alt="Ekran Resmi 2020-09-22 21 07 41" src="https://user-images.githubusercontent.com/54211029/93920517-f4b81000-fd17-11ea-87fa-5e103e5f9bf2.png">

İOS 

<img width="273" alt="Ekran Resmi 2020-09-22 21 02 41" src="https://user-images.githubusercontent.com/54211029/93920532-faadf100-fd17-11ea-8ddb-d852ff152c53.png">

**Comment by metinemredonmez** [comment] 2020-09-22 18:48
and sms login error 
<img width="381" alt="Ekran Resmi 2020-09-22 21 43 47" src="https://user-images.githubusercontent.com/54211029/93924381-5333bd00-fd1d-11ea-9c8c-0f424d4c986a.png">

**Comment by metinemredonmez** [comment] 2020-09-22 19:09
I tried this error on my own phone gave android facebook login error ? 
![WhatsApp Image 2020-09-22 at 22 06 24](https://user-images.githubusercontent.com/54211029/93926511-42d11180-fd20-11ea-8bb8-6527715f7bf4.jpeg)

**Comment by minhcasi** [comment] 2020-09-23 03:44
Duplicate of #5006

**Closed by minhcasi** 2020-09-23 03:44 UTC
