### ISSUE TITLE
Fluxstore multivendor subcategories not showed

### ISSUE THREAD

**Issue by nadhim1991** [inspireui/support#4527] opened 2020-08-08 16:09 UTC
Hi

I am trying to get categories, subcategories and sub subcategories to be shown under categories tab in fluxstore but I couldn't find a way please help

I managed to get only main categories and some of subcategories only

Following is the structure i am looking for.

- Category A

--Category AA
---Category a1
---Category a2
---Category a3

--Category BB
---Category b1
---Category b2
---Category b3

--Category CC
---Category c1
---Category c2
---Category c3

--Category DD
---Category d1
---Category d2
---Category d3

Thanks

**Comment by minhcasi** [comment] 2020-08-09 02:15
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by nadhim1991** [comment] 2020-08-09 07:40
Submitted awaiting your response 

Many thanks

**Comment by minhcasi** [comment] 2020-08-10 04:46
Duplicate of https://github.com/inspireui/fluxbuilder/issues/178

We will update on the same ticket

**Closed by minhcasi** 2020-08-10 04:46 UTC
Labels: FluxstoreMV, feature-request 🆕
