### ISSUE TITLE
build in ios device failed

### ISSUE THREAD

**Issue by EVENFATE** [inspireui/support#3214] opened 2020-05-16 00:44 UTC
1.Your development team, "XXXXXX", does not support the Push Notifications, Associated Domains, and Sign In with Apple capabilities.
2.No profiles for 'mstore123' were found

two errors when build in iOS device

how to fix it

**Comment by minhcasi** [comment] 2020-05-16 07:00
@EVENFATE 
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-05-17 07:43
I'm sorry to close this ticket as there is no response, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-05-17 07:43 UTC
Labels: needs-more-info
