### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:19001     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)

### ISSUE THREAD

**Issue by anandkausha** [inspireui/support#2741] opened 2020-04-16 12:34 UTC
Step 1 (require): When we give build android command we are getting this error

![444](https://user-images.githubusercontent.com/63690210/79456466-34155e80-800c-11ea-83f1-ebf44eff8fcc.png)

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please submit ticket support by following above 2 require steps, we may close the ticket without providing full information.*

**Comment by minhcasi** [comment] 2020-04-17 00:55
Duplicate of #2742

**Closed by minhcasi** 2020-04-17 00:55 UTC

**Comment by dragslag** [comment] 2020-05-19 08:12
I got this error. If you're using expo, this might be worth a shot.

What worked for me was:
cd myproject
expo start
*press _control c_ to stop the metro bundler*
export EXPO_DEBUG=true
expo build:android -t app-bundle
