### ISSUE TITLE
[my-product] - 

### ISSUE THREAD

**Issue by spss20** [inspireui/support#1183] opened 2019-10-06 09:37 UTC
Sir, I checked your demo app for fluxstore which was only of 20 Mb. But when i am building my own fluxstore app. Its size is 61 Mb. Also it is not smooth like your demo app and loads data from server slowly
---------

**Comment by minhcasi** [comment] 2019-10-06 11:24
Duplicate of #1173

**Closed by minhcasi** 2019-10-06 11:24 UTC
Labels: question ❓
