### ISSUE TITLE
TAP PAYMENT & ORDER STATUS ISSUES 

### ISSUE THREAD

**Issue by siyashamsudeen** [inspireui/support#3081] opened 2020-05-07 22:59 UTC
Step 1 (require): detail issues and screenshots

Please do not ignore my support request. 

I really appreciate the support you are providing . to make the app fully functional i need some more help from your end. Please help to fix the following issues:

**MAIN Issue A:**  For Wrong Card details also order gets completed in the App - When Wrong card details are entered the payment is declined in TAP dashboard Transactions but in App it shows payment successful and order completed . 

<img width="361" alt="Screen Shot 2020-05-07 at 6 00 46 AM" src="https://user-images.githubusercontent.com/57159602/81246916-d03dee80-9029-11ea-9dd6-0ca54cfdd02b.png">

![image](https://user-images.githubusercontent.com/57159602/81246811-97057e80-9029-11ea-9b2a-4888fdf135c5.png)
![image](https://user-images.githubusercontent.com/57159602/81246873-b8666a80-9029-11ea-8b66-5ca9002b04ea.png)

**Screenshot from TAP Transanctions:**

<img width="1010" alt="Screen Shot 2020-05-07 at 6 16 10 AM" src="https://user-images.githubusercontent.com/57159602/81247196-6d008c00-902a-11ea-9c32-a9cafc811e92.png">

But when trying through woocommerce website directly it shows correct the payment declined and asks to enter the card details again - 

Screenshot from Web with same card details (not working card ):

<img width="667" alt="Screen Shot 2020-05-07 at 5 59 55 AM" src="https://user-images.githubusercontent.com/57159602/81247039-05e2d780-902a-11ea-9238-f3462814eb6d.png">

**Issue B:** Order status of orders from App are changing to **COMPLETED** after successful payment . it is suppose to be **PROCESSING** . for TAP Payment orders from APP are changing to "Completed". 

But from WooCommerce Direct Website Checkout it change status correctly to "Processing"

**CUSTOMIZATION HELP** : Is it possible to force users to enter phone number in a specific format such as starting with country code without any trailing 0 and + .

May be by prefixing the country as a dropdown box and asking them to enter only the local phone number or Atleast in the label is it possible to give instruction . 

i tried the below but is not working: ( change the label text in language file )

![image](https://user-images.githubusercontent.com/57159602/81247397-f44dff80-902a-11ea-93bd-88205994b358.png)

its not reflecting : 

![image](https://user-images.githubusercontent.com/57159602/81247363-e304f300-902a-11ea-9ec5-b5af4bfce616.png)

**Issue C:**

This build issue i had mentioned previously in another ticket also but its not yet resolved . im currently building the app through XCode after adding a new build phase run script:

im getting codesign error when i run the code after making any file change in the project directory such as adding logo file or changing app icon or any file if i just add it to the project directory it will throw code sign error.

![image](https://user-images.githubusercontent.com/57159602/81247539-5a3a8700-902b-11ea-96a1-1c056b0f03aa.png)

After hours of research i managed to run the code through xcode by adding a new build phase run script . but still it runs through xcode only . in android studio it still gives the error . please find the below screenshots . what can be done so that i can run the code in android studio without errors ?

<img width="731" alt="81003497-07f73b80-8e5c-11ea-91e1-e60c02043e1f" src="https://user-images.githubusercontent.com/57159602/81247518-47c04d80-902b-11ea-9f5f-140998ba12d3.png">

Please help to fix the above issues . thank you so much in advance and requesting for your kind support. 

Thank You

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

![image](https://user-images.githubusercontent.com/57159602/81247687-b30a1f80-902b-11ea-985d-302a11ea1b0a.png)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment] 2020-05-08 03:03
Duplicate of #3063

**Closed by minhcasi** 2020-05-08 03:03 UTC
