### ISSUE TITLE
@michmj - we got your verify purchased - sorry we have closed your previous ticket as you could not provide the verify on step 2 - would you mind to update our rating?

### ISSUE THREAD

**Issue by michmj** [inspireui/support#3658] opened 2020-06-09 20:25 UTC
here is the result after running flutter doctor:
C:\Users\Michael\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [VersiÃ³n 10.0.18362.836], locale es-MX)
    • Flutter version 1.17.2 at C:\Users\Michael\flutter
    • Framework revision 5f21edf8b6 (12 days ago), 2020-05-28 12:44:12 -0700
    • Engine revision b851c71829
    • Dart version 2.8.3

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Michael\AppData\Local\Android\sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
Process finished with exit code 0

_Originally posted by @minhcasi in https://github.com/inspireui/support/issues/3638#issuecomment-640963578_

**Comment by minhcasi** [comment] 2020-06-10 02:45
Duplicate of #3638

**Closed by minhcasi** 2020-06-10 02:45 UTC
