### ISSUE TITLE
Warning: FormatException

### ISSUE THREAD

**Issue by opooletech** [inspireui/support#3099] opened 2020-05-08 20:11 UTC
<img width="317" alt="76146795-1b03b000-6053-11ea-9483-8b51960c013b" src="https://user-images.githubusercontent.com/8824264/81445184-db139300-9191-11ea-8e26-65604d732f2b.png">
I've sent common folder and proof of purchase. Thanks.
![image](https://user-images.githubusercontent.com/8824264/81445282-fe3e4280-9191-11ea-83a4-af08ba6aaa81.png)
Warning: FormatException: Unexpected character (at chaacter1)
Dear sir having issue in signin signup please help to resolve the issue
even everything correct connect
Be sure you have pasted the SHA-1 key to your Firebase setting. Check more in https://docs.inspireui.com/fluxstore/common-issues/ - thank you
Everything done even purchase key enter also in mstore
but still having issue in signin or signup product show in app

**Comment by minhcasi** [comment] 2020-05-09 03:22
Duplicate of #3097

**Closed by minhcasi** 2020-05-09 03:22 UTC
