### ISSUE TITLE
[FluxStore Pro] Do I need to open a new issue for every comment?!!

### ISSUE THREAD

**Issue by bikostudio** [inspireui/support#3247] opened 2020-05-17 20:48 UTC
Hi 

Before I buy the app I asked the support If I don't have any flutter skills will you give me the support to build my app? and the answer was yes.

First, I'm sorry to say that but I really don't understand why you recently  close new issues once you answer the question and before I replay with the feedback? And when I replay with feedback I got no answer.

Do I have to open a new issue for feedback too?

Second, What I know that every update is suppose to fix old bugs and/ or adding new features. What I;m facing with FluxStore Pro app, every update I errors fixed and another errors appear which were working before. Is this normal?

Please if you don't have time or patience to support. tell me and I will not ask again for anything.

Thank you

**Comment by minhcasi** [comment] 2020-05-18 04:35
@bikostudio - we will keep this ticket open for your question, please help to give your comment here. 

Please help to try your best with the document to support the customization https://docs.inspireui.com/fluxstore/customization/ instead of raising a new ticket for any question that you don't know. For some question regarding the customization/integration with your website, we may not support as not include from our support scope - https://tppr.me/u3lSj - but we have tried our best with the answer on previous questions.

Thank you for your time!

**Comment by minhcasi** [comment] 2020-05-18 04:38
Duplicate of #3255 - we will keep you comment on this ticket

**Closed by minhcasi** 2020-05-18 04:38 UTC
Labels: FluxStore
