### ISSUE TITLE
[Fluxstore Pro v1.6.6b] After reopen the app, all items in shopping cart shows error 

### ISSUE THREAD

**Issue by karltai** [inspireui/support#2615] opened 2020-04-08 03:38 UTC
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: 
After reopen the app, all items in shopping cart shows error 

2. Screenshots issues (required):
<img width="364" alt="螢幕截圖 2020-04-08 上午1 36 44" src="https://user-images.githubusercontent.com/60211232/78741935-3a149b00-798d-11ea-83da-e6ea836fb859.png">

3. Proof of my purchased (required):
<img width="589" alt="螢幕截圖 2020-04-08 上午11 37 36" src="https://user-images.githubusercontent.com/60211232/78741994-5e707780-798d-11ea-8b3b-d7ee0e8ce384.png">

3. Config files (required)
<img width="566" alt="螢幕截圖 2020-04-08 上午11 38 04" src="https://user-images.githubusercontent.com/60211232/78742015-6f20ed80-798d-11ea-9377-f9a95e4fa0b7.png">

**Comment by Pascalnhuis** [comment] 2020-04-08 05:21
Same error here! This Error is also in there demo itself. So they need to know about this Error.

**Comment by karltai** [comment] 2020-04-08 05:47
<img width="671" alt="螢幕截圖 2020-04-08 下午1 46 09" src="https://user-images.githubusercontent.com/60211232/78748744-56213800-799f-11ea-9205-79e82be7cb28.png">
incorrect key
onSale -> on_sale
salePrice -> salse_price
inStock -> in_stock

**Comment by karltai** [comment] 2020-04-08 06:32
<img width="697" alt="螢幕截圖 2020-04-08 下午2 30 46" src="https://user-images.githubusercontent.com/60211232/78751862-8ff53d00-79a5-11ea-980e-d84ed19a67b6.png">
Also models/cart.dart should also update _productVariationInCart & _productSkuInCart when isSaveLocal is false

**Comment by Pascalnhuis** [comment] 2020-04-08 07:10
![studio64_TFycB91HCV](https://user-images.githubusercontent.com/62649032/78754970-a9cc5b00-7978-11ea-8daa-3f828b6e220b.png)

For people who using version 1.6.6b, you don't need to update _**_productVariationInCart & _productSkuInCart**_, but you need to update: isSaveLocal: false --> isSaveLocal: true

**Comment by philipvu30** [comment] 2020-04-08 09:47
Thanks @Pascalnhuis

Or you could just replace this file [cart.zip](https://github.com/inspireui/support/files/4449634/cart.zip) in lib/models/cart.dart.

**Comment by philipvu30** [comment] 2020-04-09 06:44
Hi @Pascalnhuis @karltai ,

Please confirm if this issue is fixed with the solution above so I can close ticket. Otherwise, it'll be automatically closed if there is no response in 2 days. Thanks

**Comment by Pascalnhuis** [comment] 2020-04-09 09:06
Hi! At my side it has fixed now, but there has started an another issue. I will send you a link to youtube. Hopefully you will watching it.

https://youtu.be/Sk0Oq8JToNA

There is a Paypal issue, that wasn't before last update and I have a mollie issue. 

Please take a look. Thanks! :)

**Comment by philipvu30** [comment] 2020-04-09 09:27
@Pascalnhuis ,

Please try to put in the right formatted address, most likely it is caused by phone number.

**Comment by Pascalnhuis** [comment] 2020-04-09 09:55
Paypal has been fixed! Thanks! Only Mollie doesn't still work now. I get the same issue as in the video. Do you know what to do?

Thanks in advanced!

**Comment by philipvu30** [comment] 2020-04-09 10:07
Hi @Pascalnhuis 

Can you make payment without opening that app (ING)?

**Comment by Pascalnhuis** [comment] 2020-04-09 12:53
Hi,

Yes I can make a payment when I press on the button below. (Gebruikersnaam en wachtwoord -> Username and Password), But for many people, this doesn't feel safe. Usually you don't want to enter your details in other apps outside your bank. It is therefore important to me that people can pay via the original bank app. I am a bit disappointed that this is just the only error before I can officially use the app. Hopefully you know how I can fix this. I have searched the internet a bit, but I am not such a code developer like you, maybe you know a solution?

In any case, I would like to thank you very much for your time and help!

**Comment by philipvu30** [comment] 2020-04-10 10:43
Hi @Pascalnhuis ,

Unfortunately, we currently do not support payment in another app at the moment. We will consider implementing it in the future. Thank you for your interest.

**Comment by Pascalnhuis** [comment] 2020-04-10 12:07
Thanks for your reply!

For now it's okay! :) Hopefully this will be a new feature for in the future! We will wait.

Thanks in advanced and for your time! 

HAve a nice day!

**Closed** 2020-04-11 04:38 UTC
Labels: FluxStore, question ❓

**Comment by danielito-1** [comment] 2020-04-20 00:21
> isSaveLoca

funciona correctamente!

 muchas gracias!
