### ISSUE TITLE
Two column sliding banner

### ISSUE THREAD

**Issue by shirochan88** [inspireui/support#5032] opened 2020-09-18 06:16 UTC
I'm trying to create a two-column sliding banner based on the two-column banner by enabling the 'autoPlay' to true.

But, the app generates a single column slider. What am I missing?

```
    {
      "layout": "bannerImage",
      "isSlider": true,
      "autoPlay": true,
      "showNumber": false,
      "design": "default",
      "showBackGround": true,
      "radius": 2.0,
      "items": [
        {
          "category": 27,
          "image": "https://user-images.githubusercontent.com/1459805/59846823-12ffc500-938b-11e9-8d93-65ead3d6b1dd.png",
          "padding": 5.0
        },
        {
          "category": 29,
          "image": "https://user-images.githubusercontent.com/1459805/59846824-12ffc500-938b-11e9-8d5a-fc42cb1b7658.png",
          "padding": 5.0,
          "featured": true
        },
        {
          "category": 26,
          "image": "https://user-images.githubusercontent.com/1459805/59846824-12ffc500-938b-11e9-8d5a-fc42cb1b7658.png",
          "padding": 5.0,
          "featured": true
        },
        {
          "category": 26,
          "image": "https://user-images.githubusercontent.com/1459805/59846824-12ffc500-938b-11e9-8d5a-fc42cb1b7658.png",
          "padding": 5.0,
          "featured": true
        },
        {
          "category": 26,
          "image": "https://user-images.githubusercontent.com/1459805/59846824-12ffc500-938b-11e9-8d5a-fc42cb1b7658.png",
          "padding": 5.0,
          "featured": true
        }
      ]
    },


```

**Comment by minhcasi** [comment] 2020-09-18 07:49
Duplicate of #5006

**Closed by minhcasi** 2020-09-18 07:49 UTC
