### ISSUE TITLE
FluxNews. the article doesnt show images (which are in the article on the website).

### ISSUE THREAD

**Issue by Jazzykhan** [inspireui/support#5043] opened 2020-09-22 23:34 UTC
Hi the articles are not showing images which are within the article on the website see this:
https://dailymans.com/never-swallow-chewing-gum/
it has one image after one paragraph that image is not showing in the application.
thanks

**Comment by minhcasi** [comment] 2020-09-23 03:45
Duplicate of #5006

**Closed by minhcasi** 2020-09-23 03:45 UTC
