### ISSUE TITLE
No route was found matching the URL and request ...

### ISSUE THREAD

**Issue by ajaysinghof** [inspireui/support#4335] opened 2020-07-23 20:34 UTC
I'm getting this error while signup and while making online payment 

No route was found matching the URL and request ...
![Simulator Screen Shot - iPhone 11 - 2020-07-24 at 02 03 54](https://user-images.githubusercontent.com/63315789/88336067-fbdf9380-cd51-11ea-911e-0c4a7bdf7e3b.png)

**Comment by ameenbadri7** [comment] 2020-07-23 21:29
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

Did you activate your [Mstore plugin](https://docs.inspireui.com/fluxstore/woocommerce-setup/
)?

**Comment by ajaysinghof** [comment] 2020-07-23 22:09
Yes Mstore plugin is activated

**Comment by ameenbadri7** [comment] 2020-07-24 03:53
Uninstall the plugin and download it again and activeate your account license again.

**Comment by minhcasi** [comment] 2020-07-24 04:14
@ajaysinghof - pls help to share the proof of purchase from step 2 - thank you!

**Comment by ameenbadri7** [comment] 2020-07-24 23:49
I'm sorry to close this ticket as there is no response or active conversation. 

Please help to create a new one and link to this ticket if the problem is not solved. 

- Thank you for your time!

**Closed** 2020-07-24 23:48 UTC
Labels: needs-more-info
