### ISSUE TITLE
Log In Problem

### ISSUE THREAD

**Issue by maurovanschaik** [inspireui/support#3994] opened 2020-07-01 02:08 UTC
Hello!

We have a problem with the log in in the app.

When I register as an user in the web (Listeo web), and I try to log in in the app, there appears the error “Flutter_user” (Exception: Unknown controller), like in the image.

![ERROR FLUX](https://user-images.githubusercontent.com/67668916/86195108-915a7f80-bb26-11ea-988e-daa51b9cc9e9.jpg)

We have already synchronized the app with de hosting.

We await your answer, regards!

**Comment by minhcasi** [comment] 2020-07-01 02:32
@maurovanschaik 

Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-07-02 03:30
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-02 03:30 UTC
Labels: needs-more-info
