### ISSUE TITLE
Too Many Issues

### ISSUE THREAD

**Issue by ajeets1978** [inspireui/support#1268] opened 2019-10-22 11:25 UTC
1. Categories Listing Issue Some Red Screen with Error Apppearing

![Category Error](https://user-images.githubusercontent.com/4997895/67281248-b8ce6680-f51a-11e9-9a5e-1a0cd7e9de54.PNG)

== Console Log ===
I/flutter ( 1431): Receiver: null
I/flutter ( 1431): Tried calling: [](0)
I/flutter ( 1431): 
I/flutter ( 1431): User-created ancestor of the error-causing widget was:
I/flutter ( 1431):   Row
I/flutter ( 1431):   file:///E:/AndroidStudio/Flutter/FluxStore/FluxStore-woo%201.5.5c/source/lib/widgets/home/category/category_icon_items.dart:163:16
I/flutter ( 1431): 
I/flutter ( 1431): When the exception was thrown, this was the stack:
I/flutter ( 1431): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
I/flutter ( 1431): #1      CategoryItem.build (package:fstore/widgets/home/category/category_icon_items.dart:28:43)
I/flutter ( 1431): #2      StatelessElement.build (package:flutter/src/widgets/framework.dart:4009:28)
I/flutter ( 1431): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3941:15)
I/flutter ( 1431): #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter ( 1431): #5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter ( 1431): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter ( 1431): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #8      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5233:32)
I/flutter ( 1431): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter ( 1431): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter ( 1431): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter ( 1431): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter ( 1431): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter ( 1431): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter ( 1431): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter ( 1431): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter ( 1431): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter ( 1431): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter ( 1431): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter ( 1431): #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter ( 1431): #35     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
I/flutter ( 1431): #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter ( 1431): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #39     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter ( 1431): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter ( 1431): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter ( 1431): #44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter ( 1431): #45     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter ( 1431): #46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter ( 1431): #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter ( 1431): #50     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter ( 1431): #51     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter ( 1431): #52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #54     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter ( 1431): #55     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #57     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter ( 1431): #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #60     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter ( 1431): #61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #63     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter ( 1431): #64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter ( 1431): #67     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter ( 1431): #68     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter ( 1431): #69     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter ( 1431): #70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter ( 1431): #73     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter ( 1431): #74     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter ( 1431): #75     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
I/flutter ( 1431): #76     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter ( 1431): #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter ( 1431): #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter ( 1431): #81     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter ( 1431): #82     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
I/flutter ( 1431): #83     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter ( 1431): #84     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter ( 1431): #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter ( 1431): #88     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter ( 1431): #89     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter ( 1431): #90     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #92     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter ( 1431): #93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter ( 1431): #96     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter ( 1431): #97     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter ( 1431): #98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter ( 1431): #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter ( 1431): #102    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter ( 1431): #103    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter ( 1431): #104    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter ( 1431): #105    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #106    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5233:32)
I/flutter ( 1431): #107    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #109    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter ( 1431): #110    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #112    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter ( 1431): #113    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #115    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter ( 1431): #116    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #118    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter ( 1431): #119    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter ( 1431): #122    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter ( 1431): #123    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter ( 1431): #124    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter ( 1431): #125    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #126    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #127    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter ( 1431): #128    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #129    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
I/flutter ( 1431): #131    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
I/flutter ( 1431): #132    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
I/flutter ( 1431): #133    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
I/flutter ( 1431): #134    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
I/flutter ( 1431): #135    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #136    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
I/flutter ( 1431): #137    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
I/flutter ( 1431): #138    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
I/flutter ( 1431): #139    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)

**Comment by minhcasi** [comment] 2019-10-22 11:53
Duplicate of #1271

Kindly notes:
- Create one ticket for your all issue with detail screenshot
- Share your config file (common/config.json and config.js) so we can reproduce issues.
- Also, make sure to check the document first - https://docs.inspireui.com/fluxstore

**Closed by minhcasi** 2019-10-22 11:53 UTC
