### ISSUE TITLE
Fluxstore MV PAYPAL CHECKOUT

### ISSUE THREAD

**Issue by yassiney120** [inspireui/support#3722] opened 2020-06-13 17:13 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 

Hello i want ask you if the app is compatible with paypal checkout
![90D43006-D18D-4DFF-A2C0-884D1C3FA795](https://user-images.githubusercontent.com/8164673/84574872-84196300-adba-11ea-89f5-b135b2969630.png)

+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

Already send verification
#3514 

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment] 2020-06-15 03:33
Duplicate of #3725

**Closed by minhcasi** 2020-06-15 03:33 UTC
