### ISSUE TITLE
Inspire UI dosnt work 

### ISSUE THREAD

**Issue by anwark** [inspireui/support#597] opened 2019-05-18 09:23 UTC
**Mandatory Info ListApp Pro
 - Your Purchased Code: ae03d146-d1ca-4017-85e6-98303d17fb33

**Describe the issues**
I try to run app with Inspire UI but it is not working please see screenshot 

**Screenshots**
https://www.screencast.com/t/sXmNj8MTb621

**Additional context**
C:\ListPro 1.3.3\source>-----------------------------------------------------------------------------------] 7698/46375
warning " > react-native-tab-view@2.0.3" has unmet peer dependency "react-native-gesture-handler@*".
warning " > react-native-tab-view@2.0.3" has unmet peer dependency "react-native-reanimated@*".
[##################----------------------------------------------------------------------------------------] 7689/46375
warning "react-navigation > react-navigation-drawer@1.3.0" has unmet peer dependency "react-native-gesture-handler@^1.0.12".
warning "react-navigation > react-navigation-drawer@1.3.0" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-stack@1.1.1" has unmet peer dependency "react-native-gesture-handler@^1.0.0[################------------------------------------------------------------------------------------------] 6794/46375
warning "react-navigation > react-navigation-stack@1.1.1" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-tabs@1.0.2" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning " > reactotron-redux@3.1.0" has unmet peer dependency "reactotron-core-client@^2.5.0".
[###############-------------------------------------------------------------------------------------------] 6777/46375

**Comment by anwark** [comment] 2019-05-18 10:46
I even just try with the latest version - ListPro 1.2.1 

Result is - https://www.screencast.com/t/DR9V7gYeg

**Comment by minhcasi** [comment] 2019-05-19 07:54
Duplicate of #592

**Closed by minhcasi** 2019-05-19 07:54 UTC
