### ISSUE TITLE
[mstore multi vender]i have problem in login ... the app is login me only as wonder... even i try with user i'd...

### ISSUE THREAD

**Issue by ZamanGoraya** [inspireui/support#1157] opened 2019-10-03 07:06 UTC
![Mstore multi vendor](https://user-images.githubusercontent.com/52818458/66105973-35ce8600-e5d6-11e9-864a-afa39e0b3993.PNG)

**Comment by ZamanGoraya** [comment] 2019-10-03 07:06
i am an employee and my boss bought it...

**Comment by ZamanGoraya** [comment] 2019-10-03 07:11
![tricells chat](https://user-images.githubusercontent.com/52818458/66106267-dfae1280-e5d6-11e9-9d54-26c255f2d621.PNG)

**Comment by minhcasi** [comment] 2019-10-03 12:03
Duplicate of #1153

**Closed by minhcasi** 2019-10-03 12:03 UTC
Labels: question ❓

**Comment by ZamanGoraya** [comment] 2019-10-03 15:56
this is an other problem dear...!

**Comment by ZamanGoraya** [comment] 2019-10-04 12:56
this is an other problem dear...
