### ISSUE TITLE
Images Not displaying for products 

### ISSUE THREAD

**Issue by muthuarcus97** [inspireui/support#4556] opened 2020-08-11 07:02 UTC
If I connect using my opencart url images are not displaying in product list .
![Screenshot_2020-08-08-14-21-57-325_host exp exponent](https://user-images.githubusercontent.com/66162709/89867304-a1a65580-dbce-11ea-808f-b2a817351774.jpg)
![Screenshot_2020-08-08-14-22-09-109_host exp exponent](https://user-images.githubusercontent.com/66162709/89867320-a539dc80-dbce-11ea-8165-38e5acb59907.jpg)
![Screenshot_2020-08-08-14-20-27-737_host exp exponent](https://user-images.githubusercontent.com/66162709/89867324-a5d27300-dbce-11ea-8598-e3d9716f7dcf.jpg)

Give some solutions for that.

**Comment by ameenbadri7** [comment] 2020-08-11 18:36
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by minhtruong315** [comment] 2020-08-13 09:27
@muthuarcus97 can u send me full your source code via email: minhtruong315@gmail.com
ping me when you sent. I'll help you check it
Thanks

**Comment by minhcasi** [comment] 2020-08-16 07:24
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Comment by minhcasi** [comment] 2020-08-17 10:41
@muthuarcus97 - pls update and send your source code to  minhtruong315@gmail.com - thanks

**Comment by minhtruong315** [comment] 2020-08-19 02:35
@muthuarcus97 ping me when you sent.
Thanks

**Comment by muthuarcus97** [comment] 2020-08-19 09:07
I sent my project to your main.Check it

**Comment by muthuarcus97** [comment] 2020-08-19 09:09
I have many issues when connect to my opencart Api.Please check and update it as soon as possible.Thank you for your response.

**Comment by muthuarcus97** [comment] 2020-08-19 09:45
i forgot to add my opencart server api in that .You can use https://inspices.com/site/ in opencart url

**Comment by minhtruong315** [comment] 2020-08-19 16:52
@muthuarcus97 can u check why your website doesn't allow to show image?
https://www.inspices.com/site/image/cache/catalog/products/4-268x268-370x370.jpg
<img width="1627" alt="Screen Shot 2020-08-19 at 11 52 00 PM" src="https://user-images.githubusercontent.com/10402500/90666054-10427d80-e277-11ea-9880-4522e8bdde7e.png">

**Comment by muthuarcus97** [comment] 2020-08-20 06:12
you can use this demo url http://inspices.in/opencart-3.0.3.6/upload/ .It shows images only for certain products.If i search some product in search it shows some error.And also gives fontfamily error ,app loading throw an unexpected errors (I attached screenchot for this errors).

**Comment by minhtruong315** [comment] 2020-08-20 08:59
Hi @muthuarcus97 please reinstall this mstore extension
[mstore.ocmod.zip](https://github.com/inspireui/support/files/5101875/mstore.ocmod.zip)

**Comment by minhtruong315** [comment] 2020-08-24 03:05
Hi, I'm closing this ticket as there is no response after more than 2 days, if you have any questions or reproducing the issue kindly reopen or create a new ticket - thank you!

**Closed by minhtruong315** 2020-08-24 03:05 UTC
Labels: Mstore-Opencart
