### ISSUE TITLE
[BeoNews] Beonews Pro Android issue

### ISSUE THREAD

**Issue by hadi13** [inspireui/support#337] opened 2019-02-26 21:40 UTC
**Mandatory Info (please complete the following information):**
Product: [Beonews]
Your Purchased Code: 2b7fa788-ea4d-4d1c-bb3a-4bf22a499783

**Describe the issues**
I have the below errors when building android pro version on android studio
**Screenshots**
https://i.postimg.cc/vHCDkyjM/Screen-Shot-2019-02-27-at-12-39-23-AM.png

**Additional context**
`WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
Affected Modules: app

WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: android-react-native-admob, android-react-native-blur, android-react-native-vector-icons, app, react-native-onesignal

WARNING: Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: react-native-onesignal

WARNING: The specified Android SDK Build Tools version (27.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.3.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '27.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
Remove Build Tools version and sync project
Affected Modules: android-lottie-react-native, android-react-native-admob, android-react-native-blur, android-react-native-fast-image, android-react-native-fbsdk, android-react-native-linear-gradient, android-react-native-vector-icons, android-react-native-webview, app, react-native-onesignal
`

**Comment by minhcasi** [comment] 2019-02-27 16:25
Duplicate of #316

**Closed by minhcasi** 2019-02-27 16:25 UTC

**Comment by hadi13** [comment] 2019-02-27 16:26
so what is the solution ????
