### ISSUE TITLE
How to enable caching in wordpress i have installed mstore api and wp-rest-cache

### ISSUE THREAD

**Issue by febinmhd** [inspireui/support#4855] opened 2020-09-03 08:24 UTC
<img width="854" alt="Screen Shot 2020-09-03 at 11 19 15 AM" src="https://user-images.githubusercontent.com/51330162/92089962-839bd180-edd7-11ea-834d-48f888898e7a.png">
i want to enable aching on my mstore react native app so that i can change the layout from the app config file. i can only see the documentation from flux store in the website not for mstore. i have installed mstore api and wp-rest-cache also yet it is not showing caching is active . please advise. thanktoy

**Comment by minhcasi** [comment] 2020-09-03 10:55
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-09-04 04:42
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-09-04 04:42 UTC
Labels: needs-more-info

**Comment by febinmhd** [comment] 2020-09-05 07:26
what more details do you require please tell
