### ISSUE TITLE
google sign in error and need to remove cancel button

### ISSUE THREAD

**Issue by mohamedibrahim89** [inspireui/support#3130] opened 2020-05-10 08:56 UTC
I have only this 2 issues

First google login give me this error also in the last version 1.7.3
![80923139-e9bd0d00-8d81-11ea-9230-e5ca1f9f0fb2](https://user-images.githubusercontent.com/35544603/81494907-a47e6b00-92ac-11ea-9233-f929685906e1.jpeg)

Second I need to cancel refund and cancel order (or show it to customer for only 15 min from make order)

![WhatsApp Image 2020-05-07 at 9 00 51 AM-1](https://user-images.githubusercontent.com/35544603/81494912-a9431f00-92ac-11ea-8326-59f3b157ee7d.jpeg)

And about refund request how it work it automatically refund not make request to me to approve or not

Thxxx 

<img width="1440" alt="Screen Shot 2020-05-10 at 10 55 13 AM" src="https://user-images.githubusercontent.com/35544603/81494923-c0820c80-92ac-11ea-8123-cd8a73d13351.png">

[config.zip](https://github.com/inspireui/support/files/4605391/config.zip)

**Comment by minhcasi** [comment] 2020-05-11 01:50
@mohamedibrahim89 

Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by mohamedibrahim89** [comment] 2020-05-11 10:53
@minhcasi  I submit the form for 4th time plz need ur help to solve this 2 issues asap

**Comment by aishema2000** [comment] 2020-05-11 14:14
This issue came with 1.7.3 version. It is impossible to login. I also submitted a ticket without knowing others are facing same problem. I am waiting for a good solution

**Comment by minhcasi** [comment] 2020-05-12 02:55
@mohamedibrahim89 - sorry we have got your verified - pls help to link other verified ticket on next time without submitting it again 😊

I've assigned to the team for checking and get back you shortly 

@trunghieuvn - pls investigate this login issue

**Comment by mohamedibrahim89** [comment] 2020-05-12 07:53
@minhcasi about cancel and refund and refund request button don't need them from where can I disable them also

**Comment by minhcasi** [comment] 2020-05-13 10:29
@mohamedibrahim89 - thank you for your confirm 

Please help us to move the login issue conversation to this ticket #3151 - this is new issue from the Google login that we could not figure out the root cause, could be some new policies from Google API - thank you!

**Closed by minhcasi** 2020-05-13 10:29 UTC
Labels: FluxStore, login-issue

**Comment by mohamedibrahim89** [comment] 2020-05-13 10:51
@minhcasi again and again u don't tell me how to solve the other issue to remove cancel and refund button from tracking 
plz need help

**Comment by mohamedibrahim89** [comment] 2020-05-13 10:52
@minhcasi need help in this plz

**Comment by minhcasi** [comment] 2020-05-13 10:54
Pls remove this line to remove the refund button

<img width="1038" alt="Screen Shot 2020-05-13 at 17 53 54" src="https://user-images.githubusercontent.com/1459805/81804041-b8db9580-9542-11ea-89c1-e9581b0508f3.png">
