### ISSUE TITLE
Home page loading

### ISSUE THREAD

**Issue by MrrHak** [inspireui/support#4249] opened 2020-07-18 11:08 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: when I add more layout vertical when I scroll it down and back to the top item at the top reload again but I don't want it reload again like this. please help me. thank
+ Product & version:`fluxstore-woocommerce-flutter-ecommerce-full-app7.5
+ Flutter (or React Native) version:   v1.17.5
+ Testing Device/Simulator: Android 7.0
+ Screenshot issues (drag the file to attach here): 

![photo_2020-07-18_18-07-02](https://user-images.githubusercontent.com/42771980/87851284-8757bf80-c921-11ea-8f7f-52e52cae8ee4.jpg)
![photo_2020-07-18_18-07-10](https://user-images.githubusercontent.com/42771980/87851285-8888ec80-c921-11ea-8f9a-338e4e185963.jpg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment] 2020-07-18 14:02
Thank you for the feedback.
Please don't share the purchase code or screenshot public here as another user will use it for activation.
Please help us to submit this form and fill all required info to continue with the support 
- http://verify.inspireui.com/ 
We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by minhcasi** [comment] 2020-07-20 03:26
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-20 03:26 UTC
Labels: needs-more-info
