### ISSUE TITLE
Failed to find Platform SDK...android-R

### ISSUE THREAD

**Issue by marvzach** [inspireui/support#4034] opened 2020-07-03 05:45 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 
![r](https://user-images.githubusercontent.com/37458467/86435811-91ff3b80-bd09-11ea-8cd8-95f175e2a2b0.JPG)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment] 2020-07-03 06:07
@marvzach 
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by marvzach** [comment] 2020-07-03 06:47
Already filled the form

**Comment by marvzach** [comment] 2020-07-03 12:28
hey whats the issue

**Comment by minhcasi** [comment] 2020-07-04 03:33
Thank you!

Could you help to check the solution on this ticket #3708

The root cause it by latest update form android studio and android R library

**Closed** 2020-07-06 03:52 UTC
Labels: FluxstoreMV
