### ISSUE TITLE
The admob intertitial and banner dont showing in my newsflux application 

### ISSUE THREAD

**Issue by 3Alouch1** [inspireui/support#3744] opened 2020-06-15 08:49 UTC
The admob intertitial and banner dont showing in my newsflux application
How can i fix this problem

**Comment by minhcasi** [comment] 2020-06-15 09:59
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-06-16 01:50
Duplicate of #3752

**Closed by minhcasi** 2020-06-16 01:50 UTC
Labels: needs-more-info
