### ISSUE TITLE
[FluxStore Pro] Had to open new issue for following up the issue  #3209

### ISSUE THREAD

**Issue by bikostudio** [inspireui/support#3256] opened 2020-05-18 04:36 UTC
Had to open new issue for following up the issue  #3209
ok no problem!

**###  I want to add an banner image to be at the end of the Category screen. An I want it to be clickable with external link url . And I want the Image is a network image not asset image please**

### **Question: How to make external open on chrome instead of opening in the app built-in browser?**

![2020-05-15_140426](https://user-images.githubusercontent.com/62074493/82048613-43440680-96b5-11ea-86d8-d786791f11a7.jpg)

In issue #3209 you said that I need to use this lib : https://pub.dev/packages/url_launcher 

But you did not tell me where to use it in app files and how.

Can i have an answer for this question

**Comment by philipvu30** [comment] 2020-05-18 06:37
Hi @bikostudio,

As this page is for supporting issues/bugs/feature requests related to our apps only, please kindly implement it yourself or asking assistance from someone that is able to help you.

Anyway, for the category screen above, you can implement it in lib/screens/categories/card.dart

Thank you.

**Comment by minhcasi** [comment] 2020-05-18 07:01
Duplicate of #3255

**Closed by minhcasi** 2020-05-18 07:01 UTC

**Comment by bikostudio** [comment] 2020-05-20 04:26
> 
> 
> Hi @bikostudio,
> 
> As this page is for supporting issues/bugs/feature requests related to our apps only, please kindly implement it yourself or asking assistance from someone that is able to help you.
> 
> Anyway, for the category screen above, you can implement it in lib/screens/categories/card.dart
> 
> Thank you.

Thank you @philipvu30  for your help. I tried to apply the code in this article : 
https://pub.dev/packages/url_launcher

in file : lib/screens/categories/card.dart

but did not work. 

please,can you tell me where in this file I should add this code in card.dart file?

thank you

**Comment by philipvu30** [comment] 2020-05-20 06:26
Hi,

Please insert your widget under the TreeView in the file like this

![image](https://user-images.githubusercontent.com/54442328/82412206-6ef03380-9a9d-11ea-9cb4-4feee0562a9a.png)

**Comment by bikostudio** [comment] 2020-05-20 11:33
> 
> 
> Hi @bikostudio,
> 
> As this page is for supporting issues/bugs/feature requests related to our apps only, please kindly implement it yourself or asking assistance from someone that is able to help you.
> 
> Anyway, for the category screen above, you can implement it in lib/screens/categories/card.dart
> 
> Thank you.

Thank you @philipvu30  for your help. I tried to apply the code in this article : 
https://pub.dev/packages/url_launcher

in file : lib/screens/categories/card.dart

but did not work. 

please,can you tell me where in this file I should add this code in card.dart file?

thank you

> 
> 
> Hi,
> 
> Please insert your widget under the TreeView in the file like this
> 
> ![image](https://user-images.githubusercontent.com/54442328/82412206-6ef03380-9a9d-11ea-9cb4-4feee0562a9a.png)

Thank you @philipvu30 for your fast respond. I will try it and feedback.

**Comment by bikostudio** [comment] 2020-05-20 12:21
Hi @philipvu30 It worked. Thank you for your time and help
