### ISSUE TITLE
mstore pro: CustomPage as About Us and Contact Us Supports Your Section News and news that you don't see this section.

### ISSUE THREAD

**Issue by jvarillas** [inspireui/support#1094] opened 2019-09-21 16:25 UTC
I have an error in the mstore application with the following scenario: I navigate to the menu Contact us or About us then I navigate to the News section I return to navigate to Contact us and again to News, it is this moment where the latter does not redirect me to the indicated section they remain stuck showing the customPage mentioned above, what can I do to resolve this error?
Additionally I have a query that is as follows:
1.- How can I configure the steps at the beginning of the app, to be able to change the background image and where those images are brought from? I attach catches

![Screenshot_20190921-111846](https://user-images.githubusercontent.com/55630741/65376119-e9905700-dc61-11e9-977f-6badd8627d9b.jpg)
![Screenshot_20190921-111321](https://user-images.githubusercontent.com/55630741/65376120-e9905700-dc61-11e9-9160-2d2ac20bd213.jpg)
![Screenshot_20190921-111853](https://user-images.githubusercontent.com/55630741/65376121-e9905700-dc61-11e9-97e0-1d932cecd634.jpg)
![Screenshot_20190921-111259](https://user-images.githubusercontent.com/55630741/65376122-e9905700-dc61-11e9-8f3f-62445025ea7c.jpg)
![Screenshot_20190921-111839](https://user-images.githubusercontent.com/55630741/65376123-ea28ed80-dc61-11e9-83af-d8777aec2fb4.jpg)

**Comment by minhcasi** [comment] 2019-09-24 00:31
Duplicate of #1102

**Closed** 2019-09-24 07:39 UTC
Labels: question ❓
