### ISSUE TITLE
the provided api key does not have write permissions fluxstore

### ISSUE THREAD

**Issue by DcStrong** [inspireui/support#4238] opened 2020-07-17 09:24 UTC
Hello, for some action like payment or refund. I get the error "the provided api key does not have write permissions".

I/flutter ( 4924): [2020-07-17 09:24:27.123780Z][Fluxstore][wocommerce_api][09:24:27.123744] postAsync START [endPoint:orders] url:https://vkusnii.com/wp-json/wc/v3/orders?consumer_key=ck_b82bcff4df6d54003d795455ecb2668d22fdf8b6&consumer_secret=cs_17e3bc0754c06300ad659781c5841ddef6c3c690
I/flutter ( 4924): [2020-07-17 09:24:27.883576Z][Fluxstore][wocommerce_api][09:24:27.883532] postAsync END [endPoint:orders]
I/flutter ( 4924): #0      WooCommerce.createOrder 
package:fstore/services/woo_commerce.dart:587
I/flutter ( 4924): <asynchronous suspension>
I/flutter ( 4924): #1      Services.createOrder 
package:fstore/services/index.dart:245
I/flutter ( 4924): #2      WooWidget.createOrder 
package:fstore/…/woocommerce/index.dart:129
I/flutter ( 4924): #3      WooWidget.placeOrder 
package:fstore/…/woocommerce/index.dart:158
I/flutter ( 4924): #4      _PaymentMethodsState.placeOrder 
package:fstore/…/checkout/payment.dart:321
I/flutter ( 4924): #5      _PaymentMethodsState.build.<anonymous closure> 
package:fstore/…/checkout/payment.dart:261
I/flutter ( 4924): #6      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:779
I/flutter ( 4924): #7      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:862
I/flutter ( 4924): #8      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
I/flutter ( 4924): #9      TapGestureRecognizer.handleTapUp 
package:flutter/…/gestures/tap.dart:504
I/flutter ( 4924): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/t

**Comment by ameenbadri7** [comment] 2020-07-17 19:37
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by minhcasi** [comment] 2020-07-19 03:47
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-19 03:47 UTC
Labels: needs-more-info
