### ISSUE TITLE
Get Dependency not working...

### ISSUE THREAD

**Issue by BinTofajjal** [inspireui/support#4989] opened 2020-09-12 21:07 UTC
C:\FluxStore-vendor-1.7.7\source>"C:\flutter\bin\cache\dart-sdk\bin\dart.exe" --packages="C:\flutter\packages\flutter_tools\.packages"  "C:\flutter\bin\cache\flutter_tools.snapshot" --no-color pub get   & exit /B !ERRORLEVEL! 
Running "flutter pub get" in source...                          

Because flutter_svg >=0.18.0 <0.18.1 depends on xml ^4.1.0 and every version of flutter_driver from sdk depends on xml 3.6.1, flutter_svg >=0.18.0 <0.18.1 is incompatible with flutter_driver from sdk.
So, because fluxstore_vendor depends on both flutter_driver any from sdk and flutter_svg 0.18.0, version solving failed.
pub upgrade failed (1; So, because fluxstore_vendor depends on both flutter_driver any from sdk and flutter_svg 0.18.0, version solving failed.)

**Comment by minhcasi** [comment] 2020-09-13 01:48
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-09-15 02:59
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-09-15 02:59 UTC
Labels: needs-more-info
