### ISSUE TITLE
[Flux News] - Oops; flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by amit81** [inspireui/support#1169] opened 2019-10-04 07:52 UTC
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

Oops; flutter has exited unexpectedly.
Crash report written to C:\Users\Amit Sanghvi\Documents\Flux new 210\codecanyon-Z6eTsb5q-fluxnews-fluxnews-flutter-mobile-app-for-wordpress\FluxNews.1.1.0\source\flutter_15.log;
please let us know at https://github.com/flutter/flutter/issues.

FAILURE: Build failed with an exception.

* Where:
**Script 'C:\Users\Amit Sanghvi\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 765**

* What went wrong:
![Screenshot (100)](https://user-images.githubusercontent.com/11808338/66190580-fc674a80-e6a9-11e9-8ddb-2175498b90c1.png)
![Screenshot (101)](https://user-images.githubusercontent.com/11808338/66190581-fc674a80-e6a9-11e9-87ea-5f227dc5af13.png)

Execution failed for task ':app:compileFlutterBuildDebugX86'.
> Process 'command 'C:\Users\Amit Sanghvi\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 25s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by minhcasi** [comment] 2019-10-04 09:28
@amit81 - could you try to remove the android/.gradle folder ?

**Comment by amit81** [comment] 2019-10-04 09:54
i try to remove it but still is same

**Comment by minhcasi** [comment] 2019-10-04 11:49
Duplicate of #1172

**Comment by minhcasi** [comment] 2019-10-04 11:50
it seems you have fixed from 1172, could you share your solution ?

**Closed by minhcasi** 2019-10-04 11:49 UTC
Labels: question ❓
