### ISSUE TITLE
[Fluxstore] - Shipping Address option not showing while checkout & Webview Not Working

### ISSUE THREAD

**Issue by themeix** [inspireui/support#2097] opened 2020-02-15 19:31 UTC
Please help me to fix the issues
---------

1. My issue:
Here following my issues after using Fluxstore for my project.
a) Shipping Address / Billing Address option not working in my app. When i click checkout its sending me direct Pagement Tab instead of Address and Shipping tab.
Example : https://raw.githubusercontent.com/themeix/temp/master/screenshot_585.png

b) Back to shop button is not working.  It just jumping the screen while tap on that button. I want Back to redirect user Back to Home or Order History page. 
Example : https://raw.githubusercontent.com/themeix/temp/master/screenshot_586.png

c) That is on of my most important issue. Cash on Delivery Payment method is working fine.  But the other 2 methods what is used there need an Input field where use submit their transaction ID. but unfortunately, **Webview shows the blank screen. It's not working.**
Example : https://raw.githubusercontent.com/themeix/temp/master/screenshot_587.png

d) There had a description for each of the payment methods where i explained the payment method. Unfortunately its not showing there.. How to show the payment method's description in my marking area.
Example : https://raw.githubusercontent.com/themeix/temp/master/screenshot_589.png

e) Order Note not working.. I cant see that in website admin panel when filling up that from APP order.

f) Facebook Login not working.. Please check my repo what i shared already, where is the fault.

2. Screenshots issues:
Link given

3. Proof of my purchased:
https://raw.githubusercontent.com/themeix/temp/master/screenshot-589.png

3. Config files (optional)
Not sure

**Comment by themeix** [comment] 2020-02-15 19:52
#1 a) is Resolved by me.. Please answer for **b) c) d)**

**Comment by inspireui-support** [comment] 2020-02-16 03:31
@themeix - could you zip the common folder here so that the team could help for checking - thank you!

**Comment by themeix** [comment] 2020-02-16 07:20
Here is the **source/lib/common** folder, https://we.tl/t-QR5s2cS4Gl

**Comment by trunghieuvn** [comment] 2020-02-17 05:33
Hi. Please provide the version of WooCommerce Fluxstore you are using.

**Comment by themeix** [comment] 2020-02-17 06:29
Wocoomerce : Version 3.9.2 |

**Comment by themeix** [comment] 2020-02-17 07:50
I bought it 3 days ago and uploaded the latest file there, its 1.6.3 i think.
Thanks,

**Comment by trunghieuvn** [comment] 2020-02-17 13:04
i try reproduce but i can't do it.
please help me provice steps reproduce or video reproduce bug. I will fix bug easier

**Comment by themeix** [comment] 2020-02-17 16:03
If you want i can share my full code in a private repo. Please give an Email. I will create a video too.

**Comment by themeix** [comment] 2020-02-17 16:30
For your kind information i am getting the following notice in console while run app.

```
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\device_apps-1.0.9\android\src\main\java\fr\g123k\deviceapps\DeviceAppsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.3+2\android\src\main\java\io\flutter\plugins\firebase\core\FirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_admob-0.9.0+10\android\src\main\java\io\flutter\plugins\firebaseadmob\AdRequestBuilderFactory.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.12.11\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.12.11\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_analytics-5.0.9\android\src\main\java\io\flutter\plugins\firebaseanalytics\FirebaseAnalyticsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_database-3.1.1\android\src\main\java\io\flutter\plugins\firebase\database\FirebaseDatabasePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-6.0.9\android\src\main\java\io\flutter\plugins\firebasemessaging\FirebaseMessagingPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.0\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.6+1\android\src\main\java\io\flutter\plugins\sharedpreferences\SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
                        ^
1 warning
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\share-0.6.3+5\android\src\main\java\io\flutter\plugins\share\SharePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.10.5+1\android\src\main\java\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
√ Built build\app\outputs\apk\debug\app-debug.apk.
```

**Comment by trunghieuvn** [comment] 2020-02-18 03:10
Please send me more information to this email: `hieu.trantrung1204@gmail.com` .  Thanks.

**Comment by themeix** [comment] 2020-02-18 09:34
Regarding the #2121 
I used app signing certificate key same as firebase what i used but its not working.

**Comment by themeix** [comment] 2020-02-18 10:02
I just sent you a email.
Subject :
[Fluxstore] Webview not working for checkout

Please reply there, I am stuck on that project for these bugs.

**Comment by themeix** [comment] 2020-02-18 12:26
@inspireui-support  I am getting the following notice in my Play.

> Your Production APK needs to meet the following criteria:
> Your APK should include custom drawables assets for common tablet screen densities

How to resolve that issue?

**Comment by themeix** [comment] 2020-02-18 13:48
```
Your Production APK needs to meet the following criteria:
Your APK should include custom drawables assets for common tablet screen
```
Getting that error in Google Play console. Can you fix that assets issue for the app?

**Comment by trunghieuvn** [comment] 2020-02-18 15:34
I try build source and checkout, 
I create account : abc@abc.com
<img width="675" alt="Screen Shot 2020-02-18 at 10 32 48 PM" src="https://user-images.githubusercontent.com/19247680/74750630-9832d500-529e-11ea-8773-1446bfbd6463.png">


I reproduct I saw some bug: 
- (1) login fb/google ( because not add hash key in web develop)
- (2) bug Select Address when checkout

**Comment by themeix** [comment] 2020-02-18 15:43
You used the payment method. Cash on delivery, which is working fine.. But the other payment methods are not working.. i mean web view not loading as it is not native ui.

1. Google login is working fine but only facebook not working.. 
Here is my settings there 
https://i.postimg.cc/7YQz4vDt/screenshot-606.png
https://i.postimg.cc/2j9yb4JV/screenshot-607.png
But not working.. 

2. Yes..  Billing address, shipping address not showing there to edit

**Comment by trunghieuvn** [comment] 2020-02-18 18:38
issue (1) login facebook you need setup develop.facebook.com 
get appID facebook and add hash key for android ...

**Comment by themeix** [comment] 2020-02-18 19:23
I did add the APP id and Hash key on there, I shared the screenshot as well with you..  Not sure where is the issue.
Can you check my other issues as well. I see you are working in github repo.. I hope issues will be fix soon.

**Comment by trunghieuvn** [comment] 2020-02-19 08:56
> b) Back to shop button is not working. It just jumping the screen while tap on that button. I want Back to redirect user Back to Home or Order History page.
> Example : https://raw.githubusercontent.com/themeix/temp/master/screenshot_586.png

Please make the following changes to correct this error:

1. Add  class `MainTabControlDelegate` before class `MainTabs` in file `lib/tabbar.dart`

```
...


class MainTabControlDelegate {
  Function(String nameTab) changeTab;
  Function(int index) tabAnimateTo;

  static MainTabControlDelegate _instance;
  static MainTabControlDelegate getInstance() {
    if (_instance == null) {
      _instance = MainTabControlDelegate._();
    }
    return _instance;
  }

  MainTabControlDelegate._();
}

class MainTabs extends StatefulWid ...

```

2. Remove `keyNavigationTabbar` and define function of `MainTabControlDelegate` in functiong `initState`

![image](https://user-images.githubusercontent.com/19247680/74807874-1c776d80-531c-11ea-876c-9846b3b72ddc.png)

3. Edit code in page use old key

![image](https://user-images.githubusercontent.com/19247680/74807950-4cbf0c00-531c-11ea-89cd-ac5d07348799.png)

![image](https://user-images.githubusercontent.com/19247680/74807962-56487400-531c-11ea-82dc-3e3fc48a6f15.png)

4. change `pushName` to `pushReplacementNamed` in file `lib/screens/checkout/success.dart`

![image](https://user-images.githubusercontent.com/19247680/74817773-13909700-5330-11ea-8f2e-de65aefcb144.png)


> c) That is on of my most important issue. Cash on Delivery Payment method is working fine. But the other 2 methods what is used there need an Input field where use submit their transaction ID. but unfortunately, Webview shows the blank screen. It's not working.
> Example : https://raw.githubusercontent.com/themeix/temp/master/screenshot_587.png

I have checked this problem. This is not a project error. I see this is an error on your web interface. When I checked the payment results on my laptop's web browser, with the mobile view, the same result happened.
When I checked it out on the app, I pulled it from left to right, it showed the menu of your website. Please check again!

![image](https://user-images.githubusercontent.com/19247680/74817009-cc55d680-532e-11ea-9ea4-d6871931e0df.png)

![image](https://user-images.githubusercontent.com/19247680/74817017-d081f400-532e-11ea-8e58-ab5fd2b0724e.png)

**Comment by themeix** [comment] 2020-02-19 14:52
**Issue c)** 
Thanks for testing it. I already deactivated [Woomobify](https://codecanyon.net/item/mcommerce-woocommerce-mobile-theme/19250607) plugin and now its showing the checkout steps. But unfortunately there Not passing the country field data and Order note from the APP.
And it does not allow me to complete the order. 

Please give me an update about it. And may i update my master brunch where has the bazarfix-app ? I saw you were working on other branch

**Comment by trunghieuvn** [comment] 2020-02-19 17:58
I fixed the error and created a pull request at branch `fixbug/back-to-shop-button`. Please check the pull request.

**Comment by themeix** [comment] 2020-02-19 20:08
@trunghieuvn 
I appreciate your hard work.
. i merged your pull request and trying to run the app. **But unfortunately its not installing or opening to the emulator.** 
https://i.postimg.cc/pdJKfjx4/screenshot-612.png
Repo : https://github.com/themeix/bazarfix-app

**Comment by themeix** [comment] 2020-02-22 17:58
Any update please?

**Comment by inspireui-support** [comment] 2020-02-24 12:30
@trunghieuvn - pls help with a suggestion

**Comment by inspireui-tech** [comment] 2020-02-26 03:15
@themeix - pls help to update latest version 1.6.4 to fix this issue - more detail changelog - https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f

**Comment by themeix** [comment] 2020-02-26 08:43
Yes.. I updated it still there have some issues.

1. Webveiw issue ( fixed )
2. Facebook Login ( fixed )  I checked on emulator

Now there have just 1 issue 
ORDER NOTE not working.

**Comment by themeix** [comment] 2020-02-26 20:38
**### NEW ISSUE :**
**Profile Update not working for me**
Here is the screenshot.
https://i.postimg.cc/SsZDRZdH/screenshot-624.png

**Comment by themeix** [comment] 2020-02-27 18:18
### Another NEW ISSUE :
Category Page showing only 11 products for me instead of 35 product..

**Comment by kvt0012** [comment] 2020-02-28 02:29
Dear sir, 
Please send me your config file, thank you

**Comment by kvt0012** [comment] 2020-02-28 10:28
Because you open #2230 , so I will close this issue. 
Thank you

**Closed by kvt0012** 2020-02-28 10:28 UTC
Labels: FluxStore, question ❓
