### ISSUE TITLE
Firebase, Login Problem

### ISSUE THREAD

**Issue by MorisTech** [inspireui/support#3854] opened 2020-06-22 14:37 UTC
Hello, you keep closing my issues, why????

I'm done with one, you close it

https://github.com/inspireui/support/issues/3769

The login and signup doesn't work
After connecting firebase, when I click login with Phone number, it just rolls, nothing..
It was working before, but it doesn't now

Also same as the Google Sign in

Secondly, The Signup doesn't work, after inputting my name and all

It still says "Please agree to our terms" after selecting the box

WHAT'S THE PROBLEM?

**Comment by ameenbadri7** [comment] 2020-06-22 16:14
sir hello. I hope you can fix all your problems asap.
I have read all your issues inside fluxstore I see these wrong ideas maybe its from you: 

he closes the first issue because you said:
[first issue](https://github.com/inspireui/support/issues/3494
)> After building the app in android studio, I run it in the emulator but it's slow
> So I try to install it on my android phone and it doesn't work, it says "App not installed"> 

and the fluxstore team gives you good feedback until test the ios on windows computer?

sir, you have to get a macOS to emulate ios. 

the second issue is this :

> Also, I don't have a Mac, how do I edit Mac version and Test it
and he answers Hi, there is no solution to build ios without mac os.
then the issue is closed.

then you repeat at the last time 
at this issue [the third issue ](https://github.com/inspireui/support/issues/3494)
and he answers and you said that ok its work 
and the issue is closed. 

but after the issue is closed you said again :
> Does that mean what I'm editing in Android Studio also works for IOS?
> If so, how do I test the ios
> 

you said now: you keep closing my issues, why????

and he closed the issues because its already finished and he gives you the answers. 

so today you have an issue its about firebase sign-in an option not working with you.
 the fix-it to see this video and apply it as you see inside the video and I guaranty that it will fix the problem because I learn it that way.

I am not related to the fluxstore team. I am just a customer just like you.

so please try this video https://www.youtube.com/watch?v=14ALBSwvV4E
and also this documentation https://docs.inspireui.com/fluxstore/sign-in/#2-google-sign-in

and please don't ask about trying ios in windows because you cant.
 and I will guide you till you fix the firebase issue from a customer to another.

**Comment by MorisTech** [comment] 2020-06-22 18:42
Thanks man, I appreciate, I bought a MAC for this project already.. 
Let me try the videos

**Comment by MorisTech** [comment] 2020-06-22 20:53
Even to login on the App itself
I"m trying to login as a vendor, it just keeps rolling and all

**Comment by MorisTech** [comment] 2020-06-22 23:15
All the edits I did in the Fluxbuilder didn't reflect, I checked the JSON file, it shows they've been changed
But ddin't reflect after I built the apk

**Comment by MorisTech** [comment] 2020-06-23 15:14
No one is replying now

**Comment by minhcasi** [comment] 2020-06-24 02:49
Duplicate of #3876

**Closed by minhcasi** 2020-06-24 02:49 UTC
Labels: FluxstoreMV
