### ISSUE TITLE
Android App  crashing on launch

### ISSUE THREAD

**Issue by hostmero** [inspireui/support#3447] opened 2020-05-28 05:21 UTC
All configuration is  default, not showing any error but app going crash on emulator 
![Screen Shot 2020-05-28 at 11 01 34 AM](https://user-images.githubusercontent.com/66052669/83101966-3bcc2680-a0d3-11ea-906b-8f5996e3aad5.png)

**Comment by hostmero** [comment] 2020-05-28 05:26
Bhushans-MacBook-Pro:news BHUSHAN$ react-native run-android 
**error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:** 
  - lottie-react-native (to unlink run: "react-native unlink lottie-react-native")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1063 file(s) to forward-jetify. Using 4 workers...
info Starting JS server...
info Installing the app...
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Task :react-native-blur:compileDebugJavaWithJavac

> Task :lottie-react-native:compileDebugJavaWithJavac

> Task :react-native-fast-image:compileDebugJavaWithJavac

> Task :react-native-fbsdk:compileDebugJavaWithJavac

> Task :react-native-gesture-handler:compileDebugJavaWithJavac

> Task :react-native-onesignal:compileDebugJavaWithJavac

> Task :react-native-webview:compileDebugJavaWithJavac

> Task :app:installDebug
Installing APK 'app-debug.apk' on 'Google Galaxy Nexus - 4.2.2 - API 17 - 720x1280 - 4.2.2' for app:debug
Installed on 1 device.

BUILD SUCCESSFUL in 3m 13s
227 actionable tasks: 227 executed
/bin/sh: adb: command not found
info Connecting to the development server...
warn Failed to connect to development server using "adb reverse": spawnSync adb ENOENT
info Starting the app...
Bhushans-MacBook-Pro:news BHUSHAN$

**Comment by minhcasi** [comment] 2020-05-28 07:06
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by hostmero** [comment] 2020-05-28 07:49
Form Url not working 

![Screen Shot 2020-05-28 at 1 34 38 PM](https://user-images.githubusercontent.com/66052669/83113871-efd7ac80-a0e7-11ea-99e2-7b95da84c9af.png)

**Comment by minhcasi** [comment] 2020-05-28 13:24
@hostmero - pls use this link https://docs.google.com/forms/d/e/1FAIpQLScWOjkAJIWJ9rgb9alopfOqLsJrGKbFM5cCYj1JBfLKLsBblQ/viewform

**Comment by minhcasi** [comment] 2020-05-30 04:34
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-05-30 04:34 UTC
Labels: needs-more-info
