### ISSUE TITLE
[FLUXSTORE] - I Want To Disable Shipping / Create New Menu Item

### ISSUE THREAD

**Issue by patrickubong** [inspireui/support#1423] opened 2019-11-19 08:53 UTC
My issues are:

1. Please guide me on how to disable shipping address, my products are virtual. But even when I try to enter some shipping address so I can proceed, it says "There's an issue with the app during request the data" Please I need to disable shipping

2. I want to add a menu that links to my-account dashboard, please provide guide on how to creat webview link to my dashboard:

3. When I do hot reload, it doesnt work for me and when it does, it continues to build with the same features even after I had made several changes. I always have to stop the App build and restart my PC before new changes is reflected in the build

4. I have shortcodes for visual composer and calculated fields form plugins on my page which do not show up, rather they only show the raw codes. Please how do I hide these codes on the App without necessarily deleting disabling the plugins from from my website

This is a great App, please keep it up.

> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: 
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

2. Screenshots issues:

3. Proof of my purchased:

3. Config files (optional)

**Comment by minhcasi** [comment] 2019-11-19 10:50
Duplicate of #1422

**Closed by minhcasi** 2019-11-19 10:50 UTC
Labels: question ❓
