### ISSUE TITLE
Task :app:bundleReleaseJsAndAssets FAILED

### ISSUE THREAD

**Issue by jitu94517** [inspireui/support#3621] opened 2020-06-06 09:46 UTC
I got this error when generating apk through command :- gradlew bundleRelease
![error_gen_apk](https://user-images.githubusercontent.com/66323700/83941376-70915980-a808-11ea-9c6d-ebe2363b5fa8.png)

**Comment by minhcasi** [comment] 2020-06-06 14:43
Duplicate of #3557

**Closed by minhcasi** 2020-06-06 14:43 UTC
