### ISSUE TITLE
We put in licence key for local URL, now as we are trying to update it to LIVE URL its giving error and we are unable to do it.

### ISSUE THREAD

**Issue by sachinsuper** [inspireui/support#4004] opened 2020-07-01 11:21 UTC
We put in licence key for local URL, now as we are trying to update it to LIVE URL its giving error and we are unable to do it.

**Comment by ameenbadri7** [comment] 2020-07-01 11:36
@sachinsuper 
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by ameenbadri7** [comment] 2020-07-01 11:42
@sachinsuper 

Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-07-02 01:09
@sachinsuper - could you share the screenshot issue so that we could help with checking - thank you!

**Comment by ameenbadri7** [comment] 2020-07-03 06:10
I'm sorry to close this ticket as there is no response or active conversation, 
please help to create a new one and link to this ticket if the problem is not solved
 - thank you for your time!

**Closed by ameenbadri7** 2020-07-03 06:10 UTC
Labels: FluxstoreMV
