### ISSUE TITLE
[listapp] How do you connect the wordpress plugins to expo and cebuilder?

### ISSUE THREAD

**Issue by befreeman5** [inspireui/support#1566] opened 2019-12-09 19:56 UTC
are there any settings you have to change in wordpress plugins or cebuilder to connect them? I don't understand how it connects the data. there is no clear path.

the simulator pulls up your demo app data not mine.

**Comment by befreeman5** [comment] 2019-12-10 04:36
Proof of purchase ![0715DF14-720E-465C-A033-FF18C8F67A54](https://user-images.githubusercontent.com/58203308/70496005-76a9b600-1ac3-11ea-8f09-ff1627d7d7ca.png)

**Comment by minhcasi** [comment] 2019-12-10 10:46
@befreeman5 - once open the CeBuilder you can open the project folder, then there will have the tab to change to your own website URL, could you take the screenshot of the Cebuilder so that we could know where your process - thanks

**Comment by minhcasi** [comment] 2019-12-10 10:47
Duplicate of #1565

**Closed by minhcasi** 2019-12-10 10:47 UTC
Labels: ListingApp, question ❓

**Comment by befreeman5** [comment] 2019-12-17 23:27
Still waiting..

**Comment by befreeman5** [comment] 2019-12-17 23:27
Someone assigned but they left to go home and still waiting
