### ISSUE TITLE
Android support for FluxStore Shopify Flutter template

### ISSUE THREAD

**Issue by BinitaShah** [inspireui/support#4826] opened 2020-09-01 13:54 UTC
Hello, 

We have purchased Fluxstore Shopify Theme but we found you have set up for IOS but not for android. We are facing with Android setup. Can you please guide on this?

THanks

**Comment by minhcasi** [comment] 2020-09-02 05:38
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-09-03 03:07
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-09-03 03:07 UTC
Labels: needs-more-info

**Comment by BinitaShah** [comment] 2020-09-11 07:11
Hello,

I have fill up the form which you shared, But still I havent receive any update on it. I have purchased the theme. ANd I need to run that set up in Android which is giving errors & crashes. Please provide running set up in android.
