### ISSUE TITLE
Plugin support

### ISSUE THREAD

**Issue by OrlandoNavarro** [inspireui/support#4570] opened 2020-08-12 01:05 UTC
A little while ago I asked a question about shipping and you said that only from WooCommece's Product Support I went to the WooCommece Docs to see if I found a plugin that controls automatic shipping but I found these docs and updates:

https://docs.woocommerce.com/document/correios-brasil/

This is now the person who was responsible for this and yes is from WooCommerce as in the docs.
https://wordpress.org/plugins/woocommerce-correios/

So I come to request assistance for this product to be shared with the App FluxStore if you would not like to request a refund for lack of this functionality.

**Comment by minhcasi** [comment] 2020-08-12 02:48
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

Also, clarify your detail issues so that the team could check your issue - thanks

**Comment by minhcasi** [comment] 2020-08-12 02:49
Btw, the plugin `https://wordpress.org/plugins/woocommerce-correios/` is an extra plugin install that is not supported from the default WooCommerce API so that you could try to use the OnePageCheckout option from the config file to process the payment via Webview, it is possible to process refund if you could not use it for your site - thank you for your time!

**Comment by minhcasi** [comment] 2020-08-13 02:14
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-08-13 02:14 UTC
Labels: needs-more-info
