### ISSUE TITLE
[Fluxstore] - errors when i make build -  import GoogleMaps

### ISSUE THREAD

**Issue by limitlessfirm** [inspireui/support#2784] opened 2020-04-19 04:31 UTC
Step 1 (require): detail issues and screenshots

when i make run in android studio i show the following

Xcode build done. 25.8s
Failed to build iOS app
Error output from Xcode build:
↳
** BUILD FAILED **

Xcode's output:
↳
/Users/fewbig/Desktop/ds-1.6.6.04/ios/Runner/AppDelegate.swift:3:8: error: no such module 'GoogleMaps'
import GoogleMaps
^
note: Using new build system
note: Planning build
note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

![screenshot](https://user-images.githubusercontent.com/59250639/79679591-5de6a500-8207-11ea-9029-43bf7c8fd2bb.JPG)

*Note: please help to fill the required information from the above 2 steps, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment] 2020-04-19 07:26
Duplicate of #2783

**Closed by minhcasi** 2020-04-19 07:26 UTC
