### ISSUE TITLE
Customer Note is gone After Directing to Website ( Webview )

### ISSUE THREAD

**Issue by limpingen** [inspireui/support#4206] opened 2020-07-15 03:53 UTC
Hi… i am satisfied with this product https://codecanyon.net/item/beostore-complete-react-native-template-for-ecommerce

but there is one bug that i need help

I have fill the customer note in the Delivery Page then In payment Page is directing to the website but the customer note is gone… Everything else such as firstname, lastname, address, etc still there but customer note is gone…

Can you help me to fix it ?

![note](https://user-images.githubusercontent.com/21377040/87501460-56f5f400-c689-11ea-9eee-26797f6811bc.jpg)

labels : MStorePro

**Comment by minhcasi** [comment] 2020-07-15 09:27
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-07-17 07:12
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-17 07:12 UTC
Labels: needs-more-info
