### ISSUE TITLE
Error in running app with Android Studio (Fluxstore Multi Vendor - Flutter E-commerce Full)

### ISSUE THREAD

**Issue by maximuskay2** [inspireui/support#2575] opened 2020-04-05 14:09 UTC
/usr/local/opt/dart/libexec/bin/dart --enable-asserts --pause_isolates_on_start --enable-vm-service:50216 /Users/kayodeakingbade/Dev/super/FluxStore-vendor-1.6.6/sup/lib/main.dart
Observatory listening on http://127.0.0.1:50216/0v7eV-CXT5A=/

lib/main.dart: Warning: Interpreting this as package URI, 'package:fstore/main.dart'.
Crash when compiling file:///Users/kayodeakingbade/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-0.2.1/lib/src/_network_image_io.dart,
at character offset 3225:
InvalidType doesn't have nullability
#0      InvalidType.nullability (package:kernel/ast.dart:5543:34)
#1      computeNullability (package:kernel/src/future_or.dart:66:15)
#2      TypeConstraintGatherer._isSubtypeMatch (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:338:11)
#3      TypeConstraintGatherer.trySubtypeMatch (package:front_end/src/fasta/type_inference/type_constraint_gatherer.dart:100:20)
#4      TypeSchemaEnvironment.inferGenericFunctionOrType (package:front_end/src/fasta/type_inference/type_schema_environment.dart:191:16)
#5      TypeInferrerImpl._inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:1691:29)
#6      TypeInferrerImpl.inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:1562:12)
#7      InferenceVisitor.visitFactoryConstructorInvocationJudgment (package:front_end/src/fasta/kernel/inference_visitor.dart:737:38)
#8      FactoryConstructorInvocationJudgment.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:443:20)
#9      TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:1473:27)
#10     InferenceVisitor.visitReturnStatement (package:front_end/src/fasta/kernel/inference_visitor.dart:4619:61)
#11     ReturnStatement.accept (package:kernel/ast.dart:4958:43)
#12     TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:2646:22)
#13     InferenceVisitor._visitStatements (package:front_end/src/fasta/kernel/inference_visitor.dart:306:20)
#14     InferenceVisitor.visitBlock (package:front_end/src/fasta/kernel/inference_visitor.dart:327:30)
#15     Block.accept (package:kernel/ast.dart:4519:43)
#16     TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:2646:22)
#17     InferenceVisitor.visitIfStatement (package:front_end/src/fasta/kernel/inference_visitor.dart:1204:52)
#18     IfStatement.accept (package:kernel/ast.dart:4925:43)
#19     TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:2646:22)
#20     InferenceVisitor._visitStatements (package:front_end/src/fasta/kernel/inference_visitor.dart:306:20)
#21     InferenceVisitor.visitBlock (package:front_end/src/fasta/kernel/inference_visitor.dart:327:30)
#22     Block.accept (package:kernel/ast.dart:4519:43)
#23     TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:2646:22)
#24     TypeInferrerImpl.inferFunctionBody (package:front_end/src/fasta/type_inference/type_inferrer.dart:1525:39)
#25     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:910:28)
#26     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:904:14)
#27     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:937:7)
#28     DietListener.endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:664:5)
#29     Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3480:20)
#30     Parser.parseClassOrMixinOrExtensionMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3241:15)
#31     Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2974:15)
#32     Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1820:13)
#33     Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1779:14)
#34     Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:574:14)
#35     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:470:14)
#36     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:352:15)
#37     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:312:14)
<asynchronous suspension>
#38     Loader.buildBodies (package:front_end/src/fasta/loader.dart:243:15)
<asynchronous suspension>
#39     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:307:20)
#40     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#41     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:305:12)
#42     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:483:28)
<asynchronous suspension>
#43     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#44     new Future.sync (dart:async/future.dart:224:31)
#45     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#46     _rootRun (dart:async/zone.dart:1126:13)
#47     _CustomZone.run (dart:async/zone.dart:1023:19)
#48     _runZoned (dart:async/zone.dart:1518:10)
#49     runZoned (dart:async/zone.dart:1465:12)
#50     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#51     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:156:20)
#52     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:58:46)
#53     IncrementalCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:302:39)
#54     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:163:45)
#55     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#56     _rootRun (dart:async/zone.dart:1122:38)
#57     _CustomZone.run (dart:async/zone.dart:1023:19)
#58     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#59     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#60     _rootRun (dart:async/zone.dart:1126:13)
#61     _CustomZone.run (dart:async/zone.dart:1023:19)
#62     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#63     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#64     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#65     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#66     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

#0      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:942:7)
#1      DietListener.endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:664:5)
#2      Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3480:20)
#3      Parser.parseClassOrMixinOrExtensionMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3241:15)
#4      Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2974:15)
#5      Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1820:13)
#6      Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1779:14)
#7      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:574:14)
#8      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:470:14)
#9      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:352:15)
#10     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:312:14)
<asynchronous suspension>
#11     Loader.buildBodies (package:front_end/src/fasta/loader.dart:243:15)
<asynchronous suspension>
#12     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:307:20)
#13     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#14     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:305:12)
#15     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:483:28)
<asynchronous suspension>
#16     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#17     new Future.sync (dart:async/future.dart:224:31)
#18     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#19     _rootRun (dart:async/zone.dart:1126:13)
#20     _CustomZone.run (dart:async/zone.dart:1023:19)
#21     _runZoned (dart:async/zone.dart:1518:10)
#22     runZoned (dart:async/zone.dart:1465:12)
#23     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#24     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:156:20)
#25     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:58:46)
#26     IncrementalCompilerWrapper.compileInternal (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:302:39)
#27     Compiler.compile.<anonymous closure> (file:///b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:163:45)
#28     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#29     _rootRun (dart:async/zone.dart:1122:38)
#30     _CustomZone.run (dart:async/zone.dart:1023:19)
#31     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#33     _rootRun (dart:async/zone.dart:1126:13)
#34     _CustomZone.run (dart:async/zone.dart:1023:19)
#35     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#36     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#37     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#38     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

**Comment by minhcasi** [comment] 2020-04-06 01:00
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by maximuskay2** [comment] 2020-04-06 06:45
**Proof of Purchase**


<img width="1405" alt="Screen Shot 2020-04-06 at 2 42 44 AM" src="https://user-images.githubusercontent.com/4710692/78529803-6fb05d00-77b0-11ea-8e2a-c28ab2d474f9.png">
<img width="1437" alt="Screen Shot 2020-04-06 at 2 43 59 AM" src="https://user-images.githubusercontent.com/4710692/78529832-7d65e280-77b0-11ea-8de2-48a4a210adc5.png">

Proof of Purchase

**Comment by maximuskay2** [comment] 2020-04-06 22:06
I have not gotten a response please


i need so many things to be achieved .. Tnx

**Comment by minhcasi** [comment] 2020-04-07 03:02
@maximuskay2 - please hep to download the latest version and check the clean cache solution on this link https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

Let us know your checking, thank you!

**Comment by minhcasi** [comment] 2020-04-08 04:21
How is your checking? Thanks

**Comment by maximuskay2** [comment] 2020-04-08 08:49
still same error .. but I manage to run with visual code editor for
android..

please I tried firebase auth no way out .. please help..

**Comment by maximuskay2** [comment] 2020-04-09 22:13
Error Generated when trying to Create New Account
![Error from Registration](https://user-images.githubusercontent.com/4710692/78945248-d756f880-7a8d-11ea-8619-fbf493911eb9.png)

**Comment by maximuskay2** [comment] 2020-04-09 22:14
Error Generated when trying to signup with Gmail
![error from google signup](https://user-images.githubusercontent.com/4710692/78945291-f5bcf400-7a8d-11ea-898e-a169adf90566.png)

**Comment by maximuskay2** [comment] 2020-04-09 22:15
Error generated when trying to sign in with user account in Wordpress Site
![Error from user ID login](https://user-images.githubusercontent.com/4710692/78945351-15541c80-7a8e-11ea-8701-f28c804a67f7.png)

**Comment by minhcasi** [comment] 2020-04-10 02:10
Duplicate of #2633

**Closed by minhcasi** 2020-04-10 02:10 UTC
Labels: Fluxstore-MV
