### ISSUE TITLE
Apple sign in error NoSuchMethodError

### ISSUE THREAD

**Issue by eraldix** [inspireui/support#4414] opened 2020-07-29 20:35 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I'm trying to add Apple sign in to my App but I get NoSuchMethodError as seen on the screen shot, I have enabled everything on Firebase. The real problem is that in Simulator everything works perfectly fine and I can log in and log out from my account correctly but in real device it doesn't. Please help asap.
+ Product & version:1.7.5
+ Flutter (or React Native) version: Flutter 
+ Testing Device/Simulator: Iphone X (Apple tester device)
+ Screenshot issues (drag the file to attach here): 
<img width="1680" alt="Screenshot 2020-07-29 at 8 32 10 PM" src="https://user-images.githubusercontent.com/44481659/88850273-6c236480-d1eb-11ea-8a34-5aacd7bba0b6.png">
![attachment Screenshot-0728-205127](https://user-images.githubusercontent.com/44481659/88850499-c6242a00-d1eb-11ea-8083-91bfa72a618a.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment] 2020-07-30 00:51
Hi,
It seems there is a lot of bugs in version 1.7.5 but most of them we've already solved at the latest version. Please consider using GitLab to pull the release 1.7.6 version or wait for the update on Codecanyon. 

Thank you.

**Comment by eraldix** [comment] 2020-07-30 08:30
How can i update and keep my changes on the project

**Comment by ameenbadri7** [comment] 2020-08-01 02:24
Do a backup and use this guide to help with the upgrades. 
https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6

THANK YOU!

**Comment by ameenbadri7** [comment] 2020-08-01 02:25
I'm sorry to close this ticket. 

Please help to create a new one and link to this ticket if the problem is not solved. 

- Thank you for your time!

**Closed by ameenbadri7** 2020-08-01 02:25 UTC
Labels: FluxstoreMV
