### ISSUE TITLE
Sign up Error on Fluxstore Woocommerce

### ISSUE THREAD

**Issue by thokoe** [inspireui/support#3788] opened 2020-06-18 12:53 UTC
Hi

I am having issue with sign up page on Fluxstore woocommerce.
it says "No route was found matching the url and request method"

And also Privacy and Term gives error:

"Opps, this page seems no longer exist! ,Go back to home page"

![Uploading Screenshot_20200618_142345_com.inspireui.fluxstore (1).jpg…]()

See screen shot.

**Comment by minhcasi** [comment] 2020-06-18 13:13
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-06-20 04:03
@thokoe - this could be build grade config issue, we could not reproduce on our side, please try some solution on this link https://stackoverflow.com/questions/45772745/build-failed-could-not-find-method-signingconfigs

Also, help to check this detailed guide from google - https://flutter.dev/docs/deployment/android

**Closed** 2020-06-20 04:04 UTC
Labels: needs-more-info
