### ISSUE TITLE
Could not find any matches for com.onesignal:OneSignal:[3.11.2,3.99.99] as no versions of com.onesignal:OneSignal are available.

### ISSUE THREAD

**Issue by vivekaris** [inspireui/support#2400] opened 2020-03-20 09:28 UTC
Could not find any matches for com.onesignal:OneSignal:[3.11.2,3.99.99] as no versions of com.onesignal:OneSignal are available.

**Comment by minhcasi** [comment] 2020-03-20 10:25
Duplicate of #2395

**Closed by minhcasi** 2020-03-20 10:25 UTC
