### ISSUE TITLE
Bank Tranfer Checkout no works

### ISSUE THREAD

**Issue by politos89** [inspireui/support#4340] opened 2020-07-24 02:44 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: the payment method, cash on delivery, works well and generates the order, the bank transfer method, redirects to the site page, does not generate the order.
+ Product & version:FluxStore-woo-1.7.6
+ Flutter (or React Native) version: Flutter version 1.17.5 / Dart version 2.8.4
+ Testing Device/Simulator: Android Studio/ AVD/ Android 7.9
+ Screenshot issues (drag the file to attach here): 
![Screenshot_20200723-212948](https://user-images.githubusercontent.com/46614736/88356268-ddb36c80-cd2c-11ea-9d20-5714c4a0e642.png)
![Screenshot_20200723-213101](https://user-images.githubusercontent.com/46614736/88356274-df7d3000-cd2c-11ea-94b8-49201a2047dd.png)

![im1](https://user-images.githubusercontent.com/46614736/88356293-ef950f80-cd2c-11ea-8483-859e4448958c.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊
![im1](https://user-images.githubusercontent.com/46614736/88356317-020f4900-cd2d-11ea-975e-ced185c0462f.png)
![Screenshot_20200723-212948](https://user-images.githubusercontent.com/46614736/88356318-02a7df80-cd2d-11ea-833f-8dab92490d28.png)
![Screenshot_20200723-213101](https://user-images.githubusercontent.com/46614736/88356320-03407600-cd2d-11ea-93c4-61d4ca4a42ce.png)

**Comment by ameenbadri7** [comment] 2020-07-24 02:59
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.
We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 
Thank you for your time!

**Comment by minhtruong315** [comment] 2020-07-26 10:40
Hi @politos89 can u send me common folder?
Thanks

**Comment by minhtruong315** [comment] 2020-07-26 15:00
Hi @politos89 can u check this solution to fix OnePageCheckout
https://github.com/inspireui/support/issues/4330#issuecomment-663998832

**Comment by minhcasi** [comment] 2020-07-29 08:24
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed** 2020-07-31 06:48 UTC
Labels: FluxStore, Mstore-API
