### ISSUE TITLE
Fluxstore WooCommerce version solving failed.

### ISSUE THREAD

**Issue by alex-9802** [inspireui/support#4850] opened 2020-09-02 23:43 UTC
I just bought Fluxstore WooCommerce today and when trying to run the app in Android Studio I got this error.

/home/alejandro/snap/flutter/common/flutter/bin/flutter --no-color pub get
Running "flutter pub get" in source...                          

Because every version of flutter_test from sdk depends on vector_math 2.1.0-nullsafety.2 and fstore depends on vector_math 2.0.8, flutter_test from sdk is forbidden.
So, because fstore depends on flutter_test any from sdk, version solving failed.
pub get failed (1; So, because fstore depends on flutter_test any from sdk, version solving failed.)
Process finished with exit code 1

Please help with this.
Thanks

**Comment by minhcasi** [comment] 2020-09-03 03:02
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-09-04 02:25
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-09-04 02:25 UTC
Labels: needs-more-info
