### ISSUE TITLE
The iss do not match with this server

### ISSUE THREAD

**Issue by sondercloud** [inspireui/support#3990] opened 2020-06-30 19:46 UTC
When uploading a product from the app I get the following issue: "The iss do not match with this server"

I am using the latest React Native MStore version (I attached my package.json).
<img width="683" alt="Screen Shot 2020-06-30 at 2 38 47 PM" src="https://user-images.githubusercontent.com/64498165/86169820-d6a78e80-badf-11ea-933c-75c85f007483.png">
<img width="455" alt="Screen Shot 2020-06-30 at 2 39 08 PM" src="https://user-images.githubusercontent.com/64498165/86169824-d9a27f00-badf-11ea-8496-623596fa560f.png">

I have followed the documentation to install all the plugins, including adding Woocommerce url and keys to Config and editing my .htacess and wp-config file
<img width="1041" alt="wp-config" src="https://user-images.githubusercontent.com/64498165/86169970-0f476800-bae0-11ea-8be2-15b0c418a023.png">
<img width="524" alt="htacess" src="https://user-images.githubusercontent.com/64498165/86169980-13738580-bae0-11ea-92f6-48cb468eb8b5.png">

My site is https://upshouts.com/

The only additional thing I have done is add SSL to my site.

**Comment by ameenbadri7** [comment] 2020-06-30 20:16
please don't share your license key here because others will use it to activate their products

Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by sondercloud** [comment] 2020-06-30 21:03
> please don't share your license key here because others will use it to activate their products
> 
> Thank you for the feedback.
> 
> Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.
> 
> We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!
> 
> > **[Google Forms - create and analyze surveys, for free.](http://verify.inspireui.com/)**Create a new survey on your own or with others at the same time. Choose from a variety of survey types and analyze results in Google Forms. Free from Google.

OK I filled it out

**Comment by luyx2412** [comment] 2020-07-02 14:13
Hi @sondercloud Can you share me your specific issue?

Thanks

**Comment by sondercloud** [comment] 2020-07-02 21:24
When upload a product from the app I get the following error:

"The iss do not match with this server"
=
What does this mean? How should I fix it?


Thanks,
Cormac

**Comment by luyx2412** [comment] 2020-07-03 13:53
Hi @sondercloud Sorry i don't understant what you meant, so can you describe specific your issue?

Thanks

**Comment by sondercloud** [comment] 2020-07-03 14:46
That’s the issue.

It’s not letting me upload a product from the app.

When I press submit the app says “the iss do not match the server”

Do you know what this means?

**Comment by sondercloud** [comment] 2020-07-03 18:21
Please see the screenshot

**Comment by luyx2412** [comment] 2020-07-05 04:11
Hi @sondercloud Sorry i dont see your screenshot, please send me again.
![image](https://user-images.githubusercontent.com/8909619/86525353-44710300-beb0-11ea-9396-29c85435e207.png)

Thanks

**Comment by sondercloud** [comment] 2020-07-07 15:21
Any luck solving this issue?

**Comment by luyx2412** [comment] 2020-07-08 14:38
Hi @sondercloud Please follow the original step to config your website https://docs.inspireui.com/mstore-mv, and please share me the screenshot issue. It will easy to investigate.

Thanks

**Comment by sondercloud** [comment] 2020-07-08 17:21
Hi I followed the steps and still get the same issue.

Please check the screenshot I have below.

**Comment by luyx2412** [comment] 2020-07-09 15:50
Hi @sondercloud Sorry but i did not see your screenshot. Can you share me again?
![image](https://user-images.githubusercontent.com/8909619/87061783-6662e080-c236-11ea-8f9a-872118f09d99.png)

Thanks

**Comment by sondercloud** [comment] 2020-07-09 16:19
Hmm. I attached another image.

Try clicking the three buttons (...)

**Comment by luyx2412** [comment] 2020-07-10 14:08
Hi @sondercloud Sorry i still don't see your image. So please upload to the drive and share the link.
![image](https://user-images.githubusercontent.com/8909619/87163369-6c69c780-c2f1-11ea-94c6-c20190093bf4.png)

Thanks

**Comment by sondercloud** [comment] 2020-07-10 15:07
https://drive.google.com/file/d/1KjW84zSqY6JHu80sBPbxf2quRJj_UbQ2/view?usp=drivesdk

**Comment by sondercloud** [comment] 2020-07-14 01:10
Hi,

Did you get my link?

**Comment by minhcasi** [comment] 2020-07-16 04:31
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. Although checking this Integration Issue is not included from our support scope - https://inspireui.com/support-policies/, but we’re working as hard as we can to reply to your request as soon as possible.

Do you mind to update our rating? It is possible to process refund if you could not use the product - thanks

**Comment by sondercloud** [comment] 2020-07-16 05:10
Hi,

Thanks so much for getting back to me.

Yeah I can definitely update it to five stars if I can get the app working.
I followed all the steps in the documentation and there’s no help for this
issue online. I’m unable to submit a product in the app.

Is Dokan Pro required or am I able to use the free version so you know? I’m
trying my best to set this app up but I’m really not sure what to do at
this point.

Thank you so much, your app is great except for this part. I can update my
rating.

Thanks

**Comment by sondercloud** [comment] 2020-07-16 21:26
Could you let me know if Dokan Pro is required?

I have updated my review to 5 stars.

Thanks!

**Comment by minhcasi** [comment] 2020-07-17 08:53
@sondercloud - thank you for your help with the rating.

Yes - it is required to active full features from the API, let us know if you have any question

**Comment by minhcasi** [comment] 2020-07-19 04:06
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-19 04:06 UTC
Labels: MStoreMV, config-site
