### ISSUE TITLE
Having problem with settings up mstore and fluxbuilder 

### ISSUE THREAD

**Issue by notthatparker** [inspireui/support#4752] opened 2020-08-26 18:55 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
- Im having a problem with activating mstore plugin i tried deactivating all of other plugins but still it keeps throwing this error ,and for now im stuck on trying to figure out what to do , 
![Screen Shot 2020-08-26 at 22 39 59](https://user-images.githubusercontent.com/34457302/91343111-15f71080-e7ed-11ea-9736-6a5145003462.png)

- And it might be my fault but when i try to activate the build the fluxbuilder always showed me a small sign about fluxlisting instead of activating  the build , sorry this one isnt to much technical just trying to figure out the fluxbuilder

**Comment by minhcasi** [comment] 2020-08-27 02:36
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

----

Does it seem there is duplicate mstore-api on your site?

**Comment by minhcasi** [comment] 2020-08-28 04:25
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-08-28 04:25 UTC
Labels: needs-more-info
