### ISSUE TITLE
MSTORE EXPO error npm install

### ISSUE THREAD

**Issue by jajamoks** [inspireui/support#3226] opened 2020-05-16 13:16 UTC
![image](https://user-images.githubusercontent.com/24262635/82120682-ce1c1400-973c-11ea-8c2e-86082bd77a9a.png)

**Comment by minhcasi** [comment] 2020-05-17 06:18
Duplicate of #3225 - pls help to raise one ticket for your all issue - thank you!

**Closed by minhcasi** 2020-05-17 06:18 UTC
