### ISSUE TITLE
[FluxStore Listing - Directory WooCommerce app by Flutter] - App will not compile after Framework update

### ISSUE THREAD

**Issue by DayneLinx** [inspireui/support#1604] opened 2019-12-13 10:33 UTC
Hi

After updating to the latest Flutter and Dart, my app will not compile. Prior to this happening I could compile but there were loads of warnings when I did. 

Please see the attached proof of purchase and the necessary screenshots
---------
![Screenshot 2019-12-13 at 10 23 47](https://user-images.githubusercontent.com/23277612/70793696-d4742180-1d93-11ea-87ab-e02794d07aed.png)
![Screenshot 2019-12-13 at 10 24 33](https://user-images.githubusercontent.com/23277612/70793698-d50cb800-1d93-11ea-863f-b7ef4259a13d.png)
![Screenshot 2019-12-13 at 10 32 42](https://user-images.githubusercontent.com/23277612/70793748-ec4ba580-1d93-11ea-83b6-4d46d948ccab.png)

**Comment by minhcasi** [comment] 2019-12-14 11:33
@DayneLinx could you help to update the pubspec.yaml and change this value   

From: cached_network_image: 1.1.3
To:   cached_network_image: 2.0.0-rc.1

Then update the package and restart again, this issue is caused by latest Flutter 1.12 update, we will update new version update on next couple of days - thank you!

**Comment by DayneLinx** [comment] 2019-12-15 19:10
Hi @minhcasi , 
I have updated the pubspec.yaml as requested but I am encountering the same issue. 

<img width="1344" alt="Screenshot 2019-12-15 at 19 07 12" src="https://user-images.githubusercontent.com/23277612/70867538-5fa90f00-1f6e-11ea-9a87-e5761bef59e9.png">
<img width="1680" alt="Screenshot 2019-12-15 at 19 08 45" src="https://user-images.githubusercontent.com/23277612/70867539-5fa90f00-1f6e-11ea-8e93-cbb7da604b26.png">

Maybe it will be better to wait for the update in a couple of days.

**Comment by minhcasi** [comment] 2019-12-16 07:10
@DayneLinx - thank you for quick feedback, we will have a check and update you shortly - thank you!

**Comment by minhcasi** [comment] 2019-12-22 06:52
Fixed on 1.2b releae - thank you!

**Closed by minhcasi** 2019-12-22 06:52 UTC
Labels: Fluxstore-Listing, priority !!!, question ❓
