### ISSUE TITLE
[Fluxstore Pro] - Original category icons list issue need updating

### ISSUE THREAD

**Issue by Alnaggar94** [inspireui/support#2061] opened 2020-02-11 06:21 UTC
1. My issue:
Hello, I have posted this issue before and it got solved but now with v1.6.3 it doesn't work anymore, It works fine in v1.6.1 
more details about the issue and the solution from @minhtruong315 - https://github.com/inspireui/support/issues/1555

Please update the solution to work with v1.6.3 so I can use my icons in the app 

2. Screenshots issues:

This error show in v1.6.3 
![Capdfdghture](https://user-images.githubusercontent.com/49800146/74214737-aa65af80-4caf-11ea-8268-e71407c4b26a.JPG)

3. Proof of my purchased:

https://imgur.com/a/9TsYcIf

**Comment by inspireui-support** [comment] 2020-02-12 04:02
Duplicate of #2001

Please help to use the solution on this ticket - thank you!

**Comment by Alnaggar94** [comment] 2020-02-12 04:33
@inspireui-support @minhtruong315 I was the one who posted the issue, The solution only works in the previous version it doesn't work in v1.6.3

**Comment by inspireui-support** [comment] 2020-02-13 01:30
@minhtruong315 - pls investigate - thanks

**Comment by Alnaggar94** [comment] 2020-02-13 02:05
@inspireui-support @minhtruong315 - I solved the problem myself, please close the ticket.

**Comment by inspireui-support** [comment] 2020-02-15 08:58
Thank you for confirm :)

**Closed by inspireui-support** 2020-02-15 08:58 UTC
Labels: FluxStore, question ❓
