### ISSUE TITLE
How to remove these error when User Click App while loading 

### ISSUE THREAD

**Issue by msesetz** [inspireui/support#4215] opened 2020-07-15 14:54 UTC
Fluxnews Version 1.4.1

How to remove this error:-

See screenshot 

![Screenshot_20200715-102735](https://user-images.githubusercontent.com/51053867/87560084-bffa5d80-c6c3-11ea-9018-b0335f8fba17.jpg)

Also Comment button not working

**Comment by minhcasi** [comment] 2020-07-16 01:52
Duplicate of #4134

**Closed by minhcasi** 2020-07-16 01:52 UTC
