### ISSUE TITLE
[Fluxstore Prestashop] Demo store is not working

### ISSUE THREAD

**Issue by pierrederuel** [inspireui/support#3870] opened 2020-06-23 13:48 UTC
Hi,

I just bought and installed the prestashop version of fluxstore without updating to my own store, I'm using the one from your demo ().

Categories are not retrieved nor the products, here's the error in the logs:

`
Configuring the default Firebase app...
Configured the default Firebase app __FIRAPP_DEFAULT.
)
)
)
)
Request <OSRequestRegisterUser: 0x60000249f300> success result {
    id = "d325eab0-e217-4f62-b8c1-4fe9c7e726d9";
    success = 1;
}
Debug service listening on ws://127.0.0.1:52474/pYof5DbQnFA=/ws
Syncing files to device iPhone 11 Pro...
WARNING: OneSignal has detected that your application delegate implements a deprecated method (application:didReceiveLocalNotification:). Please note that this method has been officially deprecated and the OneSignal SDK will no longer call it. You should use UNUserNotificationCenter instead
)
)
)
)
flutter: [2020-06-23 13:13:01.803229Z][Fluxstore][main] ============== main.dart START ==============
flutter: [2020-06-23 13:13:01.961999Z][Fluxstore][AppState] initState
flutter: [2020-06-23 13:13:01.974921Z][Fluxstore][AppState] build
ERROR: Error! iOS Simulator does not support push! Please test on a real iOS device. Error: Error Domain=NSCocoaErrorDomain Code=3010 "remote notifications are not supported in the simulator" UserInfo={NSLocalizedDescription=remote notifications are not supported in the simulator}
flutter: [2020-06-23 13:13:02.027166Z][Fluxstore][AppState] build Theme
flutter: screenName /
flutter: [2020-06-23 13:13:02.904376Z][Fluxstore][AppState] Inital Data
flutter: [2020-06-23 13:13:03.026604Z][Fluxstore][Services] setAppConfig: --> presta <--
flutter: [2020-06-23 13:13:03.070521Z][Fluxstore][AppState] init mobile modules ..
flutter: [2020-06-23 13:13:03.088536Z][Fluxstore][AppState] register modules .. DONE
ERROR: Error! iOS Simulator does not support push! Please test on a real iOS device. Error: Error Domain=NSCocoaErrorDomain Code=3010 "remote notifications are not supported in the simulator" UserInfo={NSLocalizedDescription=remote notifications are not supported in the simulator}
flutter: [Debug] Finish Load AppConfig
flutter: [2020-06-23 13:13:03.254937Z][Fluxstore][AppState] Init Data Finish
flutter: [2020-06-23 13:13:03.291281Z][Fluxstore][Category] getCategories
WARNING: OneSignal has detected that your application delegate implements a deprecated method (application:didReceiveLocalNotification:). Please note that this method has been officially deprecated and the OneSignal SDK will no longer call it. You should use UNUserNotificationCenter instead
flutter: [2020-06-23 13:13:03.333590Z][Fluxstore][AppState] build Theme
flutter: [2020-06-23 13:13:03.382443Z][Fluxstore][MyConnectivity] online
flutter: [2020-06-23 13:13:03.390045Z][Fluxstore][App] internet issue change: {ConnectivityResult.wifi: true}
flutter: screenName null
flutter: [2020-06-23 13:13:05.936707Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
flutter: [2020-06-23 13:13:05.986986Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
flutter: [2020-06-23 13:13:06.127126Z][Fluxstore][Home] initState
flutter: [2020-06-23 13:13:06.130277Z][Fluxstore][Home] build
**flutter: [2020-06-23 13:13:06.480631Z][Fluxstore][Category] getCategories
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      new List.from (dart:core-patch/array_patch.dart:54:19)
#2      Prestashop.getProductOptions (package:fstore/services/prestashop.dart:320:23)
<asynchronous suspension>
#3      Prestashop.fetchProductsLayout (package:fstore/services/prestashop.dart:105:15)
<asynchronous suspension>
#4      Services.fetchProductsLayout (package:fstore/services/index.dart:185:23)
#5      _ProductListLayoutState.getProductLayout.<anonymous closure> (package:fstore/widgets/home/product_list_layout.dart:165:25)
#6      new Future.sync (dart:async/future.dart:224:31)
#7      AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#8      _ProductListLayoutState.getProductLayout (package:fstore/widgets/home/product_list_layout.dart:159:64)
#9      _ProductListLayoutState.initState (package:fstore/widgets/home/product_list_layout.dart:35:25)
#10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640<…>
flutter: NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      new List.from (dart:core-patch/array_patch.dart:54:19)
#2      Prestashop.getProductOptions (package:fstore/services/prestashop.dart:320:23)
<asynchronous suspension>
#3      Prestashop.fetchProductsLayout (package:fstore/services/prestashop.dart:105:15)
<asynchronous suspension>
#4      Services.fetchProductsLayout (package:fstore/services/index.dart:185:23)
#5      _ProductListLayoutState.getProductLayout.<anonymous closure> (package:fstore/widgets/home/product_list_layout.dart:165:25)
#6      new Future.sync (dart:async/future.dart:224:31)
#7      AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#8      _ProductListLayoutState.getProductLayout (package:fstore/widgets/home/product_list_layout.dart:159:64)
#9      _ProductListLayoutState.initState (package:fstore/widgets/home/product_list_layout.dart:35:25)
#10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640<…>
flutter: NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      new List.from (dart:core-patch/array_patch.dart:54:19)
#2      Prestashop.getProductOptions (package:fstore/services/prestashop.dart:320:23)
<asynchronous suspension>
#3      Prestashop.fetchProductsLayout (package:fstore/services/prestashop.dart:105:15)
<asynchronous suspension>
#4      Services.fetchProductsLayout (package:fstore/services/index.dart:185:23)
#5      _ProductListLayoutState.getProductLayout.<anonymous closure> (package:fstore/widgets/home/product_list_layout.dart:165:25)
#6      new Future.sync (dart:async/future.dart:224:31)
#7      AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#8      _ProductListLayoutState.getProductLayout (package:fstore/widgets/home/product_list_layout.dart:159:64)
#9      _ProductListLayoutState.initState (package:fstore/widgets/home/product_list_layout.dart:35:25)
#10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640<…>
flutter: NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator**
flutter: [2020-06-23 13:13:15.028954Z][Fluxstore][AppState] build
flutter: [2020-06-23 13:13:15.029485Z][Fluxstore][AppState] build Theme
flutter: [2020-06-23 13:13:15.036951Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
flutter: [2020-06-23 13:13:15.049282Z][Fluxstore][Home] build
flutter: [2020-06-23 13:13:15.188439Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
flutter: [2020-06-23 13:13:15.305408Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
flutter: [2020-06-23 13:13:15.395070Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============

`

Could you take a look please?

Thanks,

Pierre

**Comment by ameenbadri7** [comment] 2020-06-23 19:05
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-06-25 00:33
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-06-25 00:33 UTC
Labels: needs-more-info
