### ISSUE TITLE
Products per Order, zero price.

### ISSUE THREAD

**Issue by gmediard** [inspireui/support#3740] opened 2020-06-15 02:38 UTC
Step 1 (require): describe detail issues & screenshots

Detail Issues:
Good, currently I would like not to show the price of the products, and make the purchase as if it were only an order.

How could I achieve this?

Later, I will enable direct purchase for the value of the product, in a next phase.

Product & version: Fluxstore Woocommerce 1.7.4

Flutter (or React Native) version: 1.19.0-2.0

Testing Device/Simulator: LG AS993

Screenshot issues (drag the file to attach here): Not necessary

Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com

Important Note:

We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
Kindly create only One Ticket & includes all the issues, that would help us focus to resolve it better.
If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment] 2020-06-15 04:12
Duplicate of #3741

**Closed by minhcasi** 2020-06-15 04:12 UTC
