### ISSUE TITLE
Exception on New user Sign Up

### ISSUE THREAD

**Issue by mohan1149** [inspireui/support#4315] opened 2020-07-22 10:23 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues:  Getting Exception on user registration. 
+ Product & version: Flux store Pro 1.7.6
+ Flutter (or React Native) version: Flutter 1.17.5
+ Testing Device/Simulator:  Simulator
![Simulator Screen Shot - iPhone X - 2020-07-22 at 13 21 11](https://user-images.githubusercontent.com/61935068/88165347-3a743180-cc1e-11ea-89ea-ca9fe120f027.png)

+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment] 2020-07-22 20:38
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by minhcasi** [comment] 2020-07-23 02:59
verified ✅

**Comment by ameenbadri7** [comment] 2020-07-23 22:01
could you check that you activate you [ mstore plugin ](https://docs.inspireui.com/fluxstore/woocommerce-setup/)? 
Thank you

**Comment by mohan1149** [comment] 2020-07-24 07:14
Yes, I have activated mstore  plugin
![Screen Shot 2020-07-24 at 10 13 39 AM](https://user-images.githubusercontent.com/61935068/88368273-5ef31980-cd96-11ea-99c0-8d50cbc11c24.png)

**Comment by ameenbadri7** [comment] 2020-07-24 23:11
I suggest you should re-add the MStore API plugin(completely delete it and add it via plugin search). After that, deactivate all the plugins except Woocommerce, dokan Plugins, and MStore API.

If that not help I will pass this ticket to a higher developer in our team. 

Thank you.

**Comment by mohan1149** [comment] 2020-07-25 09:39
Yes, Its worked

**Comment by mohan1149** [comment] 2020-07-29 15:24
For archive, error: bitcode bundle could not be generated with flutter webview

**Comment by mohan1149** [comment] 2020-07-29 15:32
bitcode bundle could not be generated because '/Users/macmini2/projects/fluttrer/FluxStore-pro-1.7.6/source/ios/Flutter/Flutter.framework/Flutter' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/macmini2/projects/fluttrer/FluxStore-pro-1.7.6/source/ios/Flutter/Flutter.framework/Flutter' for architecture armv7

**Comment by minhcasi** [comment] 2020-07-30 04:30
@mohan1149 - pls try to run `flutter build ios` before open XCode to Archive the project

**Comment by minhcasi** [comment] 2020-08-01 04:19
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-08-01 04:19 UTC
Labels: FluxstoreMV

**Comment by mohan1149** [comment] 2020-08-09 13:07
Sign In with Apple Button is only showing iPhone 11 and above but not in iPhone X and below variants.
![Simulator Screen Shot - iPhone 11 Pro - 2020-08-09 at 14 01 45](https://user-images.githubusercontent.com/61935068/89732849-26239780-da5a-11ea-99de-3d5bcbda7bf7.png)
![Simulator Screen Shot - iPhone X - 2020-08-09 at 14 03 13](https://user-images.githubusercontent.com/61935068/89732850-2754c480-da5a-11ea-9be7-fbcc7d709ead.png)
