### ISSUE TITLE
Whay you close my ticket with out answer .#545

### ISSUE THREAD

**Issue by osamasparky** [inspireui/support#625] opened 2019-05-22 08:24 UTC
Please the
1-cart still disabled. On the app on all products. please check you app demo on android it have the same problem the cart not active on the product page . i notes it now
2-facebook what should i do.

**Comment by minhcasi** [comment] 2019-05-22 10:01
hi there try to JUST CREATE ONE TICKET for your issues, thanks

Duplicate of #625

**Closed by minhcasi** 2019-05-22 10:01 UTC
