### ISSUE TITLE
FLUXSTORE - Change icon color when tab is active

### ISSUE THREAD

**Issue by nicholasanthonys** [inspireui/support#4236] opened 2020-07-17 03:40 UTC
How do i change the icon color when bottom tab is active like this picture?

![image](https://user-images.githubusercontent.com/46061570/87746059-d0bce780-c819-11ea-84c2-3736b7accb28.png)

**Comment by ameenbadri7** [comment] 2020-07-17 05:22
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by ameenbadri7** [comment] 2020-07-18 00:59
I'm sorry to close this ticket as there is no response or active conversation.

Please help to create a new one and link it to this ticket if the problem is not solved.

thank you.

**Closed by ameenbadri7** 2020-07-18 00:59 UTC
Labels: needs-more-info
