### ISSUE TITLE
Logo Issue

### ISSUE THREAD

**Issue by ajeets1978** [inspireui/support#1269] opened 2019-10-22 11:26 UTC
Even After replacing the logo.png in the asset file, still I see only Fluxstore logos.

**Comment by minhcasi** [comment] 2019-10-22 11:53
Duplicate of #1271

Kindly notes:
- Create one ticket for your all issue with detail screenshot
- Share your config file (common/config.json and config.js) so we can reproduce issues.
- Also, make sure to check the document first - https://docs.inspireui.com/fluxstore

**Closed by minhcasi** 2019-10-22 11:53 UTC
Labels: question ❓
