### ISSUE TITLE
 EXCEPTION CAUGHT BY WIDGETS LIBRARY 

### ISSUE THREAD

**Issue by DimataIT** [inspireui/support#3425] opened 2020-05-26 23:45 UTC
Hi, I just compile and run my fresh purchased fluxstore multi vendor for my WCFM marketplace, but no success.
It seems the source code I downloaded from codecanyon are not ready or complete, due to:
1) had to comment out lines in lib/config.dart, due source not found
//export 'config/advance.dart';
//export 'config/basic.dart';
//export 'config/languages.dart';

2) had to import lib/common/config/general.dart on some code.. to fix 150 errors

3) On run :
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (21304): The following NoSuchMethodError was thrown building OnBoardScreen(dirty, state:
I/flutter (21304): _OnBoardScreenState#2a513):
I/flutter (21304): The method '[]' was called on null.
I/flutter (21304): Receiver: null
I/flutter (21304): Tried calling: []("OnBoarding")
I/flutter (21304): 
I/flutter (21304): The relevant error-causing widget was:
I/flutter (21304):   OnBoardScreen
I/flutter (21304):   file:///D:/user/ktanjana/product/fluxstore/FluxStore-vendor-1.7.3/source/lib/app_init.dart:90:45
I/flutter (21304): 
I/flutter (21304): When the exception was thrown, this was the stack:
I/flutter (21304): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
I/flutter (21304): #1      _OnBoardScreenState.build (package:fstore/screens/home/onboard_screen.dart:181:40)
I/flutter (21304): #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
I/flutter (21304): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
I/flutter (21304): #4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
I/flutter (21304): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (21304): #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
I/flutter (21304): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
I/flutter (21304): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
I/flutter (21304): ...     Normal element mounting (95 frames)
I/flutter (21304): #103    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
I/flutter (21304): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
I/flutter (21304): #105    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5580:32)
I/flutter (21304): #106    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5957:17)
I/flutter (21304): #107    Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
I/flutter (21304): #108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter (21304): #109    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
I/flutter (21304): #110    Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (21304): #111    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
I/flutter (21304): #112    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:20)
I/flutter (21304): #113    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
I/flutter (21304): #114    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
I/flutter (21304): #115    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
I/flutter (21304): #116    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
I/flutter (21304): #120    _invoke (dart:ui/hooks.dart:261:10)
I/flutter (21304): #121    _drawFrame (dart:ui/hooks.dart:219:3)
I/flutter (21304): (elided 3 frames from dart:async)
I/flutter (21304): 
I/flutter (21304): ════════════════════════════════════════════════════════════════════════════════════════════════════
please help. thank you

**Comment by minhcasi** [comment] 2020-05-27 01:48
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by DimataIT** [comment] 2020-05-27 04:51
> Thank you for the feedback.
> 
> Please help us to submit this form and fill all required info to continue with the support - [http://private.inspireui.com/ -](http://private.inspireui.com/%C2%A0-) please don't share the purchase code or screenshot public here as another user will use it for activation.
> 
> We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

I posted already in the private form support. please follow up. Thx

**Comment by minhcasi** [comment] 2020-05-28 02:40
@kvt0012 - pls help with investigating

**Comment by kvt0012** [comment] 2020-05-29 08:09
This is your first run time or you integrate your config ? 
Please try to run on the default project, thank you

**Comment by minhcasi** [comment] 2020-05-31 02:43
'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-05-31 02:43 UTC
Labels: FluxstoreMV, common-integration
