### ISSUE TITLE
[my-product] - fluxstore woocommerce

### ISSUE THREAD

**Issue by macahamed** [inspireui/support#2453] opened 2020-03-26 12:18 UTC
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: terminal is not working, how to chnage app icon

2. Screenshots issues (required):
![Screen Shot 2020-03-26 at 4 14 01 PM](https://user-images.githubusercontent.com/62641104/77645945-0f821580-6f7d-11ea-87a0-2dea39002921.png)

3. Proof of my purchased (required):![Screen Shot 2020-03-26 at 3 24 15 PM](https://user-images.githubusercontent.com/62641104/77645969-19a41400-6f7d-11ea-9f6e-c35cf86888b9.png)

3. Config files (required)

**Comment by minhcasi** [comment] 2020-03-26 12:27
Duplicate of #2452

**Closed by minhcasi** 2020-03-26 12:27 UTC
Labels: question ❓
