### ISSUE TITLE
Buzapp

### ISSUE THREAD

**Issue by easln** [inspireui/support#4774] opened 2020-08-28 03:27 UTC
Hello, post text are displayed on my wordpress site, but the pictures, twitter, instagram, youtube embedded contents in the post do not appear. How can I solve this problem. Good work.

**Comment by minhcasi** [comment] 2020-08-28 04:23
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-08-29 06:02
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-08-29 06:02 UTC
Labels: needs-more-info

**Comment by easln** [comment] 2020-09-23 05:35
hello, what html code do I need to generate the video to get the videos from my wordpress site? I want to receive my own videos, not a youtube video, with a method other than iframe.
________________________________
Gönderen: Minh Pham <notifications@github.com>
Gönderildi: 29 Ağustos 2020 Cumartesi 09:03
Kime: inspireui/support <support@noreply.github.com>
Bilgi: easln <easln@outlook.com>; Author <author@noreply.github.com>
Konu: Re: [inspireui/support] Buzapp (#4774)


I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
