### ISSUE TITLE
[Fluxstore MV] - No Adress

### ISSUE THREAD

**Issue by aberatadiguzel** [inspireui/support#2598] opened 2020-04-07 11:41 UTC
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I choose but no address
2. Screenshots issues (required): https://imgur.com/G6LL9v1

3. Proof of my purchased (required): https://imgur.com/HOxrZyA

3. Config files (required)
https://drive.google.com/open?id=1qkJUCXRJ_cRvFJD6k2pCdCWLduKDyeJ3

**Comment by minhcasi** [comment] 2020-04-08 02:05
Duplicate of #2600

**Closed by minhcasi** 2020-04-08 02:05 UTC
Labels: question ❓
