### ISSUE TITLE
Please reopen my ticket #3181 Having error in Fluxstore 1.7.5 app

### ISSUE THREAD

**Issue by amitw7786** [inspireui/support#4122] opened 2020-07-08 14:54 UTC
Having some error and bugs in app

**Comment by ameenbadri7** [comment] 2020-07-08 20:36
please provide details about them so we can help? 

thank you

**Comment by minhcasi** [comment] 2020-07-09 02:51
Duplicate of #3181

We will check on that ticket - thank you for your time

**Closed by minhcasi** 2020-07-09 02:51 UTC
