### ISSUE TITLE
User data not available on checkout page

### ISSUE THREAD

**Issue by magic-coding** [inspireui/support#3836] opened 2020-06-21 09:45 UTC
I have an issue with the checkout page. When I choose the payment method (online payment) it redirects me to my website the checkout page but without:
- First name
- last name
- Address
- mobile number

Video:
https://www.dropbox.com/s/f08pda8o6vri9zu/demo-1.mov?dl=0

I have the latest version of the app and Mstore API plugin.

**Comment by ameenbadri7** [comment] 2020-06-21 11:59
الذي بتسخدمة الآن هو نافذة لصفحة المتجر كان الزبون دخل للصفحة عبر الكروم ودخل يشتري عبر الموقع لهذا بتلاحظ أن الزبون بحاجة أنه تعبئة الخانات من جديد,
ولو تلاحظ لو الزبون حفظ إيميله وكمان بقية الخانات مسبقا في الكروم راح تتعبى تلقائياً لانك تتعامل مع الكروم بشكل مباشر مش مع التطبيق نفسه. 


in programing language, they call this a web view because if you want the customer to buy with external views as the woocommerce view or any bank in your country you as a programmer don't need to code the program all over again. 
just go and build a simple web view inside your app it's like going to google chrome but from inside the app.

for further info go to this like 
[multi payment on fluxstore](https://docs.inspireui.com/fluxstore/multi-payment/#webview-multi-payment).

if you want to know more about web views see this [ link also ](https://medium.com/flutter/the-power-of-webviews-in-flutter-a56234b57df2).

**Comment by magic-coding** [comment] 2020-06-21 12:19
Sorry but this already works on the old version and it already passes the user email that I enter on the shipping address tab but the other details not passed to the checkout page lie first name, last name, and address.

**Comment by enriqueleon80** [comment] 2020-06-22 17:59
I second this issue.  Seeing it now.  I'm running on 1.7.3 Flutter using WOOCOMMERCE.  

My debugging indicates this is a problem with the Mstore API function prepare_checkout().  When this code runs it sets the customer data from the prepared checkout, HOWEVER, WooCommerce is calling it's own hooks after the fact and seems to be setting the value back.

Rather strange as this was working for me before.  It's mostly likely caused by an upgrade to WOOCOMMERCE or the Mstore API itself. 

Following this thread as I was going to code around this problem so I can go live.

**Comment by enriqueleon80** [comment] 2020-06-22 18:00
PS: Please provide CHANGLOG updates on the Mstore API.  We're on 2.5.9 and no updates since 2.0.0.  It's pretty nuts!

**Comment by enriqueleon80** [comment] 2020-06-22 18:11
@ameenbadri7 Could I also ask where the GITHUB repo is for the MSTORE-API?  Would love to be able to track and see changes so I can determine when I will update.

**Comment by enriqueleon80** [comment] 2020-06-23 13:10
Hey guys, this is a rather urgent issue for me.  Without checkout data getting transferred transactions can't be completed.  We are at a DEAD STOP.  Just wanted to make sure this gets the necessary priority? @minhcasi

**Comment by enriqueleon80** [comment] 2020-06-23 14:21
For anyone facing this problem, this was fixed with a workaround hook which gets called prior to standard Mstore API.  Same logic, it just updates the DB as opposed to the WOO cart session.

/**
 * WORKAROUND: Update customer info to DB prior to MSTORE API hook to update WOO cart.  Awaiting fix.
 */
function dt_woocommerce_checkout_fields($fields)
{
    if (isset($_GET['mobile']) && isset($_GET['code'])) {

        $code = $_GET['code'];
        global $wpdb;
        $table_name = $wpdb->prefix . "mstore_checkout";
        $item = $wpdb->get_row("SELECT * FROM $table_name WHERE code = '$code'");
        if ($item) {
            $data = json_decode(urldecode(base64_decode($item->order)), true);
        } else {
            //return var_dump("Can't not get the order");
        }

        if (isset($data['token'])) {
            // Validate the cookie token
            $userId = wp_validate_auth_cookie($data['token'], 'logged_in');
            // Check user and authentication
            $user = get_userdata($userId);
        }
    } else {
        //If code not set & not validated, do nothing
        return;
    }

    global $woocommerce;
    $shipping = isset($data['shipping']) ? $data['shipping'] : $data['billing'];
    $billing = isset($data['billing']) ? $data['billing'] : $shipping;
    // $woocommerce->customer->set_shipping_first_name($shipping["first_name"]);
    // $woocommerce->customer->set_shipping_last_name($shipping["last_name"]);
    // $woocommerce->customer->set_shipping_company($shipping["company"]);
    // $woocommerce->customer->set_shipping_address_1($shipping["address_1"]);
    // $woocommerce->customer->set_shipping_address_2($shipping["address_2"]);
    // $woocommerce->customer->set_shipping_city($shipping["city"]);
    // $woocommerce->customer->set_shipping_state($shipping["state"]);
    // $woocommerce->customer->set_shipping_postcode($shipping["postcode"]);
    // $woocommerce->customer->set_shipping_country($shipping["country"]);

    // $woocommerce->customer->set_billing_first_name($billing["first_name"]);
    // $woocommerce->customer->set_billing_last_name($billing["last_name"]);
    // $woocommerce->customer->set_billing_company($billing["company"]);
    // $woocommerce->customer->set_billing_address_1($billing["address_1"]);
    // $woocommerce->customer->set_billing_address_2($billing["address_2"]);
    // $woocommerce->customer->set_billing_city($billing["city"]);
    // $woocommerce->customer->set_billing_state($billing["state"]);
    // $woocommerce->customer->set_billing_postcode($billing["postcode"]);
    // $woocommerce->customer->set_billing_country($billing["country"]);
    // $woocommerce->customer->set_billing_email($billing["email"]);
    // $woocommerce->customer->set_billing_phone($billing["phone"]);

    update_user_meta($userId, 'billing_first_name', $billing["first_name"]);
    update_user_meta($userId, 'billing_last_name', $billing["last_name"]);
    update_user_meta($userId, 'billing_company', $billing["company"]);
    update_user_meta($userId, 'billing_address_1', $billing["address_1"]);
    update_user_meta($userId, 'billing_address_2', $billing["address_2"]);
    update_user_meta($userId, 'billing_city', $billing["city"]);
    update_user_meta($userId, 'billing_state', $billing["state"]);
    update_user_meta($userId, 'billing_postcode', $billing["postcode"]);
    update_user_meta($userId, 'billing_country', $billing["country"]);
    update_user_meta($userId, 'billing_email', $billing["email"]);
    update_user_meta($userId, 'billing_phone', $billing["phone"]);

    return $fields;
}
add_action('template_redirect', 'dt_woocommerce_checkout_fields', 5);

**Comment by minhcasi** [comment] 2020-06-24 03:48
@enriqueleon80 are you the same team with @magic-coding ?

Do you mean the above solution will fix the issue? Thank you!

**Comment by magic-coding** [comment] 2020-06-24 04:09
No, we are not on the same team.

**Comment by enriqueleon80** [comment] 2020-06-24 15:40
No, not on the same team.

To circle back on my snippet.  On further review, it does fix the issue where the values don't get transferred to the checkout page because it updates the user info.  However, when I look at the WooCommerce order the billing information isn't there.

That said, it would seem version 2.6.2 is released of the Mstore API which seems to address this problem!  If so, great turn around guys.  

PS: Possible to update the change logs on the Mstore API?  Every time I hit update, I get scared ; P

**Comment by enriqueleon80** [comment] 2020-06-25 00:00
Doh... I take it back. Issue not resolved.

**Comment by enriqueleon80** [comment] 2020-06-25 01:07
Figured I'd provide an update.  Sorry for all the messages, just working double-time to get us live.

It would seem my snippet does work.  I have a plugin that was hiding fields and so the values weren't going where they needed to.  My snippet updates the user details every single time the application tries to do a checkout, in the end... this is something I might want so that the backend always contains the latest information sent from MSTORE APP.  

Moving forward with this workaround until a fix is issued

PS: Please provide a change log : )

**Comment by minhcasi** [comment] 2020-06-25 08:17
@minhtruong315 - could you help to review the mstore-api with the code-snippet above to see if we could fix the issue "other details not passed to the checkout page lie first name, last name, and address." - thank you!

**Comment by magic-coding** [comment] 2020-06-26 10:02
Any update on this issue, please?

**Comment by minhtruong315** [comment] 2020-06-27 12:29
Hi @magic-coding can u send me admin info via email: truong@inspireui.com
with subject: https://github.com/inspireui/support/issues/3836

**Comment by minhtruong315** [comment] 2020-06-28 15:19
Hi @magic-coding Please update MStore Api plugin then try again. Let me know the result
Thanks

**Comment by magic-coding** [comment] 2020-06-28 17:18
Hello @minhtruong315 
It was working yesterday but after I update the plugin today the issue appears again. Can I get the previous version of the MStore Api plugin to confirm if it's working or not? 

Thank you

**Comment by minhtruong315** [comment] 2020-06-29 01:58
@magic-coding Add my skype: minhtruong315
I will help you check via teamviewer
Thanks

**Comment by magic-coding** [comment] 2020-06-29 05:10
Added! Please check.

**Comment by minhtruong315** [comment] 2020-06-30 02:28
Hi @magic-coding give me your skype. I dont see any request
Thanks

**Comment by magic-coding** [comment] 2020-07-04 07:36
> Hi @magic-coding give me your skype. I dont see any request
> 
> Thanks


https://join.skype.com/invite/hrurygQFe8qQ

**Comment by minhtruong315** [comment] 2020-07-06 03:57
Hi @magic-coding I messaged you on the skype. pls check

**Comment by minhtruong315** [comment] 2020-07-06 08:02
supported via teamviewer

**Closed by minhtruong315** 2020-07-06 08:02 UTC
Labels: FluxStore, Mstore-API
