### ISSUE TITLE
Sticky

### ISSUE THREAD

**Issue by rabahaldoori** [inspireui/support#3461] opened 2020-05-29 01:17 UTC
how i make the App Sticky Home not moving when i scroll down, link the picture i don't need it to go above the background image 

<img width="367" alt="Screen Shot 2020-05-28 at 8 15 18 PM" src="https://user-images.githubusercontent.com/31085177/83210326-2cbf9580-a120-11ea-8add-cfdc204a18b6.png">

<img width="365" alt="Screen Shot 2020-05-28 at 8 15 11 PM" src="https://user-images.githubusercontent.com/31085177/83210321-2a5d3b80-a120-11ea-9658-ccafebeb90fc.png">

Thank you

**Comment by minhcasi** [comment] 2020-05-30 08:16
this bug is fixed on latest release `1.7.5` - we will release it on 1-2 days - thank you!

**Comment by rabahaldoori** [comment] 2020-05-31 02:28
@minhcasi i got update 1.7.4 its didn't  fix the issue, do you have another update ? upcoming  days ?

**Comment by minhcasi** [comment] 2020-05-31 02:41
Duplicate of #3404

**Closed by minhcasi** 2020-05-31 02:41 UTC
Labels: 1.7.5, FluxstoreMV
