### ISSUE TITLE
Default Layout in list

### ISSUE THREAD

**Issue by daboujey** [inspireui/support#3931] opened 2020-06-26 17:44 UTC
Detail Issues: Page productos display list as default view, without having to select list on the filter page
Product & version: Version: 1.7.5
Flutter (or React Native) version: 1.17.4
Testing Device/Simulator: Nexus 6 API 26
Screenshot issues (drag the file to attach here):

![TELA-APP2](https://user-images.githubusercontent.com/64880213/85885585-f32f8800-b7ba-11ea-9ad2-c3e65d159e43.jpeg)

![TELA-APP](https://user-images.githubusercontent.com/64880213/85885318-80bea800-b7ba-11ea-9fe6-94ecb9fc135a.jpeg)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment] 2020-06-26 18:43
sorry @daboujey but on your last issue we answered and you haven't confirmed that you purchase the app.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 
Thank you for your time!

**Comment by daboujey** [comment] 2020-06-26 19:30
OK SENT
the email is:  daboudjey@gmail.com

**Comment by ameenbadri7** [comment] 2020-06-28 18:00
`Page products display list as default view, without having to select list on the filter page
`
please could you give us more details about this issue and what you want in more detail? 
because I have seen it yesterday again and could not understand?

**Comment by ameenbadri7** [comment] 2020-06-29 19:42
I'm sorry to close this ticket as there is no response or active conversation, 
please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by ameenbadri7** 2020-06-29 19:42 UTC
Labels: FluxStore
