### ISSUE TITLE
FormatException of Categories & products names (lang FR) fluxstore

### ISSUE THREAD

**Issue by benzhir** [inspireui/support#4385] opened 2020-07-27 17:07 UTC
```
I/flutter (16685): [2020-07-27 16:40:16.960746Z][xxx][Category] getCategories
E/flutter (16685): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FormatException: Unexpected character (at character 1)
E/flutter (16685): <!doctype html>
E/flutter (16685): ^
```
FluxStore Prestashop 1.7.6
Flutter v 1.17.5
Testing Device 

Screenshots:
https://drive.google.com/file/d/1S9fYS7V9FgBKOxosA6jC4wmhcHvKXBbi/view?usp=sharing
https://drive.google.com/file/d/1mWZIa-XekbxY7TWBRWw7FsbjnpjTiEhm/view?usp=sharing

**Comment by ameenbadri7** [comment] 2020-07-27 17:52
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by vumanhsn97** [comment] 2020-07-29 07:46
@benzhir 
Update this module to fix order not showing product issue: 
[customapi.zip](https://github.com/inspireui/support/files/4993370/customapi.zip)
In other issue, please submit a form with common folder (config.dart file with your webservice key) to  http://verify.inspireui.com
Thanks!

**Comment by benzhir** [comment] 2020-07-29 12:35
@vumanhsn97 
this update works, not i can showing list of product but still showing total_peoducts 0.00 !!
![Capture du 2020-07-29 13-21-29](https://user-images.githubusercontent.com/44715941/88800561-47ee6600-d1a0-11ea-9d8a-ab06a2a75772.png)

**Comment by benzhir** [comment] 2020-08-06 00:35
Hi, have an issue in login with facebook or google, always getting user object null ?

Screenshot:
https://drive.google.com/file/d/1HBeJEDnFDJnr6df-euBjuwB-F2nbWrId/view?usp=sharing

**Comment by minhcasi** [comment] 2020-08-07 01:09
Duplicate of #4492

**Closed by minhcasi** 2020-08-07 01:09 UTC
Labels: common-integration, fluxstore-prestashop
