### ISSUE TITLE
Fluxstore Woocommerce First Login Home Screen Layout Error

### ISSUE THREAD

**Issue by Amitjeypore** [inspireui/support#3127] opened 2020-05-10 07:14 UTC
Step 1 (require): detail issues and screenshots

Hi,

Once I login using the onboarding screen I get this screen filled with errors. Once I close the app and open it works fine but this error comes on onboarding first time login, please help me fix this ASAP.

![Screenshot_20200510-122809](https://user-images.githubusercontent.com/65069372/81493138-8835fa80-92bb-11ea-8585-3bbce959f1c9.jpg)
![Screenshot_20200510-123350](https://user-images.githubusercontent.com/65069372/81493140-89672780-92bb-11ea-8c5a-b7d9e8466778.jpg)

this is happening with your unmodified app as downloaded from codecanyon as well

PFA the Console Messages

[pls help to copy the error log as file on next time :) ]

**Comment by iamar1k92** [comment] 2020-05-10 10:09
same issue. Please find an solution on priority.

**Comment by NabiNeamati** [comment] 2020-05-10 10:53
I have the same issue 
please help us to solve this issu

**Comment by harjono-flux** [comment] 2020-05-11 00:47
i have same error message, when successful login wiht facebook login. Suddenly that message apprear.
I restart the app, my profile is succesfull sign in, but my homescreen apprear the same error
![Screen Shot 2020-05-11 at 00 29 34](https://user-images.githubusercontent.com/64935574/81514885-064ddc00-9364-11ea-8994-2ba169b292ae.png)
![Screen Shot 2020-05-11 at 08 47 34](https://user-images.githubusercontent.com/64935574/81514892-11087100-9364-11ea-979a-ccdc80359160.png)

**Comment by minhcasi** [comment] 2020-05-11 01:40
@all - please help to check if your json config has this setting - https://tppr.me/8qruQ - this is the new setting that could cause the issue, please try to add
```
"Setting": {
...
    "StickyHeader": false
}
```

**Comment by iamar1k92** [comment] 2020-05-11 08:18
![75e4a92a-dc6f-4a22-a85d-f1b0da9448ec](https://user-images.githubusercontent.com/58983166/81539542-d285ad00-9389-11ea-9abc-8bf0f3c8daff.jpeg)
Same error, not fixed but above solution.

**Comment by Amitjeypore** [comment] 2020-05-11 08:26
Yes tried not working.

**Comment by minhcasi** [comment] 2020-05-12 03:05
@kvt0012 - pls help to investigate this issue

**Comment by kvt0012** [comment] 2020-05-12 03:36
Can you record your video and I will check your behaviour to check where is error in, thank you   
Or you can step by step do your flow and capture your screen to it here, thank you

**Comment by iamar1k92** [comment] 2020-05-12 16:10
[video-bug.zip](https://github.com/inspireui/support/files/4616852/video-bug.zip)
It reproduces 2-3 kinds of error but problem is same.

**Comment by harjono-flux** [comment] 2020-05-12 16:52
this is my video

https://drive.google.com/file/d/1nfmdkEWT6Xv5eURuKG0t0UK7sAXrPUSh/view?usp=sharing
https://drive.google.com/file/d/1cDqwdOVUDU1spwagugQ5gQuZtUZppLj1/view?usp=sharing

**Comment by kvt0012** [comment] 2020-05-14 07:58
I think this problem is not easy. Can you share me your whole project via my email : khiem@inspireui.com or vinhkhiemt135@gmail.com, I will check it for you, thank you

**Comment by harjono-flux** [comment] 2020-05-15 00:40
wow, its more than 1GB file size, any option?

**Comment by iamar1k92** [comment] 2020-05-15 01:29
yes, first do flutter clean. Add your project to git. and download from git and send it will be hardly become 50mbs or less.

**Comment by minhcasi** [comment] 2020-05-15 04:22
You could also remove the following folder
```
- android/.gradle (hidden folder)
- ios/.symplinks  (hidden folder)
- ios/Pods/
- build/
```
Then see the magic 🧘‍♀️

**Comment by kvt0012** [comment] 2020-05-15 04:29
**@Amitjeypore  Please keep up this ticket and send me**   
Can you record your video and I will check your behaviour to check where is error in, thank you   
Or you can step by step do your flow and capture your screen to it here, thank you  
  
Thank you   
  
I'm sorry but we must be priority for verified people, the other guys please open new ticket, we will verify and serve you later, thank you

**Comment by harjono-flux** [comment] 2020-05-16 00:02
> You could also remove the following folder
> 
> ```
> - android/.gradle (hidden folder)
> - ios/.symplinks  (hidden folder)
> - ios/Pods/
> - build/
> ```
> 
> Then see the magic 🧘‍♀️

hola.... this works... thx very much

**Comment by harjono-flux** [comment] 2020-05-16 22:39
> You could also remove the following folder
> 
> ```
> - android/.gradle (hidden folder)
> - ios/.symplinks  (hidden folder)
> - ios/Pods/
> - build/
> ```
> 
> Then see the magic 🧘‍♀️

halo @minhcasi 

this solution is temporary. After 3-4 times running the program, the trouble is comeback

**Comment by iamar1k92** [comment] 2020-05-17 13:49
This is not the solution as well, it was just to tell how to decrease size of the project.

**Comment by harjono-flux** [comment] 2020-05-17 23:03
i'm miss understanding. ok i will try to send my full project

**Comment by harjono-flux** [comment] 2020-05-18 01:55
> I think this problem is not easy. Can you share me your whole project via my email : [khiem@inspireui.com](mailto:khiem@inspireui.com) or [vinhkhiemt135@gmail.com](mailto:vinhkhiemt135@gmail.com), I will check it for you, thank you

already send. plis help, thx

**Comment by Amitjeypore** [comment] 2020-05-18 07:38
Is this issue solved, why was it marked closed ??

**Comment by minhcasi** [comment] 2020-05-18 08:08
@Amitjeypore - it is closed as there is no updated from yours, please let us know your current issues status - thank you for your time

**Comment by Amitjeypore** [comment] 2020-05-18 08:15
The problem is still there, what I did was get rid of Sigin/signup from the onboarding screen because I had a tight delivery date. But every time the onboarding screen loads up like its the first time.

Please help, will update the app with it.

**Comment by minhcasi** [comment] 2020-05-18 08:52
@Amitjeypore - we will update the latest fix on Gitlab today, you could also try to compare with this file to check the onboarding 

[app_init.dart.txt](https://github.com/inspireui/support/files/4643078/app_init.dart.txt)

**Comment by iamar1k92** [comment] 2020-05-18 10:01
Well, Home Screen error due to headerview is still not solved, I cannot also open a duplicate ticket for this, but i have already sent the code to provided email. Please check and solution.

**Comment by harjono-flux** [comment] 2020-05-19 23:43
hello, any update for this issue? or i must make new ticket/posting?

**Comment by iamar1k92** [comment] 2020-05-20 14:24
Well this issue was fixed by: IsRequired = false.

Otherwise, if we go for IsRequired = true. then this error continues.

**Comment by minhcasi** [comment] 2020-05-21 03:32
@iamar1k92 - good point, we will try to reproduce it

**Comment by harjono-flux** [comment] 2020-05-21 03:56
> Well this issue was fixed by: IsRequired = false.
> 
> Otherwise, if we go for IsRequired = true. then this error continues.

sory, which page this query?

**Comment by Mcrahul555** [comment] 2020-05-21 09:29
> 
> 
> @iamar1k92 - good point, we will try to reproduce it

please find a solution am also facing the same problem 
![error layout](https://user-images.githubusercontent.com/65422936/82545013-12594b00-9b67-11ea-9b72-a28e561c249d.jpg)

**Comment by minhcasi** [comment] 2020-05-24 12:30
We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

We sincerely apologize for the delay and hope you’re staying safe.

@kvt0012

**Comment by iamar1k92** [comment] 2020-05-24 18:08
> > Well this issue was fixed by: IsRequired = false.
> > Otherwise, if we go for IsRequired = true. then this error continues.
> 
> sory, which page this query?

lib/common/config/general.dart
const kLoginSetting = {
  "IsRequiredLogin": false,
}

**Comment by minhcasi** [comment] 2020-05-25 03:52
@Amitjeypore - pls try to update this value to `false` to fix the issue - we also upgraded and fixed some minor issue the Require login feature on next release.

<img width="863" alt="Screen Shot 2020-05-25 at 10 50 29" src="https://user-images.githubusercontent.com/1459805/82776635-c283c800-9e75-11ea-94c1-25968a5e3cfd.png">

**Comment by Amitjeypore** [comment] 2020-05-25 05:29
> @Amitjeypore - pls try to update this value to `false` to fix the issue - we also upgraded and fixed some minor issue the Require login feature on next release.
> 
> <img alt="Screen Shot 2020-05-25 at 10 50 29" width="863" src="https://user-images.githubusercontent.com/1459805/82776635-c283c800-9e75-11ea-94c1-25968a5e3cfd.png">

Hello Yes this worked, thank you som much. I have a doubt even if I am signed in every time i reopen the app i get the onboarding screen, how do I change it to only one time.

**Comment by minhcasi** [comment] 2020-05-25 05:35
As per our investigation, it is caused by the slack of duration, pls try to update to +3s of duration on app_init.dart to fix the repeat onboarding issue.

<img width="987" alt="Screen Shot 2020-05-25 at 12 34 35" src="https://user-images.githubusercontent.com/1459805/82781480-185f6c80-9e84-11ea-9c45-de67d0d9fbb3.png">

Let us know your checking

**Comment by Amitjeypore** [comment] 2020-05-25 05:43
![Capture](https://user-images.githubusercontent.com/65069372/82781770-50f94900-9e78-11ea-9932-36f1cc5960c8.PNG)
Also not able to change the text colour of Signin Signup , cant use HEX values

![Capture1](https://user-images.githubusercontent.com/65069372/82781923-c1a06580-9e78-11ea-8389-6e582394b2f0.PNG)
Changed the value but the onboarding screen shows neverthless

**Comment by minhcasi** [comment] 2020-05-26 02:45
@Amitjeypore - we confirm to fix this issue completely on the latest code - we will share the latest source on Gitlab pre-1.7.5 on today - thank you!

**Comment by Amitjeypore** [comment] 2020-05-26 04:17
Please fix and update the following issues too:
-Onboarding Screen every time the app opens
-Onboarding Signin Signup Text not in primary colour
-Notification on/off doesn't save, every time app reopens it goes back to on

**Comment by minhcasi** [comment] 2020-05-28 13:22
@Amitjeypore - try to get the latest `pre-1.7.5` on gitlab to fix this issue - thank you!

**Comment by Amitjeypore** [comment] 2020-05-28 18:49
> @Amitjeypore - try to get the latest `pre-1.7.5` on gitlab to fix this issue - thank you!

Hi, Thank you for the update.
I am a newbie so if I want to update my existing app with your new one do I need to download this pack and make all the mods I had made to the earlier one or should I replace a few files.

**Comment by minhcasi** [comment] 2020-05-29 02:09
@Amitjeypore - please check this guide - https://www.youtube.com/watch?v=SWLHKx-xzn0

**Closed** 2020-05-30 13:11 UTC
Labels: 1.7.5, FluxStore
