### ISSUE TITLE
[List App] - Does not display chat option and booking not working

### ISSUE THREAD

**Issue by hungnguyen9276** [inspireui/support#1171] opened 2019-10-04 10:59 UTC
Hi,
I configed firebase by followed this https://docs.inspireui.com/listapp/firebase/. I logined however I see no chat option when I enter a listing. How can I fix it?
My purchase code: 2c21e8c4-d8cc-4226-aeba-68cd81289fe6
<img width="306" alt="Screen Shot 2019-10-04 at 17 53 07" src="https://user-images.githubusercontent.com/25025251/66202707-9fcb5600-e6d0-11e9-8703-f54e199f0d73.png">

**Comment by hungnguyen9276** [comment] 2019-10-06 01:52
One more thing, booking option not work. When I click on booking icon the message display "You can't book this product".
<img width="305" alt="Screen Shot 2019-10-06 at 08 51 52" src="https://user-images.githubusercontent.com/25025251/66263038-93e9ac00-e816-11e9-833a-39e6aaa22f49.png">

**Comment by codingastronaut** [comment] 2019-10-06 04:47
I also have the booking error, @hungnguyen9276 @minhcasi will tell you to enable "booking = true" but that dosent help at all, they should give a guide for people that have wc bookings and job manager.
please give us steps to follow

**Comment by hungnguyen9276** [comment] 2019-10-06 12:52
@codingastronaut Enable "booking = true" does not solve the problem. It still get an error.

**Comment by codingastronaut** [comment] 2019-10-06 21:55
@hungnguyen9276 @minhcasi this problem is also there for me as well, ive been trying to get an answer from them for the past 5 days and they have all gone silent

**Comment by codingastronaut** [comment] 2019-10-07 23:23
@hungnguyen9276 @minhcasi i finally fixed it, please add to your documentations, you have to purchase the wc bookings and job manager plugins, then create a bookable product and then lint that bookable product to the listing you created. but now i have a different issue, the app crashes when i try to fill the customer information forms to complete booking

**Comment by hungnguyen9276** [comment] 2019-10-08 02:48
@codingastronaut Could you give me link of that plugins? Thanks!

**Comment by sfoulad** [comment] 2019-10-08 14:26
@codingastronaut

I have same issue Any fixes for :

the app crashes when i try to fill the customer information forms to complete booking

**Comment by codingastronaut** [comment] 2019-10-08 15:18
@hungnguyen9276 , it's for sale at https://woocommerce.com/products/woocommerce-bookings/ for $250, I'm willing to sell to you for less, email me (johnmichaeldavis1992@gmail.com) i can also give you the job manager plugin. 
As for the error, I can't really help there, @minhcasi would have to help with that, but i think it has to do with the payment integration, just follow the documentation and make sure the payments work on your site

**Comment by minhcasi** [comment] 2019-10-09 11:59
@codingastronaut  - thank you for sharing, we will update document for this feature

**Comment by hungnguyen9276** [comment] 2019-10-09 12:59
@minhcasi how about chat option? How can I see it?

**Comment by hungnguyen9276** [comment] 2019-10-10 03:12
@codingastronaut "then create a bookable product and then lint that bookable product to the listing you created" I created bookable product however I don't know how to lint that bookable product to the listing. Could you please show me?

**Comment by hungnguyen9276** [comment] 2019-10-20 14:14
@thangvo9x Could you help me for chat option?

**Comment by minhcasi** [comment] 2019-11-03 02:37
Duplicate of #1191

**Closed by minhcasi** 2019-11-03 02:37 UTC
Labels: ListingApp, question ❓
