### ISSUE TITLE
[FluxStore Pro] Throws SocketException In some times

### ISSUE THREAD

**Issue by Sayandhkp** [inspireui/support#3435] opened 2020-05-27 10:26 UTC
Single Vendor FluxStore App- V1.7.3+3001

I am facing some issues in the api response in some times.  I have configured all required fields in admin and installed required wordpress plugins. Api is working fine in Postman in all cases, but in mobile app it throws following exceptions in some times.

**Exception Throwing**

SocketException: OS Error: Connection refused, errno=111, address = grocerystore.*****demo.com, port = 39490

We are not able to find the reason for this exception, Please support us to solve this issue.

**ScreenShot**

![Screenshot_20200525_202225](https://user-images.githubusercontent.com/28803144/83008271-877ac380-a032-11ea-9769-705b5ff241e2.jpg)

**Comment by philipvu30** [comment] 2020-05-28 02:30
Hi,

Got a few questions before solving your issues.
1. Are you testing the app in a local machine/host?
2. Is your internet connection good? As sometimes, this may be the cause.
3. Have you declared the Internet Permission in the Manifest.xml?
4. Have you replaced all our package name from com.inspireui.fluxstore.vendor to your package name "grocerystore.acubedemo.com" (Just giving example as I don't know if this is your correct package name or not)?

**Comment by Sayandhkp** [comment] 2020-05-28 12:36
> Hi,
> 
> Got a few questions before solving your issues.
> 
> 1. Are you testing the app in a local machine/host?
> 2. Is your internet connection good? As sometimes, this may be the cause.
> 3. Have you declared the Internet Permission in the Manifest.xml?
> 4. Have you replaced all our package name from com.inspireui.fluxstore.vendor to your package name "grocerystore.acubedemo.com" (Just giving example as I don't know if this is your correct package name or not)?

Hi, Please find the answers below.

1. Server
2. Yeah internet is stable
3. Yes declared permission
4. Yes

Actually it is working successfully in most of the conditions , but some cases it is not working.

**Comment by philipvu30** [comment] 2020-06-01 02:53
Hi,

I'm sorry I don't know how to replicate your issue. I have tried many ways but none of them cause the issue above. Would you mind giving some ideas when it will happen? Thank you.

**Comment by Sayandhkp** [comment] 2020-06-01 12:36
@philipvu30 I am not getting this issue right now. I don't know how to reproduce the issue. It happens some time if i try to close and restart app 3,4 times it will work. So I am not sure what is the actual cause.

**Comment by philipvu30** [comment] 2020-06-02 03:34
Hi,

I'll close this ticket as it cannot replicate. If you encounter this kind of issue in the future, feel free to ask us to re-open this ticket. 

Thank you for your patience.

**Closed by philipvu30** 2020-06-02 03:34 UTC
Labels: FluxStore, common-integration

**Comment by Sayandhkp** [comment] 2020-06-02 06:51
@philipvu30 @minhcasi  Please check [This Issue-3522](https://github.com/inspireui/support/issues/3522) . iOS build is not working with latest version also.
