### ISSUE TITLE
invalid VCS root mapping

### ISSUE THREAD

**Issue by ammadeyyy** [inspireui/support#4381] opened 2020-07-27 09:08 UTC
invalid VCS root mapping, in android studio
how to fix this issue?
![Capture](https://user-images.githubusercontent.com/62202402/88524394-b1d90500-d012-11ea-9286-8ee1c1e164b7.JPG)

**Comment by ameenbadri7** [comment] 2020-07-27 13:57
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by minhcasi** [comment] 2020-07-29 03:01
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-29 03:01 UTC
Labels: needs-more-info
