### ISSUE TITLE
Stock and Add to cart button issue in Product List ListTile layout

### ISSUE THREAD

**Issue by immortal-kid** [inspireui/support#3325] opened 2020-05-20 14:57 UTC
My purchase  http://prntscr.com/skfnr7

1. Stock Quantity Bug: If there stock quantity of a product is 2, customer should not be able to select more than two, but people are able to add more than stock quantity, (upto maxQuantity value) It can be ordered out of stock.  Please fix on this bug. 

2. In Product List screen, the word "Out of stock" is not shown. (Even if it is enabled in settings)

3. In Product List ListTile layout, for variable products, why is Add to cart button is shown? its like customers can add a product to cart without selecting any variation. In default woocommerce site "Select option" is shown for variable products, where select option takes to product detail screen. You could do the same thing here. If product type is variable, show "select options" where select options takes to product detail screen. 

4. Why is download button shown i order detail screen? that button does nothing. also showing cancel button and refund button is not necessary. its like customer can easily click on cancel button soon after order is placed, so this feature is misused.

5. Why is order notes are shown in order details screen? i mean its for store owner's reference right? it is showing everything that customer shouldn't know.

I made a lot of changes. You can implement to make your app even better.
(i don't want to tell here check ur mail with subject "some customization i did")

**Comment by minhcasi** [comment] 2020-05-21 03:42
@immortal-kid - thank you so much for the valuable feedback ⭐️. Could you help to resend the email to support@inspireui.com - it seems i have missed the detail

**Comment by magic-coding** [comment] 2020-05-21 14:43
I already report issue 1 with variable product before version 1.7.3, unfortunately this is still not fixed on FluxStore-woo 1.7.4 .

**Comment by minhcasi** [comment] 2020-05-22 02:52
@magic-coding - pls reopen your ticket if the issue is not soled 👍

**Comment by minhcasi** [comment] 2020-05-25 08:38
@immortal-kid - we have fixed your all feedbacks on next release (the download button from order detail could not be produced so that we could not fix this issue)

<img width="346" alt="Screen Shot 2020-05-25 at 15 34 24" src="https://user-images.githubusercontent.com/1459805/82794820-48673980-9e9d-11ea-8c91-bd65cd980d69.png">
<img width="351" alt="Screen Shot 2020-05-25 at 15 34 14" src="https://user-images.githubusercontent.com/1459805/82794825-48ffd000-9e9d-11ea-8123-8590443c42ac.png">
<img width="352" alt="Screen Shot 2020-05-25 at 15 38 03" src="https://user-images.githubusercontent.com/1459805/82795112-bb70b000-9e9d-11ea-80df-86892ae24adb.png">

**Closed by minhcasi** 2020-05-25 08:38 UTC
Labels: FluxStore, feature-request 🆕
