### ISSUE TITLE
[mstore RTL] -  RTL fixed but in new ver not

### ISSUE THREAD

**Issue by kiamoz** [inspireui/support#2090] opened 2020-02-14 10:36 UTC
Dear support , in this ver RTL went wrong ..
You fixed it with teamviwer in redux but I forget to save the files..
could you please re connect me today ?
just fix RTL  in redux .

**Comment by kiamoz** [comment] 2020-02-14 10:45
@luyx2412 Help me again  please

**Comment by inspireui-support** [comment] 2020-02-15 08:38
Duplicate of #2044

**Closed by inspireui-support** 2020-02-15 08:38 UTC
Labels: question ❓

**Comment by kiamoz** [comment] 2020-02-15 10:36
it's not duplicated ! , 2 other things ! RTL and fonts !
