### ISSUE TITLE
Fluxstore 1.7.5 give this issue

### ISSUE THREAD

**Issue by Alqumairi** [inspireui/support#3897] opened 2020-06-25 05:57 UTC
I have an issue with fluxstore 1.7.5 it gave me the error in the screenshot 

![Annotation 2020-06-25 135223](https://user-images.githubusercontent.com/37410069/85663381-9a44ee80-b6eb-11ea-914d-143e5f6b35a4.png)

**Comment by ameenbadri7** [comment] 2020-06-25 06:23
Thank you for the feedback.

Consider using a new fresh fluxstore update 1.7.5 

Or try to use this [gits](https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1).

And Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/

 - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by Alqumairi** [comment] 2020-06-25 06:40
it is 1.7.5 version

**Comment by Alqumairi** [comment] 2020-06-25 08:00
Hello

**Comment by ameenbadri7** [comment] 2020-06-25 13:21
could you try to fork our Gitlab repo and send the invitation to your own private repo to these email
` minhcasi@gmail.com` and `inspireui-team@inspireui.com`
 - we will help to check and apply the patching if there are new issues.

Also, help to check this guide https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6 - thank you!

**Comment by ameenbadri7** [comment] 2020-06-27 00:01
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by ameenbadri7** 2020-06-27 00:01 UTC
Labels: FluxStore
