### ISSUE TITLE
No autocomplete field address and shipping method not same like website

### ISSUE THREAD

**Issue by hakihosting** [inspireui/support#310] opened 2019-02-16 23:31 UTC
**Required Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the bug**

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

![image](https://user-images.githubusercontent.com/47614045/52906390-28cd7400-324b-11e9-94c0-bae57eb12d0e.png)

Shipping method: 
I have 2 method : Forfait 6€ or FREE ( but you must order for 70 €) why can i choice free here on this step. It must be not appear.

Autocomplete Info : 
I am logged , but the field is not autocomplete

**Comment by minhcasi** [comment] 2019-02-18 01:23
Duplicate of #301

**Closed by minhcasi** 2019-02-18 01:23 UTC
