### ISSUE TITLE
[Fluxstore 1.5] - Magento Cart: Two way sync issue

### ISSUE THREAD

**Issue by DrChrispoper** [inspireui/support#1117] opened 2019-09-26 10:20 UTC
1. My issue
I am using Fluxstore 1.5 with Magento.
I have seen an issue (or missing feature?).
If I have a cart with items on my account on Magento they are not shown on Fluxstore.
If I add items to my cart in Fluxstore they will be added to Magento cart when I start the checkout. 
If I remove my items from the Fluxstore cart they will not be removed in Magento.
If I checkout on Fluxtore I will pay for all the items that have been added and are on the Magento cart without knowing it.

I hope the explanation helps. If you need more info, I'll be happy to provide.
Thanks for the help.

**Comment by minhtruong315** [comment] 2019-10-01 10:38
@DrChrispoper if you add items in Fluxstore, it only save in local. so you will see it in Magento when you add items to cart or remove items.

**Comment by DrChrispoper** [comment] 2019-10-01 11:48
For a logged-in user.
The problem is that if you checkout on Fluxstore, you will be charged for items you can't see are in the Magento cart.

> @DrChrispoper if you add items in Fluxstore, it only save in local. so you will see it in Magento when you add items to cart or remove items.

They are initially only stored in local.
But when you start to checkout, they are added to the Magento cart.

Would it be possible to fetch the Magento cart items if the user is logged-in?

**Comment by minhcasi** [comment] 2019-10-01 13:00
@DrChrispoper pls try to create 1 ticket for your all issues instead of creating multi one, that will help us focus on your issues 

Duplicate of #1115

**Closed by minhcasi** 2019-10-01 13:00 UTC
Labels: question ❓
