### ISSUE TITLE
onboarding disable and product variable problem

### ISSUE THREAD

**Issue by effec-tline** [inspireui/support#3839] opened 2020-06-21 12:51 UTC
hey 
we use fluxstore pro last version

use it woocomerce last version
we face 2 isseus 
1 - we cant disable the onborading screen on first time use app
we use this code on general file like you descripe on documents  

"OnBoardOnlyShowFirstTime": false,
but also  onboarding not disabe

2 - we have problem on product variable problem

we have just 1 pcs size (XL) and another sized out of stock

on the app show all product variable and customer can choose this 1 pcs from any size
and can complete the order with item out of stock like this screen 

![1](https://user-images.githubusercontent.com/65735249/85224954-fcd97a00-b3cd-11ea-82fd-ec146981a1bb.png)

we use on the product type variable pruducts so we use colors with size so the stock numbers not syn with item many variables

Product & version: FluxStore 1.7.5
Flutter (or React Native) version: Flutter 1.17.3-stable
Testing Device/Simulator:  android studio last version / simulator nexus 6

Step 2: Please verify license and sharing config files by submitting on this google form, http://verify.inspireui.com,   (done )

**Comment by philipvu30** [comment] 2020-06-22 11:09
Hi,

1. In lib/common/config/onboarding.dart, set it like this
![image](https://user-images.githubusercontent.com/54442328/85280981-6e3f2880-b4b3-11ea-8037-96b39da0078b.png)

2. Make sure you have checked the Manage Stock option for each variable product.
![image](https://user-images.githubusercontent.com/54442328/85280957-62536680-b4b3-11ea-9dc4-d89e053c8caa.png)

**Comment by effec-tline** [comment] 2020-06-22 22:23
thanks onboarding issue solved

and about product variable  we sure checked the Manage Stock option for each variable product.  
and the problem still please tell me what do on this . thanks

**Comment by effec-tline** [comment] 2020-06-23 18:41
hey please need resolve to our problem not solved until now

**Comment by effec-tline** [comment] 2020-06-24 02:48
hey now 3 days still not provide resolve for our probem

**Comment by philipvu30** [comment] 2020-06-24 03:19
Hi,

What is the name of the item you referred to?

**Comment by effec-tline** [comment] 2020-06-24 03:33
you can check this item dress398

and also all product have variables same problem

![33](https://user-images.githubusercontent.com/67228253/85496191-37b0fd00-b5dc-11ea-97fb-e5ca6afab79f.png)

**Comment by philipvu30** [comment] 2020-06-24 03:38
Hi,

Please send me a support account of your website to my email: toan@inspireui.com

Thank you.

**Comment by effec-tline** [comment] 2020-06-24 03:41
ok

**Comment by philipvu30** [comment] 2020-06-24 07:17
Hi,

In the file lib/services/woo_commerce.dart, please remove this term.

Thank you.

![image](https://user-images.githubusercontent.com/54442328/85513543-51c2fd80-b625-11ea-956f-e7d5b18e2fa0.png)

**Comment by effec-tline** [comment] 2020-06-25 02:03
thanks dear this problem fixed and now options give me out of stock when click on it  but i suggest if we can frozen the option that out of stock so cant member click on it

i see another problem now if we have item have just 1 pcs from it if i add it to cart and close item page and return on it again can add another 1 pcs from same item so cart will be 2 pcs and etc can add any number  from this model  on my cart we can fix it?

**Comment by effec-tline** [comment] 2020-06-25 23:41
any reply please??

**Comment by minhcasi** [comment] 2020-06-27 05:47
Duplicate of #3940

**Closed by minhcasi** 2020-06-27 05:47 UTC
Labels: FluxStore, product-variant
