### ISSUE TITLE
Fluxstore Multi Vendor 

### ISSUE THREAD

**Issue by bangbiggy** [inspireui/support#2347] opened 2020-03-14 04:33 UTC
Hello guys am facing an issue when i run my app (Fluxstore MV) looks like every thing runs fine but i get an error saying

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building Consumer<AppModel>(dirty, dependencies: [_DefaultInheritedProviderScope<AppModel>]):
The method '[]' was called on null.
Receiver: null
Tried calling: []("Setting")

The relevant error-causing widget was: 
  Consumer<AppModel> file:///E:/multivendor/FluxStore/source/lib/app.dart:274:14
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      AppState.build.<anonymous closure> (package:fstore/app.dart:318:39)
#2      Consumer.buildWithChild (package:provider/src/consumer.dart:175:12)
#3      SingleChildStatelessWidget.build (package:nested/nested.dart:260:41)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4291:28)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
and on my device i get this message 
![Screenshot_20200312-144721](https://user-images.githubusercontent.com/60167322/76674790-1182c680-65c4-11ea-8b9a-4aa84be0ebcd.png)

help plz!!
proof of my purcharse
![Untitled](https://user-images.githubusercontent.com/60167322/76674985-15afe380-65c6-11ea-8721-63c9d51976bb.png)

**Comment by minhcasi** [comment] 2020-03-15 01:47
@bangbiggy - this is caused by missing config, pls help to share your common and config folder so that i could have a check - thank you!

**Comment by bangbiggy** [comment] 2020-03-19 03:21
> @bangbiggy - this is caused by missing config, pls help to share your common and config folder so that i could have a check - thank you!

hello sorry for late reply been crazy past few day in our country. nut here are the folders https://drive.google.com/open?id=1fBbPBWHZ2t13L7UUyodVEQACvp--gnxp

**Comment by minhcasi** [comment] 2020-03-19 04:37
@bangbiggy - pls help to show only the common and config folder, don't share the public source here 🙏

**Comment by kvt0012** [comment] 2020-03-20 04:45
You can send me your file on my email : khiem@inspireui.com 
or my personal email if it's priority : vinhkhiemt135@gmail.com 
thank you

**Comment by bangbiggy** [comment] 2020-03-23 07:56
i have sent the file on both your mail!

**Comment by kvt0012** [comment] 2020-03-23 10:27
> i have sent the file on both your mail!

dear sir, please confirm that your email is bang.bbent@gmail.com ?  Thank you

**Comment by bangbiggy** [comment] 2020-03-23 11:14
yes that is my email! thank you!

**Comment by kvt0012** [comment] 2020-03-24 03:12
I'm sorry sir, please check again because I can't see anything here 
![image](https://user-images.githubusercontent.com/49152325/77384424-ec5a3900-6db7-11ea-9f36-af8ef623528b.png)

Thank you

**Comment by bangbiggy** [comment] 2020-03-24 10:30
i have sent the mail again! plz find it in ur email!! thanks!

**Comment by minhcasi** [comment] 2020-03-26 04:02
@kvt0012 - please keep follow up the issue - thank you!

**Comment by bangbiggy** [comment] 2020-03-26 19:13
i am! thanks

**Comment by kvt0012** [comment] 2020-03-27 01:57
Ok, I'll receive and check it

**Comment by kvt0012** [comment] 2020-03-30 01:41
Sorry sir, because our app changes a alot from the last change, so we cannot run your config file. 
If it's convenient, please feel free to share your whole project file, it helps us check your problem quicker. 
With the whole project, you can send me via my company email : khiem@inspireui.com and announce me that you send me here, I will check and help you 
Thanks for your enthusiastic.

**Comment by bangbiggy** [comment] 2020-04-01 03:39
hello, thanks but i was able to fix this after i uncomment the "Our Blog Post" code in the config_en.json file. i ddint want the blog but seems i will have to go with it.
thanks.

**Comment by kvt0012** [comment] 2020-04-01 06:49
I;m very glad when I here that, sir. 
If you have any issue, please raise again, I will close this ticket, thank you

**Closed by kvt0012** 2020-04-01 06:49 UTC
Labels: Fluxstore-MV

**Comment by kenngigz** [comment] 2020-04-22 16:38
Having the same issue , its working when i comment  the blog part , but i really need the blog
