### ISSUE TITLE
Magento Mstore extension installation error

### ISSUE THREAD

**Issue by sarzali07** [inspireui/support#4744] opened 2020-08-26 10:59 UTC
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
After uploading extension file to app/code then run upgrade and cache flush I receive an error on both frontend and backend
"An error has happened during application run. See exception log for details."

**Comment by minhcasi** [comment] 2020-08-27 01:57
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-08-28 04:24
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-08-28 04:24 UTC
Labels: needs-more-info
