### ISSUE TITLE
OneSignal Push Notifications (Apns Delegate Never Fired)

### ISSUE THREAD

**Issue by vuln3r** [inspireui/support#4525] opened 2020-08-08 12:49 UTC
**_Step 1 (require): describe detail issues & screenshots_**
I'm trying to get one signal push notifications on iOS work but till now I didn't manage it.
On start, I'm getting prompt to enable push notifications and I can see myself registered but there is an error:
![image](https://user-images.githubusercontent.com/13506241/89710660-4a617480-d985-11ea-9449-07a0105dbfd9.png)

I also tried to update pods and pubspecs to the latest version but didn't help :(

In-App messages are working fine I have problems just with Push Notifications... On Android, I didn't try yet.

+ Product & version: Fluxstore WooCommrece 1.7.4
+ Flutter (or React Native) version: 1.22.0
+ Testing Device/Simulator: Real Device iPhone XS (13.6)
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
![image](https://user-images.githubusercontent.com/13506241/89710740-ed19f300-d985-11ea-8e74-a2123de6caef.png)

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment] 2020-08-09 02:14
@vuln3r - could you help to check latest code `1.7.6` - there is a fix the push notification (pls check the app.dart file) - thank you!

**Comment by vuln3r** [comment] 2020-08-09 04:32
Roger that, but is there any way to get only changed files to update the project? I'm struggling now to update it on 1.7.6 and not to lose my configuration and all that stuff?

**Comment by vuln3r** [comment] 2020-08-09 07:55
I've updated to the 1.7.6 but in the dashboard, I'm still getting APNs Delegate is never fired...

**Comment by minhcasi** [comment] 2020-08-10 04:38
Duplicate of #4542

**Comment by minhcasi** [comment] 2020-08-10 04:38
@vuln3r - pls help to keep on open ticket for your all issues, thank you for your time

**Closed by minhcasi** 2020-08-10 04:38 UTC
Labels: FluxStore
