### ISSUE TITLE
Delivery

### ISSUE THREAD

**Issue by MorisTech** [inspireui/support#4128] opened 2020-07-08 19:13 UTC
Here is my issue that was closed
https://github.com/inspireui/support/issues/3876

Capture
I'm getting this error when I try uploading to google play

And also a language error

How do I fix it

**Comment by MorisTech** [comment] 2020-07-08 19:13
![86957011-fa0eb100-c151-11ea-8f7c-cb8d564850fb](https://user-images.githubusercontent.com/31305956/86960482-7b1c7700-c157-11ea-9508-d9ad3cb237c3.png)

**Comment by minhcasi** [comment] 2020-07-09 02:45
@MorisTech - pls try to edit the `AndroidManifest.xml` to support that permission

Ref:
https://stackoverflow.com/questions/41234205/warnings-your-apk-is-using-permissions-that-require-a-privacy-policy-android-p

**Comment by MorisTech** [comment] 2020-07-10 20:10
I also have this error

FAILURE: Build failed with an exception.



* Where:

Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 962



* What went wrong:

Could not determine the dependencies of task ':app:compileFlutterBuildRelease'.

> 1



* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.



* Get more help at https://help.gradle.org



BUILD FAILED in 1m 20s
Running Gradle task 'bundleRelease'...                             81.9s
Gradle task bundleRelease failed with exit code 1

**Comment by minhcasi** [comment] 2020-07-11 12:16
@MorisTech - always try to clean the cache with `flutter clean` - more refer https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by MorisTech** [comment] 2020-07-11 19:14
Okay, it worked, but I can't install the app on some android devices

**Comment by minhcasi** [comment] 2020-07-14 04:21
could you share the detail log when building on the real device?

You could check to see if you could run the default Test Drive on devices as well? - https://flutter.dev/docs/get-started/test-drive?tab=vscode

**Comment by MorisTech** [comment] 2020-07-14 10:23
I fixed it, they can install through the bundle uploaded 


My users get this error when they try to signup

Please attend to this 
![CA8D480F-0F9F-46DA-AFE9-0DDCB3ECB0DC](https://user-images.githubusercontent.com/31305956/87414947-65c6a300-c5c4-11ea-8703-762b0654f813.jpeg)

**Comment by minhcasi** [comment] 2020-07-15 03:54
@MorisTech - we could not reproduce this issue, could i check if you are using the latest release - thank you!

**Comment by MorisTech** [comment] 2020-07-15 08:03
Yes, I am using the Latest release 1.7.5, what's the error, I need to fix this ASAP

**Comment by minhcasi** [comment] 2020-07-16 03:21
@MorisTech - did you config the enable all the plugins as this guide - https://docs.inspireui.com/fluxstore/multi-vendor/ 

Please also try our pre-config site as well

**Comment by MorisTech** [comment] 2020-07-16 06:40
Yes I did 
I enabled all the plugins

**Comment by MorisTech** [comment] 2020-07-16 07:42
Once I try to register, it throws that error, but if I try to click register again, it says User already exists

So I login with the username and pass I tried to signup with and I successfully login

What's the problem??

**Comment by MorisTech** [comment] 2020-07-16 08:55
Your Mstore Api doesn't work again

**Comment by MorisTech** [comment] 2020-07-16 19:54
@philipvu30

I get errors on my signup page in thr Fluxstore MV 
Can you help me?

**Comment by minhcasi** [comment] 2020-07-17 09:44
@MorisTech - could you try the pre-config site here - https://docs.inspireui.com/fluxstore/multi-vendor/#1-website-integration - we have set up this site with all the config that help you install more easily - thanks

**Comment by philipvu30** [comment] 2020-07-17 10:49
Hi,

Please update the MStore API plugin to the latest version. It should fix your issue.

Thank you.

**Comment by MorisTech** [comment] 2020-07-17 20:18
> Hi,
> 
> Please update the MStore API plugin to the latest version. It should fix your issue.
> 
> Thank you.

Thank you for your reply
I've updated the mstore api, still not working

I mistakenly deactivated the jwt plugin because register page wasn't working, so I activated it back and now mstore api doesn't work

**Comment by MorisTech** [comment] 2020-07-17 20:29
> @MorisTech - could you try the pre-config site here - https://docs.inspireui.com/fluxstore/multi-vendor/#1-website-integration - we have set up this site with all the config that help you install more easily - thanks
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/c1f5c35bdee2cf5a71b0e35ef38becdf8ec89d72/68747470733a2f2f646f63732e696e737069726575692e636f6d2f696d616765732f6d6574612f47686f73742d446f63732e6a7067">InspireUI Document**[FluxStore - Universal mobile commerce Flutter app for Magento, WooCommerce and Opencart](https://docs.inspireui.com/fluxstore/multi-vendor/)**Fluxstore is universal app that fully integration with the Woocommerce, Mangeto and Opencart

Done this, my products are not still showing, obviously the Mstore Api

**Comment by MorisTech** [comment] 2020-07-18 19:25
@minhcasi @philipvu30 @minhtruong315 

Please who is helping me, I've seriously being troubled

**Comment by philipvu30** [comment] 2020-07-20 03:01
Hi,

My apologies for the delayed response and the confusion you are facing.
Please install the required plugins in this [guide](https://docs.inspireui.com/fluxstore/multi-vendor/) only except Dokan and Options Importer. We've already updated the guide and it is no longer require jwt plugin.
Please give it a check as it seems you are referring to our old guide.

Thank you.

**Comment by MorisTech** [comment] 2020-07-20 07:12
I have installed all the plugins apart from Dokan and Options Importer
It still doesn't show the products in my app

**Comment by philipvu30** [comment] 2020-07-20 07:19
Hi,

I thought you were referring to the registration error. 
About the "products not display" issue, please check if the products are assigned to any stores. 
You can replace this file 
[woo_commerce.dart.zip](https://github.com/inspireui/support/files/4946105/woo_commerce.dart.zip) in lib/services/woo_commerce.dart or pull the latest version release pre-1.7.6 from our GitLab repository. 

Thank you.

**Comment by MorisTech** [comment] 2020-07-20 07:21
Thanks for your response..
I have 2 errors


No products display and Reg error

How do I update my Fluxstore from Gitlab?

**Comment by MorisTech** [comment] 2020-07-20 07:22
I just even testes the app on my phone, The reg still doesn't work

**Comment by MorisTech** [comment] 2020-07-20 20:51
@minhcasi @minhtruong315 @philipvu30 
please help, I have a deadline

**Comment by minhcasi** [comment] 2020-07-21 03:07
@MorisTech - you could try this link to update the latest source - https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6 - thank you!

**Comment by MorisTech** [comment] 2020-07-21 06:58
I've gotten the latest release, but my products still doesn't show on the app and I'm still getting the error on Signup page

**Comment by philipvu30** [comment] 2020-07-21 07:12
Hi,

Send me your config.dart and config_en.json to my email: toan@inspireui.com and make sure you've already updated the MStore API plugin to version 2.7.3.

**Comment by MorisTech** [comment] 2020-07-21 07:41
Alright
Thanks man @philipvu30

**Comment by MorisTech** [comment] 2020-07-21 07:47
I've updated the plugin and sent my files to your mail

**Comment by philipvu30** [comment] 2020-07-21 08:26
Hi,

I've sent the latest project that is able to log in and shows the products.
Please have a check.

**Comment by MorisTech** [comment] 2020-07-21 08:27
Okay
Thank you

let me check

**Comment by MorisTech** [comment] 2020-07-21 09:06
@philipvu30 
When I try running flutter build apk --split-per-abi

I was asked to input Gitlab credentials

**Comment by philipvu30** [comment] 2020-07-21 09:12
Delete this file then

![image](https://user-images.githubusercontent.com/54442328/88035922-055bd680-cb6d-11ea-85fb-89e3278d1158.png)

**Comment by MorisTech** [comment] 2020-07-21 09:47
thanks

**Comment by MorisTech** [comment] 2020-07-21 10:25
@philipvu30 
It works but still doesn’t display the products on the homepage 

![B93958D8-B926-4859-B6D4-18B5BEDECE4D](https://user-images.githubusercontent.com/31305956/88043018-c6b22600-cb44-11ea-9ddc-380f99f93b7e.jpeg)

It’s not showing the products on the homepage

**Comment by MorisTech** [comment] 2020-07-21 10:26
Or wait, let confirm if the categories that are meant to be on the homepage exists

**Comment by MorisTech** [comment] 2020-07-21 10:27
And also, @philipvu30 
The files you sent to me are the latest right

You know I had issues with the signup page on the app

**Comment by MorisTech** [comment] 2020-07-21 22:43
All products work fine and everything works fine now
except the registration page...

Still the same error

@minhcasi  @philipvu30

**Comment by philipvu30** [comment] 2020-07-22 03:14
Hi,

Can you redo steps 3 and 4 in this [guide](https://medium.com/@inspireui/setup-google-login-for-flutter-apps-fedc58a490b8)? Also, can I have a screenshot of MStore Plugin version on your website?

Thank you.

**Comment by MorisTech** [comment] 2020-07-22 18:45
@philipvu30 
Alright, I'll try,
Here is the screenshot
![mstoreapi](https://user-images.githubusercontent.com/31305956/88215621-db311400-cc53-11ea-9e7c-653c579edf76.PNG)

Also my categories page doesn't show all the categories

**Comment by MorisTech** [comment] 2020-07-23 00:24
@philipvu30 @minhtruong315 @minhcasi 
Products show now

Only the reg doesn't show

**Comment by philipvu30** [comment] 2020-07-23 04:35
Hi,

I have no idea why you're getting this error as I checked your config files with our firebase settings and it went well.
Did you apply the new google settings in the [guide](https://medium.com/@inspireui/setup-google-login-for-flutter-apps-fedc58a490b8) I mentioned?

**Comment by MorisTech** [comment] 2020-07-23 09:29
@philipvu30 
I'll try that now and give an update

**Comment by MorisTech** [comment] 2020-07-23 19:25
@philipvu30 

Done, still did not work

**Comment by philipvu30** [comment] 2020-07-24 03:53
Hi,

As I tested your site, after registration, the generated cookie is still invalid until 5 minutes later. That's why you get the error above because the app cannot get the user info from that cookie.
I suggest you should re-add the MStore API plugin(completely delete it and add it via plugin search). After that, deactivate all the plugins except Woocommerce, WCFM Plugins, and MStore API.

**Comment by MorisTech** [comment] 2020-07-24 07:52
@philipvu30 
Okay, I’ll do that 
So after deactivating all the plugins but leaving WCFM and Mstore 

I’ll try again
If it works, I’ll activate the remaining plugins back

**Comment by MorisTech** [comment] 2020-07-24 08:27
Hoooorrrayyyy!!!

@philipvu30 it worked

Am i to activate all plugins back?

**Comment by MorisTech** [comment] 2020-07-24 08:35
But it appears a plugin is causing it not to work...

**Comment by MorisTech** [comment] 2020-07-24 08:53
@philipvu30 

W3 Total Cache was causing it not to work..

**Comment by MorisTech** [comment] 2020-07-24 08:59
@philipvu30 @minhcasi 
Thanks for the help on Android
i'll prolly open another ticket for IOS
i'm jumping to IOS now lol

Thanks

**Comment by philipvu30** [comment] 2020-07-24 09:47
I'm glad I was able to help

If you are happy with our services/support, would you mind rating us on your [download page](https://codecanyon.net/downloads)?
We truly appreciate your help.

**Closed** 2020-07-24 12:52 UTC
Labels: FluxstoreMV, config-site
