### ISSUE TITLE
mstore-expo TypeError: categories.forEach is not a function.

### ISSUE THREAD

**Issue by jaime-hub** [inspireui/support#4038] opened 2020-07-03 10:41 UTC
Hi. I'm trying to launch the application connected to my WordPress (I've used the WordPress that you provide in the manual) but I can't get it to work. It throws me the error that I have put in the title.

I need help to solve this, it's very urgent.

Regards.

![mstore-expo-error](https://user-images.githubusercontent.com/56959929/86461552-72c4d600-bd2a-11ea-9578-496b0459416c.PNG)

**Comment by minhcasi** [comment] 2020-07-03 11:49
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by jaime-hub** [comment] 2020-07-03 12:13
The config folder doesn't exist in the mstore-expo template. What files should I upload?

**Comment by luyx2412** [comment] 2020-07-05 04:06
Hi @jaime-hub Please read the document to setup your website. https://docs.inspireui.com/mstore/getting-started/. Please follow the screenshot, this is the config folder.
![image](https://user-images.githubusercontent.com/8909619/86525295-7e8dd500-beaf-11ea-84fc-3b857f6e4b41.png)

Thanks

**Comment by jaime-hub** [comment] 2020-07-06 07:06
Hi @luyx2412, I've configured my WordPress following the steps in the documentation.

I already submitted the form with the common folder attached.

I'm waiting for a response.

Thanks for the help.

**Comment by luyx2412** [comment] 2020-07-06 14:24
Hi @jaime-hub Please upgrade latest version Mstore 4.0. I just tested and everything worked normal. So please test again and give me the specific issue.
![image](https://user-images.githubusercontent.com/8909619/86604043-0d454380-bfcf-11ea-8f63-b4f1df25abd0.png)
![image](https://user-images.githubusercontent.com/8909619/86604044-0e767080-bfcf-11ea-9067-a5f5bf5a80a8.png)

Thanks

**Comment by jaime-hub** [comment] 2020-07-06 15:05
Thanks luyx2412. What steps have you followed in the template? What I do is just put the URL of my WordPress and the Woo keys in the file.

Do I have to change something else?

If it has worked for you, I understand that WordPress is well configured, right?

**Comment by jaime-hub** [comment] 2020-07-08 14:30
Hi, I'm still waiting for help.

Thanks.

**Comment by luyx2412** [comment] 2020-07-08 14:32
Hi @jaime-hub Please upgrade Mstore 4.0, and i dont change any config. I used your config and sceenshot for you. And can you give me the specific issue?

Thanks

**Comment by jaime-hub** [comment] 2020-07-08 15:06
This is what I do, step by step:

First, I configure the Config.js file with my consumerKey, consumerSecret and url.

Then I open mstore-expo in cmd and run yarn install.

![1](https://user-images.githubusercontent.com/56959929/86933936-68944480-c13b-11ea-8017-4becfe2d3713.PNG)

After that I run yarn start, and in Metro Bundler I choose the option "Run on Android device / emulator" and the app starts.

![2](https://user-images.githubusercontent.com/56959929/86934581-291a2800-c13c-11ea-82be-9a78f97e2e4c.PNG)


![3](https://user-images.githubusercontent.com/56959929/86934586-2b7c8200-c13c-11ea-9e1e-6764c04029d1.PNG)


The video with the application running and the error:

[https://anonfiles.com/T4I8NdE7o7/video_mp4](url)

**Comment by jaime-hub** [comment] 2020-07-09 13:48
Hi @luyx2412, could you tell me how you have configured your development environment? Your version of Node, your version of React, Expo, Yarn, ... 

These are the versions that I use: Node (v10.21.0), Expo (3.22.0), react-native-cli: 2.0.1, yarn (1.22.4).

What tool do you use to debug the project? Reactotron?

Regards.

**Comment by luyx2412** [comment] 2020-07-09 15:48
Hi @jaime-hub This is my config which same your config. And the debug tool is Reactotron. Can you try with React native original without the expo?

![image](https://user-images.githubusercontent.com/8909619/87061069-7cbc6c80-c235-11ea-8636-f8d970e0f388.png)

Thanks

**Comment by jaime-hub** [comment] 2020-07-09 15:59
Hi @luyx2412, I've already tried to run the application with React native original, and exactly but the same thing happens.

I've tried to run the app from another computer and it doesn't work.

What can I do? I'm desperate... 

Thanks.

**Comment by jaime-hub** [comment] 2020-07-10 12:39
If it doesn't work, how can I request a refund?

I've tried all the options and none works.

What OS do you use to launch the application?

**Comment by jaime-hub** [comment] 2020-07-13 11:53
Hi @luyx2412, I still need help.

**Comment by luyx2412** [comment] 2020-07-13 14:14
Hi @jaime-hub I am running Mac OS. you can download https://github.com/infinitered/reactotron in there. The project integrated Reactotron, you can change the config in `src/common/Constants.js` line 13. And can you take screenshot your issue?
![image](https://user-images.githubusercontent.com/8909619/87314674-c961b980-c54d-11ea-86ec-1b9816a6534a.png)

Thanks

**Comment by jaime-hub** [comment] 2020-07-13 14:29
Hi @luyx2412 , in the videos you can see the errors.

The video with the application running and the error:

https://anonfiles.com/T4I8NdE7o7/video_mp4

Other error, when I click on Card, List View, Two Column, ...:

https://anonfiles.com/Jc10OaE6o4/t_video5778252711443040236_mp4

Copy and paste the url. If you click on the url, it doesn't work.

**Comment by luyx2412** [comment] 2020-07-13 14:57
Hi @jaime-hub Please send full source code project via inspireui.team@gmail.com . let me investigate and fix it, after that resend you soon.

Thanks

**Comment by jaime-hub** [comment] 2020-07-13 15:44
Done ^^

Thanks @luyx2412

**Comment by jaime-hub** [comment] 2020-07-14 13:12
Hi @luyx2412, I've connected the app with Reactotron, and when a request is made to my Woocommerce, it returns status code 0... What could be wrong?

![Captura](https://user-images.githubusercontent.com/56959929/87429682-6c651280-c5e4-11ea-941f-bb59a0187176.PNG)

In your screenshot it works fine, the request returns the code 200.

**Comment by jaime-hub** [comment] 2020-07-15 13:26
Hi, do you know something about status code 0?

Regards.

**Comment by jaime-hub** [comment] 2020-07-16 13:52
Hi @luyx2412, I've uninstalled my WordPress because I think the problem is in the WordPress that you provide. I've installed a clean one, but now I can't activate the Mstore API plugin. 

When I try to activate the plugin, I get a message that says: "Your code is being used by ..."

Regards.

**Comment by luyx2412** [comment] 2020-07-18 07:47
Hi @jaime-hub please access email inspireui.team@gmail.com

Thanks

**Comment by minhcasi** [comment] 2020-07-25 06:44
@jaime-hub - could you give an update pls - thank you!

**Comment by jaime-hub** [comment] 2020-07-27 07:03
Hi @minhcasi. At the moment we are working on http. Today we are going to install the https certificate again and try to work on https and see if it continues to give us problems.

I sent you the project by mail, but I have not received a reply.

Regards.

**Comment by jaime-hub** [comment] 2020-07-27 08:53
Hi again @minhcasi, 

Using http everything works fine, but when I try to use https this happens:

![image](https://user-images.githubusercontent.com/56959929/88522938-6ebd6880-cff7-11ea-91fd-0223891819df.png)

**Comment by luyx2412** [comment] 2020-07-28 14:06
Hi @jaime-hub Can you give me the hosting information? for example the service which used for your website.

Thanks

**Comment by jaime-hub** [comment] 2020-07-29 07:09
Hi @luyx2412, 

It was a problem with the certificate, it's already solved.

One last question before closing the ticket. Does verticalLayout work? It doesn't work for me.

Regards.

**Comment by minhcasi** [comment] 2020-07-31 07:15
@jaime-hub - please try to check some of our json examples (from the project folder) from that has an example for the verticalLayout config.

It will work fine after user login, please make sure to keep your previous consumerKey and consumerSecret on the Woocommerce side, otherwise they need to login again

**Comment by jaime-hub** [comment] 2020-07-31 07:43
Hi, @minhcasi vertical layouts don't work for me.


In my WordPress I have different roles, and depending on the role, different prices. I want that when a user with role "X" connects, the passwords for users with role "X" are used. And when a user with the role "Y" connects, the keys for users with the role "Y" are used. Those keys I have already saved in Constants.js, what I want is that when the user logs in, the value of consumerKey and consumerSecret changes depending on the role of the user who is logged in.

Regards.

**Comment by luyx2412** [comment] 2020-08-01 07:03
Hi @jaime-hub You meant the cache AppConfig.json file? Because we are using redux-persist to cache local config. So please uninstall and reinstall again. In `src/components/HorizonList/HList.js` line 156 please change this line with `const { VerticalLayout } = AppConfig;` to fix the issue. We will improve in next version.

Thanks

**Comment by jaime-hub** [comment] 2020-08-03 07:28
> Hi @jaime-hub You meant the cache AppConfig.json file? Because we are using redux-persist to cache local config. So please uninstall and reinstall again. In `src/components/HorizonList/HList.js` line 156 please change this line with `const { VerticalLayout } = AppConfig;` to fix the issue. We will improve in next version.
> 
> Thanks

Line 156 change doesn't work.

error: SyntaxError: mstore-pro\src\components\HorizonList\HList.js: Identifier 'VerticalLayout' has already been declared (156:12)

On line 150 there is already this: const VerticalLayout = get(layouts, "VerticalLayout");

I'm using Mstore 4.0.

**Comment by luyx2412** [comment] 2020-08-05 13:42
Hi @jaime-hub Please import AppConfig like the screenshot to declare `VerticalLayout `

Thanks

**Comment by jaime-hub** [comment] 2020-08-06 08:28
Okay, now it works, thanks!

A question, when the user logs in, I save with MMKV (something similar to AsyncStorage) their role, and I want that when the user starts the app again, the user role is verified (this I have done), and depending on the role , the consumerKey and consumerSecret are changed.

I have this, to see if you can help me, I have tried to do it myself so as not to disturb, but I have not succeeded, I would appreciate some help.

In \src\containers\Login\index.js I save the role after login:

![SaveRole](https://user-images.githubusercontent.com/56959929/89508748-9f0ebf00-d7ce-11ea-8489-b934bf88e17c.PNG)

Then in Config.js I retrieve the role, and there I change consumerKey and consumerSecret depending on the recovered role:

![Config](https://user-images.githubusercontent.com/56959929/89509071-1d6b6100-d7cf-11ea-9b47-250d6bcce573.PNG)

But the export takes consumerKey and consumerSecret without changing. I know it is because the role recovery is asynchronous, and when it finishes running the export has already been run before. But I don't know how to fix it, any ideas?

I would greatly appreciate any help or ideas. Regards.

Thanks for everything, Luyx.

**Comment by luyx2412** [comment] 2020-08-08 08:06
Hi @jaime-hub You meant the Consumer Key and Secret depend on the user login?  but It can not because the login depend on Consumer Key and Secret.

Thanks

**Comment by jaime-hub** [comment] 2020-08-10 07:08
> Hi @jaime-hub You meant the Consumer Key and Secret depend on the user login? but It can not because the login depend on Consumer Key and Secret.
> 
> Thanks

Hi @luyx2412, yes, I mean that. For example, I have two Keys.

- Login with keys 1.

- After logging in, I switch to keys 2.

Is it possible to do that?

**Comment by luyx2412** [comment] 2020-08-11 14:02
Hi @jaime-hub You can do it, but both keys must valid. You can test it with the postman or something like it.

Thanks

**Comment by jaime-hub** [comment] 2020-08-13 09:52
Hi @luyx2412, that's done! Thank you!

Another question, how can I add webhooks to app actions? I need that when an action is performed in the application (for example, when adding an item to the cart), a webhook is started.

I need the actions that a user performs in the application to be reported to another server.

The problem is that we are adding several webhooks, but at the moment we are only receiving one (cancel an order).

Regards.

**Comment by minhcasi** [comment] 2020-08-14 04:09
@jaime-hub - could you share the detail WebHook function to that we could reproduce on our side, it seems an interesting feature, please share private to inspireui.team@gmail.com - thank you!

**Comment by minhcasi** [comment] 2020-08-19 04:22
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-08-19 04:22 UTC
Labels: MStorePro
