### ISSUE TITLE
Flux News .IPA file size are too big about 200mb

### ISSUE THREAD

**Issue by zemeister2332** [inspireui/support#2739] opened 2020-04-16 08:34 UTC
My .ipa file are too big size about 200mb. how can i small this size about 30-40mb

**Comment by minhcasi** [comment] 2020-04-16 11:00
Hi, we don't have good solution so far - the apk from Android is much smaller (under 20mb), but i'm not why it is quite high on iOS - please try to remove some Firebase library if you don't use these kinds of the library. 

We have the blogs to share about this optimize on Android  https://medium.com/@inspireui/how-to-build-flutter-instant-app-with-fluxstore-7d14c4630ae6

**Comment by zemeister2332** [comment] 2020-04-16 20:44
> Hi, we don't have good solution so far - the apk from Android is much smaller (under 20mb), but i'm not why it is quite high on iOS - please try to remove some Firebase library if you don't use these kinds of the library.
> 
> We have the blogs to share about this optimize on Android https://medium.com/@inspireui/how-to-build-flutter-instant-app-with-fluxstore-7d14c4630ae6
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/42723cbbfddf05782da1bea1fecfacf052a310cc/68747470733a2f2f6d69726f2e6d656469756d2e636f6d2f6d61782f313230302f312a536b2d695565494f5770476d4f3533797130413553772e6a706567"><img alt="" height="14" src="https://camo.githubusercontent.com/a1c598ee8610a8cdb0e8bdbf112f3f1c77af25cb/68747470733a2f2f63646e2d7374617469632d312e6d656469756d2e636f6d2f5f2f66702f69636f6e732f66617669636f6e2d72656272616e642d6d656469756d2e33593678705a2d3046536457446e504d3368534249412e69636f"> Medium**[How to build Flutter Instant App with FluxStore](https://medium.com/@inspireui/how-to-build-flutter-instant-app-with-fluxstore-7d14c4630ae6)**Imagine how great it would be if you could try out Flutter apps without even installing them. Yes, you can make it with the awesome…

I release my app and get some problem can u help me? I recorded my video. here is link
https://vimeo.com/408607299

**Comment by minhcasi** [comment] 2020-04-19 08:07
Duplicate of #2775

**Closed by minhcasi** 2020-04-19 08:07 UTC
Labels: FluxNews
