### ISSUE TITLE
Error in the lib/main.dart debug mode

### ISSUE THREAD

**Issue by guilhermezm** [inspireui/support#4641] opened 2020-08-18 05:38 UTC
Hi everyone! I was making the flutter basic installation on windows and in the 23:00 minutes of the video where he do the debug mod, but my console said it: ![image](https://user-images.githubusercontent.com/63873843/90474529-d9942800-e0fb-11ea-8883-b99e74caf414.jpeg)
What is this error? How can I fix it? Thanks!

**Comment by minhcasi** [comment] 2020-08-18 06:57
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-08-19 03:39
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-08-19 03:39 UTC
Labels: needs-more-info
