### ISSUE TITLE
Showing "No Products" when i reopen particular category

### ISSUE THREAD

**Issue by akhiltrivedi** [inspireui/support#4504] opened 2020-08-07 07:52 UTC
Hello I purchased flux store Shopify app, connected my store with app and it seems to be connected as I can see list of products under different categories as my store, but I noticed one issue like when I click on particular category for eg: flavours, it will show me a list of products in it, but once I come back on the home screen and click on that category again it will show me "No Products". I am attaching video link I have recorded my screen for it. 

https://drive.google.com/file/d/1d-2N1DKUCV-Ias012FxUlS5auDiT5pJk/view?usp=sharing

**Comment by ameenbadri7** [comment] 2020-08-08 01:15
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by minhcasi** [comment] 2020-08-09 02:59
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-08-09 02:59 UTC
Labels: needs-more-info
