### ISSUE TITLE
Error when logging in with a phone number or a Google account

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#4358] opened 2020-07-25 08:10 UTC
Fluxstore Version: 1.7.6
Flutter : v1.17.5
test on emulator and Samsung device

Error when logging in with a phone number or a Google account
![555](https://user-images.githubusercontent.com/54249914/88452425-3dae2e00-ce67-11ea-9d76-65efc67385f3.PNG)

**Comment by ameenbadri7** [comment] 2020-07-25 14:49
Hello sir.

You should get the key that is connected to your app build.
Maybe it's one of the keys inside your app folder or the default keys of your android debug keys.
So please double-check this [ticket ](https://github.com/inspireui/support/issues/4240#issuecomment-660312902).
And also our main [ticket ](https://github.com/inspireui/support/issues/4251).
and this to check your settings on the [firebase](https://github.com/inspireui/support/issues/4251).

Thank you.

**Comment by haidarsalim** [comment] 2020-07-26 11:41
@ameenbadri7  شكرا لك صديقي

**Comment by ameenbadri7** [comment] 2020-07-26 15:37
you are welcome, my friend. العفو صديقي

**Comment by ameenbadri7** [comment] 2020-07-26 15:37
I'm sorry to close this ticket 

Please help to create a new one and link it to this ticket if the problem is not solved.

thank you for your time ❤️

**Closed by ameenbadri7** 2020-07-26 15:37 UTC
Labels: FluxStore
