### ISSUE TITLE
Issue when login

### ISSUE THREAD

**Issue by GNAG1993** [inspireui/support#4488] opened 2020-08-06 10:30 UTC
now the issue is, when login through mobile number, email is being created like: Countrycode-mobilenumber@websitedomain. Ex.:91xxxxxxxxxx@xxxx.com
For proof I have submitted earlier ticket https://github.com/inspireui/support/issues/4469

**Comment by minhcasi** [comment] 2020-08-07 01:03
Duplicate of #4469 - pls give your all comment to that ticket

**Closed by minhcasi** 2020-08-07 01:03 UTC
