### ISSUE TITLE
[Fluxstore WooCommerce 1.7.5] Cannot get Product images to load in app

### ISSUE THREAD

**Issue by kobylogan** [inspireui/support#3620] opened 2020-06-06 04:57 UTC
I am unable to get product images from my website to display in the app. (See Screenshots below)

**Things I Have Tried**
a. Installed Mstore API
b. Installed Regenerate Plugins and regenerated for recommended sizes, 300 x 300, 600 x 600, 1024 x 1024.
c. Installed WP Rest Cache
d. Set isCaching to "true".
e. Set kisResizeImage to "true"

**Flutter Version**
1.17.1

**Testing Device/Simulator**
Android Studio Simulator and Letv x900+ android 6.0.1 device

![Screenshot_20200606-041553](https://user-images.githubusercontent.com/43590567/83935971-5cb90980-a7ae-11ea-93e2-d2dea17eb50b.jpg)

![Screenshot_20200606-041738](https://user-images.githubusercontent.com/43590567/83935973-6478ae00-a7ae-11ea-9194-79ac71a91b65.jpg)

![purchase](https://user-images.githubusercontent.com/43590567/83936280-c1c22e80-a7b1-11ea-8b39-ac05a8fbfa70.JPG)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment] 2020-06-06 14:41
@kobylogan - could you help to submit the form to http://verify.inspireui.com? Attache the screenshot will be invalid to validate the proof purchase, thank you for your time

**Comment by philipvu30** [comment] 2020-06-08 09:13
Hi,

Please check if you have installed any plugin that prevents access from outside? Because the app always returns error 403 (Access is forbidden) so it cannot load the image.

**Comment by kobylogan** [comment] 2020-06-08 12:50
I have deactivated all plugins except Woocommerce v 4.2, wp rest cache v2020.1.1 and Mstore api v2.5.3. I have also cleared all caches, including server cache. I still get the same issue. Kindly try on your end and lets see.

**Comment by philipvu30** [comment] 2020-06-09 07:20
Hi,

The app can get information about the products, but the images won't load. I've tested it with other image's URLs and they are fine to load but not with yours.

According to this issue #3341, it is a bug on the server. Please check.

**Comment by kobylogan** [comment] 2020-06-10 07:06
I have not been able to figure out what bug on the server is causing the issue. After reviewing issue #3341, I found out that the image URLs the app is trying to access (which is the medium sized or 600 x 600 version of each product image) did not exist on the server for many of the products. the reason being that, the original image that was uploaded for each product before regenerating thumbnails is 400 x 400.this is the case for thousands of products after regeneration, only 300 x 300 images were regenerated. 
![image](https://user-images.githubusercontent.com/43590567/84236826-d40cd700-aae7-11ea-8a2a-064c1fb5afa9.png)
 

I thought this was the cause of the problem till i found products that have whose medium sized images and they still did not show up in the app. I also intentionally uploaded products with 1500 x 1500 product image to test. Still did not see those images. this is one those links. still got "bad State, failed to load" error. 
https://www.phos.ml/wp-content/uploads/2020/06/161374-medium.jpg

https://www.phos.ml/wp-content/uploads/2020/06/m21a20-medium.jpg

I have not been able to find any connection between the issue and wp rocket yet. I have deleted the plugin completely but still get the issue. 

Hoping you can help out here. Thanks.

**Comment by philipvu30** [comment] 2020-06-11 09:45
Hi,

As you can see, I already tested your [image URL](https://www.phos.ml/wp-content/uploads/2019/12/54434332_2295935453797809_8685391103442026496_n.jpg) that is currently working with a simple base code but it does not load at all. So this issue definitely is caused by your server. Also, this is the first time we encounter this kind of error, we currently don't know how to solve this one as it does not happen on our server.

![image](https://user-images.githubusercontent.com/54442328/84370485-85079480-ac02-11ea-9aa9-6b6ab47ba462.png)

**Comment by kobylogan** [comment] 2020-06-11 15:54
Alright. thanks. I will keep checking for what the cause is and post a solution when i find one.

**Comment by kobylogan** [comment] 2020-06-11 20:32
Found the cause of the issue. Problem was in my .htaccess. Added this line to help deal with bots:
RewriteRule .* - [R=403,L]. 
Commenting it out fixed the image download issue.

**Comment by philipvu30** [comment] 2020-06-12 07:38
Hi,

Thank you for your solution. This will help us a lot in assisting later users.
If you have any questions, feel free to ask us here. Otherwise, it will be closed after 2 days of no activity.

If you are happy with our services/support, would you mind rating us on your download page? We truly appreciate your help.

**Closed** 2020-06-16 02:44 UTC
Labels: FluxStore, image-issue
