### ISSUE TITLE
[ Mstore ] - Profile photo in home page right top

### ISSUE THREAD

**Issue by santhosh2210** [inspireui/support#647] opened 2019-05-28 05:58 UTC
I want to display the my profile image on home top right side...

minhcasi reply message - , you can navigate to the Profilescreen when click to that icon - example: https://tppr.me/C1Bsb

This code also use but not working...only display the empty screen...
See the screenshot -> http://prntscr.com/nu8tws

so please change the code and give me...its very important for me...thanks for your reply..

![WhatsApp Image 2019-05-28 at 10 17 24 AM](https://user-images.githubusercontent.com/32481586/58454293-9e46bb80-813b-11e9-978c-6603110acf26.jpeg)

**Comment by minhcasi** [comment] 2019-05-28 12:40
kindly raise just one ticket for your issues, don't spam here - Duplicate of #642

**Closed by minhcasi** 2019-05-28 12:40 UTC
