### ISSUE TITLE
Product Description Not show

### ISSUE THREAD

**Issue by BasitAmin** [inspireui/support#4363] opened 2020-07-25 12:18 UTC
![Screenshot_20200725-171119](https://user-images.githubusercontent.com/35036635/88456849-b5498080-ce9a-11ea-860d-a75a6a0e0e74.jpg)

Hi am using Fluxstore Woocomrace 1.7.6 and facing this issue on product description please guide me how to fix this 
Thanks

**Comment by ameenbadri7** [comment] 2020-07-25 14:36
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

Thank you for your time!

**Comment by minhcasi** [comment] 2020-07-27 01:45
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-07-27 01:45 UTC
Labels: needs-more-info
