### ISSUE TITLE
Hey I’m experiencing this issue to. What’s a the fix for this. I’m on the update posted on June 11.

### ISSUE THREAD

**Issue by justinekatebe69** [inspireui/support#3828] opened 2020-06-20 20:09 UTC
Hey I’m experiencing this issue to. What’s a the fix for this. I’m on the update posted on June 11.

_Originally posted by @justinekatebe69 in https://github.com/inspireui/support/issues/3061#issuecomment-647040291_

**Comment by minhcasi** [comment] 2020-06-21 05:42
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by justinekatebe69** [comment] 2020-06-21 06:31
Hey Minh,

I have filled in the form and submitted it.

**Comment by justinekatebe69** [comment] 2020-06-21 06:35
This is my store url:
https://makumbi-zed.myshopify.com/

For some reason, it won’t load the page with “www.” in the url.

**Comment by minhcasi** [comment] 2020-06-22 02:36
@justinekatebe69 - thank you for the quick response - it is verified

@luyx2412 - pls help for investigating

**Comment by luyx2412** [comment] 2020-06-23 14:19
HI @justinekatebe69 I just invited you to the latest version in gitlab repo, so please try this version.

Thanks

**Comment by justinekatebe69** [comment] 2020-06-23 15:48
Thanks, let me try them out

**Comment by justinekatebe69** [comment] 2020-06-23 20:10
Hey the error is still present even with the update i was sent a few hours
ago

**Comment by justinekatebe69** [comment] 2020-06-23 20:20
![Screenshot_20200623-220705](https://user-images.githubusercontent.com/67024464/85456814-a6239a00-b59f-11ea-8c71-282e3d4f19ac.jpg)

**Comment by justinekatebe69** [comment] 2020-06-25 12:20
???

**Comment by luyx2412** [comment] 2020-06-25 12:23
HI @justinekatebe69 Sorry about reply you late. Please uninstall and reinstall your app again, and please add the variable in `payments.dart` same the screenshot.
![image](https://user-images.githubusercontent.com/8909619/85719014-42bd7780-b719-11ea-899e-3750fef3cf5d.png)

Thanks

**Comment by justinekatebe69** [comment] 2020-06-25 12:38
Hey is there any Whatsapp or telegram number I can use to contact you much
faster than email?

**Comment by minhcasi** [comment] 2020-06-26 01:44
@justinekatebe69 - try to help to list your all issues at the same time, instead of posting multi comments, we will review and get back you ASAP - thanks

**Comment by minhcasi** [comment] 2020-06-28 03:17
Duplicate of #3949

**Closed by minhcasi** 2020-06-28 03:17 UTC
Labels: Fluxshopify, priority !!!
