### ISSUE TITLE
The method '[]' was called on null. Receiver: null Tried calling: []("TabBar")

### ISSUE THREAD

**Issue by framepoint-id** [inspireui/support#3144] opened 2020-05-11 08:08 UTC
Dear @minhcasi ,
I have added the sticky header false to the file. http://prnt.sc/sejzo2
This is the result http://prnt.sc/sek08p
The method '[]' was called on null.
Receiver: null
Tried calling:
Can i attach my config_en.json file here? Your help will be much appreciated. Thank You.

**Comment by minhcasi** [comment] 2020-05-11 09:07
Duplicate of #3138

**Closed by minhcasi** 2020-05-11 09:07 UTC
