### ISSUE TITLE
coupon code in fluxstore 1.7.3

### ISSUE THREAD

**Issue by Mcrahul555** [inspireui/support#4861] opened 2020-09-03 15:14 UTC
HI 

IN WEB VIEW CHECK OUT THE COUPON CODE IS NOT WORKING ITS GETTING CALCULATED IN CART PAGE AND WHEN MOVE ON TO CHECK OUT SINCE ITS WEB VIEW THE APPLIED COUPON IS NOT SHOWING 

KINDLY GIVE A SOLUTION OR JUST GIVE AN OPTION TO HIDE COUPON TAB FROM CART PAGE OF FLUXSTORE
![COUPON APPLIED](https://user-images.githubusercontent.com/65422936/92133451-77386880-ee19-11ea-9c80-d98ec6886430.jpg)
![CHECKOUT PAGE COUPON NOT SHOWING](https://user-images.githubusercontent.com/65422936/92133475-7d2e4980-ee19-11ea-8612-b2dcd59c9e47.jpg)

 

PLS CHK THE AMOUNT IN CART AND CHECK OUT PAGE

**Comment by minhcasi** [comment] 2020-09-04 01:58
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment] 2020-09-05 02:09
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Closed by minhcasi** 2020-09-05 02:09 UTC
Labels: needs-more-info
