### ISSUE TITLE
Where do we get consumer keys with listingpro theme and not woocommerce .? 

### ISSUE THREAD

**Issue by naveenaryag** [inspireui/support#4730] opened 2020-08-25 09:00 UTC
**_Step 1 (require): describe detail issues & screenshots_**

I followed the tutorial at the below-mentioned URL, But unable to find **consumer keys** for listing pro theme. I saw other link showing consumer keys in woocommerce theme, But my website is on listingpro theme . 

https://docs.inspireui.com/fluxstore/listing-directory

And this tutorial does not explain or talk about how we get that in listingpro theme.
https://pasteboard.co/JnYCuF7.png

**Comment by naveenaryag** [comment] 2020-08-25 09:01
I followed the tutorial at the below-mentioned URL, But unable to find consumer keys for listing pro theme. I saw other link showing consumer keys in woocommerce theme, But my website is on listingpro theme .

https://docs.inspireui.com/fluxstore/listing-directory

And this tutorial does not explain or talk about how we get that in listingpro theme.
https://pasteboard.co/JnYCuF7.png

**Comment by minhcasi** [comment] 2020-08-25 10:54
Hi, you could let the blank consumer and secret key for listingpro - thank you!

**Comment by naveenaryag** [comment] 2020-08-25 11:02
ok , 

Thanks 

Can you help me with error .?
https://pasteboard.co/JnZqeVJ.png

**Comment by minhcasi** [comment] 2020-08-26 03:00
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by naveenaryag** [comment] 2020-08-26 03:18
https://pasteboard.co/Jo0P7PR.png

**Comment by naveenaryag** [comment] 2020-08-26 03:18
https://pasteboard.co/Jo0P7PR.png

How do We fix this error , Please respond

**Comment by minhcasi** [comment] 2020-08-26 03:30
@naveenaryag - could you help to verify purchase code from the form - or you could give the comment on codecayon to prove you have purchased our product - thank you for your time!

**Comment by naveenaryag** [comment] 2020-08-26 03:50
https://pasteboard.co/Jo61wWQ.png

**Comment by minhcasi** [comment] 2020-08-27 02:56
@naveenaryag - these issues caused by the error JSON from your server, please try to turn of the debug mode on your site (wp-config.php) then try again with the fluxbuilder troubleshooting checking.

Also, make sure to activate all the plugin as document - https://docs.inspireui.com/fluxstore/listing-directory/

**Comment by minhcasi** [comment] 2020-08-28 05:07
Let us know your checking - thank you!

**Closed** 2020-08-29 08:25 UTC
Labels: FluxListing
