### ISSUE TITLE
Multiple issues in Magento2

### ISSUE THREAD

**Issue by subhquad** [inspireui/support#3639] opened 2020-06-08 06:43 UTC
Detail Issues:
Blank Screen when you click on reset password .
In checkout page select address is not showing saved addresses in magento.
Banner image not loading loading from asset folder.Its working fine when we are providing external image link.
category images not pulling from magento2 .
Product & version: Fluxstore Pro 1.7.5
Flutter (or React Native) version:
Testing Device/Simulator: iPhone 11
Screenshot issues (drag the file to attach here):

https://user-images.githubusercontent.com/10830054/83645461-6d992d80-a5aa-11ea-9079-b3acf5614fea.png

https://user-images.githubusercontent.com/10830054/83645476-725de180-a5aa-11ea-8c59-e13f0dd909c1.png

https://user-images.githubusercontent.com/10830054/83645508-7be74980-a5aa-11ea-8617-dbd26dbe6e0b.png

https://user-images.githubusercontent.com/10830054/83645496-7853c280-a5aa-11ea-92a3-f6d1ab1b646b.png

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

80f2ca3f-3e8f-43cd-97ba-9dd311d5fb75

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by subhquad** [comment] 2020-06-08 06:44
Git hub access provided
https://github.com/subhquad/magento-flutter

**Comment by minhcasi** [comment] 2020-06-08 07:24
Duplicate of #3573

**Closed by minhcasi** 2020-06-08 07:24 UTC
