### ISSUE TITLE
cached_network_image issue

### ISSUE THREAD

**Issue by Carlosdmendoza** [inspireui/support#3797] opened 2020-06-19 03:26 UTC
**_Step 1 (require): describe detail issues & screenshots_*Because cached_network_image >=2.1.0 <2.3.0-beta.1 depends on flutter_cache_manager ^1.2.0 which depends on file ^5.1.0, cached_network_image >=2.1.0 <2.3.0-beta.1 requires file ^5.1.0.
So, because file depends on cached_network_image 2.2.0+1 and file is 1.4.1+2, version solving failed.
Running "flutter pub get" in file...
pub get failed (1; So, because file depends on cached_network_image 2.2.0+1 and file is 1.4.1+2, version solving failed.)
*
+ Detail Issues: This happens when trying to build the apk file using flutter build apk

+ Product & version:
+ Flutter (or React Native) version: Multivendor Ecommerce app Latest Version
+ Testing Device/Simulator: Android Studio
+ Screenshot issues (drag the file to attach here): 

![image](https://user-images.githubusercontent.com/46724211/85093583-ece15080-b1a9-11ea-8d87-f680f76dbf53.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #https://github.com/inspireui/support/issues/3727#issue-638231267

I have submitted the form already from a different issue if it's needed I would do it again. LEt me know please.

Thank you so much for your time 😊

**Comment by minhcasi** [comment] 2020-06-19 04:36
@Carlosdmendoza - could you confirm this happen on latest fluxstore `1.7.5`? Thank you!

**Comment by Carlosdmendoza** [comment] 2020-06-19 04:39
That is correct it is happening in 1.7.5

**Comment by Carlosdmendoza** [comment] 2020-06-19 04:57
I tried doing what it said that file needed to be at least in version 5.1.0 so I updated the main pubsec.yaml to see if that would do it and I get this error with that version 

![image](https://user-images.githubusercontent.com/46724211/85098069-bd851080-b1b6-11ea-9993-67fc76cb2ff7.png)

But if I change it back to the version it had before the version 1.4.1+2
the original error remains
any suggestions? 
![image](https://user-images.githubusercontent.com/46724211/85098169-0f2d9b00-b1b7-11ea-86b2-34b5782cf6b3.png)

**Comment by Carlosdmendoza** [comment] 2020-06-19 06:31
Hi I was able to partially solve the issu by deleting the .pub-cache folder and was able to build the apk however at the moment o f building it a lot of proceeses failed and when I install the application it just says failed installation, can you please help me here is the log that I got for that:

C:\Users\carlo\OneDrive\Desktop\Multi-Vendor\FluxStore-vendor-1.7.5\source\file\emprendedorhn>flutter build apk
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Running Gradle task 'assembleRelease'...
Plugin project :firebase_core_web not found. Please update settings.gradle.
Plugin project :cloud_firestore_web not found. Please update settings.gradle.
Plugin project :firebase_auth_web not found. Please update settings.gradle.
Plugin project :connectivity_macos not found. Please update settings.gradle.
Plugin project :url_launcher_web not found. Please update settings.gradle.
Error: unable to find directory entry in pubspec.yaml: C:\Users\carlo\OneDrive\Desktop\Multi-Vendor\FluxStore-vendor-1.7.5\source\file\emprendedorhn\assets\icons\catego
ries\
Error: unable to find directory entry in pubspec.yaml: C:\Users\carlo\OneDrive\Desktop\Multi-Vendor\FluxStore-vendor-1.7.5\source\file\emprendedorhn\assets\icons\tabs\
Error: unable to find directory entry in pubspec.yaml: C:\Users\carlo\OneDrive\Desktop\Multi-Vendor\FluxStore-vendor-1.7.5\source\file\emprendedorhn\assets\icons\profil
e\
Error: unable to find directory entry in pubspec.yaml: C:\Users\carlo\OneDrive\Desktop\Multi-Vendor\FluxStore-vendor-1.7.5\source\file\emprendedorhn\assets\icons\paymen
t\
Error: unable to find directory entry in pubspec.yaml: C:\Users\carlo\OneDrive\Desktop\Multi-Vendor\FluxStore-vendor-1.7.5\source\file\emprendedorhn\assets\images\
Error: unable to find directory entry in pubspec.yaml: C:\Users\carlo\OneDrive\Desktop\Multi-Vendor\FluxStore-vendor-1.7.5\source\file\emprendedorhn\assets\images\count
ry\
Error: unable to find directory entry in pubspec.yaml: C:\Users\carlo\OneDrive\Desktop\Multi-Vendor\FluxStore-vendor-1.7.5\source\file\emprendedorhn\assets\images\categ
ories\
Error: unable to locate asset entry in pubspec.yaml: "assets/fonts/Raleway-Regular.ttf".
No se encuentra el archivo: C:\Users\carlo\OneDrive\Desktop\Multi-Vendor\FluxStore-vendor-1.7.5\source\file\emprendedorhn\build\app\intermediates\flutter\release/flutte
r_assets/*
Note: C:\Users\carlo\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\connectivity-0.4.8+6\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityBroadcastRec
eiver.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\carlo\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\device_apps-1.0.9\android\src\main\java\fr\g123k\deviceapps\DeviceAppsPlugin.java uses or overrides
 a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\carlo\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore-0.13.4\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirest
orePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\carlo\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\url_launcher-5.4.11\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses
or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\carlo\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\video_player-0.10.11+1\android\src\main\java\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java
uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\carlo\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\uni_links-0.4.0\android\src\main\java\name\avioli\unilinks\UniLinksPlugin.java uses or overrides a
deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\carlo\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\webview_flutter-0.3.22+1\android\src\main\java\io\flutter\plugins\webviewflutter\FlutterWebView.jav
a uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Calling mockable JAR artifact transform to create file: C:\Users\carlo\.gradle\caches\transforms-2\files-2.1\c1f8395745bca25c4ff3d664bf37dec3\android.jar with input C:\
Users\carlo\AppData\Local\Android\sdk\platforms\android-29\android.jar
Removed unused resources: Binary resource data reduced from 846KB to 844KB: Removed 0%
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                    1774,3s (!)
√ Built build\app\outputs\apk\release\app-release.apk (18.1MB).
 
![image](https://user-images.githubusercontent.com/46724211/85103537-1effac00-b1c4-11ea-8487-0597c6d26dbb.png)

![image](https://user-images.githubusercontent.com/46724211/85103588-35a60300-b1c4-11ea-8e56-139dfab0698a.png)

**Comment by Carlosdmendoza** [comment] 2020-06-19 17:39
Can you please help me?

**Comment by minhcasi** [comment] 2020-06-21 05:49
Duplicate of #3831

**Closed by minhcasi** 2020-06-21 05:49 UTC
Labels: FluxstoreMV
