### ISSUE TITLE
MStore Pro Wrong totals at customer order page

### ISSUE THREAD

**Issue by IvoKalu** [inspireui/support#614] opened 2019-05-21 07:49 UTC
**Required Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [41384711-598d-400d-9b04-1b414a388036 ]

**Describe the bug**
The sums being showed to the customer at the customer order page are wrongly calculated

**Screenshots**
![Screenshot_20190520-152906_Bue Shopping](https://user-images.githubusercontent.com/8544219/58077828-3b867a80-7ba5-11e9-8bc4-9cf1e074d3d9.jpg)

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by IvoKalu** [comment] 2019-05-21 07:49
MStore Pro

**Comment by minhcasi** [comment] 2019-05-22 02:26
Duplicate of #613

Please try to create one ticket for your all issues as for better focus on your issues - thank you!

**Closed by minhcasi** 2019-05-22 02:26 UTC
